### ISSUE TITLE
Download media stuck

### ISSUE THREAD

**Issue by mehrant95** [LonamiWebs/Telethon#1001]
I've face two issues with the `download_media` method:

1. Download speed is very low (about 17 KB/s) despite of having **cryptg** installed using command `pip3 install cryptg`. (my actual download speed is around 250 KB/s)
2. It sometimes stuck and makes no progress for hours. (I download small files, mostly less than 20 MB)

I'm calling `download_media` with a callback function to show download speed, like this:
```python
def progress_callback(current, total):
    nonlocal last_current, last_time
    now = time.time()
    speed = round(((current-last_current)/(now-last_time))/1000)
    last_current = current
    last_time = now
    percent = int((current/total)*100)
    print('\r{} % .... {} KB/s'.format(percent, speed), end='')
    if percent == 100:
        print()

self._client.download_media(message, temp_path, progress_callback=progress_callback)

```
Of the two problems stated above, second one is more frustrating and i need some way to handle it.

**Comment by mehrant95** [comment]
I enabled debug logging and some of the debug logs:

```
97 % .... 6 KB/s
DEBUG:telethon.network.mtprotosender:Decoding packet of 664 bytes...
DEBUG:telethon.network.mtprotosender:Handling gzipped data
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 808 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 984 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 712 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 984 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 792 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 648 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 552 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 600 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 1032 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 872 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 952 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 1048 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 712 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 552 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 664 bytes...
DEBUG:telethon.network.mtprotosender:Handling gzipped data
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 952 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 856 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 584 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) PingRequest...
DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6602070522327500836 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 600 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6602070522352216260 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 88 bytes...
DEBUG:telethon.network.mtprotosender:Handling pong for message 6602070522327500836
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
WARNING:telethon.extensions.tcpclient:Timeout when partial 88548/131180 had been received
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
ERROR:telethon.network.mtprotosender:Unhandled exception while receiving
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtprotosender.py", line 425, in _recv_loop
    body = await self._connection.recv()
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/connection/tcpfull.py", line 47, in recv
    body = await self.read(packet_len - 8)
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcpclient.py", line 199, in read
    self.sock_recv(bytes_left)
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcpclient.py", line 166, in _wait_timeout_or_close
    return done.pop().result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcpclient.py", line 236, in _sock_recv
    data = self._socket.recv(n)
ValueError: negative buffersize in recv
DEBUG:telethon.network.mtprotosender:Awaiting for the send loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Awaiting for the receive loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Closing current connection...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91 complete!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) GetFileRequest...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6602070441984100912 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 168 bytes...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling detailed info for message 6602070441655646209
DEBUG:telethon.network.mtprotosender:Handling detailed info for message 6602070441655646209
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 824 bytes...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling update UpdateShort
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 568 bytes...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 104 bytes...
DEBUG:telethon.network.mtprotosender:Handling update UpdateShort
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 104 bytes...
DEBUG:telethon.network.mtprotosender:Handling update UpdateShort
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...

After the `negative buffersize in recv` error, it successfully connects and continues printing `Receiving items from the network` but `download_media` never finishes.

Is there any way to detect this situation and recall `download_media` when such error happens? Maybe calling `download_media` on another thread and controlling this thread from main thread? (my code is now single threaded)

**Comment by Lonami** [comment]
Are you running the code in a multi-threaded context? The client is not thread-safe.

**Comment by mehrant95** [comment]
No, it's single threaded. Output of `pip3 show telethon`:
```
Metadata-Version: 2.1
Name: Telethon
Version: 1.2
```
I changed the country of my VPN connection and speed is now better and no stuck till now but the problem is definitely there on slow connections.

**Comment by mehrant95** [comment]
No idea how can i handle the `ValueError: negative buffersize in recv` exception in my codes?

**Comment by mehrant95** [comment]
Did you reproduce the issue? I think it can be reproduced using a slow connection, such as using public telegram proxies.
As i need to run my code on server for long time, I have to use some trick for now. I'm going to try two ways:
 1. Running `download_media` on another thread. What happens in worse case scenario? Is it possible to download the file after some try and fails?
 2. Running all of my code inside a subprocess and check it's log output. Whenever I see the exception in the logs, terminate the process and restart it. 
Any easier way? :)

**Comment by Lonami** [comment]
> Did you reproduce the issue

No, I honestly didn't try anything regarding this issue yet. Regarding your two solutions, monitoring it like that could be good if you need such high reliability while the issue is present.

**Comment by ingria** [comment]
@mehrant95 you can also use supervisor's monitoring services, like httpok. I'm using this method to circumvent #955.

**Comment by mehrant95** [comment]
@ingria Wonderful, would you please share some example code ?

**Comment by Lonami** [comment]
Try https://github.com/LonamiWebs/Telethon/compare/096424ea7809e5512a932c79eff6676695c1d27e...dc7713645329c26b83c38fa0350a69031d81c638 (install master) and see if it's fixed.
