### ISSUE TITLE
does not install the Telegram Client on python 3.7

### ISSUE THREAD

**Issue by rdbox** [LonamiWebs/Telethon#1006]
DON'T ASK QUESTIONS HERE.

This place is for issues with the library, so please make sure that:
1. The error is in the library's code, and not in your own.
2. You have already searched for your error on existing issues.
3. You are testing with upstream code (pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip).

If you have a question, ask in the official Telegram group https://t.me/TelethonChat or  https://stackoverflow.com. Enhancement ideas are currently welcome, too.

 log
``` 
 Desktop py -3 telethon.py
Traceback (most recent call last):
  File "telethon.py", line 1, in <module>
    from telethon import TelegramClient, sync
  File "C:\Users\user\Desktop\telethon.py", line 1, in <module>
    from telethon import TelegramClient, sync
ImportError: cannot import name 'TelegramClient' from 'telethon' (C:\Users\user\Desktop\telethon.py)
```

 
``` python
from telethon import TelegramClient, sync

# Use your own values here
api_id = 12345
api_hash = '0123456789abcdef0123456789abcdef'

client = TelegramClient('some_name', api_id, api_hash)
```
**version**
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by Lonami** [comment]
Don't call your script `telethon.py`.

**Comment by rdbox** [comment]
@Lonami 
I renamed, but now another error
```
 Desktop py -3 botTelegram.py
Traceback (most recent call last):
  File "botTelegram.py", line 1, in <module>
    from telethon import TelegramClient, sync
ImportError: bad magic number in 'telethon': b'\x03\xf3\r\n'
```

**Comment by Lonami** [comment]
Delete all `.pyc` files.
