### ISSUE TITLE
events.ChatAction event.get_input_user() return access_hash=None

### ISSUE THREAD

**Issue by T-bps** [LonamiWebs/Telethon#1018]
When I try to get an InputUser from a function for the  event ChatAction like this:

````
@client.on(events.ChatAction(chats=chats_invitacion))
async def nuevoMiembro(event):
````
I get None as a result:

````
	users = await event.get_users()
        iusers = await event.get_input_users()
        iuser = await event.get_input_user()
        user = await event.get_user()
		
        logging.info(users)
        logging.info(user)
        logging.info(iuser)
        logging.info(iusers)

        await client.send_message(iuser, message=msg_test, link_preview=False)
````

LOG:

2018-10-02 19:29:50,799 [INFO] [<telethon.tl.types.User object at 0x7f7dd34e2d68>]
2018-10-02 19:29:50,799 [INFO] User(id=611727666, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False, bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=True, bot_inline_geo=False, access_hash=None, first_name='Isidro', last_name='lopez', username=None, phone=None, photo=None, status=UserStatusRecently(), bot_info_version=None, restriction_reason=None, bot_inline_placeholder=None, lang_code=None)
2018-10-02 19:29:50,800 [INFO] None
2018-10-02 19:29:50,800 [INFO] []

Traceback (most recent call last):
  File "/home/test/.local/lib/python3.6/site-packages/telethon/utils.py", line 121, in get_input_peer
    if entity.SUBCLASS_OF_ID == 0xc91c90b6:  # crc32(b'InputPeer')
AttributeError: 'NoneType' object has no attribute 'SUBCLASS_OF_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/.local/lib/python3.6/site-packages/testMrMarshall/test.py", line 191, in nuevoMiembro
    await client.send_message(iuser, message=msg_test, link_preview=False)
  File "/home/test/.local/lib/python3.6/site-packages/telethon/client/messages.py", line 448, in send_message
    entity = await self.get_input_entity(entity)
  File "/home/test/.local/lib/python3.6/site-packages/telethon/client/users.py", line 304, in get_input_entity
    return utils.get_input_peer(peer)
  File "/home/test/.local/lib/python3.6/site-packages/telethon/utils.py", line 130, in get_input_peer
    _raise_cast_fail(entity, 'InputPeer')
  File "/home/test/.local/lib/python3.6/site-packages/telethon/utils.py", line 112, in _raise_cast_fail
    type(entity).__name__, target))
TypeError: Cannot cast NoneType to any kind of InputPeer.

**Comment by T-bps** [comment]
For example, can you try with this user id: 281330046?

I get this:
User(id=281330046, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False, bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=True, bot_inline_geo=False, access_hash=None, first_name='Alex', last_name=None, username=None, phone=None, photo=None, status=UserStatusRecently(), bot_info_version=None, restriction_reason=None, bot_inline_placeholder=None, lang_code=None)

**Comment by Lonami** [comment]
> For example, can you try with this user id: 281330046?

No, I need the access hash, and of course an event from them.

**Comment by T-bps** [comment]
Maybe I need to read the last group chat messages to get the acces_hash?

I try this and don't work:
'''
user = client.get_entity(PeerUser(281330046))
logging.info(user)
'''

But this yes:
'''
    client.get_messages('ChatName', 100)
    user = client.get_entity(PeerUser(281330046))
    logging.info(user)
'''

**Comment by cosmicwize** [comment]
Do you still have this problem? I'm facing the same, but having more success today (read below). What I did:

In this function:
`@client.on(events.ChatAction(chats=channel_name))
async def my_event_handler(event):
    dialogs = await client.get_dialogs() # get all dialogs and such, so we can work with them
    if (event.user_added or event.user_joined):        
        users = await event.get_users()
        iusers = await event.get_input_users()
        iuser = await event.get_input_user()
        user = await event.get_user()`

I execute:
`await client(EditBannedRequest(channel_name, user.username, banned_rights)) # ban user`

Error:
`ERROR:telethon.client.updates:Unhandled exception on my_event_handler
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.6/site-packages/telethon/utils.py", line 117, in get_input_peer
    if entity.SUBCLASS_OF_ID == 0xc91c90b6:  # crc32(b'InputPeer')
AttributeError: 'NoneType' object has no attribute 'SUBCLASS_OF_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 279, in _dispatch_update
    await callback(event)
  File "./cryptoboerderijboer.py", line 101, in my_event_handler
    await client(EditBannedRequest(channel_name, user.username, banned_rights)) # ban user
  File "/home/me/.local/lib/python3.6/site-packages/telethon/client/users.py", line 21, in __call__
    await r.resolve(self, utils)
  File "/home/me/.local/lib/python3.6/site-packages/telethon/tl/functions/channels.py", line 349, in resolve
    self.user_id = utils.get_input_user(await client.get_input_entity(self.user_id))
  File "/home/me/.local/lib/python3.6/site-packages/telethon/client/users.py", line 304, in get_input_entity
    return utils.get_input_peer(peer)
  File "/home/me/.local/lib/python3.6/site-packages/telethon/utils.py", line 126, in get_input_peer
    _raise_cast_fail(entity, 'InputPeer')
  File "/home/me/.local/lib/python3.6/site-packages/telethon/utils.py", line 108, in _raise_cast_fail
    type(entity).__name__, target))
TypeError: Cannot cast NoneType to any kind of InputPeer`

I changed user.username to user.userid in:
`await client(EditBannedRequest(channel_name, user.username, banned_rights))`

First tests look promising..

**Comment by cosmicwize** [comment]
It seems I have fixed this error permanently by reading this https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/extra/basic/entities.rst 
(like it's printed in a lot of errors that are like these...)

My problem is that I didn't want to believe that I had to do all of the following:

```
entity = client.get_entity(username)
client.get_dialogs()
client.get_participants('TelethonChat')
client.get_messages('TelethonChat', 100)
```

Before I really could issue a ban command or something based on the user ID. Because when the 'new user joined event' was visible I assumed only a get_dialogs() would be enough to interact with this user (sending a message to it might work, but limiting rights in a channel not, for example)

**Comment by Lonami** [comment]
Does https://github.com/LonamiWebs/Telethon/commit/4a8a85d7a62d16db552d4e6f99a7d0a613842a15 help?

**Comment by cosmicwize** [comment]
> Does [4a8a85d](https://github.com/LonamiWebs/Telethon/commit/4a8a85d7a62d16db552d4e6f99a7d0a613842a15) help?

This looks great! I do have a solution for now, but I think I will create an extra function asap in which I will need this again and I will test it. 

@T-bps you were the original starter of this topic, maybe this is something you can check, as you might not have implemented a workaround yet?

**Comment by Lonami** [comment]
@cosmicwize I can close the issue if you can confirm that the commit fixes it too. So anyone with the issue can try it.
