### ISSUE TITLE
FloodWaitError raised

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#1020]
Should this be catched by myself?
version: 1.3
```
 Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/downloads.py", line 146, in download_media
    media, file, date, progress_callback
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/downloads.py", line 354, in _download_document
    progress_callback=progress_callback)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/downloads.py", line 244, in download_file
    input_location, offset, part_size
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 738 seconds is required
```

**Comment by hnikaein** [comment]
no response?

**Comment by Lonami** [comment]
GitHub issues are for errors *with the library*, which this is not. Handling the error is documented.

**Comment by hnikaein** [comment]
I know it and know what is FloodWaitError and how I should handle it! But after some version telethon begin handle FloodWaitError by itself and I just asking if this is an exception or bug!

Anyway thanks, I got my answer

**Comment by Lonami** [comment]
There exists a [`flood_sleep_threshold`](https://telethon.readthedocs.io/en/stable/telethon.client.html?highlight=flood_sleep_threshold#telethon.client.telegrambaseclient.TelegramBaseClient).
