### ISSUE TITLE
[Bug] RuntimeError: File descriptor 22 is used by transport

### ISSUE THREAD

**Issue by vicdup** [LonamiWebs/Telethon#1027]
I have been using Telethon for a few days but suddenly my code is not working anymore, here is my code (using Sanic)

```python
@app.route('/check-login', methods=['GET'])
async def chat(request):
    client = getClient()
    await client.connect()
    phone_number = '+XXXX'
    await client.send_code_request(phone_number)
```

and here is the getclient part
```python
def getClient():
    api_id = xxx
    api_hash = 'xxx'

    client = TelegramClient('name', api_id, api_hash)
    return client
```

I get the following error :
```
[2018-10-22 20:49:35 +0200] [26093] [ERROR] Traceback (most recent call last):
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/client/users.py", line 60, in __call__
    result = await future
telethon.errors.rpcerrorlist.PhoneMigrateError: The phone number a user is trying to use for authorization is associated with DC 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/sanic/app.py", line 603, in handle_request
    response = await response
  File "/Users/myuser/git/python-telegram/main.py", line 60, in chat
    await client.send_code_request(phone_number)
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/client/auth.py", line 370, in send_code_request
    phone, self.api_id, self.api_hash))
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/client/users.py", line 86, in __call__
    await self._switch_dc(e.new_dc)
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 377, in _switch_dc
    await self._disconnect()
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 346, in _disconnect
    await self._sender.disconnect()
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 140, in disconnect
    await self._disconnect()
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 147, in _disconnect
    await self._connection.close()
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/network/connection/tcpfull.py", line 42, in close
    self.conn.close()
  File "/Users/myuser/git/python-telegram/venv/lib/python3.6/site-packages/telethon/extensions/tcpclient.py", line 148, in close
    self._loop.remove_reader(fd)
  File "uvloop/loop.pyx", line 2262, in uvloop.loop.Loop.remove_reader
  File "uvloop/loop.pyx", line 724, in uvloop.loop.Loop._remove_reader
  File "uvloop/loop.pyx", line 692, in uvloop.loop.Loop._ensure_fd_no_transport
RuntimeError: File descriptor 22 is used by transport <TCPTransport closed=False reading=False 0x7fd666994298>
``` 

Using python 3.6.5 in virtual env

Any clue where this can come from?

**Comment by Lonami** [comment]
Could you try `pip install --upgrade git+https://github.com/LonamiWebs/Telethon@master`?

**Comment by vicdup** [comment]
Hi Lonami,

thanks for the quick answer, it works now !
