### ISSUE TITLE
Race condition when invoking requests from the main thread

### ISSUE THREAD

**Issue by IlyaSemenov** [LonamiWebs/Telethon#105]
If I add an update handler and then `invoke()` requests (e.g. send messages) from the main thread, sooner or later Telethon will crash with this:

```
Exception in thread UpdatesThread:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/telethon/telegram_client.py", line 985, in _updates_thread_method
    result = self.sender.receive_update(timeout=timeout)
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 113, in receive_update
    self.receive(timeout=timeout, updates=updates)
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 99, in receive
    request, updates)
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 194, in _process_msg
    msg_id, sequence, reader, request)
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 348, in _handle_rpc_result
    'The request needed to read this RPC result was not '
ValueError: The request needed to read this RPC result was not found (possibly called receive() from another thread).
```

This basically means the whole update handler API is unusable and one either needs to poll for updates with `client.sender.receive_update(timeout=timeout)` in the main thread, or invoke requests only from within the update handler.

This is **telethon==0.10.1** from pypi.

**Comment by Lonami** [comment]
I've tried a few times to make it usable by making use of flags and mutexs, but it's a bug hard to reproduce hence hard to test. I will try a different approach.

**Comment by Lonami** [comment]
So as long as you do [`.send()`](https://github.com/LonamiWebs/Telethon/blob/65912f926bb91d995c0e9cc7b6faccc0d1e7e4ad/telethon/network/mtproto_sender.py#L59) one, it will be available to be received, even from the updates thread. Then, on [`.receive()`](https://github.com/LonamiWebs/Telethon/blob/65912f926bb91d995c0e9cc7b6faccc0d1e7e4ad/telethon/network/mtproto_sender.py#L108-L109), it will already be read. I would really appreciate if you could test the upstream version and let me know how well it goes.

Regarding this part:
> This basically means the whole update handler API is unusable

The whole [`.invoke()`](https://github.com/LonamiWebs/Telethon/blob/v0.10.1/telethon/telegram_client.py#L307) uses an [`RLock`](https://github.com/LonamiWebs/Telethon/blob/v0.10.1/telethon/telegram_client.py#L324-L358), so the updates thread should [not](https://github.com/LonamiWebs/Telethon/blob/v0.10.1/telethon/telegram_client.py#L980-L1009) be able to receive anything (again, not sure why this still happens; not to say, it's hard to test).

**Comment by IlyaSemenov** [comment]
Unfortunately I've already reworked my code to the single-thread approach (which was better fit for my case anyway) and will not be able to test the changes. I appreciate this very quick turnaround though! Please close the ticket if you believe the problem is fixed (or at least better handled).

**Comment by Lonami** [comment]
Yes, I think (_think_) it should cause more issues. Someone else can always ask to reopen this or create a new one.

**Comment by IlyaSemenov** [comment]
I think it made it worse. Telethon wouldn't even connect after this change.

Consider `test.py`:

```python
from telethon import TelegramClient
telegram = TelegramClient('foo', 12345, 'xxxxx')
telegram.connect()
```

With 65912f926bb91d995c0e9cc7b6faccc0d1e7e4ad (`master`), it crashes:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    telegram.connect()
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_client.py", line 136, in connect
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_bare_client.py", line 113, in connect
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_client.py", line 226, in invoke
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_bare_client.py", line 189, in invoke
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 105, in receive
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 203, in _process_msg
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 275, in _handle_container
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 197, in _process_msg
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 348, in _handle_rpc_result
ValueError: The request needed to read this RPC result was not found (possibly called receive() from another thread).
```

With c6acd6adc5eada59ea3a3e1821c717407cb5a739 (`master^`), it works fine.

I double checked this by uninstalling and reinstalling the corresponding versions.

**Comment by Lonami** [comment]
Yeah… I had issues too, but it's very strange. I will take another look.

**Comment by IlyaSemenov** [comment]
By the way, the reason I went into testing the new version is that even in a fully single-threaded environment, 0.10.1 still crashed with the same exception after working for a few hours under reasonable load (a few hundred messages sent and received). I totally understand that without reproducible environment it's not a very helpful bug report, but just wanted to let you know.

**Comment by Lonami** [comment]
[`3ed59d0`](https://github.com/LonamiWebs/Telethon/commit/3ed59d08e5acc34c872c98c4a09f0c90b33356b3) should do.

**Comment by IlyaSemenov** [comment]
Yes, I am running 76166cd1ec8eb7909ad63eea600cf7b5ac5d8b4d and it doesn't suffer from the errors above. Thank you.

I am still getting occasional crashes with RPC error (0x2144ca19) but it's probably unrelated.

**Comment by Lonami** [comment]
> RPC error (0x2144ca19)

What error more precisely? Like, the message of it.

**Comment by IlyaSemenov** [comment]
I only get this:

```
Traceback (most recent call last):
.....
  File "/root/foo/foo.py", line 379, in send_text
    self.telegram.send_message(telegram_entity, text)
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_client.py", line 417, in send_message
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_client.py", line 226, in invoke
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_bare_client.py", line 189, in invoke
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 105, in receive
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 203, in _process_msg
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 351, in _handle_rpc_result
telethon.errors.rpc_errors.ServerError
```

Let me know how else I can help? Catch that exception and print its `__dict__`?

**Comment by Lonami** [comment]
I've never got a `ServerError`, they happen only when the code is [500](https://github.com/LonamiWebs/Telethon/blob/master/telethon/errors/__init__.py#L40) so it really is a server error. Currently I don't store its message anywhere so you would have to modify [this file](https://github.com/LonamiWebs/Telethon/blob/master/telethon/errors/__init__.py) and a `print(message)` to see what's going on.
