### ISSUE TITLE
The api_id/api_hash combination is invalid (caused by SendCodeRequest)

### ISSUE THREAD

**Issue by geeklingo** [LonamiWebs/Telethon#1056]
With newer bots, this issue seems to have returned. If the bot api was recently created (9-digits) the code no longer works and gives the following error:

`Traceback (most recent call last):
  File "cbt.py", line 51, in <module>
    telegramClient.start()
  File "/usr/lib64/python3.6/site-packages/telethon/client/auth.py", line 114, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.6/site-packages/telethon/client/auth.py", line 148, in _start
    sent_code = await self.send_code_request(phone, force_sms=force_sms)
  File "/usr/lib64/python3.6/site-packages/telethon/client/auth.py", line 374, in send_code_request
    phone, self.api_id, self.api_hash))
  File "/usr/lib64/python3.6/site-packages/telethon/client/users.py", line 60, in __call__
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa9f65b8128>`

Using the same code but older bot API (6-digits) it works fine.

**Comment by Lonami** [comment]
There's not much we can do to solve that besides Telegram fixing it.

**Comment by Lonami** [comment]
#836 has more details.
