### ISSUE TITLE
edit_2fa + recovery email

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1088]
Currently not handled: `EMAIL_UNCONFIRMED_6`.

**Comment by drmizzcrypto** [comment]
Traceback (most recent call last):
  File "<pyshell#517>", line 1, in <module>
    import seaser
  File "C:\Users\drmiz\AppData\Local\Programs\Python\Python37-32\Scripts\seaser.py", line 219, in <module>
    fa()
  File "C:\Users\drmiz\AppData\Local\Programs\Python\Python37-32\Scripts\seaser.py", line 56, in fa
    client.edit_2fa(new_password= password_2fa,email= email_2fa)
  File "C:\Users\drmiz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\sync.py", line 54, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\drmiz\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "C:\Users\drmiz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\client\auth.py", line 493, in edit_2fa
    new_secure_settings=None
  File "C:\Users\drmiz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\client\users.py", line 60, in __call__
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: EMAIL_UNCONFIRMED_6 (caused by UpdatePasswordSettingsRequest)

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/51f0bf5d848b35623cc12c392f052a392ea26fef
