### ISSUE TITLE
SInce 1.5.3 download_media throws an error for some media

### ISSUE THREAD

**Issue by bertploeger** [LonamiWebs/Telethon#1089]
Hi,

Since yesterday with the release of 1.5.3 i get an error in message.download_media() but not with all files.

```
ERROR:telethon.client.updates:Unhandled exception on my_event_handler
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telethon/client/updates.py", line 277, in _dispatch_update
    await callback(event)
  File "./getMessages.py", line 61, in my_event_handler
    account_id)
  File "/opt/application/helper/messages.py", line 47, in process_message_async
    progress_callback=download_progress_callback
  File "/usr/lib/python3.6/site-packages/telethon/tl/custom/message.py", line 682, in download_media
    return await self._client.download_media(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telethon/client/downloads.py", line 146, in download_media
    media, file, date, progress_callback
  File "/usr/lib/python3.6/site-packages/telethon/client/downloads.py", line 359, in _download_document
    progress_callback=progress_callback)
  File "/usr/lib/python3.6/site-packages/telethon/client/downloads.py", line 220, in download_file
    sender = await self._borrow_exported_sender(dc_id)
  File "/usr/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 493, in _borrow_exported_sender
    sender = await self._create_exported_sender(dc_id)
  File "/usr/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 472, in _create_exported_sender
    dc.ip_address, dc.port, loop=self._loop, proxy=self._proxy))
TypeError: __init__() missing 1 required keyword-only argument: 'loggers'
```

I tried to trace it down and find the issue but could not find a clue of what goes wrong.
The code is use is (stripped down to the essentials):

```
@client.on(events.NewMessage)
async def my_event_handler(event):
    item = await process_message_async(event.message,
                                                       event.chat,
                                                       event.sender,
                                                       event.media
                                                      )

async def process_message_async(message, chat, sender, media):
    if media is not None:
        filename = await message.download_media(
            file=destdir,
            progress_callback=download_progress_callback
        )
```

As a test i swithed back to 1.4.3 and with this version everythings works as expected.

I hope you can help with this.

Regards, Bert

**Comment by Lonami** [comment]
We sure as hell need #716.
