### ISSUE TITLE
AuthKeyUnregisteredError in case of migrating

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#1098]
I'm using telethon 1.4.3 (and know it is better to upgrade it)
I have multiple clients runing. When one of them want to download a media from a datacenter that wants migration, telethon gets this error log:

This happens in case of migrating and not happen in case of regular media download.

<details><summary>Info logs</summary><pre>
2019-01-30 20:04:48,530_telethon.network.mtprotosender_INFO: Connecting to 149.154.175.50:443/TcpAbridged...
2019-01-30 20:04:48,664_telethon.network.mtprotosender_INFO: Connection to 149.154.175.50:443/TcpAbridged complete!
2019-01-30 20:04:48,666_telethon.client.downloads_INFO: Downloading file in chunks of 131072 bytes
2019-01-30 20:04:48,944_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,945_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,945_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,946_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,946_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,946_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,946_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,947_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,947_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,948_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,948_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,948_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,948_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,949_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,949_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,951_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,952_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,952_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,953_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,953_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,953_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,953_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,953_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,954_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,954_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,954_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,954_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,955_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,955_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,955_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,955_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,956_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,957_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,958_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,958_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,958_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,958_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,959_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,959_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,960_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,960_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,960_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,960_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,960_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,961_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,961_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,961_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,961_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,962_telethon.network.mtprotosender_INFO: Received response without parent request: None
2019-01-30 20:04:48,964_telethon.client.telegrambaseclient_INFO: Disconnecting borrowed sender for DC 1
2019-01-30 20:04:48,965_telethon.network.mtprotosender_INFO: Disconnecting from 149.154.175.50:443/TcpAbridged...
2019-01-30 20:04:48,965_telethon.network.mtprotosender_INFO: Disconnection from 149.154.175.50:443/TcpAbridged complete!
2019-01-30 20:04:48,966_root_ERROR: The key is not registered in the system (caused by GetFileRequest)
2019-01-30 20:04:48,966_root_ERROR: Traceback (most recent call last):
  .....
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 142, in download_media
    media, file, date, progress_callback
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 311, in _download_photo
    progress_callback=progress_callback)
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 244, in download_file
    input_location, offset, part_size
telethon.errors.rpcerrorlist.AuthKeyUnregisteredError: The key is not registered in the system (caused by GetFileRequest)
</pre></details>

**Comment by Lonami** [comment]
> and know it is better to upgrade it

Why haven't you, then? Anyway, this may still be present in the latest version, so I will check.

**Comment by hnikaein** [comment]
Because of breaking changes, and no gain for update. If you are sure that this bug is not present in latest version, I will upgrade

**Comment by Lonami** [comment]
I cannot reproduce the issue on the master branch.
<details><summary>Debug logs</summary><pre>
INFO:telethon.crypto.aes:libssl detected, it will be used for encryption
DEBUG:asyncio:Using selector: EpollSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpFull complete!
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602953125691252 to InvokeWithLayerRequest (7f8e373c7400)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 84 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling bad salt for message 6652602953125691252
DEBUG:telethon.network.mtprotosender:1 message(s) will be resent
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602953429192384 to InvokeWithLayerRequest (7f8e373c7400)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 84 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602953432615120 to MsgsAck (7f8e373c7780)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling new session created
DEBUG:telethon.network.mtprotosender:Handling acknowledge for [6652602953429192384]
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652602953429192384
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602953776989776 to GetStateRequest (7f8e373c7400)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 20 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602953779036360 to MsgsAck (7f8e373c7a20)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 60 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652602953776989776
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602954156387168 to GetHistoryRequest (7f8e373c7b38)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 52 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602954160129388 to MsgsAck (7f8e37624ba8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652602954156387168
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602954560127100 to GetConfigRequest (7f8e373c76a0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 20 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602954566359360 to MsgsAck (7f8e373c7b00)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652602954560127100
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 1...
DEBUG:telethon.network.mtprotosender:Handling update UpdateShort
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51:443/TcpFull complete!
INFO:telethon.client.telegrambaseclient:Exporting authorization for data center DcOption(id=2, ip_address='149.154.167.51', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, secret=None)
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602958212287388 to ExportAuthorizationRequest (7f8e373e9dd8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 24 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602958215232332 to MsgsAck (7f8e373e9240)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 44 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652602958212287388
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602958569591960 to InvokeWithLayerRequest (7f8e3737d128)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 220 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling bad salt for message 6652602958569591960
DEBUG:telethon.network.mtprotosender:1 message(s) will be resent
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602958958525144 to InvokeWithLayerRequest (7f8e3737d128)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 220 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602958961494884 to MsgsAck (7f8e3737d0b8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling new session created
DEBUG:telethon.network.mtprotosender:Handling acknowledge for [6652602958958525144]
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652602958958525144
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.client.downloads:Downloading file in chunks of 131072 bytes
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602959741708840 to GetFileRequest (7f8e373e9dd8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 80 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602959743730628 to MsgsAck (7f8e3737d588)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 60 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652602959741708840
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.client.downloads:Saving 99026 more bytes
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602961830163084 to GetFileRequest (7f8e373e9dd8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 80 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652602961831707084 to MsgsAck (7f8e3737d2e8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652602961830163084
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.client.telegrambaseclient:Disconnecting borrowed sender for DC 2
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.51:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
DEBUG:telethon.network.mtprotosender:Cancelling the send loop...
DEBUG:telethon.network.mtprotosender:Cancelling the receive loop...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.51:443/TcpFull complete!
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.91:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
DEBUG:telethon.network.mtprotosender:Cancelling the send loop...
DEBUG:telethon.network.mtprotosender:Cancelling the receive loop...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.91:443/TcpFull complete!
</pre></details>

Can you?

**Comment by hnikaein** [comment]
Could it have relation with TcpAbridged?

**Comment by Lonami** [comment]
<details><summary>Debug logs, <code>TcpAbridged</code></summary><pre>
INFO:telethon.crypto.aes:libssl detected, it will be used for encryption
DEBUG:asyncio:Using selector: EpollSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpAbridged...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpAbridged complete!
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604399248160608 to InvokeWithLayerRequest (7ff9f2d7d4a8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 84 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling bad salt for message 6652604399248160608
DEBUG:telethon.network.mtprotosender:1 message(s) will be resent
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604399553557640 to InvokeWithLayerRequest (7ff9f2d7d4a8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 84 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604399556663756 to MsgsAck (7ff9f2d7d860)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling new session created
DEBUG:telethon.network.mtprotosender:Handling acknowledge for [6652604399553557640]
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652604399553557640
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604399900873428 to GetStateRequest (7ff9f2d7d4a8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 20 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604399902446992 to MsgsAck (7ff9f2d7db00)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 60 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652604399900873428
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604400279009108 to GetHistoryRequest (7ff9f2d7dc18)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 52 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604400282188660 to MsgsAck (7ff9f2fdcc18)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling update UpdateShort
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652604400279009108
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604400691059356 to GetConfigRequest (7ff9f2d7d4a8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 20 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604400697169548 to MsgsAck (7ff9f36166d8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 44 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652604400691059356
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpAbridged...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 1...
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51:443/TcpAbridged complete!
INFO:telethon.client.telegrambaseclient:Exporting authorization for data center DcOption(id=2, ip_address='149.154.167.51', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, secret=None)
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604404639662632 to ExportAuthorizationRequest (7ff9f2da3f28)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 24 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604404642619976 to MsgsAck (7ff9f61d8048)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652604404639662632
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604400694721468 to InvokeWithLayerRequest (7ff9f2d34160)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 220 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling bad salt for message 6652604400694721468
DEBUG:telethon.network.mtprotosender:1 message(s) will be resent
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604401075974708 to InvokeWithLayerRequest (7ff9f2d34160)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 220 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604401079283004 to MsgsAck (7ff9f2d34208)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling new session created
DEBUG:telethon.network.mtprotosender:Handling acknowledge for [6652604401075974708]
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652604401075974708
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.client.downloads:Downloading file in chunks of 131072 bytes
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604401513401276 to GetFileRequest (7ff9f2da3f28)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 80 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604401516027696 to MsgsAck (7ff9f2d345f8)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 60 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652604401513401276
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.client.downloads:Saving 99026 more bytes
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604403747761616 to GetFileRequest (7ff9f2da3f28)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 80 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6652604403748967060 to MsgsAck (7ff9f2d34358)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6652604403747761616
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.client.telegrambaseclient:Disconnecting borrowed sender for DC 2
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.51:443/TcpAbridged...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
DEBUG:telethon.network.mtprotosender:Cancelling the send loop...
DEBUG:telethon.network.mtprotosender:Cancelling the receive loop...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.51:443/TcpAbridged complete!
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.91:443/TcpAbridged...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
DEBUG:telethon.network.mtprotosender:Cancelling the send loop...
DEBUG:telethon.network.mtprotosender:Cancelling the receive loop...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.91:443/TcpAbridged complete!
</pre></details>

**Comment by Lonami** [comment]
Reason to close?

**Comment by hnikaein** [comment]
Just a mistake!

**Comment by Lonami** [comment]
Did you try reproducing in the last version? If so, could you provide minimal code to trigger the bug, and perhaps which media caused it?
