### ISSUE TITLE
_get_dc fails when called on a TakeoutClient

### ISSUE THREAD

**Issue by K900** [LonamiWebs/Telethon#1103]
`TelegramBaseClient._get_dc` refers to `self.__class__._config`, which is not set in the `TakeoutClient` wrapper, so downloading files via `TakeoutClient` occasionally fails with the following traceback:

```
Traceback (most recent call last):
  File "$virtualenv/lib/python3.7/site-packages/telethon/client/downloads.py", line 256, in download_file
    input_location, offset, part_size
telethon.errors.rpcerrorlist.FileMigrateError: The file to be accessed is currently stored in DC 4 (caused by GetFileRequest)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$my_code", line 83, in _download_if_needed
    progress_callback=update_hook
  File "$virtualenv/lib/python3.7/site-packages/telethon/client/downloads.py", line 263, in download_file
    sender = await self._borrow_exported_sender(e.new_dc)
  File "$virtualenv/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 502, in _borrow_exported_sender
    sender = await self._create_exported_sender(dc_id)
  File "$virtualenv/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 469, in _create_exported_sender
    dc = await self._get_dc(dc_id)
  File "$virtualenv/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 448, in _get_dc
    if not cls._config:
AttributeError: type object '_TakeoutClient' has no attribute '_config'
```

A simple fix would be `cls = TelegramBaseClient`, which is what I've done locally, but I'm not sure if it's correct for all cases.

**Comment by cher-nov** [comment]
Seems to be fixed now, please test.
@K900

**Comment by K900** [comment]
I couldn't reproduce this consistently before either, but it seems to be working fine now.
