### ISSUE TITLE
Disconnect in destructor causes asyncio errors

### ISSUE THREAD

**Issue by dmig** [LonamiWebs/Telethon#1133]
Python 3.6.7 x64, Ubuntu 18.10, latest code from `master` branch.

Nailed down an error:
```
2019-03-13 20:23:03,672 E asyncio Task was destroyed but it is pending!
task: <Task pending coro=<_recv_loop() running at lib/python3.6/site-packages/telethon/network/mtprotosender.py:416> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc534ab2a98>()]>>
Exception ignored in: <coroutine object _recv_loop at 0x7fc534a71f10>
Traceback (most recent call last):
  File "lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 416, in _recv_loop
    body = await self._connection.recv()
  File "lib/python3.6/site-packages/telethon/network/connection/connection.py", line 119, in recv
    result = await self._recv_queue.get()
  File "/usr/lib/python3.6/asyncio/queues.py", line 169, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.6/asyncio/base_events.py", line 580, in call_soon
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 366, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-03-13 20:23:03,674 E asyncio Task was destroyed but it is pending!
task: <Task pending coro=<_send_loop() running at lib/python3.6/site-packages/telethon/network/mtprotosender.py:378> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc534ab2ca8>()]>>
2019-03-13 20:23:03,674 E asyncio Task was destroyed but it is pending!
task: <Task pending coro=<Connection._send_loop() running at lib/python3.6/site-packages/telethon/network/connection/connection.py:131> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc534ab2cd8>()]>>
2019-03-13 20:23:03,674 E asyncio Task was destroyed but it is pending!
task: <Task pending coro=<Connection._recv_loop() running at lib/python3.6/site-packages/telethon/network/connection/connection.py:149> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc534ab2af8>()]>>
2019-03-13 20:23:03,674 E telethon.network.connection.connection Unexpected exception in the send loop
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/python3.6/site-packages/telethon/network/connection/connection.py", line 131, in _send_loop
    self._send(await self._send_queue.get())
  File "/usr/lib/python3.6/asyncio/queues.py", line 169, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.6/asyncio/base_events.py", line 580, in call_soon
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 366, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Connection._send_loop at 0x7fc534a71fc0>
Traceback (most recent call last):
  File "lib/python3.6/site-packages/telethon/network/connection/connection.py", line 141, in _send_loop
    self.disconnect()
  File "lib/python3.6/site-packages/telethon/network/connection/connection.py", line 96, in disconnect
    self._recv_task.cancel()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 580, in call_soon
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 366, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-03-13 20:23:03,676 E asyncio Task was destroyed but it is pending!
task: <Task pending coro=<UpdateMethods._update_loop() done, defined at lib/python3.6/site-packages/telethon/client/updates.py:207> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc534ab2b28>()]>>
```

Reason:
```python
# create client, connect, do something
del client
# ... and soon after
loop.close()
```

Not sure if it's a python issue, maybe a way how GC works or destructor being called. But definitely, all disconnect routines must await their tasks.

For now, the workaround is:
```python
# create the client, connect, do something
client.disconnect()
del client
# ... and soon after
loop.close()
```
Calling `.disconnect()` manually helps.

**Comment by dmig** [comment]
Update: calling `.disconnect()` manually helps only on simple testcase. For more complex code with socket server only 0.5s sleep before `loop.stop()` help to prevent this error.

**Comment by dmig** [comment]
Better workaround:
```python
# create the client, connect, do something, disconnect
loop.run_until_complete(asyncio.wait(asyncio.Task.all_tasks(loop))) 
loop.close()
```

**Comment by Lonami** [comment]
> Disconnect in destructor

Thing is `disconnect` is not called in `__del__`, but the issue persists. It is very unfortunate that Python's `asyncio` has no way to `Task.cancel()` without requiring the loop to run that task again, just to kill it, because in my opinion `disconnect` should *not* be asynchronous.

I actually purposedly introduced that change in https://github.com/LonamiWebs/Telethon/commit/9cbc088b76b99527ef47e1dc20afeb0de356b20d in a non-breaking way and now reverting it would be breaking.

The only real reason to `disconnect` in `__del__` (which I emphasize does *not* happen in your issue) is to properly close everything, including the session file, giving it a chance to save entities to disk, because else a lot of people complain that "it can't find the corresponding entity" (and it's their fault because they are supposed to disconnect).

You can run `loop.run_until_complete(asyncio.wait(asyncio.Task.all_tasks(loop)))`, but it would be trickier for the library, because we don't want to unconditionally run all tasks until their completion. Who knows what the user has in there.

Thoughts?
