### ISSUE TITLE
ValueError: Cannot find any entity corresponding to "****" For Groups

### ISSUE THREAD

**Issue by alebuffoli** [LonamiWebs/Telethon#1135]
I'm trying to get the messages from a group.
I've updated the library to the last version.

I'm using this cycle:
```
for message in client.iter_messages("GO VIRAL Dx24h"):
      print(message)
```

But if I start it, I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/Telethon/telethon/requestiter.py", line 88, in __next__
    return self.client.loop.run_until_complete(self.__anext__())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/root/Telethon/telethon/requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "/root/Telethon/telethon/client/messages.py", line 23, in _init
    self.entity = await self.client.get_input_entity(entity)
  File "/root/Telethon/telethon/client/users.py", line 315, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/root/Telethon/telethon/client/users.py", line 448, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "GO VIRAL Dx24h"
```

then I thought it could be an error caused by me coping and pasting the name, so I tried:

```
result = client(functions.messages.CheckChatInviteRequest(hash='Brlog0fOzcdVyD9e_4tStg'))

print(result.chat.title)
```
And it prints:
```
GO VIRAL Dx24h
```
So I tried whit this code:
```
for message in client.iter_messages(result.chat.title):
        print(message)
```

But I'm getting the same error, I guess that what I'm doing it is correct. Hopefully I can find a solution because I really like this library.

Thankyou

**Comment by Lonami** [comment]
Using chat titles is a bad idea because you rely on them being cached and not having changed. The documentation goes in depth about entities.

**Comment by SmartManoj** [comment]
Is there any friendly method for this ?

**Comment by Lonami** [comment]
@SmartManoj this is the wrong place for questions.

**Comment by XinTact69** [comment]
How about send message with link as username??
