### ISSUE TITLE
'The server closed the connection' during media download

### ISSUE THREAD

**Issue by dmig** [LonamiWebs/Telethon#1146]
Looks like the old bug is back in master branch: no retry after server closes the connection.

I left my app running for a few hours, later found this in logs:
```
...
2019-03-31 18:11:14,730 I telethon.network.mtprotosender Connecting to 149.154.167.92:443/TcpFull...
2019-03-31 18:11:15,315 I telethon.network.connection.connection The server closed the connection
2019-03-31 18:11:15,316 E lib.daemon.core Repost failed: 1044298783/3686
Traceback (most recent call last):
  File "lib/daemon/core.py", line 124, in _repost_message
    m_id = await xposter.upload()
  File "lib/xpost.py", line 624, in upload
    if not await a.upload():
  File "lib/xpost.py", line 119, in upload
    filename = await self._download_media()
  File "lib/python3.7/site-packages/telethon/client/downloads.py", line 153, in download_media
    media, file, date, progress_callback
  File "lib/python3.7/site-packages/telethon/client/downloads.py", line 328, in _download_photo
    progress_callback=progress_callback)
  File "lib/python3.7/site-packages/telethon/client/downloads.py", line 231, in download_file
    sender = await self._borrow_exported_sender(dc_id)
  File "lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 510, in _borrow_exported_sender
    sender = await self._create_exported_sender(dc_id)
  File "lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 488, in _create_exported_sender
    proxy=self._proxy
  File "lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 140, in connect
    await self._connect()
  File "lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 237, in _connect
    await authenticator.do_authentication(plain)
  File "lib/python3.7/site-packages/telethon/network/authenticator.py", line 31, in do_authentication
    res_pq = await sender.send(ReqPqMultiRequest(nonce))
  File "lib/python3.7/site-packages/telethon/network/mtprotoplainsender.py", line 36, in send
    body = await self._connection.recv()
  File "lib/python3.7/site-packages/telethon/network/connection/connection.py", line 123, in recv
    raise ConnectionError('Not connected')
ConnectionError: Not connected
...
```

Can't add any details right now, I'll watch for this to repeat to see any regularity. Probably I was downloading too many times over the short period, but official client downloads dozens of photos/videos at once. I download only one file at a time, so definitely no parallel downloads happen.

**Comment by Lonami** [comment]
You seem to be downloading media from a different data center. I tried downloading media from a data center which I know is not mine with:
```python
with client:
    msgs = client.get_messages('TelethonRussian', 4, offset_id=14219)
    for _ in range(3):
        for msg in msgs:
            msg.download_media()
```

And it worked correctly. It wouldn't surprise me if (re)connections aren't handled as well in exported senders, though.
