### ISSUE TITLE
PersistentTimestampInvalidError when handle events

### ISSUE THREAD

**Issue by bugchecker** [LonamiWebs/Telethon#1160]
I subscribed to message events:
```python
@events.MessageEdited(chats=listen_chats)
@events.NewMessage(chats=listen_chats)
async def handler(event):
    print(f"{'edited' if event.edit_date else 'new'} {event.message.id} {event.message.date}")

with client:
    client.run_until_disconnect()
```
And after starting event loop I get errors from time to time:
![Screenshot_2019-04-20_13-34-25](https://user-images.githubusercontent.com/10050080/56456471-730ec680-635c-11e9-9b59-f2e9aa280dfa.png)
The most of `GetDifferenceRequest` requests finish successfully but some of it fail. `handler` accept listen events and can handle it (the errors appear in the background). The errors will appear if listen chats don't produce message events (and if produce too). If `PersistenTimestampInvalidError` is expected error, it should be retrieved by its launcher, but I cannot diagnose that case. Debugging commit: https://github.com/bugchecker/Telethon/commit/33cce810041493e36293ae62bb15290f2de8d59a

**Comment by bugchecker** [comment]
My code is more complexity, but I don't think that it is source of the errors
<details>
<summary>code</summary>

```python
assert not client.list_event_handlers()

def multiple_raise(errors):
    try:
        raise errors.pop()
    finally:
        if errors:
            multiple_raise(errors)

print(f'monitoring started at {datetime.utcnow()}Z')
with client:
    listen_chats = list(dialogs)
    listen_events = [
        events.MessageEdited(chats=listen_chats),
        events.NewMessage(chats=listen_chats)
    ]
    for event in listen_events:
        client.add_event_handler(handler, event)
    try:
        client.run_until_disconnected()
    except (KeyboardInterrupt, Exception) as e:
        for event in listen_events:
            client.remove_event_handler(handler, event)
        cancelled = [task for task in asyncio.Task.all_tasks() if task.cancelled()]
        try:
            returned_errors = loop.run_until_complete(asyncio.gather(*cancelled, return_exceptions=True))
            non_cancelled = [e for e in returned_errors if not isinstance(e, asyncio.CancelledError)]
            if non_cancelled:
                multiple_raise(e, *non_cancelled)
        except KeyboardInterrupt:
            raise
        if not isinstance(e, KeyboardInterrupt):
            print(f'monitoring broken at {datetime.utcnow()}Z')
            raise
    print(f'monitoring stopped at {datetime.utcnow()}Z')
```

</details>

**Comment by Lonami** [comment]
See #1125. This is a known bug I haven't yet fixed in `master`.

**Comment by Lonami** [comment]
That should probably help.

**Comment by bugchecker** [comment]
LGTM. No more error messages. Thank you.

**Comment by bugchecker** [comment]
```
ERROR:telethon.network.mtprotosender:Unhandled error while processing msgs
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtprotosender.py", line 443, in _recv_loop
    await self._process_message(message)
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtprotosender.py", line 458, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtprotosender.py", line 533, in _handle_container
    await self._process_message(inner_message)
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtprotosender.py", line 458, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtprotosender.py", line 550, in _handle_update
    self._update_callback(message.obj)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 207, in _handle_update
    self._process_update(u, entities)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 216, in _process_update
    update._pts_date = self._state_cache[StateCache.get_channel_id(update)]
  File "/usr/local/lib/python3.7/dist-packages/telethon/statecache.py", line 106, in get_channel_id
    return update.message.to_id.channel_id
AttributeError: 'NoneType' object has no attribute 'channel_id'
```

**Comment by Lonami** [comment]
`to_id` can be `None`? That's interesting. I wonder when it happens.

**Comment by Lonami** [comment]
Could you print that faulty update or message and show it here?

**Comment by bugchecker** [comment]
It's a rare event. May be it's a mistake in my code.  I will observe to catch it.

**Comment by Lonami** [comment]
`to_id` is not optional in `Message` and `MessageService`. It's only missing on `MessageEmpty`, and those should not arrive as update.

**Comment by Lonami** [comment]
Good enough for me.

**Comment by Lonami** [comment]
Good enough for me.

**Comment by bugchecker** [comment]
```
<class 'telethon.tl.core.tlmessage.TLMessage'>
{'_': 'TLMessage', 'msg_id': 6683410539422996481, 'seq_no': 440, 'obj': <telethon.tl.core.messagecontainer.MessageContainer object at 0x7fdc9ed237f0>}
```
It catched by `events.Raw()`, not by `NewMessage`/`MessageEdited`. I continue using https://github.com/LonamiWebs/Telethon/commit/c1880c9191120526b584339ed0648eed9cd71a54 without updating.

**Comment by Lonami** [comment]
`TLMessage`'s should not be being dispatched to update handlers.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/40d32cee957414378dfb9bb793df73f517f9216b should keep us safe from such things being dispatched there.
