### ISSUE TITLE
ConnectionError: Not connected

### ISSUE THREAD

**Issue by feng504x** [LonamiWebs/Telethon#1187]
api_id = 123456
api_hash = 'xxxxxxxxxxxxxxxx'

with TelegramClient('testApp', api_id, api_hash) as client:
    client.send_message('me', 'Hello, myself!')

**Comment by feng504x** [comment]
how do i solve this problem?

**Comment by Lonami** [comment]
Please enable `logging` as explained documentation and show the output with *that`* code.

**Comment by DenisVanyushkin** [comment]
can I continue this conversation?
so my code mostly took from documentation:

import logging
from decouple import config
from telethon.sync import TelegramClient

# Use your own values from my.telegram.org
api_id = config('APP_API_ID', cast=int)
api_hash = config('APP_API_HASH')
logging.basicConfig(level=logging.DEBUG)

# The first parameter is the .session file name (absolute paths allowed)
with TelegramClient('anon', api_id, api_hash) as client:
    # Getting information about yourself
    me = client.get_me()


and this is the output:

DEBUG:asyncio:Using selector: KqueueSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 1...
INFO:telethon.network.connection.connection:The server closed the connection
WARNING:telethon.network.connection.connection:Unhandled <class 'ConnectionResetError'> on disconnect: [Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "/Users/denisvanyushkin/OneDrive/Programming/Projects/informer/tg_client.py", line 12, in <module>
    with TelegramClient('anon', api_id, api_hash) as client:
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/helpers.py", line 122, in _sync_enter
    return loop.run_until_complete(self.__aenter__())
  File "/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/client/auth.py", line 631, in __aenter__
    return await self.start()
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/client/auth.py", line 141, in _start
    await self.connect()
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 412, in connect
    proxy=self._proxy
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 122, in connect
    await self._connect()
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 218, in _connect
    await authenticator.do_authentication(plain)
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/network/authenticator.py", line 31, in do_authentication
    res_pq = await sender.send(ReqPqMultiRequest(nonce))
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/network/mtprotoplainsender.py", line 36, in send
    body = await self._connection.recv()
  File "/Users/denisvanyushkin/python/informer/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 142, in recv
    raise ConnectionError('Not connected')
ConnectionError: Not connected

is it authentication problem?

**Comment by DenisVanyushkin** [comment]
@Lonami hello, could you please comment?
should I open a new issue?

**Comment by Lonami** [comment]
Does it happen consistently? Is your country limited?

**Comment by DenisVanyushkin** [comment]
This is the only result I get
By limited you mean Telegram blocking by state? No, it is available in my country

**Comment by Lonami** [comment]
What version are you using?

**Comment by DenisVanyushkin** [comment]
1.8.0

**Comment by Lonami** [comment]
It is strange, because it's working for me and probably everyone else or there would be more reports. Telegram shouldn't be closing the connection so early and I don't know if reconnecting will help.

**Comment by DenisVanyushkin** [comment]
I just tried to put this code to DO VPS and it's worked

So problem in my Mac, please advice what should I check?

**Comment by Lonami** [comment]
The log says `INFO:telethon.network.connection.connection:The server closed the connection`, but it doesn't say *when* it happened (i.e. has it sent/received any data at all before this happened?) which would be helpful to know, so if you're willing to investigate that (maybe add a breakpoint on that log line so you can inspect the stack back up), it would be nice.

**Comment by DenisVanyushkin** [comment]
So it is happened on one of iteration at base_events.py, line 539.
I am really happy to help, but I'm not sure what to do - I'm quite new at programming

**Comment by Lonami** [comment]
`asyncio` way of dealing with sockets probably won't make debugging this easier, due to how it works. It may not be a suitable task for a new comer like you, and that's fine.

**Comment by DenisVanyushkin** [comment]
OK, so if I can help you somehow - just let me know

**Comment by Lonami** [comment]
Closing due to inactivity. Might be related to the more recent #1376 so discussion should probably happen there.

**Comment by sinarezaei** [comment]
I'm facing the same issue

I simply start the telethon and wait for the updates via client.run_until_disconnected and after few minutes I get a `Connection Error: Not Connected` Exception

Traceback:
`
Trace: Traceback (most recent call last):
  File "main_telegram.py", line 841, in <module>
    loop.run_until_complete(start_telegram(loop=loop))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "main_telegram.py", line 199, in start_telegram
    return await client.run_until_disconnected()
  File "/usr/local/lib/python3.7/site-packages/telethon/client/updates.py", line 24, in _run_until_disconnected
    return await self.disconnected
ConnectionError: Not connected
`


Logs:
'
[DEBUG/2020-12-12 03:14:22,270] my_package.extensions.messagepacker: Assigned msg_id = 6905148897160183816 to PingRequest (7f514be15090)
[DEBUG/2020-12-12 03:14:22,270] my_package.network.mtprotosender: Encrypting 1 message(s) in 28 bytes for sending
[DEBUG/2020-12-12 03:14:22,270] my_package.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2020-12-12 03:14:22,270] my_package.network.mtprotosender: Waiting for messages to send...
[DEBUG/2020-12-12 03:14:22,270] my_package.extensions.messagepacker: Assigned msg_id = 6905148897163041024 to MsgsAck (7f514be15b10)
[DEBUG/2020-12-12 03:14:22,271] my_package.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2020-12-12 03:14:22,271] my_package.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2020-12-12 03:14:22,271] my_package.network.mtprotosender: Waiting for messages to send...
[DEBUG/2020-12-12 03:14:22,366] my_package.network.mtprotosender: Handling pong for message 6905148897160183816
[DEBUG/2020-12-12 03:14:22,367] my_package.network.mtprotosender: Receiving items from the network...
[DEBUG/2020-12-12 03:15:22,332] my_package.extensions.messagepacker: Assigned msg_id = 6905149155108906312 to PingRequest (7f514be157d0)
[DEBUG/2020-12-12 03:15:22,333] my_package.network.mtprotosender: Encrypting 1 message(s) in 28 bytes for sending
[DEBUG/2020-12-12 03:15:22,333] my_package.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2020-12-12 03:15:22,333] my_package.network.mtprotosender: Waiting for messages to send...
[DEBUG/2020-12-12 03:15:22,334] my_package.extensions.messagepacker: Assigned msg_id = 6905149155114301248 to MsgsAck (7f514be15590)
[DEBUG/2020-12-12 03:15:22,334] my_package.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2020-12-12 03:15:22,336] my_package.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2020-12-12 03:15:22,336] my_package.network.mtprotosender: Waiting for messages to send...
[ INFO/2020-12-12 03:15:22,367] my_package.network.connection.connection: The server closed the connection
[ INFO/2020-12-12 03:15:22,374] my_package.network.mtprotosender: Connection closed while receiving data
[ INFO/2020-12-12 03:15:22,375] my_package.network.mtprotosender: Closing current connection to begin reconnect...
[ERROR/2020-12-12 03:15:22,375] my_package.network.mtprotosender: Automatic reconnection failed 0 time(s)
[ INFO/2020-12-12 03:15:22,375] my_package.network.mtprotosender: Disconnecting from 149.154.167.91:443/TcpFull...
[DEBUG/2020-12-12 03:15:22,376] my_package.network.mtprotosender: Closing current connection...
[DEBUG/2020-12-12 03:15:22,376] my_package.network.mtprotosender: Cancelling 1 pending message(s)...
[ INFO/2020-12-12 03:15:22,376] my_package.network.mtprotosender: Disconnection from 149.154.167.91:443/TcpFull complete!
[ERROR/2020-12-12 03:15:22,376] asyncio: Future exception was never retrieved
future: <Future finished exception=ConnectionError('Not connected')>
'

**Comment by Lonami** [comment]
What is some minimal code sample that triggers the above issue?
