### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by SachinNandal** [LonamiWebs/Telethon#1219]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
with TelegramClient(phone, api_id, api_hash) as client:
    client.send_message('me', 'Hello, myself!')
    print("hello")
    
...

```

**Traceback**
```
Traceback (most recent call last):

  File "<ipython-input-49-cf2c1ed7ccdb>", line 14, in <module>
    with TelegramClient(phone, api_id, api_hash) as client:

  File "C:\Users\Sac\Anaconda3\lib\site-packages\telethon\client\telegrambaseclient.py", line 200, in __init__
    base_logger = __default_log__

TypeError: __init__() got an unexpected keyword argument 'timeout'
```

**Comment by SachinNandal** [comment]
Please help me to solve this error TypeError: __init__() got an unexpected keyword argument 'timeout'
