### ISSUE TITLE
RCP Server Error

### ISSUE THREAD

**Issue by IlyaSemenov** [LonamiWebs/Telethon#124]
This was discussed in #105 (now closed) but it's probably not related, so I'll put it into a new ticket.

Every now and then Telethon crashes with a `ServerError`:

```
Traceback (most recent call last):
  File "/root/foo/foo.py", line 420, in send_command
    self.telegram.send_message(entity, text)
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_client.py", line 417, in send_message
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_client.py", line 226, in invoke
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/telegram_bare_client.py", line 189, in invoke
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 106, in receive
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 205, in _process_msg
  File "/root/.pyenv/versions/foo/lib/python3.5/site-packages/Telethon-0.10.1-py3.5.egg/telethon/network/mtproto_sender.py", line 353, in _handle_rpc_result
telethon.errors.rpc_errors.ServerError
```

As asked in #105, I logged parameters passed to `rpc_message_to_error`:

```python
# telethon/errors/__init__.py

    elif code == 500:
        import sys; print("rpc_message_to_error({}, {})".format(code, message), file=sys.stderr)
        return ServerError()
```

which prints:

```
>>> rpc_message_to_error(500, RPC_CALL_FAIL)
```

Unfortunately, I don't know the specific steps to reproduce this. Due to privacy reasons, I don't include the message but it's not something special (meaning that the bot sends exactly the same message many times, and only in rare cases it leads to the crash.)

I understand that it's a *server* error and chances are Telethon is not causing it directly, meaning it's not really a *bug* that can be fixed. But since it's quite common I believe we may benefit if it's somehow handled in Telethon itself (some sort of automatic reconnect maybe?) rather than requiring each and every client to include `try/except` boilerplate.

**Comment by Lonami** [comment]
> I believe we may benefit if it's somehow handled in Telethon itself (some sort of automatic reconnect maybe?) rather than requiring each and every client to include `try/except` boilerplate.

I've never got one of this, so I can't quite test whether a simple reconnect would work. Have you tried to add said `try/except`, and reconnecting on said except? Does it work just fine if you resend the *same* request afterwards? If so, we can simply move it to the `TelegramBareClient.invoke()` method.

As a side note, editing your issue will not notify me, so you were lucky I was checking over the issues. Next time simply post a new comment if it adds new information, and if it's not a very quick change.

**Comment by danog** [comment]
As you can see here https://github.com/danog/MadelineProto/blob/master/src/danog/MadelineProto/RPCErrorException.php#L21, `RPC_CALL_FAIL` and `RPC_MCGET_FAIL` (and a few others) are the RPC errors triggered by KPHP's RPC proxy that forwards requests to the various machines in the telegram datacenters.
If you get one of those RPC errors, it means telegram devs messed something up on the production environment (that is, assuming they don't use the infinite deploy method as described in https://twitter.com/php_ceo/status/622402637883944961: in this case, they most likely hit save in the IDE without closing a brace, first :^)
