### ISSUE TITLE
ConnectionError during DC change

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#1273]
Telethon v1.9.0

**Traceback**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 70, in _request
    result = await self._sender.send(self.request)
telethon.errors.rpcerrorlist.FileMigrateError: The file to be accessed is currently stored in DC 1 (caused by GetFileRequest)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  .....
  .....
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 352, in download_media
    media, file, date, thumb, progress_callback
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 714, in _download_document
    progress_callback=progress_callback
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 435, in download_file
    input_location, request_size=part_size, dc_id=dc_id):
  File "/usr/local/lib/python3.6/dist-packages/telethon/requestiter.py", line 75, in __anext__
    if await self._load_next_chunk():
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 60, in _load_next_chunk
    cur = await self._request()
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/downloads.py", line 78, in _request
    self._sender = await self.client._borrow_exported_sender(e.new_dc)
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/telegrambaseclient.py", line 587, in _borrow_exported_sender
    sender = await self._create_exported_sender(dc_id)
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/telegrambaseclient.py", line 565, in _create_exported_sender
    proxy=self._proxy
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/mtprotosender.py", line 122, in connect
    await self._connect()
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/mtprotosender.py", line 218, in _connect
    await authenticator.do_authentication(plain)
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/authenticator.py", line 145, in do_authentication
    encrypted_data=client_dh_encrypted,
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/mtprotoplainsender.py", line 36, in send
    body = await self._connection.recv()
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/connection/connection.py", line 142, in recv
    raise ConnectionError('Not connected')
ConnectionError: Not connected
```

**Comment by Lonami** [comment]
Is there any way to reliably and consistently reproduce this issue? From my attempts, downloading media from another datacenter gives me no issues.

**Comment by hnikaein** [comment]
Unfortunately no. I receive this error rarely.
I think this problem raises when there is an issue with connection together with dc change.

**Comment by Lonami** [comment]
This is an old issue, so I'll close it, and nobody else seems to have complained. If there's a way to reproduce in newer versions, post the relevant code/traceback and we may be able to look at it again.
