### ISSUE TITLE
User cli On update  error

### ISSUE THREAD

**Issue by micodev** [LonamiWebs/Telethon#1278]
```
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetPeerDialogsRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 454, in _get_difference
    utils.get_input_dialog(where)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetPeerDialogsRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
Task exception was never retrieved
future: <Task finished coro=<_dispatch_update() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 381, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/updates.py", line 464, in _get_difference
    force=True
  File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 64, in __call__
    result = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
```

**Comment by Lonami** [comment]
Old version.
