### ISSUE TITLE
Error when calling the get_participants method

### ISSUE THREAD

**Issue by duanzheng** [LonamiWebs/Telethon#1299]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

telegram_client = TelegramClient(
    StringSession("xxx"),
    "xxx",
    "xxx",
).start()
channel = telegram_client.get_input_entity("xxx")
responses = telegram_client.get_participants(channel, aggressive=True)
```

**Traceback**
```
([None, FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)',), FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)',), FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)',), FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)',), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.types.channels.ChannelParticipants object at 0x7fae43d3ad30>, None, None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43ce39b0>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae4803b908>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43d18b38>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43d6e4e0>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43c68860>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43b89e48>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43bc45c0>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43b67f60>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43ac04a8>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43a99160>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43a6d6d8>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae4398cf60>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43967550>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae439c4a20>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae438c84a8>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae438926d8>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae4386c9e8>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae437c1b38>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43792e80>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae43768278>, <telethon.tl.types.channels.ChannelParticipants object at 0x7fae436bae80>], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4804c6a0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e358>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e5c0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e630>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e6a0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e710>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e780>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e7f0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e860>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e8d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e940>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806e9b0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ea20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ea90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806eb00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806eb70>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ebe0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ec50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ecc0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ed30>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806eda0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ee10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ee80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806eef0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806ef60>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7fae4806efd0>])
```

**Comment by Lonami** [comment]
Closing as won't fix. The flood wait for `get_participants` varies per account, and if we added a sleep it would be ridiculously slow for everyone else. You can stop using `aggessive=True` to perform a slower search, which should hit less flood waits.

**Comment by csuresh** [comment]
> Closing as won't fix. The flood wait for `get_participants` varies per account, and if we added a sleep it would be ridiculously slow for everyone else. You can stop using `aggessive=True` to perform a slower search, which should hit less flood waits.

Thanks. Well done.

**Comment by vishalsharma9411** [comment]
Fetching Members...
Traceback (most recent call last):
  File "C:\Users\visha\PycharmProjects\test\pythonProject2\Other Work\copyer online by numbers one.py", line 90, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "C:\Paython 39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Paython 39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Paython 39\lib\site-packages\telethon\client\chats.py", line 474, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Paython 39\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Paython 39\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Paython 39\lib\site-packages\telethon\client\chats.py", line 200, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Paython 39\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Paython 39\lib\site-packages\telethon\client\users.py", line 75, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), None, None, None, None, FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)')], [None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x0000025272239100>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000025271C25EE0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000025271B022E0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000025271C25BE0>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AA9B50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000252719C8940>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEA00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEAC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEB80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEC40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAED00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEDC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEE80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEF40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2040>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2100>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB21C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2280>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2340>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2400>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB24C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2580>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2640>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2700>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB27C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2880>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2940>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2A00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2AC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2B80>])

Process finished with exit code 1

**Comment by arthurbarros** [comment]
This is happening to me as well, was working normaly and 2 days ago started to give FloodWaitError when using agressive=True

**Comment by Codeforhelping** [comment]
> ccount, and if w

yeah my friend what to do no clue bro

**Comment by Lonami** [comment]
#928.
