### ISSUE TITLE
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object....

### ISSUE THREAD

**Issue by bertploeger** [LonamiWebs/Telethon#1307]
Hi,

I upgraded telethon to 1.10 and found al lot of errors. I tried to disable all my @client event handlers to make sure it was not something in my code. After searching for current bugs it seems that #1303 was fixed in 1.9, but i think it is still present in 1.10.0.

```
bash-5.0# pip3 install telethon==1.10
Requirement already satisfied: telethon==1.10 in /usr/lib/python3.7/site-packages (1.10.0)
```

My Python version is:

```
bash-5.0# python3.7
Python 3.7.5 (default, Oct 17 2019, 12:25:15) 
```

The exception thrown is:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<UpdateMethods._dispatch_update() done, defined at /usr/lib/python3.7/site-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)')>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/telethon/client/updates.py", line 382, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/lib/python3.7/site-packages/telethon/client/updates.py", line 473, in _get_difference
    force=True
  File "/usr/lib/python3.7/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
```

**Comment by bertploeger** [comment]
I found there is a newer version 1.10.7 which seems to be ok.

**Comment by alirezaimi** [comment]
I have this problem in 1.10.9 version.

**Comment by bakiev** [comment]
this usually means it's time to upgrade telethon :)

**Comment by KTGJ** [comment]
Faced the same problem. Yesterday I updated the telethon, but this did not solve the problem. (python 3.7)

**Comment by Lonami** [comment]
Unless you provide the code amd scenario needed to trigger the bug, no help can be given. Access hashes from other accounts will also not work.

**Comment by c3rf1g** [comment]
gavno kotoroe ne reshaetsya

**Comment by Sanjarbek17** [comment]
i have this problem telethon 1.37.0 python 3.10.5
