### ISSUE TITLE
error when install on win

### ISSUE THREAD

**Issue by seby2000** [LonamiWebs/Telethon#133]
os - windows 7

```
C:\Users\seby\Desktop\project\Telethon\telethon_generator>python tl_generator.py

Traceback (most recent call last):
  File "tl_generator.py", line 9, in <module>
    from .parser import SourceBuilder, TLParser
ModuleNotFoundError: No module named '__main__.parser'; '__main__' is not a pack
age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tl_generator.py", line 11, in <module>
    from parser import SourceBuilder, TLParser
ImportError: cannot import name 'SourceBuilder'

C:\Users\seby\Desktop\project\Telethon\telethon_generator>
```

**Comment by Lonami** [comment]
```
cd ..
python telethon_generator/tl_generator.py
```

?

**Comment by seby2000** [comment]
do not work
```
C:\Users\seby\Desktop\project\Telethon\telethon_generator>cd ..

C:\Users\seby\Desktop\project\Telethon>python telethon_generator/tl_generator.py

Traceback (most recent call last):
  File "telethon_generator/tl_generator.py", line 9, in <module>
    from .parser import SourceBuilder, TLParser
ModuleNotFoundError: No module named '__main__.parser'; '__main__' is not a pack
age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "telethon_generator/tl_generator.py", line 11, in <module>
    from parser import SourceBuilder, TLParser
ImportError: cannot import name 'SourceBuilder'

C:\Users\seby\Desktop\project\Telethon>
```

**Comment by Lonami** [comment]
Change:
```python
from .parser import SourceBuilder, TLParser
```

with:
```python
from telethon_generator.parser import SourceBuilder, TLParser
```

And try again.

**Comment by seby2000** [comment]
`ModuleNotFoundError:` No module named 'telethon_generator'

**Comment by Lonami** [comment]
Have you tried both inside and outside said folder?

**Comment by seby2000** [comment]
inside it work and generate the TLObjects correctly
