### ISSUE TITLE
Exception in thread Thread-3:，TypeError: __init__() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by wdsjxh** [LonamiWebs/Telethon#1338]
mul_pool = Pool(processes=thread_number)
    for i in range(thread_number):
        print("client_name_list index ----x ")
        print(client_name_list[i - 1])
        pool_result = mul_pool.apply_async(func=done, args=(multi_pool_dict, client_name_list[i - 1], event))
        my_threading_list.append(pool_result)

Traceback (most recent call last):
  File "D:\software\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\software\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\software\Python36\lib\multiprocessing\pool.py", line 463, in _handle_results
    task = get()
  File "D:\software\Python36\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() takes 1 positional argument but 3 were given
```

**Comment by Lonami** [comment]
Do you realize the traceback doesn't mention `telethon` at all?
