### ISSUE TITLE
telethon not running on python 3.6.9

### ISSUE THREAD

**Issue by micodev** [LonamiWebs/Telethon#1339]
```Traceback (most recent call last):
  File "mainback.py", line 2, in <module>
    from telethon import TelegramClient, events, sync
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/client/__init__.py", line 12, in <module>
    from .telegrambaseclient import TelegramBaseClient
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 7, in <module>
    import typing
  File "/mnt/g/dif-project/telethon/typing.py", line 2, in <module>
    from telethon import TelegramClient, events, sync ,functions, types
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/events/__init__.py", line 1, in <module>
    from .raw import Raw
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/events/raw.py", line 1, in <module>
    from .common import EventBuilder
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/events/common.py", line 6, in <module>
    from .. import utils
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/utils.py", line 20, in <module>
    from .extensions import markdown, html
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/extensions/__init__.py", line 6, in <module>
    from .binaryreader import BinaryReader
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/extensions/binaryreader.py", line 11, in <module>
    from ..tl.alltlobjects import tlobjects
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/tl/alltlobjects.py", line 3, in <module>
    from . import types, functions, patched
  File "/home/micodev/.local/lib/python3.6/site-packages/telethon/tl/types/__init__.py", line 3, in <module>
    from typing import Optional, List, Union, TYPE_CHECKING
ImportError: cannot import name 'Optional'```

**Comment by Lonami** [comment]
Your Python installation is most likely corrupt, and reinstalling Python should fix it.
