### ISSUE TITLE
Investigate ConnectionResetError

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1346]
[Original report](https://t.me/TelethonChat/172587) follows:

> i'm having the same problem. the loop throws exceptions, but the `run_until_disconnected() `doesn't raise them.
> i get the `ConnectionResetError` thrown endlessly in the loop after I connect/reconnect from a system-wide VPN and then receive a bot event.
> ```python
> try:
>     print("Starting bot \"" + BOT_NAME + "\"...")
>     with bot:
>         bot.run_until_disconnected()
> except ConnectionResetError:
>     print("Caught ConnectionResetError exception. Restarting bot...")
> ```
>
> ```
> ERROR:asyncio:Exception in callback BaseSelectorEventLoop._read_from_self()
> handle: <Handle BaseSelectorEventLoop._read_from_self()>
> Traceback (most recent call last):
>   File "C:\Program Files\Python37\lib\asyncio\events.py", line 88, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Program Files\Python37\lib\asyncio\selector_events.py", line 114, in _read_from_self
>     data = self._ssock.recv(4096)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> ```

> any tip on how i can reproduce the issue?

> i think i can try to reproduce it by connecting and then disconnecting from a system-wide VPN on windows while the bot is running

> i'm using Windscribe VPN, which has a firewall feature that blocks connections when connecting to the VPN. maybe that helps?

**Comment by Lonami** [comment]
This is quite old and I have no idea how to reproduce this, so closing (nobody has complained they have the same issue either, so it seems rare).
