### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by invious** [LonamiWebs/Telethon#139]
Trying to `sudo -H pip install telethon` and getting:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-HgcWJO/telethon/setup.py", line 15, in <module>
        from telethon import TelegramClient
      File "telethon/__init__.py", line 1, in <module>
        from .telegram_bare_client import TelegramBareClient
      File "telethon/telegram_bare_client.py", line 9, in <module>
        from .network import authenticator, MtProtoSender, TcpTransport
      File "telethon/network/__init__.py", line 1, in <module>
        from .mtproto_plain_sender import MtProtoPlainSender
      File "telethon/network/mtproto_plain_sender.py", line 4, in <module>
        from ..extensions import BinaryReader, BinaryWriter
      File "telethon/extensions/__init__.py", line 9, in <module>
        from .tcp_client import TcpClient
      File "telethon/extensions/tcp_client.py", line 111
        'The read operation exceeded the timeout.') from error
                                                       ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-HgcWJO/telethon/
```

**Comment by Lonami** [comment]
`from error` syntax is not supported on Python 2.x. However, if that's the *only* thing that makes it not work on Python 2.x, I can change that. Did it work on Python 2 before (it was never a target for me)?
