### ISSUE TITLE
PeerFloodError

### ISSUE THREAD

**Issue by JepsonHerts** [LonamiWebs/Telethon#1399]
When i make new userbot and try to message an user, it give me this error:
 ```Traceback (most recent call last):
  File "prova2.py", line 26, in <module>
    client(SendMessageRequest(peer="JepsonHerts", message="Sei un grande"))
  File "/root/.local/lib/python3.6/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by SendMessageRequest)
```

**Comment by Lonami** [comment]
Not a bug, RPC errors are raised as intended.

**Comment by JepsonHerts** [comment]
How can i resolve?
