### ISSUE TITLE
AttributeError: 'InputFileBig' object has no attribute 'md5' while sending album

### ISSUE THREAD

**Issue by drforse** [LonamiWebs/Telethon#1400]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```
await client.send_file(entity=CHANNEL_ID, file=(long_vid_path, short_vid_path, pic_path), caption=caption, parse_mode='html')
```

**Traceback**
```
2020-03-11T01:21:17.933069+00:00 app[bot.1]: Traceback (most recent call last):
2020-03-11T01:21:17.933070+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 332, in _process_polling_updates
2020-03-11T01:21:17.933071+00:00 app[bot.1]: for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
2020-03-11T01:21:17.933072+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 188, in process_updates
2020-03-11T01:21:17.933072+00:00 app[bot.1]: return await asyncio.gather(*tasks)
2020-03-11T01:21:17.933073+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
2020-03-11T01:21:17.933073+00:00 app[bot.1]: response = await handler_obj.handler(*args, **partial_data)
2020-03-11T01:21:17.933074+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 208, in process_update
2020-03-11T01:21:17.933074+00:00 app[bot.1]: return await self.message_handlers.notify(update.message)
2020-03-11T01:21:17.933075+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
2020-03-11T01:21:17.933075+00:00 app[bot.1]: response = await handler_obj.handler(*args, **partial_data)
2020-03-11T01:21:17.933076+00:00 app[bot.1]: File "/app/bot_funcs.py", line 14, in post_now
2020-03-11T01:21:17.933077+00:00 app[bot.1]: await post_porn()
2020-03-11T01:21:17.933077+00:00 app[bot.1]: File "/app/main.py", line 36, in post_porn
2020-03-11T01:21:17.933078+00:00 app[bot.1]: await client.send_file(entity=CHANNEL_ID, file=(vid.info.download_path, demo_path, thumb_path), caption=caption, parse_mode='html')
2020-03-11T01:21:17.933078+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.8/site-packages/telethon/client/uploads.py", line 299, in send_file
2020-03-11T01:21:17.933078+00:00 app[bot.1]: result += await self._send_album(
2020-03-11T01:21:17.933079+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.8/site-packages/telethon/client/uploads.py", line 402, in _send_album
2020-03-11T01:21:17.933079+00:00 app[bot.1]: fh.md5, fh.size, utils.get_input_document(r.document))
2020-03-11T01:21:17.933080+00:00 app[bot.1]: AttributeError: 'InputFileBig' object has no attribute 'md5'

```

**Comment by drforse** [comment]
I have forked the library code and changed the _send_album method like this:
```    async def _send_album(self: 'TelegramClient', entity, files, caption='',
                          progress_callback=None, reply_to=None,
                          parse_mode=(), silent=None, schedule=None,
                          supports_streaming=None, clear_draft=None):
        """Specialized version of .send_file for albums"""
        # We don't care if the user wants to avoid cache, we will use it
        # anyway. Why? The cached version will be exactly the same thing
        # we need to produce right now to send albums (uploadMedia), and
        # cache only makes a difference for documents where the user may
        # want the attributes used on them to change.
        #
        # In theory documents can be sent inside the albums but they appear
        # as different messages (not inside the album), and the logic to set
        # the attributes/avoid cache is already written in .send_file().
        entity = await self.get_input_entity(entity)
        if not utils.is_list_like(caption):
            caption = (caption,)

        captions = []
        for c in reversed(caption):  # Pop from the end (so reverse)
            captions.append(await self._parse_message_text(c or '', parse_mode))

        reply_to = utils.get_message_id(reply_to)

        # Need to upload the media first, but only if they're not cached yet
        media = []
        for file in files:
            # Albums want :tl:`InputMedia` which, in theory, includes
            # :tl:`InputMediaUploadedPhoto`. However using that will
            # make it `raise MediaInvalidError`, so we need to upload
            # it as media and then convert that to :tl:`InputMediaPhoto`.
            fh, fm, _ = await self._file_to_media(
                file, supports_streaming=supports_streaming)
            if isinstance(fm, types.InputMediaUploadedPhoto):
                r = await self(functions.messages.UploadMediaRequest(
                    entity, media=fm
                ))
                self.session.cache_file(
                    fh.md5, fh.size, utils.get_input_photo(r.photo))

                fm = utils.get_input_media(r.photo)
            elif isinstance(fm, types.InputMediaUploadedDocument):
                r = await self(functions.messages.UploadMediaRequest(
                    entity, media=fm
                ))
                try:
                    self.session.cache_file(
                        fh.md5, fh.size, utils.get_input_document(r.document))
                except AttributeError:
                    pass

                fm = utils.get_input_media(
                    r.document, supports_streaming=supports_streaming)

            if captions:
                caption, msg_entities = captions.pop()
            else:
                caption, msg_entities = '', None
            media.append(types.InputSingleMedia(
                fm,
                message=caption,
                entities=msg_entities
                # random_id is autogenerated
            ))

        # Now we can construct the multi-media request
        request = functions.messages.SendMultiMediaRequest(
            entity, reply_to_msg_id=reply_to, multi_media=media,
            silent=silent, schedule_date=schedule, clear_draft=clear_draft
        )
        result = await self(request)

        random_ids = [m.random_id for m in media]
        return self._get_response_message(random_ids, result, entity)
```

But I don't know if it a good resolving)0))
