### ISSUE TITLE
AttributeError: 'TelegramClient' object has no attribute '_cache_media'

### ISSUE THREAD

**Issue by TishSerg** [LonamiWebs/Telethon#1418]
**Version**
```
>>> import telethon; print(telethon.__version__)
1.11.3
```

**Code that causes the issue**
```python
import telethon
...
async def callback_query_handler(event: telethon.events.CallbackQuery):
    await event.edit(text='new text1', buttons=[telethon.Button.inline('New btn')])
    pass
...
ui_tg_bot = telethon.TelegramClient(...)
ui_tg_bot.add_event_handler(callback_query_handler, telethon.events.CallbackQuery)
ui_tg_bot.start(bot_token=bot_token)
ui_tg_bot.run_until_disconnected()
```

**Traceback**
```
[ERROR/2020-03-27 19:04:22,200] telethon.client.updates: Unhandled exception on callback_query_handler
Traceback (most recent call last):
  File "C:\Users\████\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\telethon\client\updates.py", line 428, in _dispatch_update
    await callback(event)
  File "D:\Lab\_repos\████████\████████.py", line 51, in callback_query_handler
    await event.edit(text='new text1', buttons=[telethon.Button.inline('New btn')])
  File "C:\Users\████\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\telethon\events\callbackquery.py", line 318, in edit
    return await self._client.edit_message(
  File "C:\Users\████\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\telethon\client\messages.py", line 1049, in edit_message
    await self._cache_media(msg, file, file_handle, image=image)
AttributeError: 'TelegramClient' object has no attribute '_cache_media'
```

**Comment by YouTwitFace** [comment]
https://github.com/LonamiWebs/Telethon/commit/68438f462127fa02021f40a0e2d686072978a264
