### ISSUE TITLE
I don't recieve verification code

### ISSUE THREAD

**Issue by Magaknuto** [LonamiWebs/Telethon#1423]
I am trying to use telethon on ubuntu running on aws ec2 and I can't receve the code. Same is happening to my phone running ubuntu with linux deploy (with full root access).
On my main ubuntu computer I managed to get verification code and everything is working.

the error I get on other devices is 

```
Traceback (most recent call last):
  File "tutorial.py", line 60, in <module>
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "tutorial.py", line 51, in main
    channel = await client(GetChannelsRequest(id=['Real group example']))
  File "/home/magaknuto/.local/lib/python3.6/site-packages/telethon/client/users.pine 34, in __call__
    await r.resolve(self, utils)
  File "/home/magaknuto/.local/lib/python3.6/site-packages/telethon/tl/functions/cls.py", line 643, in resolve
    _tmp.append(utils.get_input_channel(await client.get_input_entity(_x)))
  File "/home/magaknuto/.local/lib/python3.6/site-packages/telethon/client/users.pine 404, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/home/magaknuto/.local/lib/python3.6/site-packages/telethon/client/users.pine 538, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "Real group example"
```

with the unchanged code that worked before
same thing happens if I try to send message to gruop

My code is:
```
from telethon.tl.functions.channels import GetChannelsRequest, JoinChannelRequest
from telethon import TelegramClient
from telethon.tl.types import InputPeerChannel
import os

session_file = "./my_cred.session"
api_id = "1385502"
api_hash = "319cc3dd4ce9b9addb263c44791fcd23"
phone = "+387065021796"

async def main():
    # await client.send_message("Call me Johny", 'Hello, this is test!')
    channel = await client(GetChannelsRequest(id=['Real group example']))
    print(channel)
    print(channel.chats[0].access_hash)
    chanel_entity = InputPeerChannel(
        channel.chats[0].id, channel.chats[0].access_hash)
    # await client(JoinChannelRequest(channel=chanel_entity))
    await client.send_message(entity=chanel_entity, message="opet s akompjutera")

with TelegramClient(session_file, api_id, api_hash) as client:
    client.loop.run_until_complete(main())
```

**Comment by Magaknuto** [comment]
I managed to connect from aws ec2. but still get:

```
...
 File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "tutorial.py", line 47, in main
    channel = await client(GetChannelsRequest(id=['Real group example']))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telethon/client/users.py", line 34, in __call__
    await r.resolve(self, utils)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telethon/tl/functions/channels.py", line 643, in resolve
    _tmp.append(utils.get_input_channel(await client.get_input_entity(_x)))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telethon/client/users.py", line 404, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telethon/client/users.py", line 538, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "Real group example"

```

**Comment by Lonami** [comment]
Can't say much about not receiving the login code without a traceback. If the only issue remaining is the `ValueError` then that's different and this can be closed because it would be working as intended.

**Comment by Magaknuto** [comment]
should I open another ISSUE? on my computer it works but on amazon and phone it doesnt

**Comment by Lonami** [comment]
No, the `ValueError` is not a bug and does not need an issue. I'm asking if there's no problem with login failing, then this can be closed.

**Comment by Magaknuto** [comment]
be happy!!!
