### ISSUE TITLE
FloodWaitError in client.download_media

### ISSUE THREAD

**Issue by max00xam** [LonamiWebs/Telethon#1426]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

@client.on(events.NewMessage())
async def message_handler(event):
     await client.download_media(event.message)
```

**Traceback**
```
ERROR:telethon.client.updates:Unhandled exception on message_handler
Traceback (most recent call last):
  File "/path/.local/lib/python3.7/site-packages/telethon/client/updates.py", line 428, in _dispatch_update
    await callback(event)
  File "telegram.py", line 1075, in message_handler
    await client.download_media(event.message, download_filename)
  File "/path/.local/lib/python3.7/site-packages/telethon/client/downloads.py", line 353, in download_media
    media, file, date, thumb, progress_callback
  File "/path/.local/lib/python3.7/site-packages/telethon/client/downloads.py", line 728, in _download_document
    progress_callback=progress_callback
  File "/path/.local/lib/python3.7/site-packages/telethon/client/downloads.py", line 436, in download_file
    input_location, request_size=part_size, dc_id=dc_id):
  File "/path/.local/lib/python3.7/site-packages/telethon/requestiter.py", line 75, in __anext__
    if await self._load_next_chunk():
  File "/path/.local/lib/python3.7/site-packages/telethon/client/downloads.py", line 60, in _load_next_chunk
    cur = await self._request()
  File "/path/.local/lib/python3.7/site-packages/telethon/client/downloads.py", line 70, in _request
    result = await self._sender.send(self.request)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 49 seconds is required (caused by GetFileRequest)

```

HACK TO FIX:
telethon/client/downloads.py
rows: 68 - 86

```
    async def _request(self):
        result = None
        count = 1
        time_chunk = .3
        max_retries = 15

        while not result:
           try:
               result = await self._sender.send(self.request)
           except:
               if count > max_retries: break
               self.client._log[__name__].info('ERROR retring in {}s'.format(count*time_chunk))
               await asyncio.sleep(count * time_chunk) # maxxam
               count += 1

        try:
            if not result:
                await asyncio.sleep(30)
                await self._sender.send(self.request)
```

**Comment by SnapDragon7410** [comment]
that is not a bug or an issue 🤣

**Comment by SnapDragon7410** [comment]
``` python
from telethon.sync import TelegramClient
from telethon import errors
import asyncio

@client.on(events.NewMessage())
async def message_handler(event):
    try:
        await client.download_media(event.message)
    except errors.FloodWaitError as e:
        await asyncio.sleep(e.seconds)
        await client.download_media(event.message)
```

this works for me

**Comment by Lonami** [comment]
> that is not a bug or an issue

It is if autosleep isn't working during download.

**Comment by mengyyy** [comment]
event wait for 90 second not work
```
   ...:             while True:
   ...:                 try:
   ...:                     file_name = await m.download_media()
   ...:                 except Exception as e:
   ...:                     logger.error(repr(e))
   ...:                     await asyncio.sleep(90)
   ...:                 else:
   ...:                     break
```
2020-04-25 19:56:50.359 | ERROR    | __main__:async-def-wrapper:18 - FloodWaitError('A wait of 12 seconds is required (caused by GetFileRequest)')
2020-04-25 19:58:23.225 | ERROR    | __main__:async-def-wrapper:18 - FloodWaitError('A wait of 16 seconds is required (caused by GetFileRequest)')
2020-04-25 19:59:56.314 | ERROR    | __main__:async-def-wrapper:18 - FloodWaitError('A wait of 17 seconds is required (caused by GetFileRequest)')
