### ISSUE TITLE
InputMessagesFilterPhoneCalls doesn't work as a filter when using get_messages()

### ISSUE THREAD

**Issue by sanjeetsuhag** [LonamiWebs/Telethon#1436]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
from telethon.tl.types import InputMessagesFilterPhoneCalls

async def main():
    dialogs = await client.get_dialogs()
    chat = await client.get_input_entity(dialogs[0])

    messages = await client.get_messages(chat, 0, filter=InputMessagesFilterPhoneCalls)
    print(messages.total)

with TelegramClient('client', key['api_id'], key['api_hash']) as client:
    client.loop.run_until_complete(main())

```

**Traceback**
```
Traceback (most recent call last):
  File "/Users/sanjeetsuhag/Developer/TelegramStats/test.py", line 27, in <module>
    client.loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/sanjeetsuhag/Developer/TelegramStats/test.py", line 23, in main
    messages = await client.get_messages(chat, 0, filter=InputMessagesFilterPhoneCalls)
  File "/Users/sanjeetsuhag/Library/Python/3.7/lib/python/site-packages/telethon/client/messages.py", line 531, in get_messages
    return await it.collect()
  File "/Users/sanjeetsuhag/Library/Python/3.7/lib/python/site-packages/telethon/requestiter.py", line 114, in collect
    async for message in self:
  File "/Users/sanjeetsuhag/Library/Python/3.7/lib/python/site-packages/telethon/requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "/Users/sanjeetsuhag/Library/Python/3.7/lib/python/site-packages/telethon/client/messages.py", line 139, in _init
    result = await self.client(self.request)
  File "/Users/sanjeetsuhag/Library/Python/3.7/lib/python/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcerrorlist.PeerIdNotSupportedError: The provided peer ID is not supported (caused by SearchRequest)
```

---

I am following [the example provided in the API for getting the total number of Photos](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.messages.MessageMethods.get_messages), and instead trying to get the total number of PhoneCalls in a chat.

**Comment by Lonami** [comment]
Not supported by the API, nothing we can do. I think it only works for global search (`None` entity).
