### ISSUE TITLE
Internals should not generate auth_key automatically

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1466]
It should be on demand, so that we don't try to generate it in weird places. There's also no use to generating it at arbitrary points because there's nothing the library can do to continue ([original report](https://t.me/TelethonChat/216709)).

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 538, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1774, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ali/Dev/sheypoor/venv/lib/python3.7/site-packages/telethon/client/updates.py", line 350, in _update_loop
    self._sender.send(functions.PingRequest(rnd()))
  File "/home/ali/Dev/sheypoor/venv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 174, in send
    state = RequestState(request, self._loop)
  File "/home/ali/Dev/sheypoor/venv/lib/python3.7/site-packages/telethon/network/requeststate.py", line 18, in init
    self.future = asyncio.Future(loop.loop)
ConnectionError: auth_key generation failed 5 time(s)
```

I don't think it would help with #1402 because it seems like there's something else going on to cause all these issues with the generation of an authorization key (location? flood trying to make keys?).

**Comment by Lonami** [comment]
It's been working fine and if v2 happens this'll work differently anyway.
