### ISSUE TITLE
telethon.errors.rpcerrorlist.AuthKeyUnregisteredError: The key is not registered in the system 

### ISSUE THREAD

**Issue by Th0rgal** [LonamiWebs/Telethon#1477]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient

async def create_bot(api_id, api_hash, bot_account, name, bot_token=None):
    client = TelegramClient(name, api_id, api_hash)
    return client.start(bot_token=bot_token) if bot_account else client

async def load_telegram_listeners(loop, config, reposters):
    bot = await create_bot(
        config.telegram_listener_api_id,
        config.telegram_listener_api_hash,
        config.telegram_listener_bot_account,
        "telegram_listener",
        config.telegram_listener_bot_token,
    )
    await bot.connect()
    async for message in bot.iter_messages("me"):
        print(message.id, message.text)
```

error:
```traceback
(bot) conda-shell-chrootenv:thomas@horus:~/workspace/photobe$ python .
Traceback (most recent call last):
  File "/home/thomas/.conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/thomas/.conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 23, in <module>
    loop.run_until_complete(main(loop))
  File "/home/thomas/.conda/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./__main__.py", line 17, in main
    await telegram.load_telegram_listeners(loop, config, None)
  File "./telegram/manager.py", line 19, in load_telegram_listeners
    async for message in bot.iter_messages("me"):
  File "/home/thomas/.local/lib/python3.7/site-packages/telethon/requestiter.py", line 75, in __anext__
    if await self._load_next_chunk():
  File "/home/thomas/.local/lib/python3.7/site-packages/telethon/client/messages.py", line 165, in _load_next_chunk
    r = await self.client(self.request)
  File "/home/thomas/.local/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/thomas/.local/lib/python3.7/site-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.AuthKeyUnregisteredError: The key is not registered in the system (caused by GetHistoryRequest)
```

I'm sorry, I don't understand what this error means and i'm unable to find documentation about it. :(

**Comment by Th0rgal** [comment]
.start() is mandatory, even for client accounts

**Comment by Lonami** [comment]
I failed to see that `client` was not being started but yes you need to login to register your authorization key to Telegram (not necessarily with `start`, `log_in` can also be used but `start` is the easiest).

**Comment by Itstunchi** [comment]
can this be more explained? how do i login or start the key?

**Comment by laminda** [comment]
Hello! I have exactly the same problem. 
The fact is that I have already received the key, but when I repeat it, all sessions on all devices break and I need to log in again. 
My actions:
1. Running the Python code 
2. I enter the code that comes to the telegram account 
3. I'm stopping the program execution 
4. I immediately restart it and then all sessions are terminated


`Traceback (most recent call last):
  File "C:\Users\111\PycharmProjects\pythonProject7\Crypto\GPT_TG_BOT\telegram_auto_tell.py", line 95, in <module>
    client.run_until_disconnected()
  File "C:\Users\111\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\updates.py", line 96, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "C:\Users\111\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\111\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\updates.py", line 38, in _run_until_disconnected
    raise self._updates_error
  File "C:\Users\111\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\updates.py", line 308, in _update_loop
    diff = await self(get_diff)
  File "C:\Users\111\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\111\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.AuthKeyUnregisteredError: The key is not registered in the system (caused by GetDifferenceRequest)`
