### ISSUE TITLE
Unhandled error while processing msgs

### ISSUE THREAD

**Issue by AndreaHasani** [LonamiWebs/Telethon#1552]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Traceback**
```
2020-09-09 18:02:14,919 - 366124203 - 6594571467 - ERROR - Unhandled error while processing msgs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telethon/utils.py", line 936, in get_peer_id
    peer = get_peer(peer)
  File "/usr/local/lib/python3.8/site-packages/telethon/utils.py", line 909, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.8/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast InputPeerEmpty to any kind of Peer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 496, in _recv_loop
    await self._process_message(message)
  File "/usr/local/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 511, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 585, in _handle_container
    await self._process_message(inner_message)
  File "/usr/local/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 511, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 607, in _handle_update
    self._update_callback(message.obj)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/updates.py", line 292, in _handle_update
    entities = {utils.get_peer_id(x): x for x in
  File "/usr/local/lib/python3.8/site-packages/telethon/client/updates.py", line 292, in <dictcomp>
    entities = {utils.get_peer_id(x): x for x in
  File "/usr/local/lib/python3.8/site-packages/telethon/utils.py", line 938, in get_peer_id
    _raise_cast_fail(peer, 'int')
  File "/usr/local/lib/python3.8/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast UserEmpty to any kind of int.
```

Looking at the source of telethon (and from the message) looks like this is a Unhandled error.

**Comment by Lonami** [comment]
Seems Telegram sent a user empty. Do you have any idea on how this happened, or if you can reproduce the issue consistently?

**Comment by AndreaHasani** [comment]
I cannot really reproduce this (since it happened in deployment) and so far I only have seen it happen once (or was it twice, well in the day I reported the bug I only saw it then)
