### ISSUE TITLE
Client auto reconnection can't be turned off

### ISSUE THREAD

**Issue by Soberia** [LonamiWebs/Telethon#1556]
* [True] The error is in the library's code, and not in my own.
* [True] I have searched for this issue before posting it and there isn't a duplicate.
* [True] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

I want to handle client reconnection myself, so I set ```TelegramClient(..., auto_reconnect=False)``` to get ```ConnectionError``` if the client was disconnected. But ```ConnectionError: Cannot send requests while disconnected``` will never rise if making a request while the client is disconnected, although uncaught exception ```ConnectionError: Connection to Telegram failed 1 time(s)``` will be raised revealing that a client reconnection occurred.

<details><summary><strong>Code that causes the issue</strong></summary>

```python
import asyncio
import logging

logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger(__name__)


def uncaught_error_handler(loop, exc):
    log.exception('Unhandled Exception', exc_info=exc['exception'])


async def main():
    try:
        async with TelegramClient(..., auto_reconnect=False) as client:
            async for message in client.iter_messages(...):
                print(f"MESSAGE_ID={message.id}")
                    break
            await asyncio.sleep(30)
            # Internet connection turned off now
            async for message in client.iter_messages(...):  # Should rise 'ConnectionError', but tryies to reconnect
                print(f"MESSAGE_ID={message.id}")
    except ConnectionError as error:
        print(error)  # Never reached


loop = asyncio.get_event_loop()
loop.set_exception_handler(uncaught_error_handler)
loop.run_until_complete(main())
```

</details>

<details><summary><strong>Traceback</strong></summary>

```
DEBUG:asyncio:Using selector: EpollSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.92:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.92:443/TcpFull complete!
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890420440130664 to InvokeWithLayerRequest (7f569e99ca90)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 96 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling bad salt for message 6870890420440130664
DEBUG:telethon.network.mtprotosender:1 message(s) will be resent
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890421904721688 to InvokeWithLayerRequest (7f569e99ca90)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 96 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890421907470176 to MsgsAck (7f569e96c550)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling new session created
DEBUG:telethon.network.mtprotosender:Handling acknowledge for [6870890421904721688]
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6870890421904721688
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890423226464700 to GetUsersRequest (7f569f340ca0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 32 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890423228407336 to MsgsAck (7f569e99c670)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 60 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6870890423226464700
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890424868948056 to GetHistoryRequest (7f569e92b790)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 64 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890424871396136 to MsgsAck (7f569e981dc0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6870890424868948056
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
MESSAGE_ID=1235
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890680983117192 to PingRequest (7f569e9cb7f0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 28 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6870890680986202328 to MsgsAck (7f569e99ca30)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [Errno 104] Connection reset by peer
INFO:telethon.network.mtprotosender:Connection closed while receiving data
DEBUG:telethon.network.mtprotosender:Closing current connection...
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [Errno 104] Connection reset by peer
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.92:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError: 
DEBUG:telethon.network.mtprotosender:Connection attempt 2...
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: TimeoutError: 
INFO:telethon.network.mtprotosender:Failed reconnection attempt 1 with ConnectionError
ERROR:telethon.network.mtprotosender:Automatic reconnection failed 1 time(s)
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.92:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Closing current connection...
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [Errno 104] Connection reset by peer
DEBUG:telethon.network.mtprotosender:Cancelling 1 pending message(s)...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.92:443/TcpFull complete!
ERROR:__main__:Unhandled Exception
ConnectionError: Connection to Telegram failed 1 time(s)
```

</details>

**Comment by Soberia** [comment]
Thanks for your work @yash-dk but now if the client can't be connected when ```auto_reconnect=False```, an uncaught exception ```ConnectionError: Not connected``` will rise

**Code that causes the issue**
```
import asyncio
import logging
from telethon import TelegramClient

logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger(__name__)


async def main():
    client = TelegramClient(..., auto_reconnect=False)
    try:
        await client.connect()
        print('-- connected --')
    except ConnectionError:
        print('-- not connected --')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
**Traceback (when client is connected)** - no probelm
```
DEBUG:asyncio:Using selector: EpollSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.92:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.92:443/TcpFull complete!
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6872845862446219876 to InvokeWithLayerRequest (7f001908ac70)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 84 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling bad salt for message 6872845862446219876
DEBUG:telethon.network.mtprotosender:1 message(s) will be resent
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6872845863970381812 to InvokeWithLayerRequest (7f001908ac70)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 84 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6872845863973032076 to MsgsAck (7f0019055790)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling new session created
DEBUG:telethon.network.mtprotosender:Handling acknowledge for [6872845863970381812]
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6872845863970381812
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
-- connected --
```
**Traceback (when client can't be connected)**
```
DEBUG:asyncio:Using selector: EpollSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.92:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.92:443/TcpFull complete!
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 6872845873117773376 to InvokeWithLayerRequest (7f8699880cd0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 84 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
DEBUG:telethon.network.mtprotosender:Closing current connection...
ERROR:telethon.network.mtprotosender:Automatic reconnection failed 0 time(s)
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.92:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 1 pending message(s)...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.92:443/TcpFull complete!
-- not connected --
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectionError('Not connected')>
Traceback (most recent call last):
  File "/root/.dev/test.py", line 12, in main
    await client.connect()
  File "/root/.TeleWebGram/.dev/venv/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 503, in connect
    await self._sender.send(self._init_with(
ConnectionError: Not connected
```

**Comment by vegeta1k95** [comment]
@Soberia 
It think you code works correctly, the exception is caught (indicated by the line "-- no connected --", but the future where it is called is never resolved for that exception.
That is a bug (?) in the library itself, because it never resolves any exceptions caught in Futures which leads to asyncio log warnings.

**Comment by Lonami** [comment]
Not sure what action is left to take here, so closing.
