### ISSUE TITLE
The library does not raise any exceptions when the Internet is off while listening to chat events, although it uses ping-pong messages

### ISSUE THREAD

**Issue by alega19** [LonamiWebs/Telethon#1564]
**Checklist**
* [True ] The error is in the library's code, and not in my own.
* [ True] I have searched for this issue before posting it and there isn't a duplicate.
* [ True] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import asyncio
import logging

import telethon


API_ID = 0  # set the value
API_HASH = ""  # set the value


async def main():
    async with telethon.client.TelegramClient(
        "path/to/session",
        API_ID,
        API_HASH,
        auto_reconnect=False,
        connection_retries=0,
        request_retries=0,
        retry_delay=0,
    ) as client:

        @client.on(telethon.events.NewMessage())
        async def handler(event):
            print(event.chat_id, event.message.id)

        await client.run_until_disconnected()  # (1)


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    try:
        asyncio.run(main())  # (1)
    except Exception as error:
        # A number of seconds later I turn the Internet off
        # and am waiting for the error kind of ConnectionError or smth else
        # but nothing happens
        # the code (1) still works
        print(error)
        exit(1)
```

**Traceback**
```
DEBUG:asyncio:Using selector: EpollSelector
INFO:chat_listener.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
DEBUG:chat_listener.network.mtprotosender:Connection attempt 1...
DEBUG:chat_listener.network.mtprotosender:Connection success!
DEBUG:chat_listener.network.mtprotosender:Starting send loop
DEBUG:chat_listener.network.mtprotosender:Starting receive loop
INFO:chat_listener.network.mtprotosender:Connection to 149.154.167.51:443/TcpFull complete!
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691343062537332 to InvokeWithLayerRequest (7f3d669cfe50)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 88 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.network.mtprotosender:Receiving items from the network...
DEBUG:chat_listener.network.mtprotosender:Handling bad salt for message 6874691343062537332
DEBUG:chat_listener.network.mtprotosender:1 message(s) will be resent
DEBUG:chat_listener.network.mtprotosender:Receiving items from the network...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691343275862832 to InvokeWithLayerRequest (7f3d669cfe50)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 88 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691343281654496 to MsgsAck (7f3d669e9050)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.network.mtprotosender:Handling container
DEBUG:chat_listener.network.mtprotosender:Handling new session created
DEBUG:chat_listener.network.mtprotosender:Handling acknowledge for [6874691343275862832]
DEBUG:chat_listener.network.mtprotosender:Receiving items from the network...
DEBUG:chat_listener.network.mtprotosender:Handling RPC result for message 6874691343275862832
DEBUG:chat_listener.network.mtprotosender:Receiving items from the network...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691343561159272 to GetUsersRequest (7f3d669cfbd0)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 32 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691343567381044 to MsgsAck (7f3d669e9c90)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 60 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.network.mtprotosender:Handling RPC result for message 6874691343561159272
DEBUG:chat_listener.network.mtprotosender:Receiving items from the network...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691343855576652 to GetStateRequest (7f3d669e9e10)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 20 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691343861777444 to MsgsAck (7f3d669e9410)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.network.mtprotosender:Handling RPC result for message 6874691343855576652
DEBUG:chat_listener.network.mtprotosender:Receiving items from the network...
# THE LIBRARY SENDS A PING MESSAGE... :
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691601533983980 to PingRequest (7f3d669cff90)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 28 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691601539113796 to MsgsAck (7f3d669e9350)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
# ... AND RECEIVES A PONG MESSAGE (IT IS OK):
DEBUG:chat_listener.network.mtprotosender:Handling **pong for message 6874691601533983980**
DEBUG:chat_listener.network.mtprotosender:Receiving items from the network...
# HERE I TURNED OFF THE INTERNET
# THE LIBRARY SENDS ANOTHER PING MESSAGE (IT IS STILL OK):
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691859477198056 to PingRequest (7f3d669e9d50)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 28 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874691859483452252 to MsgsAck (7f3d669e94d0)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
# AS YOU SEE THERE IS NO PONG BECAUSE MY INTERNET IS OFF
# BUT THE LIBRARY DOES NOT RAISE EXCEPTION OF THAT AND 20-40s LATER THE LIBRARY SENDS A NEW PING MESSAGE (IT IS NOT OK):
DEBUG:chat_listener.extensions.messagepacker:Assigned msg_id = 6874692117415317604 to PingRequest (7f3d669e9cd0)
DEBUG:chat_listener.network.mtprotosender:Encrypting 1 message(s) in 28 bytes for sending
DEBUG:chat_listener.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:chat_listener.network.mtprotosender:Waiting for messages to send...
# HERE I STOPPED THE PROGRAM (THE REST DOES NOT MATTER):
INFO:chat_listener.network.mtprotosender:Disconnecting from 149.154.167.51:443/TcpFull...
DEBUG:chat_listener.network.mtprotosender:Closing current connection...
DEBUG:chat_listener.network.mtprotosender:Cancelling 2 pending message(s)...
INFO:chat_listener.network.mtprotosender:Disconnection from 149.154.167.51:443/TcpFull complete!
INFO:chat_listener.network.mtprotosender:Not disconnecting (already have no connection)
Traceback (most recent call last):
  File "/home/oleg/projects/tg_project/chat_listener/main.py", line 53, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1735, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

Process finished with exit code 1
```

**Comment by GowthamSaminathan** [comment]
Same issue, after internet disconnection.
```
client = TelegramClient(SESSION, API_ID, API_HASH)

@client.on(events.NewMessage)
async def my_event_handler(event):
    msg = event.raw_text
    sender = await event.get_sender()
    print(sender)
    print(msg)
    if msg.find('>') == 0:
        out = subprocess.Popen(msg.split(">")[1], stdout=subprocess.PIPE)
        out = out.communicate()[0].decode('utf-8')
        await event.reply(out)
    else:
        await event.reply('hellow ')
        await event.respond('I am test prototype...')
    print(msg)



if __name__ == "__main__":
    client.start()
    client.run_until_disconnected()
```

**Comment by GowthamSaminathan** [comment]
How others are using this library without fixing this major issue !!! ??

**Comment by Lonami** [comment]
Others are simply not having this "major issue". Back when I tested and tried turning off my WiFi, the library remained "connected", and after WiFi was back on, it kept working fine. It's using `asyncio`'s `open_connection`, so that's the thing dealing with network here, not the library directly.

I just skimmed through the log, and perhaps the library should disconnect if there's not a pong quick enough? That seems easy to do.

**Comment by Lonami** [comment]
This will still take the library a minute to realize a ping was not yet received, but it should improve the situation.

**Comment by Soberia** [comment]
I don't know this is relevant to this issue but after this commit, I got this after turning off my WiFi:

```
ERROR:    [29628] [asyncio] Task exception was never retrieved
future: <Task finished name='Task-10' coro=<MTProtoSender._reconnect() done, defined at /*/lib/python3.9/site-packages/telethon/network/mtprotosender.py:339> exception=AttributeError("'NoneType' object has no attribute 'with_traceback'")>
Traceback (most recent call last):
  File "/*/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 407, in _reconnect
    await self._disconnect(error=last_error.with_traceback(None))
AttributeError: 'NoneType' object has no attribute 'with_traceback'
ERROR:    [29625] [main.utilities.logger] <Uncaught Exception>
ConnectionError: Connection to Telegram failed 2 time(s)
```

**Comment by Lonami** [comment]
Closing as I consider the above commit good enough (and I haven't heard back).
