### ISSUE TITLE
tcp_client error

### ISSUE THREAD

**Issue by 88ee55** [LonamiWebs/Telethon#158]
telethon 0.11.3
 run try_telethon.py

```
Initializing interactive example...
Connecting to Telegram servers...
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/telethon/extensions/tcp_client.py", line 97, in read
    partial = self._socket.recv(bytes_left)
BlockingIOError: [Errno 11] Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./try_telethon.py", line 37, in <module>
    **kwargs)
  File "/opt/telethon/interactive_telegram_client.py", line 58, in __init__
    if not self.connect():
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_client.py", line 140, in connect
    return super().connect()
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 132, in connect
    layer=layer, query=request
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 104, in receive
    seq, body = self.transport.receive(**kwargs)
  File "/usr/lib64/python3.4/site-packages/telethon/network/tcp_transport.py", line 56, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/usr/lib64/python3.4/site-packages/telethon/extensions/tcp_client.py", line 115, in read
    'The read operation exceeded the timeout.') from error
TimeoutError: The read operation exceeded the timeout.
```

telethon 0.11.1 ok

**Comment by Lonami** [comment]
> telethon 0.11.3
> run try_telethon.py

```
git checkout v0.11.3
python3.6 try_telethon.py

==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
First run. Sending code request...
Enter the code you just received: 4xxxx
Initialization done!
```

I couldn't reproduce the issue. I wonder if it's an issue with [Python 3.4](https://stackoverflow.com/questions/23365696/blockingioerror-errno-11-resource-temporarily-unavailable-python-in-cygwin#32340657)? Are you using Windows (I only have a Linux machine)?

**Comment by 88ee55** [comment]
python 3.4.5
centos 7.3

**Comment by 88ee55** [comment]
I'm starting a new account, everything is fine
Start old account, now another error

` 
File "/opt/client/client.py", line 65, in __init__
    if not self.connect():
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_client.py", line 140, in connect
    return super().connect()
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 132, in connect
    layer=layer, query=request
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 109, in receive
    remote_msg_id, remote_seq, reader, updates)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 213, in _process_msg
    return self._handle_container(msg_id, sequence, reader, updates)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 285, in _handle_container
    inner_msg_id, sequence, reader, updates):
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 216, in _process_msg
    return self._handle_gzip_packed(msg_id, sequence, reader, updates)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 382, in _handle_gzip_packed
    msg_id, sequence, compressed_reader, updates)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 241, in _process_msg
    result = reader.tgread_object()
  File "/usr/lib64/python3.4/site-packages/telethon/extensions/binary_reader.py", line 128, in tgread_object
    result.on_response(self)
  File "/usr/lib64/python3.4/site-packages/telethon/tl/types/updates_tg.py", line 84, in on_response
    chats_item = reader.tgread_object()
  File "/usr/lib64/python3.4/site-packages/telethon/extensions/binary_reader.py", line 123, in tgread_object
    raise TypeNotFoundError(constructor_id)
telethon.errors.common.TypeNotFoundError: (TypeNotFoundError(...), 'Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 0xa14dca52. Most likely, a TLObject was trying to be read when it should not be read.')
`

**Comment by Lonami** [comment]
> ```
> Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 0xa14dca52.
> ```

The old session seems broken, it's trying to read a [channel](https://github.com/telegramdesktop/tdesktop/blob/8d28d0691f668a67587b056aeb53302929f77385/Telegram/Resources/scheme.tl#L219) but [it has now changed](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl#L222) so Telethon fails to read that. This happens because we're receiving old updates from layer 66 before we even tell Telegram to use the new layer 68.

**Comment by 88ee55** [comment]
Excellent, you can close issues

**Comment by Lonami** [comment]
No, leave this open so I can workaround migrating from layers.

**Comment by pazis** [comment]
I have the same issue. 

Telethon 0.11.5
Python 3.6.1
CentOS 6

I can't connect to any of my Telegram accounts. I tried deleting the session file, still the same error.

```
Initializing interactive example...
Connecting to Telegram servers...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telethon/extensions/tcp_client.py", line 97, in read
    partial = self._socket.recv(bytes_left)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by Lonami** [comment]
> I tried deleting the session file, still the same error.

If your system time in sync? See #172. I think Telegram doesn't talk back if the messages are too old or ahead of time.
