### ISSUE TITLE
sqlite3 operational error

### ISSUE THREAD

**Issue by batiscuff** [LonamiWebs/Telethon#1582]
I use simple code example:
```
from telethon import TelegramClient
  

api_id = 1471199
api_hash = "1kf405982jfjy358e71c5ace912371999"

with TelegramClient("batiscuff", api_id, api_hash) as client:
    client.loop.run_until_complete(client.send_message("me", "Hello!"))
```
On startup displays an error:
```
Traceback (most recent call last):
  File "1.py", line 7, in <module>
    with TelegramClient("batiscuff", api_id, api_hash) as client:
  File "/home/batiscuff/.local/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 250, in __init__
    session = SQLiteSession(session)
  File "/home/batiscuff/.local/lib/python3.8/site-packages/telethon/sessions/sqlite.py", line 51, in __init__
    c.execute("select version from version")
sqlite3.OperationalError: no such column: version
```

**Comment by Lonami** [comment]
Chances are the session file somehow got corrupted or it's using a newer version in an older one. If using a new session file doesn't fix it, please indicate the steps necessary to reproduce, not just the code, but closing for now under the assumption there's no issue.
