### ISSUE TITLE
Error installing telethon

### ISSUE THREAD

**Issue by Juancho2004gg** [LonamiWebs/Telethon#1586]
I try to install telethon but i got this error

C:\Users\JUAN>pip3 install telethon
Collecting telethon
  Using cached Telethon-1.16.4-py3-none-any.whl (483 kB)
Collecting pyaes
  Using cached pyaes-1.6.1.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\juan\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JUAN\\AppData\\Local\\Temp\\pip-install-i2of7eld\\pyaes\\setup.py'"'"'; __file__='"'"'C:\\Users\\JUAN\\AppData\\Local\\Temp\\pip-install-i2of7eld\\pyaes\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\JUAN\AppData\Local\Temp\pip-pip-egg-info-pffewwkh'
         cwd: C:\Users\JUAN\AppData\Local\Temp\pip-install-i2of7eld\pyaes\
    Complete output (24 lines):
    Traceback (most recent call last):
      File "c:\users\juan\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2867, in get_entry_map
        ep_map = self._ep_map
      File "c:\users\juan\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2825, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JUAN\AppData\Local\Temp\pip-install-i2of7eld\pyaes\setup.py", line 10, in <module>
        setup(name = 'pyaes',
      File "c:\users\juan\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\juan\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 423, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\users\juan\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 657, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\users\juan\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2869, in get_entry_map
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "c:\users\juan\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2550, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output., in <code>

**Comment by Lonami** [comment]
The error does not seem to come from Telethon itself. You might try reinstalling and/or updating pip, setuptools, and maybe reinstalling Python itself.

**Comment by Juancho2004gg** [comment]
i see, I solved the problem by uninstalling python and pip, the python version I had was 3.8.5 and the latest version is 3.8.9.
