### ISSUE TITLE
Internal futures of the library never retrieves exceptions

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#1589]
Exceptions in some of the internal asyncio futures of the library are never retrieved which occasionally leads to messages like:

``` python
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectionError('Not connected')>
Traceback (most recent call last):
  File "/root/.dev/test.py", line 12, in main
    await client.connect()
  File "/root/.TeleWebGram/.dev/venv/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 503, in connect
    await self._sender.send(self._init_with(
ConnectionError: Not connected
```

Example:
Coroutine `_disconnect` in `mtprotosender.py` has lines like

``` python
...
for state in self._pending_state.values():
    if error and not state.future.done():
        state.future.set_exception(error)
    else:
        state.future.cancel()
self._pending_state.clear()
...

if self._disconnected and not self._disconnected.done():
    if error:
        self._disconnected.set_exception(error)
    else:
        self._disconnected.set_result(None)

```
so that futures are set with exception / cancelled, but the exception like `ConnectionError` is never retrieved from it.

Fix:
Insert `future.exception()` line to retrieve exception and avoid warning message, like:

``` python
...
for state in self._pending_state.values():
    if error and not state.future.done():
        state.future.set_exception(error)
        state.future.exception() # <- silently retrieve exception
    else:
        state.future.cancel()
self._pending_state.clear()
...

if self._disconnected and not self._disconnected.done():
    if error:
        self._disconnected.set_exception(error)
        self._disconnected.exception() # <- silently retrieve exception
    else:
        self._disconnected.set_result(None)
```

There are other places where cases like this can be found. I'll try to make commit with fixes later.

**Comment by Lonami** [comment]
The one example you provided does not seem to come within the library (most recent call is from user code, not the library). Having code that triggers the issue, even if one needs to inject errors inside the library to have it happen, would be useful. Really the thing here is tracking who is creating those tasks, what is causing those tasks to never be handled, and then working from there. Silencing the error is not the right solution.

**Comment by vegeta1k95** [comment]
@Lonami No, wrong - this one comes from inside the library, let us investigate:

1) I call `await TelegramClient.connect()` which is essentially the `TelegramBareClient.connect()`.
2) Inside the definition of `TelegramBareClient.connect()` there is this line 
```python 
...
await self._sender.send(self._init_with(
    functions.help.GetConfigRequest()))
...
```
3) The `_sender` is the instance of `MTProtoSender`, so let us see what is inside `MTProtoSender.send()`.
4) Inside `MTProtoSender.send()` we have lines:
``` python
....
if not utils.is_list_like(request):
    try:
        state = RequestState(request)
    except struct.error as e:
        # "struct.error: required argument is not an integer" is not
        # very helpful; log the request to find out what wasn't int.
        self._log.error('Request caused struct.error: %s: %s', e, request)
        raise

    self._send_queue.append(state)
    return state.future
...
We see that the `RequestState` is created with the future inside it, the state is added to `_send_queue` and future itself returned to the caller.

5) Now:
 a) the future which returned to the caller (that is, to step 2) is only awaited inside the `TelegramBareClient.connect()` and never exposed to the user to retrieve any exceptions or results from it.
 b) the `_send_queue` is never (!) cleared on the full disconnect in the code on `MTProtoSender`. I've looked through the code, and the only place where elements are withdrawn from it are the `MTProtoSender_send_loop()` coro, which means that if client disconnected completely and does not reconnects, the `_send_queue` elements are left unresolved, so when GC comes asyncio yields the error.

So that means, that if `ConnectionError` happens on initial connection and user does not want to reconnect (e.g. `auto_reconnect=False`, futures inside `send_queue` are never resolved for exception, so then when `TelegramClient` goes out of scope, error is produced.

The solution would be, for example, either to expose to the user future which is awaited at step 2), so that he can retrieve exception if anything happens on `client.connect()`, or dispose all enqueued requests and futures inside `_send_queue` on the full disconnect.

**Comment by vegeta1k95** [comment]
I can provide some code for testing (with exception injection inside the lib)  if needed.

**Comment by vegeta1k95** [comment]
Here is the way to reproduce the issue:

1) Inside `telethon.network.connection.connection.py` in the `Connection` class add the dummy exception raising inside
the methods `def send(self, data)` and `async def recv(self)`, like this:

``` python
def send(self, data):
        """
        Sends a packet of data through this connection mode.

        This method returns a coroutine.
        """
        raise ConnectionError("Dummy!")  # <- raise dummy error

        if not self._connected:
            raise ConnectionError('Not connected')

        return self._send_queue.put(data)

async def recv(self):
        """
        Receives a packet of data through this connection mode.

        This method returns a coroutine.
        """
        raise ConnectionError("Dummy!")  # <- raise dummy error

        while self._connected:
            result = await self._recv_queue.get()
            if result:  # None = sentinel value = keep trying
                return result

        raise ConnectionError('Not connected')

```

2) Run this simple script:

``` python

import asyncio
import gc

from telethon import TelegramClient

async def test():

    client = TelegramClient(...)

    try:
        await client.connect()
    except ConnectionError as error:
        print("I got you!", str(error))
    finally:
        await client.disconnect()

loop = asyncio.get_event_loop()
loop.run_until_complete(test())

gc.collect()
```

3) You should see a log like:

``` python
I got you! Dummy!

Future exception was never retrieved
future: <Future finished exception=ConnectionError('Dummy!')>
Traceback (most recent call last):
  File "D:/!_Work/_tests/test/test_2.py", line 25, in test
    await client.connect()
  File "D:\!_Work\Python38\lib\site-packages\telethon-1.16.4-py3.8.egg\telethon\client\telegrambaseclient.py", line 530, in connect
    await self._sender.send(self._init_with(
ConnectionError: Dummy!

Process finished with exit code 0
```

**Comment by vegeta1k95** [comment]
Here is the way to reproduce another instance of this issue:

1) Inside `telethon.client.updates.py` add the dummy exception raising inside
the method `async def _dispatch_update`, like this:

``` python
async def _dispatch_update(self: 'TelegramClient', update, others, channel_id, pts_date):
     raise Exception("Dummy update error!")
     ...
```

2) Send to your session some message, or make channel post, for some Update to arrive.

3) Run this simple script:

``` python

import asyncio
import gc

from telethon import TelegramClient

async def test():

    client = TelegramClient(..., auto_reconnect=False,  connection_retries=0)

    try:
        await client.connect()
        await client.catch_up()
        await asyncio.sleep(2)

    except Exception as error:
        print("I got you!", str(error))
    finally:
        await client.disconnect()

loop = asyncio.get_event_loop()
loop.run_until_complete(test())

gc.collect()
```

4) You should see a log like:

``` python

Task exception was never retrieved
future: <Task finished name='Task-8' coro=<UpdateMethods._dispatch_update() done, defined at D:\!_Work\Python38\lib\site-packages\telethon-1.16.4-py3.8.egg\telethon\client\updates.py:383> exception=Exception('Dummy update error!')>
Traceback (most recent call last):
  File "D:\!_Work\Python38\lib\site-packages\telethon-1.16.4-py3.8.egg\telethon\client\updates.py", line 385, in _dispatch_update
    raise Exception("Dummy update error!")
Exception: Dummy update error!

Process finished with exit code 0
```
