### ISSUE TITLE
RecursionError in iter_messages with offset_date

### ISSUE THREAD

**Issue by igerzog** [LonamiWebs/Telethon#1606]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import asyncio
import logging
import datetime

from telethon import events, types, errors

bot = TelegramClient(...)
client = TelegramClient(...)

@bot.on(events.CallbackQuery(chats=chat, data=b'pressButton')))
async def handler(event):
    
    current_time = datetime.datetime.now()
    offset_datetime = current_time.replace(hour=0, minute=1)

    async for message in client.iter_messages(channel, limit=20, offset_date=offset_datetime, reverse=True):
        logging.info(message)

    return
```

**Traceback**
```
Traceback (most recent call last):
  File "/***/.pyenv/versions/3.8.2/lib/python3.8/site-packages/telethon/client/updates.py", line 446, in _dispatch_update
    await callback(event)
  File "/***/projects/helper.py", line 16, in handler
    async for message in client.iter_messages(channel, limit=20, offset_date=offset_datetime, reverse=True):
  File "/***/.pyenv/versions/3.8.2/lib/python3.8/site-packages/telethon/requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "/***/.pyenv/versions/3.8.2/lib/python3.8/site-packages/telethon/client/messages.py", line 137, in _init
    async for m in self.client.iter_messages(
...
  File "/***/.pyenv/versions/3.8.2/lib/python3.8/site-packages/telethon/requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "/***/.pyenv/versions/3.8.2/lib/python3.8/site-packages/telethon/client/messages.py", line 137, in _init
    async for m in self.client.iter_messages(
  File "/***/.pyenv/versions/3.8.2/lib/python3.8/site-packages/telethon/client/messages.py", line 513, in iter_messages
    return _MessagesIter(
  File "/***/.pyenv/versions/3.8.2/lib/python3.8/site-packages/telethon/requestiter.py", line 34, in __init__
    self.limit = max(float('inf') if limit is None else limit, 0)
RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by igerzog** [comment]
Error was fixed but the new issue occurred — no messages to iterate through when `reverse=True`.
