### ISSUE TITLE
InvalidStateError after wait_event times out

### ISSUE THREAD

**Issue by sh4dowb** [LonamiWebs/Telethon#1618]
**Checklist**
* [?] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
...
@client.on(events.NewMessage(func=lambda e: e.is_private))
async def handler(event):
	try:
		if event.message.message != "start":
			return
		async with client.conversation(username, exclusive=True, timeout=600) as conv:
			for i in range(5):
				lastMessage = await conv.send_message(f"test {i}", buttons=[Button.inline("next", "something")])
				try:
					print("waiting for press")
					press = await conv.wait_event(events.CallbackQuery(func=lambda e: e.data == b'something'), timeout=5)
					print("received press")
					await lastMessage.edit("clicked")
				except asyncio.TimeoutError:
					await lastMessage.edit("timed out")
	except:
		traceback.print_exc()

client.loop.run_forever()

```

**Traceback**
```
Task exception was never retrieved
future: <Task finished coro=<UpdateMethods._dispatch_update() done, defined at /home/pi/.local/lib/python3.7/site-packages/telethon/client/updates.py:383> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/telethon/client/updates.py", line 429, in _dispatch_update
    await conv._check_custom(built)
  File "/home/pi/.local/lib/python3.7/site-packages/telethon/tl/custom/conversation.py", line 352, in _check_custom
    fut.set_result(inst)
asyncio.base_futures.InvalidStateError: invalid state

```

After a `wait_event` times out, when I call `wait_event` again on same conversation, as soon as I click the button I get the error above.

![image](https://user-images.githubusercontent.com/12783710/98161603-ec86ef00-1ed7-11eb-8969-bd4abaa5b881.png)

**Comment by sh4dowb** [comment]
08d5bfc now makes catching conversation timeouts impossible. any workarounds?

**Comment by Lonami** [comment]
I forgot to put a `raise` in the `except`.
