### ISSUE TITLE
MTProto problem

### ISSUE THREAD

**Issue by amir20172018** [LonamiWebs/Telethon#1637]
I'm trying to use MTProto for signing in telegram but i got traceback
```
async def main():
client = TelegramClient('session/' + phone_number, api_id, api_hash, connection=connection.ConnectionTcpMTProxyRandomizedIntermediate, proxy=('Bank.tsetmc.com.tsetmc--com.tk', 443, '7jK5IN_7UWQwKOL2uHjU6sF3MS53ZWIud2hhdHNhcHAuY29t'))
await client.start(phone_number)
me = await client.get_me()
```
```
Traceback (most recent call last):
  File "C:\Users\User\Downloads\MEmu Download\ltc\vltc3.py", line 285, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\User\Downloads\MEmu Download\ltc\vltc3.py", line 229, in main
    await client.start(phone_number)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\client\auth.py", line 140, in _start
    await self.connect()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\client\telegrambaseclient.py", line 516, in connect
    if not await self._sender.connect(self._connection(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\network\connection\tcpmtproxy.py", line 101, in __init__
    self._secret = bytes.fromhex(proxy[2])
ValueError: non-hexadecimal number found in fromhex() arg at position 1
```
problem comes from this tcpmtproxy.py
in other issues they said try this:
Edit line 34:
is_dd = (len(secret) == 17) and ((secret[0] == 0xDD) or (secret[0] == 0xEE))
but it did't work for me

**Comment by Lonami** [comment]
#1319.

**Comment by amir20172018** [comment]
I try this:
Edit line 34:
is_dd = (len(secret) == 17) and ((secret[0] == 0xDD) or (secret[0] == 0xEE))
if it work how to use this kind of link https://t.me/proxy?server=PeerTopeer.Peer--to--peer.tk&port=2590&secret=3fQ1mpsyX_HR5QhN8OD3U3s

**Comment by Lonami** [comment]
I have no idea how MTProto proxies work, if you're interested in them go to the older issue I linked where there's more people.
