### ISSUE TITLE
Bug while scraping

### ISSUE THREAD

**Issue by bububox** [LonamiWebs/Telethon#1658]
Hi, I've been using Telethon for a while now, mainly for scraping channels. All of the sudden it stopped working, I can't figure out why. I get these error messages:

`Unhandled error while processing msgs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 522, in _recv_loop
    await self._process_message(message)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 537, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 611, in _handle_container
    await self._process_message(inner_message)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 537, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 583, in _handle_rpc_result
    if not isinstance(reader.tgread_object(), upload.File):
  File "/usr/local/lib/python3.8/dist-packages/telethon/extensions/binaryreader.py", line 120, in tgread_object
    constructor_id = self.read_int(signed=False)
  File "/usr/local/lib/python3.8/dist-packages/telethon/extensions/binaryreader.py", line 37, in read_int
    return int.from_bytes(self.read(4), byteorder='little', signed=signed)
  File "/usr/local/lib/python3.8/dist-packages/telethon/extensions/binaryreader.py", line 60, in read
    raise BufferError(
BufferError: No more data left to read (need 4, got 0: b''); last read None
`

I have thought about being banned, but changing the account or country IP does not make any difference.

**Comment by Lonami** [comment]
Provide clear reproduction steps and a proper traceback. The above is unreadable.

**Comment by bububox** [comment]
Ok, so this is the central part of the code that is failing:

`
for chat in chats:
    async def main():
            await client(ImportChatInviteRequest(chat))
            time.sleep(5)
    with client:
        client.loop.run_until_complete(main())
`

and it is producing this error message:


`
Unhandled error while processing msgs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 522, in _recv_loop
    await self._process_message(message)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 537, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 611, in _handle_container
    await self._process_message(inner_message)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 537, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 583, in _handle_rpc_result
    if not isinstance(reader.tgread_object(), upload.File):
  File "/usr/local/lib/python3.8/dist-packages/telethon/extensions/binaryreader.py", line 120, in tgread_object
    constructor_id = self.read_int(signed=False)
  File "/usr/local/lib/python3.8/dist-packages/telethon/extensions/binaryreader.py", line 37, in read_int
    return int.from_bytes(self.read(4), byteorder='little', signed=signed)
  File "/usr/local/lib/python3.8/dist-packages/telethon/extensions/binaryreader.py", line 60, in read
    raise BufferError(
BufferError: No more data left to read (need 4, got 0: b''); last read None
`
No channel can be joined anymore.

**Comment by bububox** [comment]
wow I used the wrong script. Wanted to join public channels, but used the invite script...
