### ISSUE TITLE
Ipv6 proxy brokes authorization key for existing session

### ISSUE THREAD

**Issue by Nizarius** [LonamiWebs/Telethon#1661]
I'm trying to use ipv6 proxy with Telethon. It seems that ipv6 brokes the authorization key for the existing session. Note that the connection to the proxy itself and the ipv6 Telegram server is successful, but the first message from the Telegram returns 404.

The same code with ipv4 proxy and use_ivp6=False works ok. 
Also, I've tested the following scenarios:
1) ipv6 proxy and use_ipv6=False: Connection refused by destination host]
2) ipv4 proxy and use_ipv6=True: Connection refused by destination host]
3) use anonymous session +  ipv6 proxy and use_ipv6=True: no errors

All of them are the expected behavior. So the problem is definitely connected with ipv6 proxy for existing sessions that were used with ipv4. 

Can you clarify why does it happen? If for some reason buffer packages for ipv6-sessions must be different, how should I handle it? Official telegram application works great with switching between multiple ipv4 and ivp6 proxies. So there definitely should be a workaround. 

**Code that causes the issue**
```python
self._telethon = TelegramClient(user_session, tg_app.api_id, tg_app.api_hash,
   use_ipv6=True,
   proxy={
    'proxy_type': 'socks5',  # (mandatory) protocol to use (see above)
    'addr': '81.4.108.157',  # (mandatory) proxy IP address
    'port': 31604,  # (mandatory) proxy port number
    'username': '11VAr4',  # (optional) username if the proxy requires auth
    'password': 'oVqt7h',  # (optional) password if the proxy requires auth
     'rdns': False # (optional) whether to use remote or local resolve, default remote
   }
)
await self._telethon.connect()
```

**Traceback**
```
Traceback (most recent call last):
  File "/Users/petrpotapov/new_projects/telestat_serverless/telestat/lambdas/channel_parsing/parse_channel_info/channel_info_handler.py", line 85, in <module>
    result = asyncio.run(run_async_lambda(lambda_coroutine))
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/petrpotapov/new_projects/telestat_serverless/telestat/services/lambda_launcher.py", line 22, in run_async_lambda
    return await lambda_coroutine
  File "/Users/petrpotapov/new_projects/telestat_serverless/telestat/lambdas/channel_parsing/parse_channel_info/channel_info_handler.py", line 29, in handler
    tg_client = await get_tg_client_for_user(user_id)  # DON'T FIXME: Type annotation is correct,
  File "/Users/petrpotapov/new_projects/telestat_serverless/telestat/utils/telegram.py", line 197, in get_tg_client_for_user
    await tg_client.prepare()
  File "/Users/petrpotapov/new_projects/telestat_serverless/telestat/utils/telegram.py", line 78, in prepare
    await self._telethon.connect()
  File "/Users/petrpotapov/new_projects/telestat_serverless/venv/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 534, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(
  File "/Users/petrpotapov/new_projects/telestat_serverless/venv/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 493, in _recv_loop
    message = self._state.decrypt_message_data(body)
  File "/Users/petrpotapov/new_projects/telestat_serverless/venv/lib/python3.9/site-packages/telethon/network/mtprotostate.py", line 125, in decrypt_message_data
    raise InvalidBufferError(body)
telethon.errors.common.InvalidBufferError: Invalid response buffer (HTTP code 404)
```

**Comment by Lonami** [comment]
I'm cleaning up proxy-related issues, so closing in favour of the new issue.
