### ISSUE TITLE
Cannot import name 'get_input_peer' from partially initialized module 'telethon.utils'

### ISSUE THREAD

**Issue by Karasiq** [LonamiWebs/Telethon#1669]
**Checklist**
* [*] The error is in the library's code, and not in my own.
* [*] I have searched for this issue before posting it and there isn't a duplicate.
* [*] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

```
Users-MacBook-Pro:copy_fx user$ python3 --version
Python 3.9.1

Users-MacBook-Pro:copy_fx user$ pip3 list
Package    Version
---------- ---------
cffi       1.14.4
cryptg     0.2.post0
pip        20.3.3
pyaes      1.6.1
pyasn1     0.4.8
pycparser  2.20
PySocks    1.7.1
rsa        4.7
setuptools 51.1.2
Telethon   1.19.0
wheel      0.36.2
youtube-dl 2021.1.3
```

**Code that causes the issue**
```python
from telethon import TelegramClient, events, sync

# These example values won't work. You must get your own api_id and
# api_hash from https://my.telegram.org, under API Development.
api_id = 12345
api_hash = '0123456789abcdef0123456789abcdef'

client = TelegramClient('session_name', api_id, api_hash)
client.start()
```

**Traceback**
```
Traceback (most recent call last):
  File "/Users/user/IdeaProjects/copy_fx/test.py", line 1, in <module>
    from telethon import TelegramClient, events, sync
  File "/usr/local/lib/python3.9/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "/usr/local/lib/python3.9/site-packages/telethon/client/__init__.py", line 12, in <module>
    from .telegrambaseclient import TelegramBaseClient
  File "/usr/local/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 11, in <module>
    from ..crypto import rsa
  File "/usr/local/lib/python3.9/site-packages/telethon/crypto/__init__.py", line 6, in <module>
    from .aes import AES
  File "/usr/local/lib/python3.9/site-packages/telethon/crypto/aes.py", line 9, in <module>
    import pyaes
  File "/usr/local/lib/python3.9/site-packages/pyaes/__init__.py", line 51, in <module>
    from .aes import AES, AESModeOfOperationCTR, AESModeOfOperationCBC, AESModeOfOperationCFB, AESModeOfOperationECB, AESModeOfOperationOFB, AESModesOfOperation, Counter
  File "/usr/local/lib/python3.9/site-packages/pyaes/aes.py", line 54, in <module>
    import copy
  File "/Users/user/IdeaProjects/copy_fx/copy.py", line 3, in <module>
    from telethon import TelegramClient, events, sync
  File "/usr/local/lib/python3.9/site-packages/telethon/events/__init__.py", line 1, in <module>
    from .raw import Raw
  File "/usr/local/lib/python3.9/site-packages/telethon/events/raw.py", line 1, in <module>
    from .common import EventBuilder
  File "/usr/local/lib/python3.9/site-packages/telethon/events/common.py", line 5, in <module>
    from .. import utils
  File "/usr/local/lib/python3.9/site-packages/telethon/utils.py", line 22, in <module>
    from .extensions import markdown, html
  File "/usr/local/lib/python3.9/site-packages/telethon/extensions/__init__.py", line 6, in <module>
    from .binaryreader import BinaryReader
  File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 11, in <module>
    from ..tl.alltlobjects import tlobjects
  File "/usr/local/lib/python3.9/site-packages/telethon/tl/alltlobjects.py", line 3, in <module>
    from . import types, functions, patched
  File "/usr/local/lib/python3.9/site-packages/telethon/tl/patched/__init__.py", line 3, in <module>
    from .. import TLObject, types, custom
  File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/__init__.py", line 1, in <module>
    from .adminlogevent import AdminLogEvent
  File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/adminlogevent.py", line 2, in <module>
    from ...utils import get_input_peer
ImportError: cannot import name 'get_input_peer' from partially initialized module 'telethon.utils' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/telethon/utils.py)

```

**Comment by akench** [comment]
I'm having this same issue.

**Comment by Lonami** [comment]
```
$ python -V
Python 3.9.1
$ python -c 'from telethon import TelegramClient, events, sync'
$ python -c 'import telethon; print(telethon.__version__)'
1.19.0
```

Maybe it's a macOS issue? @akench do you also use macOS?

**Comment by Lonami** [comment]
```
Traceback (most recent call last):
  File "/Users/user/IdeaProjects/copy_fx/test.py", line 1, in <module>
    from telethon import TelegramClient, events, sync
  File "/usr/local/lib/python3.9/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
-snip-
  File "/usr/local/lib/python3.9/site-packages/pyaes/aes.py", line 54, in <module>
    import copy
  File "/Users/user/IdeaProjects/copy_fx/copy.py", line 3, in <module>
    from telethon import TelegramClient, events, sync
  File "/usr/local/lib/python3.9/site-packages/telethon/events/__init__.py", line 1, in <module>
    from .raw import Raw
```

I wonder why the following appears twice?

```
File "/Users/user/IdeaProjects/copy_fx/copy.py", line #, in <module>
```

**Comment by Lonami** [comment]
`draft.py` also has a `from utils import get_input_peer`, and that's a lot older, so if this wasn't an issue before I don't know why it is now. Python's import system is kind of lame when you compare it with something like Rust's, but I guess the language's dynamic nature is to blame here…

**Comment by Lonami** [comment]
Can any of you tell me if the above fixes it?

```
pip install -U https://github.com/LonamiWebs/Telethon/archive/circularimport.zip
```

**Comment by Lonami** [comment]
If you could also try that:

```
pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip
```

**Comment by akench** [comment]
I tried installing both of the above and I'm now getting a different error. Note that I'm running Ubuntu using WSL. I'm also using Python 3.8.5.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/XXX/venv/lib/python3.8/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "/XXX/venv/lib/python3.8/site-packages/telethon/client/__init__.py", line 12, in <module>
    from .telegrambaseclient import TelegramBaseClient
  File "/XXX/venv/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 3, in <module>
    import asyncio
  File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/asyncio/base_events.py", line 25, in <module>
    import subprocess
  File "/usr/lib/python3.8/subprocess.py", line 49, in <module>
    import signal
  File "/XXX/signal.py", line 1, in <module>
    from telethon import TelegramClient, events, sync
  File "/XXX/venv/lib/python3.8/site-packages/telethon/sync.py", line 17, in <module>
    from . import events, errors, utils, connection
ImportError: cannot import name 'connection' from partially initialized module 'telethon' (most likely due to a circular import) (/XXX/venv/lib/python3.8/site-packages/telethon/__init__.py)
```

**Comment by Lonami** [comment]
Note that both the above fixes are different, and should not be installed at the same time (only tested one at a time). I don't understand how it goes from `stdin`, into `telethon`, back into your code. Is all your code/environment just the code you posted originally, or is there something else?

**Comment by Lonami** [comment]
Closing due to inactivity.
