### ISSUE TITLE
ConnectionError while connecting to telegram on mac

### ISSUE THREAD

**Issue by dineshh-choudhary** [LonamiWebs/Telethon#1683]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
client = TelegramClient(self.username, self.api_id, self.api_hash)
client.start()
...

```

**Traceback**
```
[DEBUG/2021-01-28 20:39:23,809] asyncio: Using selector: KqueueSelector
[ INFO/2021-01-28 20:39:23,811] telethon.network.mtprotosender: Connecting to 149.154.167.51:443/TcpFull...
[DEBUG/2021-01-28 20:39:23,811] telethon.network.mtprotosender: Connection attempt 1...
[DEBUG/2021-01-28 20:39:23,956] telethon.network.mtprotosender: Connection success!
[DEBUG/2021-01-28 20:39:23,956] telethon.network.mtprotosender: New auth_key attempt 1...
[ INFO/2021-01-28 20:39:23,971] telethon.network.connection.connection: The server closed the connection
[WARNING/2021-01-28 20:39:23,971] telethon.network.mtprotosender: Connection error 1 during auth_key gen: ConnectionError: Not connected
[DEBUG/2021-01-28 20:39:24,974] telethon.network.mtprotosender: Connection attempt 2...
[DEBUG/2021-01-28 20:39:24,994] telethon.network.mtprotosender: Connection success!
[DEBUG/2021-01-28 20:39:24,995] telethon.network.mtprotosender: New auth_key attempt 2...
[ INFO/2021-01-28 20:39:25,016] telethon.network.connection.connection: The server closed the connection
[WARNING/2021-01-28 20:39:25,016] telethon.network.mtprotosender: Connection error 2 during auth_key gen: ConnectionError: Not connected
[DEBUG/2021-01-28 20:39:26,019] telethon.network.mtprotosender: Connection attempt 3...
[DEBUG/2021-01-28 20:39:26,036] telethon.network.mtprotosender: Connection success!
[DEBUG/2021-01-28 20:39:26,037] telethon.network.mtprotosender: New auth_key attempt 3...
[ INFO/2021-01-28 20:39:26,048] telethon.network.connection.connection: The server closed the connection
[WARNING/2021-01-28 20:39:26,048] telethon.network.mtprotosender: Connection error 3 during auth_key gen: ConnectionError: Not connected
[DEBUG/2021-01-28 20:39:27,050] telethon.network.mtprotosender: Connection attempt 4...
[DEBUG/2021-01-28 20:39:27,145] telethon.network.mtprotosender: Connection success!
[DEBUG/2021-01-28 20:39:27,145] telethon.network.mtprotosender: New auth_key attempt 4...
[ INFO/2021-01-28 20:39:27,237] telethon.network.connection.connection: The server closed the connection
[WARNING/2021-01-28 20:39:27,238] telethon.network.mtprotosender: Connection error 4 during auth_key gen: ConnectionError: Not connected
[DEBUG/2021-01-28 20:39:28,242] telethon.network.mtprotosender: Connection attempt 5...
[DEBUG/2021-01-28 20:39:29,043] telethon.network.mtprotosender: Connection success!
[DEBUG/2021-01-28 20:39:29,043] telethon.network.mtprotosender: New auth_key attempt 5...
[ INFO/2021-01-28 20:39:29,092] telethon.network.connection.connection: The server closed the connection
[WARNING/2021-01-28 20:39:29,093] telethon.network.mtprotosender: Connection error 5 during auth_key gen: ConnectionError: Not connected
[DEBUG/2021-01-28 20:39:30,098] telethon.network.mtprotosender: Connection attempt 6...
[DEBUG/2021-01-28 20:39:30,279] telethon.network.mtprotosender: Connection success!
[DEBUG/2021-01-28 20:39:30,279] telethon.network.mtprotosender: New auth_key attempt 6...
[ INFO/2021-01-28 20:39:30,332] telethon.network.connection.connection: The server closed the connection
[WARNING/2021-01-28 20:39:30,332] telethon.network.mtprotosender: Connection error 6 during auth_key gen: ConnectionError: Not connected
Traceback (most recent call last):
  File "/Users/dinesh.choudhary/Downloads/telegram_client.py", line 42, in <module>
    with TelegramClient("string", 1598223, "9cc019d48284aa1a40f6bc1261c4b6e5") as client:
  File "/usr/local/lib/python3.9/site-packages/telethon/helpers.py", line 184, in _sync_enter
    return loop.run_until_complete(self.__aenter__())
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/telethon/client/auth.py", line 713, in __aenter__
    return await self.start()
  File "/usr/local/lib/python3.9/site-packages/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/usr/local/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 514, in connect
    if not await self._sender.connect(self._connection(
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 125, in connect
    await self._connect()
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 251, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)
```

**Comment by Lonami** [comment]
The logs seem normal. Are you able to connect with an official application from that same device?

**Comment by dineshh-choudhary** [comment]
I am able to open telegram application and also able to send messages.
This API also was working fine few days back but its not working.
Same code is running fine on windows system.
It just hangs on mac in start() function.

**Comment by dineshh-choudhary** [comment]
If I copy the session file from windows to mac and then runs it.
It runs a infinite loop with below error.
```
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.150:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.150:443/TcpFull complete!
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.150:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.150:443/TcpFull complete!
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.150:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.150:443/TcpFull complete!
INFO:telethon.network.connection.connection:The server closed the connection
```

**Comment by Lonami** [comment]
So if you run an older version of the library it works? Which version is the last one that works and the first one that fails? You don't need to login, just connect.

**Comment by imakarsh** [comment]
I see the same issue. It works on my Virtual env on Mac, but see above mentioned issues on Docker when run on Mac.

**Comment by vashchukmaksim** [comment]
Same for me, I see an infinite log with `The server closed the connection` as mentioned above.

Python: 3.7/3.8/3.9
OS: Docker on Mac with python:3.x images
Telethon: 1.21.1

If I disable INFO logs after some silence time I see the following (I'm using Quart setup and also tried to run a Quart example exactly how it is in the examples folder and still see the same behaviour).

```
app_telegram_1     | Traceback (most recent call last):
app_telegram_1     |   File "/usr/local/lib/python3.9/asyncio/locks.py", line 226, in wait
app_telegram_1     |     await fut
app_telegram_1     | asyncio.exceptions.CancelledError
app_telegram_1     | 
app_telegram_1     | During handling of the above exception, another exception occurred:
app_telegram_1     | 
app_telegram_1     | Traceback (most recent call last):
app_telegram_1     |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
app_telegram_1     |     fut.result()
app_telegram_1     | asyncio.exceptions.CancelledError
app_telegram_1     | 
app_telegram_1     | The above exception was the direct cause of the following exception:
app_telegram_1     | 
app_telegram_1     | Traceback (most recent call last):
app_telegram_1     |   File "/root/.local/lib/python3.9/site-packages/hypercorn/asyncio/lifespan.py", line 55, in wait_for_startup
app_telegram_1     |     await asyncio.wait_for(self.startup.wait(), timeout=self.config.startup_timeout)
app_telegram_1     |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
app_telegram_1     |     raise exceptions.TimeoutError() from exc
app_telegram_1     | asyncio.exceptions.TimeoutError
app_telegram_1     | 
app_telegram_1     | The above exception was the direct cause of the following exception:
app_telegram_1     | 
app_telegram_1     | Traceback (most recent call last):
app_telegram_1     |   File "/home/root/app/server/test.py", line 34, in <module>
app_telegram_1     |     client.loop.run_until_complete(main())
app_telegram_1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
app_telegram_1     |     return future.result()
app_telegram_1     |   File "/home/root/app/server/test.py", line 30, in main
app_telegram_1     |     await hypercorn.asyncio.serve(app, hypercorn.Config())
app_telegram_1     |   File "/root/.local/lib/python3.9/site-packages/hypercorn/asyncio/__init__.py", line 39, in serve
app_telegram_1     |     await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
app_telegram_1     |   File "/root/.local/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 62, in worker_serve
app_telegram_1     |     await lifespan.wait_for_startup()
app_telegram_1     |   File "/root/.local/lib/python3.9/site-packages/hypercorn/asyncio/lifespan.py", line 57, in wait_for_startup
app_telegram_1     |     raise LifespanTimeout("startup") from error
app_telegram_1     | hypercorn.utils.LifespanTimeout: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.

```

**Comment by vashchukmaksim** [comment]
It turned out it works on Mac without docker but not inside docker. I have created a test repo. @Lonami could you have a look please? Unfortunately I don't have any other OS with docker to test now.

https://github.com/vashchukmaksim/telethon_test

**Comment by Lonami** [comment]
Sorry, this issue is not in my priority list (and I don't even have a Mac). The only thing I can see there is you're using `hypercon`. Maybe try without it? Just Telethon. There's been some issues with proxies and the event loop used on Windows. Maybe try a different `asyncio` event loop, if available? If a bare Telethon script doesn't work on Docker, then al that's left is digging into why, where and when the connection fails.

**Comment by vashchukmaksim** [comment]
I tried on Windows and Ubuntu both with and without Docker. All works fine, so this is only an issue with a pair Docker/Mac.

Yeah, looks like a minor in this case but really annoying for me since that's my main setup :)

Will try different options and post here in case any of them are working.

**Comment by vashchukmaksim** [comment]
Works fine with Docker Mac 3.2.2 but not with the latest version. Looks like a Docker issue. https://docs.docker.com/docker-for-mac/release-notes/

**Comment by Lonami** [comment]
Closing as it seems to be a Docker issue according to the previous post, thanks.
