### ISSUE TITLE
network error when receiving phonemigrateerror

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#170]
`
2017-07-13 17:03:45_root_WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 109, in receive
    remote_msg_id, remote_seq, reader, updates)
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 207, in _process_msg
    return self._handle_rpc_result(msg_id, sequence, reader)
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 355, in _handle_rpc_result
    raise error
telethon.errors.rpc_errors_303.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 4.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcp_client.py", line 97, in read
    partial = self._socket.recv(bytes_left)
BlockingIOError: [Errno 11] Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/elenoon/telegram-chanel-copier/channel_copier.py", line 120, in main
    client.send_code_request(LAST_PHONE_NUMBER)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 259, in send_code_request
    SendCodeRequest(phone_number, self.api_id, self.api_hash))
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 221, in invoke
    self.reconnect(new_dc=e.new_dc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 171, in reconnect
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 140, in connect
    return super().connect()
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 132, in connect
    layer=layer, query=request
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 104, in receive
    seq, body = self.transport.receive(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/tcp_transport.py", line 56, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcp_client.py", line 115, in read
    'The read operation exceeded the timeout.') from error
TimeoutError: The read operation exceeded the timeout.
`

**Comment by Lonami** [comment]
[Check your system time](https://time.is/)?

**Comment by hnikaein** [comment]
:|
not_related!

**Comment by Lonami** [comment]
> not_related

So your system time is correct?

**Comment by hnikaein** [comment]
yes!
when I'm working with telethon, suddenly I receive this error!

**Comment by Lonami** [comment]
Since reading is already blocking, "BlockingIOError: [Errno 11] Resource temporarily unavailable" won't happen. I'm closing this issue. Open a new one with new traceback if it still happens etc.
