### ISSUE TITLE
AttributeError: 'PhotoSizeProgressive' object has no attribute 'size'

### ISSUE THREAD

**Issue by Soberia** [LonamiWebs/Telethon#1700]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

<details><summary><strong>Code that causes the issue</strong></summary>

```python
import asyncio

from telethon import TelegramClient


async def main():
    async with TelegramClient(...) as client:
        async for message in client.iter_messages('sportsru', ids=29303):
            await client.download_media(message, thumb=0)


asyncio.run(main())
```

</details>

<details><summary><strong>Traceback</strong></summary>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "<stdin>", line 4, in main
  File "/*/.dev/venv/lib/python3.9/site-packages/telethon/client/downloads.py", line 408, in download_media
    return await self._download_photo(
  File "/*/.dev/venv/lib/python3.9/site-packages/telethon/client/downloads.py", line 821, in _download_photo
    file_size=size.size,
AttributeError: 'PhotoSizeProgressive' object has no attribute 'size'
```

</details>

**Comment by Lonami** [comment]
Thanks for the detailed report.
