### ISSUE TITLE
AttributeError: 'Message' object has no attribute '_finish_init'

### ISSUE THREAD

**Issue by Soberia** [LonamiWebs/Telethon#1701]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

This only occurs with the master repo, no issue with v1.19.5

<details><summary><strong>Code that causes the issue</strong></summary>

```python
import asyncio

from telethon import TelegramClient


async def main():
    async with TelegramClient(...) as client:
        async for message in client.iter_messages('telegram', limit=1):
            ...


asyncio.run(main())
```

</details>

<details><summary><strong>Traceback</strong></summary>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in main
  File "/*/.dev/venv/lib/python3.9/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/*/.dev/venv/lib/python3.9/site-packages/telethon/client/messages.py", line 198, in _load_next_chunk
    message._finish_init(self.client, entities, self.entity)
AttributeError: 'Message' object has no attribute '_finish_init'
```

</details>

**Comment by Lonami** [comment]
Note that this is solved if the code ever imports the `patched` module, which is why I wasn't seeing the bug…
