### ISSUE TITLE
struct.error: argument out of range

### ISSUE THREAD

**Issue by Nadni** [LonamiWebs/Telethon#1702]
**Code that causes the issue**
```
from telethon import TelegramClient

chat = ...
api_id = ...
api_hash = ...

client = TelegramClient('session_id', api_id, api_hash)

with client:
    for msg in client.iter_messages(chat, 10):
        print(msg.sender.first_name, ':', msg.text)

```

**Traceback**
```
Traceback (most recent call last):
  File "downloader.py", line 12, in <module>
    for msg in client.iter_messages(chat, 10):
  File "C:\Program Files\Python38\lib\site-packages\telethon\requestiter.py", line 87, in __next__
    return self.client.loop.run_until_complete(self.__anext__())
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Program Files\Python38\lib\site-packages\telethon\requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "C:\Program Files\Python38\lib\site-packages\telethon\client\messages.py", line 26, in _init
    self.entity = await self.client.get_input_entity(entity)
  File "C:\Program Files\Python38\lib\site-packages\telethon\client\users.py", line 440, in get_input_entity
    users = await self(functions.users.GetUsersRequest([
  File "C:\Program Files\Python38\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Program Files\Python38\lib\site-packages\telethon\client\users.py", line 58, in _call
    future = sender.send(request, ordered=ordered)
  File "C:\Program Files\Python38\lib\site-packages\telethon\network\mtprotosender.py", line 174, in send
    state = RequestState(request)
  File "C:\Program Files\Python38\lib\site-packages\telethon\network\requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "C:\Program Files\Python38\lib\site-packages\telethon\tl\tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "C:\Program Files\Python38\lib\site-packages\telethon\tl\functions\users.py", line 72, in _bytes
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(x._bytes() for x in self.id),
  File "C:\Program Files\Python38\lib\site-packages\telethon\tl\functions\users.py", line 72, in <genexpr>
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(x._bytes() for x in self.id),
  File "C:\Program Files\Python38\lib\site-packages\telethon\tl\types\__init__.py", line 11203, in _bytes
    struct.pack('<i', self.user_id),
struct.error: argument out of range
```

**Comment by Lonami** [comment]
What is `chat`?

**Comment by Nadni** [comment]
9977754872

**Comment by Nadni** [comment]
> 
> 
> What is `chat`?

9977754872

**Comment by Lonami** [comment]
That ID cannot be correct. Telegram user IDs are only 32-bit long, and that would need 34.
