### ISSUE TITLE
Allow Clicking on @BotFather buttons using Telethon TelegramClient

### ISSUE THREAD

**Issue by SpEcHiDe** [LonamiWebs/Telethon#1716]
currently, in Telethon, if I try to click on Transfer Ownership button 

![IMG_20210303_114501_475](https://user-images.githubusercontent.com/6317196/109761225-07633900-7c16-11eb-8522-8b30db2a4c62.jpg)

I get the following error
```>>> await j[0].buttons[0][0].click()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/home/shrimadhav/UniBorg/venv/lib/python3.9/site-packages/telethon/tl/custom/messagebutton.py", line 100, in click
    return await self._client(req)
  File "/home/shrimadhav/UniBorg/venv/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/shrimadhav/UniBorg/venv/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.PasswordHashInvalidError: The password (and thus its hash value) you entered is invalid (caused by GetBotCallbackAnswerRequest)
```

## I think, 🤔 Telethon should check the requires_password field, and pass password parameter to the GetBotCallbackAnswerRequest.

The button has another attribute `requires_password`
```{'text': 'Yes, I am sure, proceed.', 'data': b'bots/7351948/trsf/7351948/c', 'requires_password': True}```

**Comment by Lonami** [comment]
What password does it expect?

**Comment by Lonami** [comment]
Please let me know if the above fixes it, if not I will reopen.

**Comment by SpEcHiDe** [comment]
![IMG_20210307_211923_081](https://user-images.githubusercontent.com/6317196/110245847-f8201a80-7f8a-11eb-847c-c89e641cc55d.jpg)


yes, it is working fine. 

I have a doubt. Is there a recommended way on how to handle 2FA passwords, in code?

**Comment by Lonami** [comment]
Doubts and questions belong in TelethonChat or StackOverflow.
