### ISSUE TITLE
Can not execute GetNotifySettingsRequest when peer is not instance of InputNotifyXxx

### ISSUE THREAD

**Issue by vanutp** [LonamiWebs/Telethon#1725]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events
from telethon.tl.functions.account import GetNotifySettingsRequest
from telethon.tl.types import InputNotifyPeer

client = TelegramClient(...)


@client.on(events.NewMessage())
async def test(event):
    # This works
    await client(GetNotifySettingsRequest(InputNotifyPeer(event.input_chat)))
    # This doesn't
    await client(GetNotifySettingsRequest(event.chat))


client.start()
client.run_until_disconnected()
```

**Traceback**
```
Unhandled exception on test
Traceback (most recent call last):
  File "...\lib\site-packages\telethon\tl\tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "...\lib\site-packages\telethon\tl\functions\account.py", line 615, in _bytes
    self.peer._bytes(),
AttributeError: 'NoneType' object has no attribute '_bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\lib\site-packages\telethon\client\updates.py", line 454, in _dispatch_update
    await callback(event)
  File "test.py", line 13, in test
    await client(GetNotifySettingsRequest(event.chat))
  File "...\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "...\lib\site-packages\telethon\client\users.py", line 58, in _call
    future = sender.send(request, ordered=ordered)
  File "...\lib\site-packages\telethon\network\mtprotosender.py", line 176, in send
    state = RequestState(request)
  File "...\lib\site-packages\telethon\network\requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "...\lib\site-packages\telethon\tl\tlobject.py", line 200, in __bytes__
    raise TypeError('a TLObject was expected but found something else')
TypeError: a TLObject was expected but found something else
```

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/blob/a1f91d6eb8eaf06b5d823852310ce86b1ad4aa6b/telethon_generator/generators/tlobject.py#L25

and

https://github.com/LonamiWebs/Telethon/blob/e1d2c81dca7c26c11365457ad2f7857853249471/telethon/client/users.py#L590-L602

should be responsible to make it work, but it's weird it isn't working.

**Comment by vanutp** [comment]
For example, if `notify` is `Channel`, it has `SUBCLASS_OF_ID`, so except at line 601 isn't triggered and the function returns None

**Comment by Lonami** [comment]
Ah, good catch.
