### ISSUE TITLE
The read operation exceeded the timeout

### ISSUE THREAD

**Issue by mrkovalchuk** [LonamiWebs/Telethon#180]
I saw issues about such mistakes, but I could not overcome my mistakes.

I create connection with InteractiveTelegramClient (default)
```python
def connect():
    client = \
        InteractiveTelegramClient(session_user_id='000000',
                                  api_id=100000,
                                  api_hash='0000000',
                                  user_phone='+0000000')

    if not client.is_user_authorized():
        client.send_code_request('+0000000')
        client.sign_in('+00000000', input('Enter code: '))

    recipient = 0
    dialogs, entities = client.get_dialogs(10)
    for i, e in enumerate(entities):
        if e.id == 00000000:
            recipient = e
            break

    return client, recipient

def send_media_to_telegram(image):
    client, recipient = connect()
    client.send_photo(image, recipient)
    client.disconnect()
```

In another place I make the following call:
`send_media_to_telegram(path)`

image = 'test5.png'
image.size = 295Kb
**Full traceback:**
```==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
Uploading test5.png...
Uploaded 32.00KB out of 287.67KB (11.12%)
Uploaded 64.00KB out of 287.67KB (22.25%)
Internal Server Error: /save_image/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcp_client.py", line 97, in read
    partial = self._socket.recv(bytes_left)
BlockingIOError: [Errno 11] Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kovalchuk-as/PycharmProjects/PlotBuilder/mainApp/views.py", line 67, in ajax
    send_media_to_telegram(path)
  File "/home/kovalchuk-as/PycharmProjects/PlotBuilder/mainApp/helpers/send_to_telegram.py", line 44, in send_media_to_telegram
    client.send_photo('test5.png', recipient)
  File "/home/kovalchuk-as/PycharmProjects/PlotBuilder/mainApp/TelegramClient.py", line 224, in send_photo
    path, progress_callback=self.upload_progress_callback)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 284, in upload_file
    result = self.invoke(request)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 261, in invoke
    request, updates=updates
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 220, in invoke
    self._sender.receive(request, updates=updates)
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 104, in receive
    seq, body = self.transport.receive(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/tcp_transport.py", line 56, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcp_client.py", line 114, in read
    'The read operation exceeded the timeout.') from error
TimeoutError: The read operation exceeded the timeout.
```

This str optional (sometimes there is, sometimes does not have time):
Uploaded 32.00KB out of 287.67KB (11.12%)
Uploaded 64.00KB out of 287.67KB (22.25%)

I do not have any ideas....

**Comment by mrkovalchuk** [comment]
Thank you) hurry, forgot to edit.

To issue. https://ibb.co/hP839k - image file.
`Internal Server Error: /save_image/` - Django runserver information

**Comment by Lonami** [comment]
Running `try_telethon.py`:
```
Enter a message: !up ~/Downloads/test5.png
Uploading /home/lonami/Downloads/test5.png...
Uploaded 32.00KB out of 288.06KB (11.11%)
Uploaded 64.00KB out of 288.06KB (22.22%)
Uploaded 96.00KB out of 288.06KB (33.33%)
Uploaded 128.00KB out of 288.06KB (44.43%)
Uploaded 160.00KB out of 288.06KB (55.54%)
Uploaded 192.00KB out of 288.06KB (66.65%)
Uploaded 224.00KB out of 288.06KB (77.76%)
Uploaded 256.00KB out of 288.06KB (88.87%)
Uploaded 288.00KB out of 288.06KB (99.98%)
Uploaded 288.06KB out of 288.06KB (100.00%)
Photo sent!
```

I can't reproduce the issue.

**Comment by pazis** [comment]
Same issue.

"The read operation exceeded the timeout.
Probably system restart, sleeping for 5 minutes..."

Python3.6
System time is correct
centOS 6

**Comment by Lonami** [comment]
It's really hard to work with these issues when I cannot reproduce them :(

**Comment by pazis** [comment]
I deleted my .session file. 

I can't authenticate anymore. Here is the output:

```
==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
Traceback (most recent call last):
  File "ignite.py", line 4, in <module>
    api_id=XXX, api_hash='XXX')
  File "/home/pazis/telethon/XXX/interactive_telegram_client.py", line 61, in __init__
    if not self.connect():
  File "/usr/lib64/python3.6/site-packages/telethon/telegram_client.py", line 140, in connect
    return super().connect()
  File "/usr/lib64/python3.6/site-packages/telethon/telegram_bare_client.py", line 106, in connect
    authenticator.do_authentication(transport)
  File "/usr/lib64/python3.6/site-packages/telethon/network/authenticator.py", line 212, in do_authentication
    raise AssertionError('Invalid new nonce hash')
AssertionError: Invalid new nonce hash
```

**Comment by Lonami** [comment]
> ```
> AssertionError: Invalid new nonce hash
> ```

That happened [here](https://github.com/LonamiWebs/Telethon/issues/172#issuecomment-316150766) :/

Retry? Maybe Telethon should be the one who retried. But where would be the limit?

**Comment by pazis** [comment]
This is retry:

```
==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/telethon/extensions/tcp_client.py", line 97, in read
    partial = self._socket.recv(bytes_left)
BlockingIOError: [Errno 11] Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ignite.py", line 4, in <module>
    api_id=XXX, api_hash='XXX')
  File "/home/pazis/telethon/interactive_telegram_client.py", line 61, in __init__
    if not self.connect():
  File "/usr/lib64/python3.6/site-packages/telethon/telegram_client.py", line 140, in connect
    return super().connect()
  File "/usr/lib64/python3.6/site-packages/telethon/telegram_bare_client.py", line 132, in connect
    layer=layer, query=request
  File "/usr/lib64/python3.6/site-packages/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/usr/lib64/python3.6/site-packages/telethon/telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "/usr/lib64/python3.6/site-packages/telethon/network/mtproto_sender.py", line 104, in receive
    seq, body = self.transport.receive(**kwargs)
  File "/usr/lib64/python3.6/site-packages/telethon/network/tcp_transport.py", line 56, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/usr/lib64/python3.6/site-packages/telethon/extensions/tcp_client.py", line 115, in read
    'The read operation exceeded the timeout.') from error
TimeoutError: The read operation exceeded the timeout.
```

**Comment by pazis** [comment]
I feel like this problem and `BadMessageError with lower or higher seq_no` are somehow related to each other. 

With Telethon 0.11.5 I can't do anything because of `The read operation exceeded the timeout.` and with Telethon 0.8 I get `BadMessageError` some times when invoking different request in a row. 😢

**Comment by pazis** [comment]
Does commit [`7e85a3c`](https://github.com/LonamiWebs/Telethon/commit/7e85a3cda487df9546fcf136700d590a0a2cdd14) for #195 fix this issue, too?

**Comment by Lonami** [comment]
> Does commit [`7e85a3c`](https://github.com/LonamiWebs/Telethon/commit/7e85a3cda487df9546fcf136700d590a0a2cdd14) for #195 fix this issue, too?

No idea, I can hardly reproduce it. Has it fixed the issue for you?

**Comment by Lonami** [comment]
Since I now have a thread which is always reading no matter what, maybe this has been fixed, as it doesn't care for `TimeoutError`'s and will just retry. Can anyone try?

**Comment by Lonami** [comment]
Closing due to inactivity. There has been many changes and this error has likely been fixed, or is present in another form.
