### ISSUE TITLE
Periodically getting 'msg_seqno too low' error message

### ISSUE THREAD

**Issue by alexvelickiy** [LonamiWebs/Telethon#195]
I'm using Telethon (version: 0.11.5) on  Django site. The page shows telegram user dialogs with TelegramClient get_dialogs() method. Most of the time it works fine, but sometimes I get error:
**msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno)**

My code:
```
def init_telegram():
    api_id = 'my_app_id'
    api_hash = 'my_app_hash'

    client = TelegramClient('anonymous', api_id, api_hash)
    client.connect()

    if not client.is_user_authorized():
        client.send_code_request('my_phone_number')
        client.sign_in('my_phone_number', input('Enter code: '))

    return client


def get_list_of_telegram_channels():
    output = []
    client = init_telegram()

    dialogs, entities = client.get_dialogs(limit=20)
    for i, entity in enumerate(entities, start=1):
        output.append({
            'name': get_display_name(entity),
            'id': entity.to_dict()['id']
        })
    client.disconnect()
    return output
```

Error traceback:

```
ERROR 2017-08-12 17:55:53,391 exception 28711 47681226286848 Internal Server Error: /
Traceback (most recent call last):
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/django/views/generic/base.py", line 155, in get
    context = self.get_context_data(**kwargs)
  File "/home/alex/btc_fast_buy/main/views.py", line 52, in get_context_data
    context['telegram_channels'] = get_list_of_telegram_channels()
  File "/home/alex/btc_fast_buy/main/funcs/telegram.py", line 52, in get_list_of_telegram_channels
    dialogs, entities = client.get_dialogs(limit=20)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/telethon/telegram_client.py", line 370, in get_dialogs
    limit=limit))
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 109, in receive
    remote_msg_id, remote_seq, reader, updates)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 222, in _process_msg
    return self._handle_bad_msg_notification(msg_id, sequence, reader)
  File "/home/alex/myproject/myenv/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 325, in _handle_bad_msg_notification
    raise error
telethon.errors.rpc_errors.BadMessageError: (BadMessageError(...), 'msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno).')

```

**Comment by Lonami** [comment]
> on Django site

Are there multiple threads involved? It seems very strange that the sequence number is too low since this part ensures it's always higher:
https://github.com/LonamiWebs/Telethon/blob/1794acdfece98c8441805175aa2ff35de4e0de2d/telethon/tl/session.py#L237-L238

**Comment by pazis** [comment]
I always had the exact same problem when multiple threads were accessing telegram client. Finally I decided to change my app into single thread!!! Because I could never get rid of this.

**Comment by Lonami** [comment]
Shoot I just realized the message ID bit is *not* thread-safe, only the sequence number. Hold on.

**Comment by Lonami** [comment]
Oh by the way you can install upstream by running:
```bash
pip install https://github.com/LonamiWebs/Telethon/zipball/master
```

**Comment by alexvelickiy** [comment]
Yeah, it's Django web-site so the code may work in multiple threads. Is this the problem that appear when multiple threads make calls in general or when calls are made to same Telegram user?

**Comment by alexvelickiy** [comment]
Sorry, what is upstream?

**Comment by Lonami** [comment]
> Is this the problem that appear when multiple threads make calls in general or when calls are made to same Telegram user?

On the same Telegram user (session) there may be a race condition. If they're different users this should be no issue because each has its own connection and should be independent from each other.

> Sorry, what is upstream?

By upstream I mean the most up-to-date version, hosted here over GitHub. I don't push changes to `pip` as often as I do here, I may be using the word wrong 😅

**Comment by alexvelickiy** [comment]
But it may be correct as well, I'm not native)

**Comment by alexvelickiy** [comment]
I tried 
```
pip install https://github.com/LonamiWebs/Telethon/zipball/master
```
And got an error: 
```
No files/directories in C:\Users\Alex\AppData\Local\Temp\pip-3_kyeibh-build\pip-
egg-info (from PKG-INFO)
```

**Comment by Lonami** [comment]
> Is it stable and tested version?

I always try to push working versions.

> got this error

Oh strange, I just followed the indications @nyuszika7h suggested over [here](https://github.com/LonamiWebs/Telethon/issues/86#issuecomment-320523063). You can also download the git repository, run `python3 setup.py gen_tl`, and then copy the `telethon/` (not `Telethon/`) folder to wherever your script is to use it.

**Comment by Herny64** [comment]
Currently (in the last few hours) I get this Error every time when I run the try_telethon.py.
5 hours ago the try_telethon.py worked like a charm.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/151e1623d3f0ed71951a73169849d6fbbeaad162 and https://github.com/LonamiWebs/Telethon/commit/12a39873f1c67b4f110a5f17dedd0e932456c293 should have fixed this a while ago now. If it still happens, leave another comment so that we can continue the discussion.
