### ISSUE TITLE
Support CDN redirects

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#208]
2017-08-23 10:50:14_root_WARNING: +989368953177: Catched: 'FileCdnRedirect' object has no attribute 'bytes'
2017-08-23 10:50:14_root_WARNING: +989368953177: Traceback (most recent call last):
  .
  .
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 682, in download_media
    message, file, add_extension, date, progress_callback
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 749, in _download_document
    progress_callback=progress_callback
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 453, in download_file
    if not result.bytes:
AttributeError: 'FileCdnRedirect' object has no attribute 'bytes'

**Comment by Lonami** [comment]
Can you please tell me what channel were you trying this on? So that I can test the new additions.

**Comment by Lonami** [comment]
Okay after [these changes](https://github.com/LonamiWebs/Telethon/compare/0cae62f0917dc96a2be366df7e6cd20b81bb4baa...09272ef6fcd6c0b4915875d250d9f66946e8190a), connecting and downloading **encrypted** media from CDNs works. Now I need to figure out how to decrypt it.

**Comment by Lonami** [comment]
Those few lines changed there? It took me *hours* to figure out how to write that correctly. But it *seems* to work from my tests, so… let me know if it works under real use cases once I push changes to `pip`.
