### ISSUE TITLE
AssertionError: Could not find a valid key for fingerprints:

### ISSUE THREAD

**Issue by einali** [LonamiWebs/Telethon#222]
gits master version  has problem in rsa encryption

for 

```
output = interactive_telegram_client.download_media(
            msg.media,
            file=output,
            progress_callback=client.download_progress_callback)
```

i got error :

```
[10]Downloading media with name usermedia10/76749...
Traceback (most recent call last):
  File "/home/mehdi/ws/temp/Telethon/example.py", line 41, in <module>
    progress_callback=client.download_progress_callback)
  File "/home/mehdi/ws/temp/Telethon/telethon/telegram_client.py", line 667, in download_media
    media, file, date, progress_callback
  File "/home/mehdi/ws/temp/Telethon/telethon/telegram_client.py", line 698, in _download_photo
    progress_callback=progress_callback
  File "/home/mehdi/ws/temp/Telethon/telethon/telegram_bare_client.py", line 491, in download_file
    offset, part_size
  File "/home/mehdi/ws/temp/Telethon/telethon/crypto/cdn_decrypter.py", line 48, in prepare_decrypter
    cdn_redirect.file_token, offset, part_size
  File "/home/mehdi/ws/temp/Telethon/telethon/telegram_bare_client.py", line 128, in connect
    authenticator.do_authentication(connection)
  File "/home/mehdi/ws/temp/Telethon/telethon/network/authenticator.py", line 82, in do_authentication
    .format(', '.join([repr(f) for f in fingerprints]))
AssertionError: Could not find a valid key for fingerprints: b'8Y\x93\x8eSrF%'

Process finished with exit code 1
```

**Comment by Lonami** [comment]
If you're using https://github.com/LonamiWebs/Telethon/commit/68cdc9eaf103d68280545155116516c19593c171, the current version is so broken I cannot even connect. I'll look into this once I solve a few issues.

**Comment by Lonami** [comment]
`master` should be working again. I assume the file you're trying to download is from a CDN. If this is the case, I'm afraid I *probably* won't be able to reproduce this issue, since I would need to test with an IP address close to wherever you live (so I get connected to the same data center and can thus get access to the same CDN). Any idea?

**Comment by Lonami** [comment]
Nevermind another person allowed me to use a proxy so I managed to download the content from the CDN. However I get "CdnTamperedError", and I doubt it's been tampered for reals, more like I'm doing something wrong…

**Comment by Lonami** [comment]
Try `v0.13.2`, it's available through `pip`.

**Comment by Lonami** [comment]
Confirmed to work thanks to #243 (it reached the end, so it worked).
