### ISSUE TITLE
TypeError: descriptor 'to_bytes' requires a 'int' object [...] When trying to send a message using phone number

### ISSUE THREAD

**Issue by Alireza2n** [LonamiWebs/Telethon#234]
Hi, 
first of all, I appreciate all the hard work for this project :)

When trying to send a message using phone number, the following error occurs:

```
Traceback (most recent call last):
 ....
  File "/usr/share/nginx/www/telegramclient/app/app/views.py", line 44, in send_msg_telegram
    client.send_message(entity=recipient, message=msg)
  File "/usr/share/nginx/www/telegramclient/env/lib/python3.4/site-packages/telethon/telegram_client.py", line 401, in send_message
    peer=self._get_entity(entity),
  File "/usr/share/nginx/www/telegramclient/env/lib/python3.4/site-packages/telethon/telegram_client.py", line 862, in _get_entity
    contacts = self(GetContactsRequest(''))
  File "/usr/share/nginx/www/telegramclient/env/lib/python3.4/site-packages/telethon/telegram_client.py", line 220, in invoke
    return super().invoke(request, call_receive=call_receive)
  File "/usr/share/nginx/www/telegramclient/env/lib/python3.4/site-packages/telethon/telegram_bare_client.py", line 303, in invoke
    self._sender.send(request)
  File "/usr/share/nginx/www/telegramclient/env/lib/python3.4/site-packages/telethon/network/mtproto_sender.py", line 74, in send
    request.on_send(writer)
  File "/usr/share/nginx/www/telegramclient/env/lib/python3.4/site-packages/telethon/tl/functions/contacts.py", line 246, in on_send
    writer.write_int(self.hash)
  File "/usr/share/nginx/www/telegramclient/env/lib/python3.4/site-packages/telethon/extensions/binary_writer.py", line 36, in write_int
    value, length=4, byteorder='little', signed=signed))
TypeError: descriptor 'to_bytes' requires a 'int' object but received a 'str'
```

### What I've done

```
    client = TelegramClient('telethon_dev_test', api_id, api_hash)
    client.connect()

    if not client.is_user_authorized():
        client.send_code_request(phone)

        try:
            client.sign_in(phone, xxxxx)
        except SessionPasswordNeededError:
            client.sign_in(password='xxxxxx')

    recipient = 9891xxxxxx
    client.send_message(entity=recipient, message='some message')
```

### More information
Currently I have worked around the issue by changing line 862 of telegram_client.py from:
`
contacts = self(GetContactsRequest(''))
`
to
`
contacts = self(GetContactsRequest(1))
`

**Comment by Lonami** [comment]
> I appreciate all the hard work for this project :)

Thank you!

> I have worked around the issue

Instead passing 1, pass 0 so it's an empty hash. That's indeed the fix, so if you would like to make a pull request to be part of the collaborators feel free! Otherwise I'll do it tomorrow ^^

The type changed when updating from layer 70 to layer 71 ([see diff](https://github.com/LonamiWebs/Telethon/commit/a5d86b4572fb0b015e8e12e670c4262f8d94fe4a#L970)) and since Python is duck typed I didn't spot it.
