### ISSUE TITLE
error in ReadThread

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#248]
hi . 
I using multithreading for getting the posts from channels. 
After about a time that is running System suddenly confronted with this error
``` python
is_user_authorized :  TrueException in thread ReadThread:
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 951, in _recv_thread_impl
    self._sender.receive(update_state=self.updates)
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 90, in receive
    body = self.connection.recv()
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 129, in _recv_tcp_full
    packet_length_bytes = self.read(4)
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 200, in _read_plain
    return self.conn.read(length)
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 101, in read
    self._raise_connection_reset()
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 112, in _raise_connection_reset
    raise ConnectionResetError('The server has closed the connection.')
ConnectionResetError: The server has closed the connection.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 960, in _recv_thread_impl
    self.reconnect()
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 202, in reconnect
    self.connect()
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 148, in connect
    ok = super().connect()
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 152, in connect
    layer=layer, query=request
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 228, in invoke
    raise AssertionError('Cannot invoke requests from the ReadThread')
AssertionError: Cannot invoke requests from the ReadThread
```
could you tell me what is the problem?
thanks.

**Comment by Lonami** [comment]
Update.

**Comment by alihossein** [comment]
@Lonami  
update telethon in my server? 
 by using  `pip3 install --upgrade telethon` command?

**Comment by Lonami** [comment]
What else could it be?

**Comment by alihossein** [comment]
I updated it yesterday, but this morning confronted with this error again : 
``` python
Exception in thread ReadThread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 951, in _recv_thread_impl
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 90, in receive
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 129, in _recv_tcp_full
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 200, in _read_plain
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 91, in read
AttributeError: 'NoneType' object has no attribute 'recv'

Exception in thread ReadThread:
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 951, in _recv_thread_impl
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 90, in receive
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 129, in _recv_tcp_full
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 200, in _read_plain
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 101, in read
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 112, in _raise_connection_reset
ConnectionResetError: The server has closed the connection.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 960, in _recv_thread_impl
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 202, in reconnect
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 148, in connect
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 152, in connect
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 228, in invoke
AssertionError: Cannot invoke requests from the ReadThread

Exception in thread ReadThread:
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 951, in _recv_thread_impl
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 90, in receive
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 129, in _recv_tcp_full
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 200, in _read_plain
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 101, in read
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 112, in _raise_connection_reset
ConnectionResetError: The server has closed the connection.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 960, in _recv_thread_impl
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 202, in reconnect
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 148, in connect
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 152, in connect
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 228, in invoke
AssertionError: Cannot invoke requests from the ReadThread

Exception in thread ReadThread:
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 951, in _recv_thread_impl
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 90, in receive
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 129, in _recv_tcp_full
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/network/connection.py", line 200, in _read_plain
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 101, in read
  File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 112, in _raise_connection_reset
ConnectionResetError: The server has closed the connection.
‍‍‍

**Comment by phretor** [comment]
I confirm having the same issue. I'm currently running with the latest version available via `pip install -U telethon`.

**Comment by Lonami** [comment]
@phretor version 0.13.4? That's weird. I forward all unhandled exceptions from the `ReadThread` to the main one…

**Comment by einali** [comment]
same problem with 0.13.4!!

**Comment by Lonami** [comment]
@alihossein I'm not sure how this:
> ```
> Exception in thread ReadThread:
> ...
>   File "/home/xxx/.local/lib/python3.5/site-packages/telethon/extensions/tcp_client.py", line 91, in read
> AttributeError: 'NoneType' object has no attribute 'recv'
> ```

Could even happen to begin with. The `socket is None`, but the `ReadThread` isn't started until you're connected (and hence the `socket is not None`). Unless the traceback order somehow got messed up. And when you got "AssertionError: Cannot invoke requests from the ReadThread" while trying to `.reconnect()` from that thread… it's impossible. The thread is set to `None` so it shouldn't even be able to know it's been called from there. I'm so clueless.

**Comment by Lonami** [comment]
So, what's expected behavior when I'm trying to reconnect from a background thread? What should I do if it crashes?

**Comment by Lonami** [comment]
It should work better on `v0.13.5`. So upgrade, test again, and let me know if it still fails by leaving here a comment or something. Meanwhile I'll assume that it has been fixed and close the issue.

**Comment by alihossein** [comment]
>It should work better on v0.13.5. So upgrade, test again

@Lonami 
thanks.
I started running with about 50 threads.If I'm back in trouble, I'll announce
