### ISSUE TITLE
try_telethon.py exit when send private message

### ISSUE THREAD

**Issue by jianggau** [LonamiWebs/Telethon#250]
### What went wrong
it works on group chat, but not private chat

### log
```
Enter a message: a
Unexpected error (<class 'AttributeError'>): 'UpdateShortSentMessage' object has no attribute 'updates' at
Traceback (most recent call last):
  File "try_telethon.py", line 43, in <module>
    client.run()
  File "/data/test2/Telethon/telethon_examples/interactive_telegram_client.py", line 226, in run
    entity, msg, link_preview=False)
  File "/data/test2/Telethon/telethon/telegram_client.py", line 444, in send_message
    for update in result.updates:
AttributeError: 'UpdateShortSentMessage' object has no attribute 'updates'

```
```
dir(result)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'confirm_received', 'constructor_id', 'content_related', 'date', 'empty', 'entities', 'id', 'media', 'on_response', 'on_send', 'out', 'pretty_format', 'pts', 'pts_count', 'request_msg_id', 'rpc_error', 'stringify', 'subclass_of_id', 'to_dict']

result.__dict__
{'request_msg_id': 0, 'confirm_received': <threading.Event object at 0x7fc0c51a79b0>, 'rpc_error': None, 'constructor_id': 0, 'content_related': False, 'out': True, 'id': 33, 'pts': 58, 'pts_count': 1, 'date': datetime.datetime(2017, 9, 18, 14, 1, 48), 'media': messageMediaEmpty#3ded6320 = MessageMedia, 'entities': []}

```

**Comment by Lonami** [comment]
Fixed on the latesy version, pushed to PyPi earlier today :)

**Comment by jianggau** [comment]
https://github.com/LonamiWebs/Telethon/blob/81d4d76d16cf24fad65d9a514d4df6ee6b5ba2a4/telethon/telegram_client.py#L430

second line  `request` should be `result` . 
that cause the issue :)
```
        result = self(request)
        if isinstance(request, UpdateShortSentMessage):
```

**Comment by Lonami** [comment]
Shoot! Would you like to make a pull request? I can't change it right now.

**Comment by jianggau** [comment]
PR :)
