### ISSUE TITLE
test server configrution and breaking signin to two seperate step

### ISSUE THREAD

**Issue by phpust** [LonamiWebs/Telethon#278]
hi 
i am new to telethon and i want to work with Test configuration. where do i must put DC address to go from Production  to test?

also i have another problem  , i want to build an api on top of telethon to let my another app login to telegram and receive data, so i need to do login step by step.

my first uri is register phone number : {
`client = TelegramClient('sessions/'+api_hash, api_id, api_hash)`
`client.connect()`
`client.sign_in(phone)`
}

my second method is confirm code : {
    `client = TelegramClient('sessions/'+api_hash, api_id, api_hash)`
    `client.connect()`
    `try:`
    `    me = client.sign_in(phone)`
    `except Exception as e:`
    `    return jsonify({`
    `        "error": "-",`
    `        "success": False,`
    `        "message": str(e)`
    `    })`
}
but always this error raise : Please make sure to call send_code_request first.
i saw telegram_client.py and look likes self._phone is None. what can i do ? 

working environment : windows 10+python3

**Comment by Lonami** [comment]
> where do i must put DC address to go from Production to test?

For now, this code should do:
```python
client = TelegramClient('sess', api_id, api_hash)
client.session.server_address = 'test ip'
client._sender.connection.ip = 'test ip'
client.session.auth_key = None
assert client.connect()
```

More info about test servers: https://core.telegram.org/api/datacenter#testing-redirects

> but always this error raise

`self._phone is None` because you're literally creating a new client, that has got nothing to do with the previous one. The phone isn't saved to the session file. So I can change that so that you can call "sign in" with phone *and* code and override the saved phone. It's just for convenience.

**Comment by Lonami** [comment]
Remember that to confirm the phone from your second method you should do:
```python
client.sign_in(phone, code)
```

Since it needs to know for which phone that code is.

**Comment by Lonami** [comment]
Oh actually, this won't work because you also need to save the phone hash…

**Comment by Lonami** [comment]
Okay so this should work:
https://github.com/LonamiWebs/Telethon/blob/9445d2ba535ed7d214a7e6e68b85e7f3af1a690e/telethon/telegram_client.py#L141-L148

But I still advice you to cache the client somehow so you don't have to recreate it.

**Comment by phpust** [comment]
your solution does not work , as you mentioned  

>  If this is done on the same client, the client will fill said values 
           for you. 
its not same client , i do this but problem is not solved.
`
    # create session and sign in request to telegram
    client = TelegramClient('sessions/'+tg_account.api_hash, tg_account.api_id, tg_account.api_hash)
    client.connect()

    # If you already have a previous 'session_name.session' file, skip this.
    try:
        client._phone = phone
        client._phone_code_hash = tg_account.phone_code_hash
        me = client.sign_in(phone, int(code), tg_account.phone_code_hash)
    except Exception as e:
        return jsonify({
            "error": "-",
            "success": False,
            "message": str(e)
        })
`
also tried this : 
` client = TelegramClient('sessions/'+tg_account.api_hash, tg_account.api_id, tg_account.api_hash)
    client.connect()

    # If you already have a previous 'session_name.session' file, skip this.
    try:
        me = client.sign_in(phone, int(code), tg_account.phone_code_hash)
    except Exception as e:
        return jsonify({
            "error": "-",
            "success": False,
            "message": str(e)
        })
`
seems problem is that i must save current instance, but how is possible to save such an instance?
is there any other way? because i don't know how is possible to save an read an instance in any persistence.

**Comment by phpust** [comment]
@Lonami did you changed the source? 
i think i must pull to get the changes :)

**Comment by Lonami** [comment]
I haven't updated on PyPi yet, changes are on the `master` branch of this repository currently.

**Comment by Lonami** [comment]
> but how is possible to save such an instance?

Is the script ran every time a request is made to your application? If so, you need to use an external file. If it's not, just use some persistent variable to hold this information (and optionally clean it up after some time passed).

**Comment by phpust** [comment]
its an api , and yes script run every time a request made.
i changed my branch to master, did you checked your solution?
i get this error : 
 "object of type 'int' has no len()"

what is the problem? 
before your solution i tried this and same error appeared : 
`
    client._phone = phone
    client._phone_code_hash = tg_account.phone_code_hash
    me = client.sign_in(phone, int(code), none, none, tg_account.phone_code_hash)`

**Comment by Lonami** [comment]
Could you please provide the line where the error happens. The error alone is not too useful.

**Comment by phpust** [comment]
i used debuger but its too complecated , i can not find the source . may you check it too? i am checking for 1 hour and some in telegram_bare_client inside invoke this error raise somehow  :( 1 hour with no luck

**Comment by Lonami** [comment]
The error should be printed to the console with the full traceback, including the line where it happened.

**Comment by phpust** [comment]
this is full traceback , if its help : 
`Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_jwt_extended\view_decorators.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "E:\python\app\api\telegram\routes.py", line 179, in confirm_code
    me = client.sign_in(phone, code, None, None, tg_account.phone_code_hash)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_client.py", line 173, in sign_in
    phone, phone_code_hash, code
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 435, in invoke
    result = self._invoke(sender, call_receive, *requests)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 451, in _invoke
    sender.send(*requests)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 79, in send
    self._send_message(message)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 125, in _send_message
    + message.to_bytes()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\tl_message.py", line 16, in to_bytes
    body = GzipPacked.gzip_if_smaller(self.request)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\gzip_packed.py", line 22, in gzip_if_smaller
    data = request.to_bytes()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\functions\auth.py", line 679, in to_bytes
    TLObject.serialize_bytes(self.phone_number),
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\tlobject.py", line 93, in serialize_bytes
    if len(data) < 254:
TypeError: object of type 'int' has no len()`

**Comment by phpust** [comment]
`
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_jwt_extended\view_decorators.py", line 38, in wrapper
    return fn(*args, **kwargs)

  File "E:\python\app\api\telegram\routes.py", line 179, in confirm_code
    me = client.sign_in(phone, code, None, None, tg_account.phone_code_hash)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_client.py", line 173, in sign_in
    phone, phone_code_hash, code

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 435, in invoke
    result = self._invoke(sender, call_receive, *requests)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 451, in _invoke
    sender.send(*requests)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 79, in send
    self._send_message(message)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 125, in _send_message
    + message.to_bytes()

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\tl_message.py", line 16, in to_bytes
    body = GzipPacked.gzip_if_smaller(self.request)

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\gzip_packed.py", line 22, in gzip_if_smaller
    data = request.to_bytes()

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\functions\auth.py", line 679, in to_bytes
    TLObject.serialize_bytes(self.phone_number),

  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\tlobject.py", line 93, in serialize_bytes
    if len(data) < 254:
TypeError: object of type 'int' has no len()
`

**Comment by Lonami** [comment]
Are you using an integer as phone number?

**Comment by phpust** [comment]
in file tlobject.py -> function serialize_bytes(data) -> line 93 data value is this : 989308645800 , its my phone number. len(data) in  raise TypeError object of type 'int' has no length.
phone number must be string :/ , number is not valid , because len(data) is for string. so i changed my call to this : 
`me = client.sign_in(str(phone), code, None, None, tg_account.phone_code_hash)`
and now its working :) thank you. i think its good to support numbers too. or raise error in top level to show a good error message.

**Comment by TanND** [comment]
Thanks @phpust

**Comment by ma9edo** [comment]
> > where do i must put DC address to go from Production to test?
> 
> For now, this code should do:
> 
> ```python
> client = TelegramClient('sess', api_id, api_hash)
> client.session.server_address = 'test ip'
> client._sender.connection.ip = 'test ip'
> client.session.auth_key = None
> assert client.connect()
> ```
> 
> More info about test servers: https://core.telegram.org/api/datacenter#testing-redirects
> 
> > but always this error raise
> 
> `self._phone is None` because you're literally creating a new client, that has got nothing to do with the previous one. The phone isn't saved to the session file. So I can change that so that you can call "sign in" with phone _and_ code and override the saved phone. It's just for convenience.

AttributeError: can't set attribute 'server_address'
