### ISSUE TITLE
Error in get_message_history

### ISSUE THREAD

**Issue by k1-hedayati** [LonamiWebs/Telethon#28]
Hi, I occasionally get this error in get_message_history method:

```
[2017-03-03 12:16:44] ERROR [utils:utils.py:log_exception:77] 'NoneType' object has no attribute 'messages'
Traceback (most recent call last):
  File "/home/k1/src/bot/bot.py", line 174, in loop
    method['method']()
  File "/home/k1/src/bot/bot.py", line 183, in detele_old_messages
    message_history = self.client_api.get_message_history(bot, config.TELEGRAM['cleanup_messages'])
  File "/home/k1/.virtualenv/bot/lib/python3.5/site-packages/telethon/telegram_client.py", line 340, in get_message_history
    total_messages = getattr(result, 'count', len(result.messages))
AttributeError: 'NoneType' object has no attribute 'messages'
```
Locals
```
{
'add_offset': '0',
'entity': 'user#d10d979a flags:None '
          'is_self:flags.10?true '
          'contact:flags.11?true '
          'mutual_contact:flags.12?true '
          'deleted:flags.13?true '
          'bot:flags.14?true '
          'bot_chat_history:flags.15?true '
          'bot_nochats:flags.16?true '
          'verified:flags.17?true '
          'restricted:flags.18?true '
          'min:flags.20?true '
          'bot_inline_geo:flags.21?true '
          'id:int access_hash:flags.0?long '
          'first_name:flags.1?string '
          'last_name:flags.2?string '
          'username:flags.3?string '
          'phone:flags.4?string '
          'photo:flags.5?UserProfilePhoto '
          'status:flags.6?UserStatus '
          'bot_info_version:flags.14?int '
          'restriction_reason:flags.18?string '
          'bot_inline_placeholder:flags.19?string '
          '= User',
'limit': '20',
'max_id': '0',
'min_id': '0',
'offset_date': 'None',
'offset_id': '0',
'result': 'None',
'self': '<telethon.interactive_telegram_client.InteractiveTelegramClient '
'object at 0x7f4225ec4a90>'
}

```

**Comment by XyLoNaMiyX** [comment]
#22:

> Sometimes at any random point in time, an `ack` request may be received, thus considering the invoked method to be confirmed. This will end the loop that checks whether the result was received yet or not, thus **having a `None` result and failing** at random points on the code.

Currently, I don't know how this can be possibly solved.
