### ISSUE TITLE
TypeNotFoundError

### ISSUE THREAD

**Issue by megahomyak** [LonamiWebs/Telethon#3010]
Happens sometimes when idle (=> listening for events). I have last version of the library (1.21.1)

```
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<UpdateMethods._dispatch_update() done, defined at C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\updates.py:386> exception=TypeNotFoundError('Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 58ae39c9. Most likely, a TLObject was trying to be read when it should not be read. Remaining bytes: b"\\xc99\\xaeX\\x00\\x01\\x80\\x00\\x04\\xa9\\x05\\x00m\\xbc\\xb1\\x9d\\x97\\xf3\\xd4_2\\xe5\\xdd\\xbd\\x01\\xd7RP\\x18\\x14b`\\rHOT \\xf0\\x9f\\x9a\\x80 \\xf0\\x9f\\x94\\xa5\\x00\\x00\\xac\\xfa(A\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x95\\x08\\x08\\x00\\xc99\\xaeX\\x80\\x01\\x80\\x00\\x05\\xa9\\x05\\x00m\\xbc\\xb1\\x9dk\\xf2rb2\\xe5\\xdd\\xbd\\x01\\xd7RP,\\x14b`\\x04$BAT\\x00\\x00\\x00\\x15\\xc4\\xb5\\x1c\\x01\\x00\\x00\\x00?tNL\\x00\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\xac\\xfa(A\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x96\\x08\\x08\\x00\\x15\\xc4\\xb5\\x1c\\x01\\x00\\x00\\x00\\xc9!u\\xc3\\x01\\xd7RP\\x15\\xc4\\xb5\\x1c\\x01\\x00\\x00\\x00\\x03\\xa9\\x05\\x00\\x96\\x08\\x08\\x00\\x00\\x00\\x00\\x00\\x15\\xc4\\xb5\\x1c\\x01\\x00\\x00\\x00\\x1e\\x96\\x1a\\xd3@!\\xd4\\x01\\x01\\xd7RP\\x17\\xfe\\xb7?\\xaa\\x1b\\x81#\\x13Satoshi Street Bets\\x11satoshistreetbets\\x00\\x00<\\x9f\\x0b\\xd2\\x00\\x00\\x00\\x00\\xcd\\xc6\\x7f\\xbc\\xb8\\xfboJ\\x17\\x00\\x00\\x00Uk\\x02\\x00\\xcd\\xc6\\x7f\\xbc\\xb8\\xfboJ\\x17\\x00\\x00\\x00Wk\\x02\\x00\\x01\\x00\\x00\\x00\\x96\\xc9M`\\x00\\x00\\x00\\x00\\x18\\x04\\x12\\x9f\\xfc\\x85\\x02\\x00\\xff\\xff\\xff\\x7f\\x15\\xc4\\xb5\\x1c\\x02\\x00\\x00\\x00\\xc1X\\x84\\x93k\\x00\\x00\\x02\\x97\\xf3\\xd4_\\x90\\x9d}\\xd4\\xd7\\xb4\\xe6r\\x05Robin\\x00\\x00\\x08RobinBoo\\x00\\x00\\x00&\\xab\\xd3i\\x00\\x00\\x00\\x00\\x94\\xb71\\x1b\\xe9l\\xe8P\\xcd\\xc6\\x7f\\xbc~\\xa7F\']\\x00\\x00\\x00\\xfd\\xf7\\x04\\x00\\xcd\\xc6\\x7f\\xbc~\\xa7F\']\\x00\\x00\\x00\\xff\\xf7\\x04\\x00\\x04\\x00\\x00\\x00\\xf1Bo\\xe2\\xc1X\\x84\\x93G\\x00\\x00\\x02k\\xf2rb$tYN\\x9d\\xeb\\xb0H\\x02ya\\x00\\x02Sh\\x00I9\\xb9\\xed\\x01\\x15b`"')>
Traceback (most recent call last):
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\updates.py", line 395, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\updates.py", line 545, in _get_difference
    result = await self(functions.updates.GetChannelDifferenceRequest(
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\users.py", line 79, in _call
    result = await future
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\network\mtprotosender.py", line 617, in _handle_rpc_result
    result = state.request.read_result(reader)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\tl\tlobject.py", line 219, in read_result
    return reader.tgread_object()
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\extensions\binaryreader.py", line 142, in tgread_object
    return clazz.from_reader(self)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\tl\types\updates.py", line 66, in from_reader
    _x = reader.tgread_object()
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\extensions\binaryreader.py", line 140, in tgread_object
    raise error
```

**Comment by Lonami** [comment]
Well there is a new layer, perhaps we should upgrade again https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/tl/api.tl. Still think it's stupid Telegram breaks like this.

**Comment by vegeta1k95** [comment]
@Lonami 
Would it take long to update to new Layer?

**Comment by Lonami** [comment]
No.

**Comment by Lonami** [comment]
Does the above commit fix it?

**Comment by megahomyak** [comment]
Error is not appearing anymore, even though I have not updated the library's files (on my local computer)

**Comment by Lonami** [comment]
Yeah this error seems to be sporadic. Most likely some server issues.

**Comment by vegeta1k95** [comment]
@Lonami 
Thank you. Could you upload this one to PyPI?

**Comment by Lonami** [comment]
The above commit is unlikely to have fixed anything.
