### ISSUE TITLE
KeyboardButtonCallback timeout error

### ISSUE THREAD

**Issue by zeusguy** [LonamiWebs/Telethon#3020]
**Checklist**
* [*] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient


api_id = "xxxx"
api_hash = "YYY"
name = "zzzz"
SOCKS5_PROXY_HOST = '127.0.0.1'
SOCKS5_PROXY_PORT = 1080
proxy = (socks.SOCKS5, SOCKS5_PROXY_HOST, SOCKS5_PROXY_PORT)

client = TelegramClient(name, api_id, api_hash, proxy=proxy).start()

async def main():
    results = await client.send_message('zwqzpdss', 'TG')
    async for message in client.iter_messages('zwqzpdss', reply_to=results.id):
        buttons = message.buttons
        res = await buttons[0][1].click()
        print(res)

with client:
    client.loop.run_until_complete(main())
```

**Traceback**
```
Traceback (most recent call last):
  File ".\b.py", line 55, in <module>
    client.loop.run_until_complete(main())
  File "C:\Users\z\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File ".\b.py", line 49, in main
    res = await buttons[0][1].click()
  File "C:\Users\z\AppData\Roaming\Python\Python37\site-packages\telethon\tl\custom\messagebutton.py", line 107, in click
    return await self._client(req)
  File "C:\Users\z\AppData\Roaming\Python\Python37\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\z\AppData\Roaming\Python\Python37\site-packages\telethon\client\users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.BotResponseTimeoutError: The bot did not answer to the callback query in time (caused by GetBotCallbackAnswerRequest)
```

modify messagebutton.py 109 line, change return to raise

**Comment by BelgenOp** [comment]
Maybe you clicked a old button/button with callback, which was not maintained

**Comment by Lonami** [comment]
The error posted is being excepted so you may be using an older version:

https://github.com/LonamiWebs/Telethon/blob/bc6bcd31ad0c46a26e8597689c69de6c1711d14a/telethon/tl/custom/messagebutton.py#L106-L109

Closing due to inactivity (there may be two errors with the same name; if that's the case please update, try again and report back).
