### ISSUE TITLE
I think there is a bug with the "inline_query method"

### ISSUE THREAD

**Issue by glucosjo** [LonamiWebs/Telethon#3055]
**Checklist**
* [ ✅ ] The error is in the library's code, and not in my own.
* [ ✅  ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ✅ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient


async def main():

    results = await client.inline_query('like', 'Do you like Telethon?')

    await client.disconnected

if __name__ == "__main__":

    client = TelegramClient(
        "default_session",
        api_id = 0000000,
        api_hash = "the api hash"
    )

    client.start()

    client.loop.run_until_complete(main())

```

**Traceback**
```
Traceback (most recent call last):
  File "/home/matteo/Scrivania/spambot-ultimate-telegram/spambot_ultimate.py", line 22, in <module>
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/matteo/Scrivania/spambot-ultimate-telegram/spambot_ultimate.py", line 6, in main
    results = await client.inline_query('like', 'Do you like Telethon?')
  File "/home/matteo/.local/lib/python3.9/site-packages/telethon/client/bots.py", line 64, in inline_query
    result = await self(functions.messages.GetInlineBotResultsRequest(
  File "/home/matteo/.local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/matteo/.local/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetInlineBotResultsRequest)

```

**Comment by Lonami** [comment]
Bot accounts cannot perform inline queries to other bots (or itself). This is an API restriction.
