### ISSUE TITLE
socks.GeneralProxyError slips through ReadThread except

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#307]
I use socks5 proxy for client connection. Sometimes proxy shuts down unexpectedly and I get this error from read thread. My main code resides inside try-except block, but this exception seems to slip over it. How can I handle it from the main thread?

> Exception in thread ReadThread:
> Traceback (most recent call last):
>   File "D:\Program Files\Python3\lib\site-packages\telethon\telegram_bare_client.py", line 786, in _recv_thread_impl
>     self._sender.receive(update_state=self.updates)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\mtproto_sender.py", line 100, in receive
>     body = self.connection.recv()
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\connection.py", line 163, in _recv_abridged
>     length = int.from_bytes(self.read(1), 'little')
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\connection.py", line 211, in _read_obfuscated
>     self.conn.read(length)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\extensions\tcp_client.py", line 128, in read
>     self._raise_connection_reset()
>   File "D:\Program Files\Python3\lib\site-packages\telethon\extensions\tcp_client.py", line 139, in _raise_connection_reset
>     raise ConnectionResetError('The server has closed the connection.')
> ConnectionResetError: The server has closed the connection.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 794, in connect
>     super(socksocket, self).connect(proxy_addr)
> ConnectionRefusedError: [WinError 10061]  No connection could be made because the target machine actively refused it
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Program Files\Python3\lib\threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "D:\Program Files\Python3\lib\threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\telegram_bare_client.py", line 792, in _recv_thread_impl
>     while self._user_connected and not self._reconnect():
>   File "D:\Program Files\Python3\lib\site-packages\telethon\telegram_bare_client.py", line 302, in _reconnect
>     return self.connect()
>   File "D:\Program Files\Python3\lib\site-packages\telethon\telegram_bare_client.py", line 186, in connect
>     self._sender.connect()
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\mtproto_sender.py", line 46, in connect
>     self.connection.connect(self.session.server_address, self.session.port)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\connection.py", line 79, in connect
>     self.conn.connect(ip, port)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\extensions\tcp_client.py", line 49, in connect
>     self._socket.connect(address)
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 96, in wrapper
>     return function(*args, **kwargs)
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 806, in connect
>     raise ProxyConnectionError(msg, error)
> socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 192.162.101.133:60986: [WinError 10061] No connection could be made because the target machine actively refused it

`

**Comment by Lonami** [comment]
What version are you using? Also I'll `except ProxyConnectionError` too.

**Comment by Lonami** [comment]
@vegeta1k95 For some reason this page is giving me a 404, I'm not sure if a reply through this bot will work…

**Comment by Lonami** [comment]
Comment here again if it still happens after you're using this version. The error will be raised on the next call to `.invoke()` or when you use `client(...)`, they're equivalent.

**Comment by vegeta1k95** [comment]
Updated version to 0.15.1.4. Another error has appeared:

> Exception in thread ReadThread:
> Traceback (most recent call last):
>   File "D:\Program Files\Python3\lib\site-packages\telethon\telegram_bare_client.py", line 795, in _recv_thread_impl
>     self._sender.receive(update_state=self.updates)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\mtproto_sender.py", line 100, in receive
>     body = self.connection.recv()
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\connection.py", line 163, in _recv_abridged
>     length = int.from_bytes(self.read(1), 'little')
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\connection.py", line 211, in _read_obfuscated
>     self.conn.read(length)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\extensions\tcp_client.py", line 128, in read
>     self._raise_connection_reset()
>   File "D:\Program Files\Python3\lib\site-packages\telethon\extensions\tcp_client.py", line 139, in _raise_connection_reset
>     raise ConnectionResetError('The server has closed the connection.')
> ConnectionResetError: The server has closed the connection.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 813, in connect
>     negotiate(self, dest_addr, dest_port)
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 477, in _negotiate_SOCKS5
>     CONNECT, dest_addr)
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 503, in _SOCKS5_request
>     chosen_auth = self._readall(reader, 2)
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 304, in _readall
>     d = file.read(count - len(data))
>   File "D:\Program Files\Python3\lib\socket.py", line 575, in readinto
>     return self._sock.recv_into(b)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Program Files\Python3\lib\threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "D:\Program Files\Python3\lib\threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\telegram_bare_client.py", line 801, in _recv_thread_impl
>     while self._user_connected and not self._reconnect():
>   File "D:\Program Files\Python3\lib\site-packages\telethon\telegram_bare_client.py", line 304, in _reconnect
>     return self.connect()
>   File "D:\Program Files\Python3\lib\site-packages\telethon\telegram_bare_client.py", line 187, in connect
>     self._sender.connect()
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\mtproto_sender.py", line 46, in connect
>     self.connection.connect(self.session.server_address, self.session.port)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\network\connection.py", line 79, in connect
>     self.conn.connect(ip, port)
>   File "D:\Program Files\Python3\lib\site-packages\telethon\extensions\tcp_client.py", line 49, in connect
>     self._socket.connect(address)
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 96, in wrapper
>     return function(*args, **kwargs)
>   File "D:\Program Files\Python3\lib\site-packages\socks.py", line 817, in connect
>     raise GeneralProxyError("Socket error", error)
> socks.GeneralProxyError: Socket error: timed out

**Comment by Lonami** [comment]
But you should `except socks.GeneralProxyError`. That's not a problem with connecting to Telegram, it's a problem with the socket, and the library can't do anything about it.

**Comment by vegeta1k95** [comment]
Yeah, but I want this exception to be raised not in ReadThread of client, but in MainThread.
My whole code looks like this:
```
try:
   #do stuff with client
except Exception as err:
   print(repr(e))
```
Still this error is being raised and I can't catch it by this construction.

**Comment by Lonami** [comment]
That's what https://github.com/LonamiWebs/Telethon/commit/f984aae391b422dc81ae5ff9e79bbcfd63b77bc4 fixed in theory.

**Comment by vegeta1k95** [comment]
Just updated to 0.15.1.5 and still get the same error. Somehow exception is not translated to MainThread.

**Comment by Lonami** [comment]
Will look more into it then.

**Comment by vegeta1k95** [comment]
Looking into my logs, it seems that most of the time exceptions of type `GeneralProxyError() ` were caught just fine. But sometimes it slip through and raises error in ReadThread. 
Part of my log:

> [Mon Oct  9 21:49:54 2017] Connecting... 
> [Mon Oct  9 21:50:00 2017]---- Trying to connect to proxy 66.172.99.225:33954
> [Mon Oct  9 21:50:05 2017]---- #[ERROR]# : GeneralProxyError()
> [Mon Oct  9 21:50:20 2017]---- Trying to connect to proxy 66.172.99.225:33954
> [Mon Oct  9 21:50:31 2017]---- #[ERROR]# : ProxyConnectionError()
> [Mon Oct  9 21:50:46 2017]---- Trying to connect to proxy 103.30.91.185:39240
> [Mon Oct  9 21:50:56 2017]---- Connected.
In this case both exceptions  `ProxyConnectionError()` and  `GeneralProxyError()` were caugth and handled  fine. But I still sometimes get  
```
raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: timed out
```

**Comment by Lerbytech** [comment]
@vegeta1k95 , I also have issue with socks5 proxy, but they don't work at all for me. I've opened issue #322  to solve it. Could you provide some code of calling TelegramClient class with proxy and maybe other important parts? I would really appreciate this as you are perhaps the only one who managed to make proxies work (sometimes)

**Comment by vegeta1k95** [comment]
With the recent versions of Telethon the problem has gone. Issue can be closed.

**Comment by Lonami** [comment]
Cool.
