### ISSUE TITLE
Problems with installing the module.

### ISSUE THREAD

**Issue by KocTu4eK** [LonamiWebs/Telethon#3077]
**Checklist**
An error occurs when installing the module via «pip install telethon».

**Traceback**
```
  ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-ure0wvdt\\pyaes_856ab4628a5e44c4a8004cd094720e28\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-ure0wvdt\\pyaes_856ab4628a5e44c4a8004cd094720e28\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-a5lgukww'
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-ure0wvdt\pyaes_856ab4628a5e44c4a8004cd094720e28\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 16, in <module>
        import pkg_resources
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz#sha256=02c1b1405c38d3c370b085fb952dd8bea3fadcee6411ad99f312cc129c536d8f (from https://pypi.org/simple/pyaes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Lonami** [comment]
Try https://stackoverflow.com/a/47278208/.

**Comment by Lonami** [comment]
I'll close the issue since the Traceback doesn't mention Telethon anywhere.
