### ISSUE TITLE
ConnectionResetError after some download time

### ISSUE THREAD

**Issue by victor141516** [LonamiWebs/Telethon#309]
I got this exception while downloading. I'm trying to download a large file (1GB) and after ~30MB I get the exception. This is the full log (dbg log + traceback):

```
DEBUG:telethon.network.mtproto_sender:Handling container
DEBUG:telethon.network.mtproto_sender:Handling RPC result
DEBUG:telethon.network.mtproto_sender:Reading request response
DEBUG:telethon.network.mtproto_sender:Handling container
DEBUG:telethon.network.mtproto_sender:Handling RPC result
DEBUG:telethon.network.mtproto_sender:Lost request will be skipped.
DEBUG:telethon.network.mtproto_sender:Handling container
DEBUG:telethon.network.mtproto_sender:Handling container
DEBUG:telethon.network.mtproto_sender:Handling container
DEBUG:telethon.telegram_bare_client:Server disconnected us. Reconnecting and resending request...
DEBUG:telethon.telegram_bare_client:Server disconnected us. Reconnecting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/telegram_client.py", line 692, in download_media
    media, file, date, progress_callback
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/telegram_client.py", line 751, in _download_document
    progress_callback=progress_callback
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 695, in download_file
    input_location, offset, part_size
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 446, in __call__
    result = self._invoke(sender, call_receive, *requests)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 465, in _invoke
    sender.send(*requests)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 79, in send
    self._send_message(message)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 133, in _send_message
    self.connection.send(result)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/network/connection.py", line 185, in _send_tcp_full
    self.write(data + crc)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/network/connection.py", line 222, in _write_plain
    self.conn.write(data)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/extensions/tcp_client.py", line 85, in write
    raise ConnectionResetError()
ConnectionResetError

DEBUG:telethon.network.mtproto_sender:Handling RPC result
DEBUG:telethon.network.mtproto_sender:Reading request response
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
```

**Comment by Lonami** [comment]
Not sure if this will work but we can try. I actually wasn't sure why I was raising it but not excepting it.

**Comment by victor141516** [comment]
I still have the same error :S

I'm using threads to make the download async and then I read from the stream to make a generator:

```
stream = BytesIO()
thread = threading.Thread(target=client.download_media, args=(message,), kwargs={'file': stream})
thread.daemon = True
thread.start()
pos = 0
while (thread.is_alive()):
    stream.seek(pos)
    r = stream.read()
    pos += len(r)
    yield r
```

**Comment by sebastianarena** [comment]
I'm commenting here, since it may be related to the problem I'm seeing.
I just started creating a script to download old media from groups.
After a minute or so of downloading... I started seeing corrupted files and videos.

Adding a "except" clause in the TelegramBareClient in download_file I got this error: `buffer size must be strictly positive`

And when failing that and getting to the next media, all files would start to fail with: `Number of retries reached 0.`

After that... every download would fail.

Ideas?

**Comment by Lonami** [comment]
> `buffer size must be strictly positive`

Likely #313. If you coule help trigger the issue so I can spot what to fix, that would be nice.

**Comment by sebastianarena** [comment]
Just tried that branch... it seems there's a file I'm trying to download that gets broken every time I download it.

The new branch outputs a lot of info to the console, but I don't know what to send to you.

File still breaks on new branch

**Comment by Lonami** [comment]
You can [message me privately](https://t.me/Lonami) with either the whole console output, or just the few 10 or so last lines so I can reproduce the issue.

**Comment by victor141516** [comment]
I can download files correctly now!

**Comment by Lonami** [comment]
I wonder what commit fixed it, or if it's just chance.

**Comment by Lonami** [comment]
Closing due to inactivity.
