### ISSUE TITLE
TypeError: Cannot cast InputPeerUser to any kind of InputChannel with LeaveChannelRequest

### ISSUE THREAD

**Issue by Rickaym** [LonamiWebs/Telethon#3113]
I've done the check list.
Not entirely sure if it's a bug but I believe i did everyhing as intended but there seems to be a problem with leaving a specific channel with the input entity specified
**Code that causes the issue**
```python
        channel = self.dialogs[query] # Dialog.dialog object
        if channel is None:
            print("[FATAL] The channel picked couldn't be found for some reason..")
            return
       # self.run simply runs a coroutine in the loop until complete (for sync reasons)
       # take it as an `await`
       # self.me is the `client`
        self.run(
            self.me(
                LeaveChannelRequest(
                    self.run(self.me.get_input_entity(channel.name))
                )
            )
        )

```

**Traceback**
```
Traceback (most recent call last):
  File "xxxx\Python\bot\entry.py", line 281, in <module>
    option_map[option]()
  File "xxxx\Python\bot\entry.py", line 199, in leave_group
    self.run(
  File "xxxx\Python\bot\entry.py", line 64, in run
    return self.me.loop.run_until_complete(coroutine)
  File "xxxx\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "xxxx\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "xxxx\lib\site-packages\telethon\client\users.py", line 37, in _call
    await r.resolve(self, utils)
  File "xxxx\lib\site-packages\telethon\tl\functions\channels.py", line 1023, in resolve
    self.channel = utils.get_input_channel(await client.get_input_entity(self.channel))
  File "xxxx\lib\site-packages\telethon\utils.py", line 263, in get_input_channel
    _raise_cast_fail(entity, 'InputChannel')
  File "xxxx\lib\site-packages\telethon\utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast InputPeerUser to any kind of InputChannel
```

**Comment by Lonami** [comment]
Your channel is probably actually a user.
