### ISSUE TITLE
Strange behaviour for get_message_history

### ISSUE THREAD

**Issue by victor141516** [LonamiWebs/Telethon#314]
I posted #309 yesterday. At that moment I had my code working:

- Initialize Telethon
- Get entity from chat_id
- Get message history

Today upgraded to the new version and my code stopped working.

I found some strange behaviour on some funcions. I don't know if I'm doing something wrong.

This is the code, commented (uppercase vars are envs):

```python
from telethon import TelegramClient
from telethon.errors import SessionPasswordNeededError
from telethon.tl.types import (InputPeerChannel, PeerChat)
from config import *

client = TelegramClient('tg_client', CLIENT_API_ID, CLIENT_API_HASH)
client.connect()
message_id = 51


# Authorize if not done
if (not client.is_user_authorized()):
    client.sign_in(CLIENT_PHONE)
    try:
        client.sign_in(code=input('Enter code: '))
    except SessionPasswordNeededError:
        client.sign_in(password=CLIENT_2FA_PASSWORD)

# This fails, but if I don't do it, the line after the try-except will fail
try:
    client.get_entity(PeerChat(1))
except ValueError:
    pass

# This works. It will fail if client.get_entity(PeerChat(1)) is not done before
peer = InputPeerChannel(CHANNEL_REPLY_TELETHON_ID, CHANNEL_REPLY_TELETHON_HASH)

# This works, get a chat and contains the correct information
chat = client.get_entity(peer)

# This fails
message = client.get_message_history(chat, max_id=message_id+1, min_id=message_id-1, limit=2147483647)[1][0]
```

This is the traceback for that last line:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/telegram_client.py", line 433, in get_message_history
    add_offset=add_offset
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 448, in __call__
    result = self._invoke(sender, call_receive, *requests)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 467, in _invoke
    sender.send(*requests)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 83, in send
    self._send_message(message)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 125, in _send_message
    + message.to_bytes()
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/tl/tl_message.py", line 16, in to_bytes
    body = GzipPacked.gzip_if_smaller(self.request)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/tl/gzip_packed.py", line 22, in gzip_if_smaller
    data = request.to_bytes()
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/tl/message_container.py", line 17, in to_bytes
    ) + b''.join(m.to_bytes() for m in self.messages)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/tl/message_container.py", line 17, in <genexpr>
    ) + b''.join(m.to_bytes() for m in self.messages)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/tl/tl_message.py", line 16, in to_bytes
    body = GzipPacked.gzip_if_smaller(self.request)
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/tl/gzip_packed.py", line 22, in gzip_if_smaller
    data = request.to_bytes()
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/tl/functions/messages.py", line 1737, in to_bytes
    self.peer.to_bytes(),
  File "/Users/victor141516/.virtualenvs/GetTempBot/lib/python3.6/site-packages/telethon/tl/types/__init__.py", line 9054, in to_bytes
    struct.pack('<i', self.channel_id),
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

So I go to `telethon/tl/types/__init__.py` line 9054 and print `self.channel_id` and I found that while my `CHANNEL_REPLY_TELETHON_ID` is `XXXXXXXXXX`, the `channel_id` in that line is `100XXXXXXXXXX`.

Sooo I hardcoded my channel_id there and it works. But I know this is not the way to do.

Am I missing something? Or is this really a strange behaviour?

EDIT: In `telethon/utils.py(340)` is where you add the `-100` on the beginning. I don't know what is this for, but it interferes with the `struct.pack`

**Comment by Lonami** [comment]
> EDIT: In `telethon/utils.py(340)` is where you add the `-100` on the beginning. I don't know what is this for, but it interferes with the `struct.pack`

I was just going to pinpoint that. That ID should be used for internal purposes, not anywhere else.

**Comment by Lonami** [comment]
Also a `limit=2147483647` for `.get_history` just won't work. Telegram will limit it to 100 messages (issue 290).

**Comment by Lonami** [comment]
The thing is, I had made a function for this purpose which I then forgot to use. Thanks, `v0.15.1.5` on PyPi.

**Comment by victor141516** [comment]
So ATM we cannot retrieve any message older than the latest 100?
