### ISSUE TITLE
User account blocked on running the script for a few days

### ISSUE THREAD

**Issue by pinahar** [LonamiWebs/Telethon#3159]
I had a script running for a few days which reads new messages being sent to a group, gets sender name and forwards some which fit a certain criteria. However, my user account got blocked because of it.
Is there a way for me avoid such instances in the future? Can I reduce the frequency of GetMessagesRequest requests somehow?

Traceback (most recent call last):
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
    await callback(event)
  File "test_telethon.py", line 96, in handler
    sender = await event.get_sender()
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/tl/custom/sendergetter.py", line 48, in get_sender
    and await self.get_input_sender():
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/tl/custom/sendergetter.py", line 81, in get_input_sender
    await self._refetch_sender()
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/tl/custom/message.py", line 1094, in _refetch_sender
    await self._reload_message()
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/tl/custom/message.py", line 1078, in _reload_message
    msg = await self._client.get_messages(chat, ids=self.id)
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/client/messages.py", line 568, in get_messages
    async for message in it:
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/client/messages.py", line 289, in _load_next_chunk
    r = await self.client(functions.messages.GetMessagesRequest(ids))
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/visa_user/.local/lib/python3.8/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.UserDeactivatedBanError: The user has been deleted/deactivated (caused by GetMessagesRequest)
2021-09-11 14:55:57     ERROR    Unhandled exception on handler

**Comment by Lonami** [comment]
The Telegram server is the one applying the limits, with their own rules, and it is not possible to know all the things they take into consideration in order to restrict an account. Telethon cannot do anything to "fix" this, either.
