### ISSUE TITLE
PhoneCodeExpiredError when trying to re-request code after first one expired

### ISSUE THREAD

**Issue by tulir** [LonamiWebs/Telethon#3185]
If you request a code, forget about it for some time, then try to request a new code with the same `TelegramClient`, it fails with `PhoneCodeExpiredError`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/web/common/auth_api.py", line 81, in post_login_phone
    await user.client.sign_in(phone.strip())
  File "/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 342, in sign_in
    return await self.send_code_request(phone)
  File "/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 532, in send_code_request
    result = await self(
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.PhoneCodeExpiredError: The confirmation code has expired (caused by ResendCodeRequest)
```

(note the "caused by ResendCodeRequest"). This should probably be caught and handled internally because the `_phone_code_hash` cache is also internal.

**Comment by tulir** [comment]
That except seems like it's in the wrong place :thinking: (it catches errors when the request object is created, but not when it's actually sent)
