### ISSUE TITLE
-404 errors should be retried during auth key generation.

### ISSUE THREAD

**Issue by penn5** [LonamiWebs/Telethon#3187]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
Sign in a lot

**Traceback**
```
Traceback (most recent call last):
  File "/home/penn/Telethon/telethon/client/users.py", line 81, in _call
    result = await future
telethon.errors.rpcerrorlist.UserMigrateError: The user whose identity is being used to execute queries is associated with DC 1 (caused by ImportBotAuthorizationRequest)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/penn/biobot2/biobot/__main__.py", line 35, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/penn/biobot2/biobot/__main__.py", line 30, in main
    async with backend_manager.Backends(config, client) as backend:
  File "/home/penn/biobot2/biobot/backend_manager.py", line 54, in __aenter__
    await self.init()
  File "/home/penn/biobot2/biobot/backend_manager.py", line 49, in init
    await backend.init()
  File "/home/penn/biobot2/biobot/backends/bot.py", line 36, in init
    await self.client.start(bot_token=self.token)
  File "/home/penn/Telethon/telethon/client/auth.py", line 182, in _start
    await self.sign_in(bot_token=bot_token)
  File "/home/penn/Telethon/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/home/penn/Telethon/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/penn/Telethon/telethon/client/users.py", line 123, in _call
    await self._switch_dc(e.new_dc)
  File "/home/penn/Telethon/telethon/client/telegrambaseclient.py", line 670, in _switch_dc
    return await self.connect()
  File "/home/penn/Telethon/telethon/client/telegrambaseclient.py", line 513, in connect
    if not await self._sender.connect(self._connection(
  File "/home/penn/Telethon/telethon/network/mtprotosender.py", line 127, in connect
    await self._connect()
  File "/home/penn/Telethon/telethon/network/mtprotosender.py", line 233, in _connect
    if not await self._try_gen_auth_key(attempt):
  File "/home/penn/Telethon/telethon/network/mtprotosender.py", line 291, in _try_gen_auth_key
    await authenticator.do_authentication(plain)
  File "/home/penn/Telethon/telethon/network/authenticator.py", line 75, in do_authentication
    server_dh_params = await sender.send(ReqDHParamsRequest(
  File "/home/penn/Telethon/telethon/network/mtprotoplainsender.py", line 38, in send
    raise InvalidBufferError(body)
telethon.errors.common.InvalidBufferError: Invalid response buffer (HTTP code 404)
```

**Comment by tomatofrankie** [comment]
I encountered the same error after I've logined my account.

**Comment by Lonami** [comment]
Still not planned, but happy to merge PRs.
