### ISSUE TITLE
Switching from IPv4 to IPv6 breaks existing authorization data

### ISSUE THREAD

**Issue by lilydjwg** [LonamiWebs/Telethon#3196]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

When I enabled IPv6 for the client, reusing an existing session that has been connecting via IPv4, I got this error:

```
[I 10-29 20:50:30.003 mtprotosender:221] Connecting to 2001:67c:4e8:f002::a:443/TcpFull...
[I 10-29 20:50:30.012 mtprotosender:272] Connection to 2001:67c:4e8:f002::a:443/TcpFull complete!
[I 10-29 20:50:30.025 mtprotosender:524] Broken authorization key; resetting
[I 10-29 20:50:30.028 mtprotosender:312] Disconnecting from 2001:67c:4e8:f002::a:443/TcpFull...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lilydjwg/workspace/luoxu/luoxu/__main__.py", line 174, in <module>
    run_until_sigint(indexer.run())
  File "/home/lilydjwg/workspace/luoxu/luoxu/util.py", line 24, in run_until_sigint
    loop.run_until_complete(fu)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/lilydjwg/workspace/luoxu/luoxu/__main__.py", line 97, in run
    await client.start(tg_config['account'])
  File "/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/usr/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 529, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(
  File "/usr/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 510, in _recv_loop
    message = self._state.decrypt_message_data(body)
  File "/usr/lib/python3.9/site-packages/telethon/network/mtprotostate.py", line 138, in decrypt_message_data
    raise InvalidBufferError(body)
telethon.errors.common.InvalidBufferError: Invalid response buffer (HTTP code 404)
```

Then I reran the program, and it asked to authorize:

```
[I 10-29 20:50:40.012 mtprotosender:221] Connecting to 2001:67c:4e8:f002::a:443/TcpFull...
[I 10-29 20:50:40.823 mtprotosender:272] Connection to 2001:67c:4e8:f002::a:443/TcpFull complete!
[I 10-29 20:50:41.137 users:115] Phone migrated to 1
[I 10-29 20:50:41.268 telegrambaseclient:660] Reconnecting to new data center 1
[I 10-29 20:50:41.425 mtprotosender:312] Disconnecting from 2001:67c:4e8:f002::a:443/TcpFull...
[I 10-29 20:50:41.425 mtprotosender:332] Disconnection from 2001:67c:4e8:f002::a:443/TcpFull complete!
[I 10-29 20:50:41.426 mtprotosender:221] Connecting to 2001:0b28:f23d:f001:0000:0000:0000:000a:443/TcpFull...
[I 10-29 20:50:42.638 mtprotosender:272] Connection to 2001:0b28:f23d:f001:0000:0000:0000:000a:443/TcpFull complete!
Please enter the code you received: 
```

It seems that the authorization data doesn't work with different protocols? There is also #1661 which sounds similar but I don't use a proxy.

Update: the reverse is also true: switching from IPv6 to IPv4 broke the session again.

**Comment by Lonami** [comment]
This is not very high priority because it is unlikely someone will keep switching back-and-forth between IPv4 and IPv6.

**Comment by w1ld32** [comment]
> This is not very high priority because it is unlikely someone will keep switching back-and-forth between IPv4 and IPv6.

For me, this problem is relevant. I register accounts on ipv4, and for further work they use IPV6, and in this case, these accounts do not work (

**Comment by Lonami** [comment]
You're welcome to review if this is still an issue in the current master version and try to correct it.

**Comment by w1ld32** [comment]
> You're welcome to review if this is still an issue in the current master version and try to correct it.

I tried it in the current version master (pip3 install -U https://github.com/LonamiWebs/Telethon/archive/master.zip ) the error has been preserved. I do not know how to solve this problem.

**Comment by w1ld32** [comment]
Sorry, maybe I'm digging absolutely in the wrong place, and I'm wrong in my judgments and searches. I also don't know how transmission protocols work in general, but the only thing I have unearthed is that the response body from the server when switching to IPV6 is very short. Perhaps there are ideas why this is so? There is no such problem in the pyrogram, it works on layer 138, attempts to change the layer in telethon did not give results.

**Comment by w1ld32** [comment]
@Lonami How save and use SessionsString on V2?

**Comment by Lonami** [comment]
@w1ld32 that's offtopic here.

**Comment by JuniorJPDJ** [comment]
still happens, but for me doesnt show any error message, just stops on connecting

**Comment by w1ld32** [comment]
> still happens, but for me doesnt show any error message, just stops on connecting

This problem lies in the addresses of the TG servers. IPV4 and IPV6 are different servers, and when switching between them, the server address does not change automatically. I solved this issue by manually changing the DC server in the session file.

**Comment by JuniorJPDJ** [comment]
It does change, but server migration is not being handled like on first startup.

**Comment by JuniorJPDJ** [comment]
@divadsn

**Comment by divadsn** [comment]
From what I have so far figured out is this one of the root causes:
https://github.com/LonamiWebs/Telethon/blob/a5c98aec50891e973b1ae4f38b8c080444aae664/telethon/client/telegrambaseclient.py#L310

When switching from IPv4 to IPv6 or vice versa the data center ID gets reset in the session file to the DEFAULT_DC_ID along with the new IP address, but for some reason Telethon does not handle the migration again like on first time.

Continuing my research from few weeks ago, it looks like it's skipping the migration due to the fact that we are already authorized, which I believe can be the reason why it's not re-migrating after a switch here:
https://github.com/LonamiWebs/Telethon/blob/a5c98aec50891e973b1ae4f38b8c080444aae664/telethon/client/users.py#L127

I would look at the issue the next days during my vacation and open a PR if I find a fix.

**Comment by JuniorJPDJ** [comment]
@divadsn bump :D

**Comment by Lonami** [comment]
Hi, I'm growing tired of GitHub, so I intend to move to https://codeberg.org/Lonami/Telethon. If the issue still matters to you, please reopen it there. Thanks.
