### ISSUE TITLE
Can't Run My Telethon Program Need Help Asap

### ISSUE THREAD

**Issue by AdityaKirad** [LonamiWebs/Telethon#3198]
Getting Error While Running My Telethon Python Script
```
Traceback (most recent call last):
  File "telethon.py", line 1, in <module>
    from telethon import TelegramClient
  File "/home/lenovo/Documents/Telethon/telethon.py", line 1, in <module>
    from telethon import TelegramClient
ImportError: cannot import name 'TelegramClient' from partially initialized module 'telethon' (most likely due to a circular import) (/home/lenovo/Documents/Telethon/telethon.py)
```
I Installed telethon using below code
```
sudo pip3 install telethon
```
and i runned the program using below code
```
python3 telethon.py
```

**Comment by joaopedrolourencoaffonso** [comment]
share the code
