### ISSUE TITLE
Client experienced this error with telethon, any advice / fixes? Cheers.

### ISSUE THREAD

**Issue by BlockchainTokenSniper** [LonamiWebs/Telethon#3212]
Error executing high-level request after reconnect: <class 'telethon.errors.common.InvalidBufferError'>: Invalid response buffer (HTTP code 404)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\program files\python39\lib\asyncio\tasks.py", line 468, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "c:\program files\python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "telegram_listener.py", line 142, in startTGListener
  File "C:\Users\kodiz\AppData\Roaming\Python\Python39\site-packages\telethon\client\updates.py", line 71, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "c:\program files\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\kodiz\AppData\Roaming\Python\Python39\site-packages\telethon\client\updates.py", line 27, in _run_until_disconnected
    return await self.disconnected
  File "C:\Users\kodiz\AppData\Roaming\Python\Python39\site-packages\telethon\client\updates.py", line 579, in _handle_auto_reconnect
    await self.get_me()
  File "C:\Users\kodiz\AppData\Roaming\Python\Python39\site-packages\telethon\client\users.py", line 156, in get_me
    me = (await self(
  File "C:\Users\kodiz\AppData\Roaming\Python\Python39\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\kodiz\AppData\Roaming\Python\Python39\site-packages\telethon\client\users.py", line 79, in _call
    result = await future
  File "C:\Users\kodiz\AppData\Roaming\Python\Python39\site-packages\telethon\network\mtprotosender.py", line 510, in _recv_loop
    message = self._state.decrypt_message_data(body)
  File "C:\Users\kodiz\AppData\Roaming\Python\Python39\site-packages\telethon\network\mtprotostate.py", line 138, in decrypt_message_data
    raise InvalidBufferError(body)
telethon.errors.common.InvalidBufferError: Invalid response buffer (HTTP code 404)

**Comment by Lonami** [comment]
The authorization key is no longer valid and relogin is needed.
