### ISSUE TITLE
Catching Errors - Event Handler

### ISSUE THREAD

**Issue by StamatisTiniakos** [LonamiWebs/Telethon#3221]
On your documentation you provide a basic example that looks like the below:

```python

from telethon import TelegramClient, events

client = TelegramClient('anon', api_id, api_hash)

@client.on(events.NewMessage(chats=('https://t.me/xxxxxx','https://t.me/xxxx'))
async def my_event_handler(event):
    if 'hello' in event.raw_text:
        await event.reply('hi!')

with client:
       client.run_until_disconnected()

```

I find it hard to understand how to catch errors on this example. e.g. when a channel closes it prints an error on the console but it keeps running and I can not catch the error with try , except. 

e.g. I tried the below but it doesn't catch the error

```python

try:
     with client:
           client.run_until_disconnected()
except Exeption ex:
   print(ex.message)
```

Any advise of what I am doing wrong? I think it will be useful to update the documentation with that.

**Comment by joaopedrolourencoaffonso** [comment]
I do like this:
```
from telethon import TelegramClient, events, utils
import asyncio
import logging

async def a_task_function():
    '''
    an task
    '''
    while True:
        try:
            something
       except Excption as e:
            print(e);

async def main():
    a_task = asyncio.create_task(a_task_function());

    await a_task;
    
        
with client:
    try:
        client.loop.run_until_complete(main());

    except:
        print("Ending...");
        future = asyncio.Future();
        future.set_result("1");
        con.close();
        print("Bye!");
```

**Comment by StamatisTiniakos** [comment]
@joaopedrolourencoaffonso  I tried your approach but now I get an error a_task_function() missing 1 required positional argument: 'event'

```python

from telethon import TelegramClient, events, utils
import asyncio
import logging

api_id = 'xxxx'
api_hash = 'xxxxxxxxxxxxxxxxxxx'
client = TelegramClient('anon', api_id, api_hash)


@client.on(events.NewMessage(chats=('https://t.me/xxxxx', 'https://t.me/xxxxxxxx', 'https://t.me/xxxxx')))
async def a_task_function(event):
    '''
    an task
    '''
    while True:
        try:
            if "hello" in event.raw_text:
                print("hei")
        except:
            print("error")


async def main():
    a_task = asyncio.create_task(a_task_function())

    await a_task


with client:
    try:
        client.loop.run_until_complete(main())

    except Exception as ex:
        print(ex)
        print("Ending...")
        future = asyncio.Future()
        future.set_result("1")
        print("Bye!")
```

**Comment by joaopedrolourencoaffonso** [comment]
1- I am newbie on Telethon to (2 months in, approximately)

2 - Maybe I am wrong, but when I try to this kind of thing my code not even run. I need another function to keep the whole thing alive, or else the script finishs.

3 - Out of curiosity, try this:

```python

from telethon import TelegramClient, events, utils
import asyncio
import logging

api_id = 'xxxx'
api_hash = 'xxxxxxxxxxxxxxxxxxx'
client = TelegramClient('anon', api_id, api_hash)


@client.on(events.NewMessage)
async def receber(event):
    try:
        print(event);

   except:
       print("Error");

async def a_task_function():
    '''
    an task
    '''
    while True:
        try:
            print("hei")
        except:
            print("error")


async def main():
    a_task = asyncio.create_task(a_task_function())

    await a_task


with client:
    try:
        client.loop.run_until_complete(main())

    except Exception as ex:
        print(ex)
        print("Ending...")
        future = asyncio.Future()
        future.set_result("1")
        print("Bye!")
```

It runs nicely for me.

4 - Try to use the chats ids rather than the links.

**Comment by StamatisTiniakos** [comment]
@joaopedrolourencoaffonso  your answer above is creating an infinite loop that prints "hei".  

To clarify my question: 

The problem that I face is is that I can not catch exceptions despite using try except.

For example when I use an invalid chat link the script will not terminate and any exception raised can not be captured.

The error that is printed on the console is the following:

```
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<UpdateMethods._dispatch_update() done, defined at C:\Python\lib\site-packages\telethon\client\updates.py:386> exception=ValueError('No user has "random_stamatis" as username')>
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\telethon\client\users.py", line 548, in _get_entity_from_string
    result = await self(
  File "C:\Python\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Python\lib\site-packages\telethon\client\users.py", line 79, in _call
telethon.errors.rpcerrorlist.UsernameNotOccupiedError: The username is not in use by anyone else yet (caused by ResolveUsernameRequest)
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\telethon\client\updates.py", line 445, in _dispatch_update
    await builder.resolve(self)
  File "C:\Python\lib\site-packages\telethon\events\common.py", line 99, in resolve
    await self._resolve(client)
  File "C:\Python\lib\site-packages\telethon\events\newmessage.py", line 93, in _resolve
    await super()._resolve(client)
  File "C:\Python\lib\site-packages\telethon\events\common.py", line 103, in _resolve
    self.chats = await _into_id_set(client, self.chats)
  File "C:\Python\lib\site-packages\telethon\events\common.py", line 33, in _into_id_set
    chat = await client.get_input_entity(chat)
  File "C:\Python\lib\site-packages\telethon\client\users.py", line 432, in get_input_entity
    await self._get_entity_from_string(peer))
  File "C:\Python\lib\site-packages\telethon\client\users.py", line 551, in _get_entity_from_string
    raise ValueError('No user has "{}" as username'
ValueError: No user has "invalid_name" as username
```

**Comment by joaopedrolourencoaffonso** [comment]
1 - I edited [my](https://github.com/LonamiWebs/Telethon/issues/3221#issuecomment-984539668) answer so there is a easier to see time. I also added an "break".

2 - For me, it works fine with "KeyboardInterrupt"

3 - According to the output, the problem is that there is an user being called as: "{}"
```
raise ValueError('No user has "{}" as username'
```
It seems that you are trying to send a message (or something similar) but is not providing the correct id name. This is raising an error *inside* the coroutine, you should try to treat the error there.

4 - Sorry, but beyond this, I can't help much.

**Comment by Lonami** [comment]
You can except errors within the handler by putting a `try/except` *inside* the handler. Uncaught errors are caught by the library and logged to avoid crashing. A `try/except` around `with client/run_until_disconnected` will catch *connection* errors (if the library loses connection or Telegram closes it).

**Comment by StamatisTiniakos** [comment]
@Lonami  I found that following solution which could capture errors https://stackoverflow.com/questions/70177146/how-to-capture-errors-on-telethon-event-coroutines. Do you think there is a better way to do it? I tried to put a try except inside the handler method on my code above but it doesn't work.
