### ISSUE TITLE
error on proccess_updates

### ISSUE THREAD

**Issue by pedram1992** [LonamiWebs/Telethon#337]
hi, i worked with my codes but this don't work some day and show this error

`Traceback (most recent call last):
  File ".\autoUpdate.py", line 223, in <module>
    needsmore = NeedsMore()
  File ".\autoUpdate.py", line 44, in __init__
    process_updates=True)
  File "c:\users\pedram\projects\python\telethon\telethon\telegram_client.py", line 115, in __init__
    **kwargs
  File "c:\users\pedram\projects\python\telethon\telethon\telegram_bare_client.py", line 123, in __init__
    raise ValueError('Unknown named parameter', name)
ValueError: ('Unknown named parameter', 'process_updates')`

**Comment by Lonami** [comment]
That's because you really should read the changelog.

**Comment by pedram1992** [comment]
i read changelog but i cant solve this problem and i have get those error

**Comment by Lonami** [comment]
[You didn't read enough](https://github.com/LonamiWebs/Telethon/releases/tag/v0.15).
