### ISSUE TITLE
FileMigrateError

### ISSUE THREAD

**Issue by IlyaKronos** [LonamiWebs/Telethon#355]
When I'm trying to download some user photo I got FileMigrateError. What to do if I need to download photo?

**Comment by Lonami** [comment]
These should be handled by the library. What are you doing exactly and what version are you using?

**Comment by IlyaKronos** [comment]
Code:
try:
    ...
    client.download_profile_photo(user, open(dir + "/photos/kenny.jpg", "wb"), True)
catch:
    There I'm got FileMigrateError(...), 'The file to be accessed is currently stored in DC 1.'

**Comment by Lonami** [comment]
I still don't know what photo it is, or what version you're using.

**Comment by IlyaKronos** [comment]
Version: Telethon-0.15.1.3
Photo is photo of user profile. Some photos downloading, but some photos not (got FileMigrateError)

**Comment by Lonami** [comment]
@IlyaKronos Kinda strange because of this:
https://github.com/LonamiWebs/Telethon/blob/f49208f96179fb775e9d32c23bb2ba66bc6a5935/telethon/telegram_bare_client.py#L710

**Comment by IlyaKronos** [comment]
```
try:
        if user.photo != None:
            saved = client.download_profile_photo(user, open(dir + "/photos/avatar.jpg", "wb"), True)

            if not saved
                os.remove("photos/avatar.jpg")
    except (SystemExit, KeyboardInterrupt):
        raise
    except:
        raise #There I'm getting this error
        os.remove("photos/avatar.jpg")
```

**Comment by Lonami** [comment]
Not sure why that except isn't being called. Instead `except` the error can you show the traceback?

**Comment by IlyaKronos** [comment]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 702, in download_file
    input_location, offset, part_size
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 447, in __call__
    result = self._invoke(sender, call_receive, *requests)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 505, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_errors_303.FileMigrateError: (FileMigrateError(...), 'The file to be accessed is currently stored in DC 1.')
```

**Comment by Lonami** [comment]
That's damn strange, the call is inside the try/except block:
https://github.com/LonamiWebs/Telethon/blob/f49208f96179fb775e9d32c23bb2ba66bc6a5935/telethon/telegram_bare_client.py#L696-L712

**Comment by IlyaKronos** [comment]
I'm added print to exception and I see printed data and then catch exception 
```
            except FileMigrateError as e:
                    print("HELLO FROM FME IN BARE")
                    client = self._get_exported_client(e.new_dc)
                    continue
```

**Comment by Lonami** [comment]
So we know it's called… but it somehow bypasses the handler afterwards. I'll probably test tomorrow, or if you'd like to figure out/patch it I encourage you to try.

**Comment by IlyaKronos** [comment]
Yep, as I think, FileMigrateError exception is in self._get_exported_client

**Comment by Lonami** [comment]
Maybe the server resends the error on the new client when it tries to connect?

**Comment by IlyaKronos** [comment]
Line 
```
client.connect(_exported_auth=export_auth, _sync_updates=False)
client._authorized = True  # We exported the auth, so we got auth
```
catch exception

**Comment by IlyaKronos** [comment]
How it can be fixed?

**Comment by IlyaKronos** [comment]
It doesn't throw exception if I don't use proxy but downloaded file have size 0kb

**Comment by Lonami** [comment]
I don't use a proxy and it doesn't throw the exception for me (I've tried adding a `print` on the `FileMigrateError`, and it does print, so I know it's called). Also, hte photo is downloaded correctly. I can't reproduce this issue.

**Comment by Lonami** [comment]
Can you test again? The line:
https://github.com/LonamiWebs/Telethon/blob/b3ca68b7d9cc7a100a9ba4550c0de442146865f4/telethon/telegram_bare_client.py#L390

Was changed for this:
https://github.com/LonamiWebs/Telethon/blob/ceb37cd4c55d67f5b1669860f18a447a668588df/telethon/telegram_bare_client.py#L350

Probably not a big difference but I'm revisitting issues and I want to know if they still happen or something fixed them.

**Comment by Lonami** [comment]
Closing due to inactivity.

**Comment by own2pwn** [comment]
Still reproducable using the latest version

```
Traceback (most recent call last):
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/telethon/client/downloads.py", line 70, in _request
    result = await self._sender.send(self.request)
telethon.errors.rpcerrorlist.FileMigrateError: The file to be accessed is currently stored in DC 4 (caused by GetFileRequest)
```

**Comment by Lonami** [comment]
@own2pwn I can download files from other datacenters just fine. Are you sure that's the full traceback?

**Comment by jaharnum** [comment]
I've come across this error today with the current version of Telethon as well. After my program failed to download media from a post, it threw this error and then a ConnectionError - and then repeated both of the errors until I restarted the program. However, as far as I can tell there were no network connection issues for other programs I'm running on the same server.

```
ERROR:telethon.client.updates:Unhandled exception on tg_message_handler

Traceback (most recent call last):
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/client/downloads.py", line 70, in _request
    result = await self._sender.send(self.request)
telethon.errors.rpcerrorlist.FileMigrateError: The file to be accessed is currently stored in DC 2 (caused by GetFileRequest)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/client/updates.py", line 428, in _dispatch_update
    await callback(event)
  File "/home/ec2-user/tgex/tgclient/handle_message.py", line 71, in tg_message_handler
    channel_id)
  File "/home/ec2-user/tgex/tgclient/handle_message.py", line 132, in download_media
    saved_media = await msg.download_media(file=file_location)
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/tl/custom/message.py", line 756, in download_media
    return await self._client.download_media(self, *args, **kwargs)
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/client/downloads.py", line 348, in download_media
    media, file, date, thumb, progress_callback
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/client/downloads.py", line 666, in _download_photo
    progress_callback=progress_callback
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/client/downloads.py", line 435, in download_file
    input_location, request_size=part_size, dc_id=dc_id):
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/requestiter.py", line 75, in __anext__
    if await self._load_next_chunk():
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/client/downloads.py", line 60, in _load_next_chunk
    cur = await self._request()
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/client/downloads.py", line 80, in _request
    return await self._request()
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/client/downloads.py", line 70, in _request
    result = await self._sender.send(self.request)
  File "/home/ec2-user/venv/python3/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 169, in send
    raise ConnectionError('Cannot send requests while disconnected')
ConnectionError: Cannot send requests while disconnected
```

**Comment by Lonami** [comment]
What should the library do if it fails to connect to a different data center when trying to download media, other than raise the error?

**Comment by jaharnum** [comment]
> What should the library do if it fails to connect to a different data center when trying to download media, other than raise the error?

I'm not really concerned about the error raising once, it's moreso that it continues to retry even while its apparently disconnected, leading to the errors repeating forever.
