### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'key_id', 'client.connect()' return False

### ISSUE THREAD

**Issue by whitepap3r** [LonamiWebs/Telethon#360]
```
from telethon import TelegramClient

api_id = 12345 
api_hash = '0123456789abcdef0123456789abcdef' 
phone = '+123456789' 

client = TelegramClient('session_name', api_id, api_hash)
client.connect()
```
change api_id , api_hash ,phone and  run the code ,output is like this:
```
Traceback (most recent call last):
  File "C:\Users\hjkhkk\Documents\telechient.py", line 13, in <module>
    client.sign_in(phone=phone)
  File "C:\Python\Python36-32\lib\site-packages\telethon\telegram_client.py", line 161, in sign_in
    return self.send_code_request(phone)
  File "C:\Python\Python36-32\lib\site-packages\telethon\telegram_client.py", line 131, in send_code_request
    result = self(SendCodeRequest(phone, self.api_id, self.api_hash))
  File "C:\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 448, in __call__
    result = self._invoke(sender, call_receive, *requests)
  File "C:\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 467, in _invoke
    sender.send(*requests)
  File "C:\Python\Python36-32\lib\site-packages\telethon\network\mtproto_sender.py", line 86, in send
    self._send_message(message)
  File "C:\Python\Python36-32\lib\site-packages\telethon\network\mtproto_sender.py", line 131, in _send_message
    key_id = struct.pack('<Q', self.session.auth_key.key_id)
AttributeError: 'NoneType' object has no attribute 'key_id'
```
And i run `try_telethon.py` , came the same output
'client.connect()' return False

Then I change the server_address (telethon\tl\seesion.py)  to Available MTProto servers  from https://my.telegram.org , nothing changes.

please help me
Thanks

**Comment by Lonami** [comment]
Try deleting the session file?

**Comment by Lonami** [comment]
No, actually, make sure .connect() returns True, otherwise retry a few times until it does (or abort and report me back).

**Comment by whitepap3r** [comment]
ok.. retry
