### ISSUE TITLE
telethon + rest api with flask error send message

### ISSUE THREAD

**Issue by thaziz** [LonamiWebs/Telethon#3677]
i want to use telethon with flask rest api ,but when i send by get method i get error and message not sent please help me

@app.route('/tele')
def tele():
	try:
		client.send_message('+62895xxxxxx', '62 Hello! Talking to you from Telethon')
		return 'success'
	except Exception as e:
		print(e)
	finally:
		client.disconnect()

![tele](https://user-images.githubusercontent.com/34264066/150785621-f8caf1fa-f430-4460-bced-bd7ff3f4408d.JPG)

There is no current event loop in thread 'Thread-1 (process_request_thread)'.
C:\xampp\htdocs\python\main.py:57: RuntimeWarning: coroutine 'MessageMethods.send_message' was never awaited
  print(e)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[2022-01-24 19:35:21,661] ERROR in app: Exception on /tele [GET]
Traceback (most recent call last):
  File "C:\Users\el farabi\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\el farabi\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\el farabi\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\el farabi\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\el farabi\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\python\main.py", line 59, in tele
    client.disconnect()
  File "C:\Users\el farabi\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\telegrambaseclient.py", line 576, in disconnect
    if self.loop.is_running():
  File "C:\Users\el farabi\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\telegrambaseclient.py", line 472, in loop
    return asyncio.get_event_loop()
  File "C:\Users\el farabi\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.
127.0.0.1 - - [24/Jan/2022 19:35:21] "GET /tele HTTP/1.1" 500 -

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
