### ISSUE TITLE
'TelegramClient' object has no attribute '_channel_pts'

### ISSUE THREAD

**Issue by apgrayedd** [LonamiWebs/Telethon#3683]
Help me!
Telethon Version v2
python 3.8.1

```
async def main():
  async with TelegramClient(session_name, api_id, api_hash) as client:
    dialogs = await client.get_dialogs()
    print(dialogs)

if __name__ == '__main__':
  loop = asyncio.get_event_loop()
  try:
    loop.run_until_complete(main())
  finally:
    pass
```
```
Traceback (most recent call last):
  File "c:/Users/User/Desktop/fffffffffffffffffffffffffffff/testPythonClient.py", line 24, in <module>
    loop.run_until_complete(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 612, in run_until_complete        
    return future.result()
  File "c:/Users/User/Desktop/fffffffffffffffffffffffffffff/testPythonClient.py", line 12, in main
    dialogs = await client.get_dialogs()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\_misc\requestiter.py", line 100, in collect
    async for message in self:
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\_misc\requestiter.py", line 72, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\_client\dialogs.py", line 85, in _load_next_chunk
    self.client._channel_pts[cd.id] = cd.dialog.pts
AttributeError: 'TelegramClient' object has no attribute '_channel_pts'
```

**Comment by Lonami** [comment]
Closing since v2 is not yet ready for public use, and this error should not be present in the currently-published v1.25 available from PyPi.
