### ISSUE TITLE
An error occurred `NameError: name 'aio_loop' is not defined` on example

### ISSUE THREAD

**Issue by kami1983** [LonamiWebs/Telethon#3717]
**Checklist**
Trying to run the example but getting an error, How to fix it?

**Code that causes the issue**
```python
cd Telethon
cd telethon_examples
python3 gui.py
...

```

**Traceback**
```
NameError: name 'aio_loop' is not defined
Exception in Tkinter callback
/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py:2349: RuntimeWarning: coroutine 'App.check_chat' was never awaited
  sys.last_traceback = tb
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/mac/work-files/coding/git-files/ke-fan/test-telethon/telethon_examples/gui.py", line 56, in wrapped
    aio_loop.create_task(result)

```

**Comment by Lonami** [comment]
The code example needs to be updated to use `asyncio` instead of `aio_loop`.
