### ISSUE TITLE
get_participants return single user in development version

### ISSUE THREAD

**Issue by MrDeveloper2022** [LonamiWebs/Telethon#3725]
**Checklist**
* [ *] The error is in the library's code, and not in my own.
* [ * ] I have searched for this issue before posting it and there isn't a duplicate.
* [  *] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

Hi 
As you know get_participants doesn't work properly on old version and @Lonami  said to use development version to use this feature , but in development version get_participants returns a single user instead of all members !

This is my code. : 
```
async def connectToTele() :
    client =TelegramClient('989303183978', teleParameters.api_id, teleParameters.api_hash)
    await client.connect()
    receiver =await client.get_input_entity('https://t.me/teletools_group')
    all_participants = []
    all_participants = await client.get_participants(receiver)
    print('participants data :  ')
    print(all_participants)
    for user in all_participants:
        print('user : ');
        print(user)
```
and this is the result : 

participants data :  
User(id=1844828401, is_self=True, contact=True, mutual_contact=True, deleted=False, bot=False, bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False, support=False, scam=False, apply_min_photo=True, fake=False, access_hash=4405022442472619117, first_name='TelegramTools.io', last_name=None, username='teletools_support', phone='989303183978', photo=UserProfilePhoto(photo_id=..., dc_id=..., has_video=..., stripped_thumb=...), status=UserStatusOffline(was_online=...), bot_info_version=None, restriction_reason=None, bot_inline_placeholder=None, lang_code=None)
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 35, in connectToTele
    for user in all_participants:
TypeError: 'User' object is not iterable

During handling of the above exception, another exception occurred:
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telethon/_client/updates.py", line 198, in _update_loop
    deadline - asyncio.get_running_loop().time()
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    asyncio.run(connectToTele() )
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 35, in connectToTele
    for user in all_participants:
TypeError: 'User' object is not iterable

```

**Comment by Lonami** [comment]
Closing since v2 is not ready for public use yet.
