### ISSUE TITLE
telethon.errors.common.TypeNotFoundError on download_media()

### ISSUE THREAD

**Issue by satrio-yudhoatmojo** [LonamiWebs/Telethon#3744]
I saw some issues related to telethon.errors.common.TypeNotFoundError but mine happened during calling download_media()

**Traceback**
`Traceback (most recent call last):
  File "telethon-rate-limit.py", line 455, in <module>
    result = get_message(msg[0], msg[1], msg[2], msg[3])
  File "telethon-rate-limit.py", line 300, in get_message
    media_filepath = message.download_media(file=temporary_directory)
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/Users/satrio/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/tl/custom/message.py", line 837, in download_media
    return await self._client.download_media(self, *args, **kwargs)
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/downloads.py", line 415, in download_media
    return await self._download_document(
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/downloads.py", line 882, in _download_document
    result = await self._download_file(
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/downloads.py", line 538, in _download_file
    async for chunk in self._iter_download(
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/downloads.py", line 66, in _load_next_chunk
    cur = await self._request()
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/downloads.py", line 95, in _request
    self._sender = await self.client._borrow_exported_sender(e.new_dc)
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 765, in _borrow_exported_sender
    sender = await self._create_exported_sender(dc_id)
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 745, in _create_exported_sender
    auth = await self(functions.auth.ExportAuthorizationRequest(dc_id))
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 617, in _handle_rpc_result
    result = state.request.read_result(reader)
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/tl/tlobject.py", line 219, in read_result
    return reader.tgread_object()
  File "/Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/extensions/binaryreader.py", line 140, in tgread_object
    raise error
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID df969c2d. Most likely, a TLObject was trying to be read when it should not be read. Remaining bytes: b'-\x9c\x96\xdfA\xa7\xd8r\x80\xc1k\xfb]\x8fh9\xb1ji\xc1\xb4\x8d1\x90\xdab\x8b2\xcbj\x85\xcc\xa9\xbb\xad\xe0"\xaf{\xf1mL#\xdf\xeb(\xd9K|K0\xf0\x9d_p{%\x94\xb0\xae\x192%\xb1\x1b\xa2g!\xd8\xbf\xac\x85\xafwz\xb7\xfa\xf7mBH\xfd\x06@~\x8as\xbfx\x95d\xec\x9d\x8b\x86:&\x03io@\xf6\xe6u\x84\xd4(o\xcd"\xd8\x0cJ\xf4~_\x8d\x8d\xee\x879B/O\xe1\xf5\x1fif\x10\xd5c\x93\x18\xfc\xba\xf3\x00\x00\x00\x92\xec\xad\xf3,{O\x88e\x19-V\nZ\x04\xab\xa0g\xaf\xd5j\xbdz\x87'
2022-02-25 10:39:14 ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1437' coro=<MTProtoSender._send_loop() running at /Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/network/mtprotosender.py:460> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc899c4b220>()]>>
2022-02-25 10:39:14 ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1438' coro=<MTProtoSender._recv_loop() running at /Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/network/mtprotosender.py:503> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc899c4b430>()]>>
2022-02-25 10:39:14 ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1435' coro=<Connection._send_loop() running at /Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/network/connection/connection.py:306> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc899c4b4c0>()]>>
2022-02-25 10:39:14 ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1436' coro=<Connection._recv_loop() running at /Users/satrio/opt/anaconda3/lib/python3.8/site-packages/telethon/network/connection/connection.py:324> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc899c4bd00>()]>>
`

**Comment by Lonami** [comment]
Telegram sometimes sends types corresponding to older or newer versions. Generally, the newer the version, the lower the chances for this to happen. v1.25 from PyPi should not have this issue.

**Comment by ismerr0990** [comment]
![image](https://github.com/LonamiWebs/Telethon/assets/146511128/db9782ad-b5b1-40d8-9e9d-d25804f9f630)

**Comment by ismerr0990** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/kxss/SocialBox/SMSBomber300/Hack-Telegram/telegram-hack.py", line 183, in <module>
    asyncio.run(main())########################################################################################################################################################
    ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/kxss/SocialBox/SMSBomber300/Hack-Telegram/telegram-hack.py", line 143, in main
    result = await client.send_code_request(phone) ############################################################################
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/client/auth.py", line 434, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/client/users.py", line 67, in _call
    future = sender.send(request, ordered=ordered)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 183, in send
    state = RequestState(request)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
                ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
           ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/tl/functions/auth.py", line 641, in _bytes
    self.serialize_bytes(self.phone_number),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/tl/tlobject.py", line 112, in serialize_bytes
    raise TypeError(
TypeError: bytes or str expected, not <class 'NoneType'>
┌─[05:37:09
