### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools' during pip install

### ISSUE THREAD

**Issue by suntong** [LonamiWebs/Telethon#3757]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

```sh
$ pip3 install telethon
Collecting telethon
  Using cached https://files.pythonhosted.org/packages/f5/2a/238c14ad6032d91ff134723d48470f8c5fe521522af323fde10c34e23047/Telethon-1.24.0-py3-none-any.whl
Collecting rsa (from telethon)
  Downloading https://files.pythonhosted.org/packages/30/ab/8fd9e88e6fa5ec41afca995938bbefb72195278e0cfc5bd76a4f29b23fb2/rsa-4.8-py3-none-any.whl
Collecting pyaes (from telethon)
  Using cached https://files.pythonhosted.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ls3mha8_/pyaes/

$ pip3 install -U https://github.com/LonamiWebs/Telethon/archive/master.zip
Collecting https://github.com/LonamiWebs/Telethon/archive/master.zip
  Downloading https://github.com/LonamiWebs/Telethon/archive/master.zip
     \ 962kB 19.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-0xq6tlzr-build/

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

I'm new to this pip ecosystem, maybe it's a very easy fix. please help.

**Comment by Lonami** [comment]
This is not something Telethon can fix https://stackoverflow.com/questions/8650459/how-to-get-setuptools-and-easy-install.
