### ISSUE TITLE
If TelegramClient.iter_messages() has limit of quantity？

### ISSUE THREAD

**Issue by killkingluo** [LonamiWebs/Telethon#3767]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from telethon import TelegramClient
api_id = 111222333
api_hash = '3a9b4...'
group_list = {1735819659: 0, 1236538274: 0, 1641083208: 0, 1547345038: 0, 1390159748: 0, 1501797606: 0, 1540623941: 0, 1674796097: 0, 1364959616: 0, 1544216989: 0, 1610053259: 0, 1181684110: 0, 1566070367: 0, 1776538437: 0, 1511117647: 0, 1496942401: 0, 1230746096: 0, 1579989785: 0, 1623720375: 0, 1360398133: 0, 1536568341: 0, 1358363513: 0, 1500356024: 0, 1600147134: 0, 1378908230: 0, 1675440403: 0, 1238725908: 0, 1706223599: 0, 1773634253: 0, 1542808487: 0, 1756302755: 0, 1517585956: 0, 1306251653: 0, 1562430354: 0, 1211673203: 0, 1625958429: 0, 1214997149: 0, 1745212404: 0, 1311656366: 0, 1425292109: 0, 1513629556: 0, 1591806003: 0, 1457853275: 0, 1340697196: 0, 1493499687: 0, 1763206229: 0, 1511951838: 0, 1562586696: 0, 1550382937: 0, 1676434530: 0, 1636139522: 0, 1766259301: 0, 1477508746: 0, 1567918031: 0, 1382396547: 0, 1409854661: 0, 1468090439: 0}

telegram_client = TelegramClient('anon', api_id, api_hash)


async def main():
    for ID in group_list.keys():
        if group_list.get(ID) == 0:
            async for message in telegram_client.iter_messages(ID, limit=1):
                group_list[ID] = message.id
                print(ID)

with telegram_client:
    telegram_client.loop.run_until_complete(main())
```

**Traceback**
```
Traceback (most recent call last):
  File "E:/python_telegram/test.py", line 21, in <module>
    telegram_client.loop.run_until_complete(main())
  File "D:\software\Python\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:/python_telegram/test.py", line 16, in main
    async for message in telegram_client.iter_messages(ID, limit=1):
  File "D:\software\Python\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "D:\software\Python\lib\site-packages\telethon\client\messages.py", line 184, in _load_next_chunk
    r = await self.client(self.request)
  File "D:\software\Python\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "D:\software\Python\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.ChannelPrivateError: The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by GetHistoryRequest)

Process finished with exit code 1

```

If TelegramClient.iter_messages() has limit of number？ When the number exceeded 40, I was refused to continue to traverse the channel message id

**Comment by Lonami** [comment]
This error comes from Telegram and it's not something Telethon can fix.
