### ISSUE TITLE
Bug in download_media function

### ISSUE THREAD

**Issue by ingria** [LonamiWebs/Telethon#3783]
`thumb` is not defined anywhere.

**Code that causes the issue**
```python
channel = await self.client(channels.GetFullChannel(...))
contents = await self.client.download_media(channel.full_chat.chat_photo)
```

**Traceback**
```
Traceback (most recent call last):
  File "/home/telegram/worker/./app/controllers.py", line 71, in utils_getChannelAvatar
    contents = await self.client.download_media(photo)
  File "/home/telegram/.venv/worker/lib/python3.8/site-packages/telethon/_client/downloads.py", line 293, in download_media
    self, media, file, date, thumb, progress_callback
NameError: name 'thumb' is not defined
```

**Comment by Lonami** [comment]
Closing since this is for v2 which is a long-time coming.
