### ISSUE TITLE
Can't fetch users of chat 

### ISSUE THREAD

**Issue by blindone0** [LonamiWebs/Telethon#3808]
### Enter a Number: 7
Fetching Members...
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/home/ihor/.local/lib/python3.8/site-packages/telethon/_client/updates.py", line 211, in _update_loop
    updates_to_dispatch.extend(_preprocess_updates(self, processed, users, chats))
  File "/home/ihor/.local/lib/python3.8/site-packages/telethon/_client/updates.py", line 218, in _preprocess_updates
    entities = Entities(self, users, chats)
  File "/home/ihor/.local/lib/python3.8/site-packages/telethon/_client/updates.py", line 226, in __init__
    self._entities = {e.id: e for e in itertools.chain(
  File "/home/ihor/.local/lib/python3.8/site-packages/telethon/_client/updates.py", line 226, in <dictcomp>
    self._entities = {e.id: e for e in itertools.chain(
  File "/home/ihor/.local/lib/python3.8/site-packages/telethon/_client/updates.py", line 228, in <genexpr>
    (Chat._new(client, c) for u in chats),
NameError: name 'c' is not defined
Traceback (most recent call last):
  File "sc.py.dev", line 77, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "sc.py.dev", line 54, in main
    all_participants = await client.get_participants(target_group)
  File "/home/ihor/.local/lib/python3.8/site-packages/telethon/_misc/requestiter.py", line 100, in collect
    async for message in self:
  File "/home/ihor/.local/lib/python3.8/site-packages/telethon/_misc/requestiter.py", line 72, in __anext__
    if await self._load_next_chunk():
  File "/home/ihor/.local/lib/python3.8/site-packages/telethon/_client/chats.py", line 208, in _load_next_chunk
    if isinstance(participant, types.ChannelParticipantLeft):
NameError: name 'types' is not defined

`from var_dump import var_dump
from pprint import pprint
import asyncio

from telethon import TelegramClient
from telethon._tl.fn.messages import GetDialogs
from telethon._tl import InputPeerEmpty
import csv

api_id=999999999
api_hash='999999'
phone='+99999999'

async def main():
    async with TelegramClient(phone, api_id, api_hash) as client:
        await client.connect()
        if not await client.is_user_authorized():
            await client.send_code_request(phone)
            await client.sign_in(phone, input('Enter the code: '))

        chats = []
        last_date = None
        chunk_size = 200
        groups=[]
        
        result = await client(GetDialogs(
                    offset_date=last_date,
                    offset_id=0,
                    offset_peer=InputPeerEmpty(),
                    limit=chunk_size,
                    hash = 0
                ))
        chats.extend(result.chats)

        for chat in chats:
            try:
                if chat.megagroup== True:
                    groups.append(chat)
            except:
                continue

        print('Choose a group to scrape members from:')
        i=0
        for g in groups:
            print(str(i) + '- ' + g.title)
            i+=1

        g_index = input("Enter a Number: ")
        target_group=groups[int(g_index)]

        print('Fetching Members...')
        all_participants = []
        all_participants = await client.get_participants(target_group)
        var_dump(all_participants)
        print('Saving In file...')
        with open("members.csv","w",encoding='UTF-8') as f:
            writer = csv.writer(f,delimiter=",",lineterminator="\n")
            writer.writerow(['username','user id', 'access hash','name','group', 'group id'])
            for user in all_participants:
                if user.username:
                    username= user.username
                else:
                    username= ""
                if user.first_name:
                    first_name= user.first_name
                else:
                    first_name= ""
                if user.last_name:
                    last_name= user.last_name
                else:
                    last_name= ""
                name= (first_name + ' ' + last_name).strip()
                writer.writerow([username,user.id,user.access_hash,name,target_group.title, target_group.id])      
        print('Members scraped successfully.')

asyncio.run(main())
`

**Comment by blindone0** [comment]
please help,
