### ISSUE TITLE
telethon.errors.rpcerrorlist.UsernameInvalidError: Nobody is using this username

### ISSUE THREAD

**Issue by RouatbiH** [LonamiWebs/Telethon#3814]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**### Code that causes the issue**
**I dont know :(**

**Traceback**
```
Task exception was never retrieved
future: <Task finished coro=<UpdateMethods._dispatch_update() done, defined at C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\client\updates.py:399> exception=UsernameInvalidError('Nobody is using this username, or the username is unacceptable. If the latter, it must match r"[a-zA-Z][\\w\\d]{3,30}[a-zA-Z\\d]" (caused by ResolveUsernameRequest)')>
Traceback (most recent call last):
  File "C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\client\updates.py", line 458, in _dispatch_update
    await builder.resolve(self)
  File "C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\events\common.py", line 99, in resolve
    await self._resolve(client)
  File "C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\events\newmessage.py", line 94, in _resolve
    self.from_users = await _into_id_set(client, self.from_users)
  File "C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\events\common.py", line 33, in _into_id_set
    chat = await client.get_input_entity(chat)
  File "C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\client\users.py", line 437, in get_input_entity
    await self._get_entity_from_string(peer))
  File "C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\client\users.py", line 554, in _get_entity_from_string
    functions.contacts.ResolveUsernameRequest(username))
  File "C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\HamamGhrab\AppData\Roaming\Python\Python37\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.UsernameInvalidError: Nobody is using this username, or the username is unacceptable. If the latter, it must match r"[a-zA-Z][\w\d]{3,30}[a-zA-Z\d]" (caused by ResolveUsernameRequest)

```

**Comment by RouatbiH** [comment]
### _Solved !_

There is deleted user in the list i entered in variable **allowed_bot**
```
@client.on(events.MessageEdited(from_users=allowed_bot))
```
### If there is user deleted or not exist in telegram you will get an error
