### ISSUE TITLE
Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetMessagesRequest)

### ISSUE THREAD

**Issue by msramalho** [LonamiWebs/Telethon#3819]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

client = TelegramClient("./anon", api_id, api_hash)

with client.start():
    # https://t.me/brokencats/6287 - this one works
    print(client.get_messages("brokencats", ids=6287))
    # https://t.me/truexanewsua/34119 - this one produces the error
    print(client.get_messages("truexanewsua", ids=34119))

```

**Traceback**
```
Traceback (most recent call last):
  File "path1/path3/telethon_code.py", line 53, in download
    post = client.get_messages(chat, ids=post_id)
  File "pathX/lib/python3.9/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "pathX/lib/python3.9/site-packages/telethon/client/messages.py", line 580, in get_messages
    async for message in it:
  File "pathX/lib/python3.9/site-packages/telethon/requestiter.py", line 74, in __anext__       
    if await self._load_next_chunk():
  File "pathX/lib/python3.9/site-packages/telethon/client/messages.py", line 289, in _load_next_chunk
    r = await self.client(
  File "pathX/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__       
    return await self._call(self._sender, request, ordered=ordered)      
  File "pathX/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more 
suited (caused by GetMessagesRequest)
```

**Comment by msramalho** [comment]
doing `with client.start(bot_token="valid bot token here"):` fixes the issue. closing issue.

**Comment by Sanjarbek17** [comment]
is it worked this one doesn't worked for me.
