### ISSUE TITLE
pip install telethon is broken

### ISSUE THREAD

**Issue by andreif** [LonamiWebs/Telethon#383]
User has to install dependencies before they can install telethon due to importing them in setup.py via the package tree.

**Comment by Lonami** [comment]
What's the error? Are you sure you're using `pip3`?

**Comment by andreif** [comment]
Can you install master in a new virtualenv? I cannot.

**Comment by Lonami** [comment]
Python version? What command? What's the error?

**Comment by andreif** [comment]
`ModuleNotFoundError: No module named 'pyaes'`

**Comment by Lonami** [comment]
Any way in which we can have a centralized place to keep the `__version__` on that can be accessed through the `setup.py`? I wonder why nobody else has complained after so long.

**Comment by andreif** [comment]
```
pip install -e .
Obtaining file:///Users/andrei/Telethon
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/andrei/Telethon/setup.py", line 153, in <module>
        main()
      File "/Users/andrei/Telethon/setup.py", line 99, in main
        from telethon import TelegramClient as TgClient
      File "/Users/andrei/Telethon/telethon/__init__.py", line 1, in <module>
        from .telegram_bare_client import TelegramBareClient
      File "/Users/andrei/Telethon/telethon/telegram_bare_client.py", line 13, in <module>
        from .crypto import rsa, CdnDecrypter
      File "/Users/andrei/Telethon/telethon/crypto/__init__.py", line 1, in <module>
        from .aes import AES
      File "/Users/andrei/Telethon/telethon/crypto/aes.py", line 2, in <module>
        import pyaes
    ModuleNotFoundError: No module named 'pyaes'
    Failed to import TelegramClient due to No module named 'pyaes'
    Detected previous TLObjects. Cleaning...
    Generating TLObjects...
    Generating errors...
    Done.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/andrei/Telethon/
```

**Comment by andreif** [comment]
I usually keep it in `mypkg/__init__.py` but I don't import the whole thingy there, which will obviously not work.

**Comment by andreif** [comment]
And yes, I keep my setup.py as simple as possible.

**Comment by andreif** [comment]
@Lonami See #384 for example
