### ISSUE TITLE
Video sticker support?

### ISSUE THREAD

**Issue by mbasaglia** [LonamiWebs/Telethon#3834]
I was trying to handle different kind of media messages but looks like video stickers aren't supported (telethon 1.24.0 from pip).

On new message events with video stickers:

`event.message.media` is `telethon.tl.types.MessageMediaUnsupported`

`event.message.sticker`, `event.message.video`, and `event.message.file` are all `None`

**Comment by Lonami** [comment]
The https://github.com/LonamiWebs/Telethon/tree/v1.24 branch should not show unsupported.

**Comment by djbone** [comment]
i checkout the v1.24 branch,when i call 
`entity = await client.get_input_entity("t.me/xxxx_bot")`

that show this error :

`

Traceback (most recent call last):
line 81, in run_until_complete
    return f.result()
  File "\lib\asyncio\futures.py", line 181, in result
    raise self._exception
  File "\lib\asyncio\tasks.py", line 249, in __step
    result = coro.send(None)
  File "<eval>", line 19, in __async_exec_func__
  File "<eval>", line 1, in __async_exec_func__
  File "\telethon\telethon\client\users.py", line 441, in get_input_entity
    return await self.session.get_input_entity(peer)
  File "\telethon\telethon\sessions\memory.py", line 214, in get_input_entity
    result = await self.get_entity_rows_by_username(username)
TypeError: object tuple can't be used in 'await' expression`

**Comment by Lonami** [comment]
Are you using an alternative session backend? Those are not supported.

**Comment by djbone** [comment]
It means only support bot,not support person account or I should initial TelegramClient without session? 
 

`
   client= await TelegramClient("account", API_ID, API_HASH, proxy=proxy).start()
   entity =await  client.get_input_entity("t.me/xxx")

`
how to initial TelegramClient without session?

I use None to initial ,and it's the same problem
client = await TelegramClient(None, API_ID, API_HASH, proxy=proxy).start()
entity =await  client.get_input_entity("t.me/xxx")

Traceback (most recent call last):
    return f.result()
  File "\lib\asyncio\futures.py", line 181, in result
    raise self._exception
  File "\lib\asyncio\tasks.py", line 249, in __step
    result = coro.send(None)
  File "<eval>", line 19, in __async_exec_func__
  File "<eval>", line 1, in __async_exec_func__
  File "\telethon\telethon\client\users.py", line 441, in get_input_entity
    return await self.session.get_input_entity(peer)
  File "\telethon\telethon\sessions\memory.py", line 214, in get_input_entity
    result = await self.get_entity_rows_by_username(username)
TypeError: object NoneType can't be used in 'await' expression

**Comment by Lonami** [comment]
Closing since v1.25 has been released on PyPi and should no longer show unsupported media for these.
