### ISSUE TITLE
MessageNotModifiedError when edit message with float value

### ISSUE THREAD

**Issue by gmunumel** [LonamiWebs/Telethon#3853]
Hello, 

I'm using Telethon version 1.24.0 and I'm getting this error when trying to edit a message with a float value:

`telethon.errors.rpcerrorlist.MessageNotModifiedError: Content of the message was not modified (caused by EditMessageRequest)`

The first time display `0` but the second time show the error. 

I tried with different format values and only this one work `await msg.edit("{}".format(current * 100 / total))`, which is not ideal because I only want 2 decimals. 

**Code that causes the issue**
```python
import asyncio

from telethon import TelegramClient

bot_name = "bot_name"
api_id = "api_id"
api_hash = "api_hash"
bot_token = "bot_token"

async def main():
    bot = TelegramClient(bot_name, api_id, api_hash)
    await bot.start(bot_token=bot_token)
   
   @bot.on(events.NewMessage())
   async def handler(event):
      msg = await event.reply("Initial message")

      current = 123
      total = 1231123
      while True:
         current += 1
         await msg.edit(f"{current * 100 / total}")  # error
         await msg.edit("{:.2f}".format(current * 100 / total)) # error
         await msg.edit("{}".format(round(current * 100 / total, 2))) # error

         await msg.edit(f"{current}")  # works
         await msg.edit("{}".format(current * 100 / total)) # works

         await asyncio.sleep(1)

if __name__ == '__main__':
    asyncio.run(main())

```

**Traceback**
```
2022-06-22 21:02:28,967 - telethon.client.updates - ERROR - Unhandled exception on handler
Traceback (most recent call last):
  File "c:\Users\gabriel\Documents\Code\python\telegram_bot\.venv\lib\site-packages\telethon\client\updates.py", line 467, in _dispatch_update
    await callback(event)
  File "c:\Users\gabriel\Documents\Code\python\telegram_bot\bot\bot.py", line 140, in handler
    await process_provider(provider, text, event)
  File "c:\Users\gabriel\Documents\Code\python\telegram_bot\bot\bot.py", line 99, in process_provider
    await msg.edit("{}".format(int(current * 100 / total)))
  File "c:\Users\gabriel\Documents\Code\python\telegram_bot\.venv\lib\site-packages\telethon\tl\custom\message.py", line 805, in edit
    return await self._client.edit_message(
  File "c:\Users\gabriel\Documents\Code\python\telegram_bot\.venv\lib\site-packages\telethon\client\messages.py", line 1194, in edit_message
    msg = self._get_response_message(request, await self(request), entity)
  File "c:\Users\gabriel\Documents\Code\python\telegram_bot\.venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "c:\Users\gabriel\Documents\Code\python\telegram_bot\.venv\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.MessageNotModifiedError: Content of the message was not modified (caused by EditMessageRequest)

```

**Comment by ghost** [comment]
Try running your code for a while without telethon, just printing the strings out:
```python
import time

current, total = 123, 1231123
while True:
    current += 1
    s1 = f"{current * 100 / total}"  # error
    s2 = "{:.2f}".format(current * 100 / total)  # error
    s3 = "{}".format(round(current * 100 / total, 2))  # error
    s4 = f"{current}"  # works
    s5 = "{}".format(current * 100 / total)  # works
    print(s1, s2, s3, s4, s5)
    time.sleep(1)

```
This yields:
```
0.010072104899347994 0.01 0.01 124 0.010072104899347994
0.01015333155176209 0.01 0.01 125 0.01015333155176209
0.010234558204176188 0.01 0.01 126 0.010234558204176188
0.010315784856590285 0.01 0.01 127 0.010315784856590285
0.01039701150900438 0.01 0.01 128 0.01039701150900438
0.010478238161418477 0.01 0.01 129 0.010478238161418477
0.010559464813832574 0.01 0.01 130 0.010559464813832574
0.01064069146624667 0.01 0.01 131 0.01064069146624667
0.010721918118660767 0.01 0.01 132 0.010721918118660767
0.010803144771074864 0.01 0.01 133 0.010803144771074864
0.010884371423488961 0.01 0.01 134 0.010884371423488961
0.010965598075903058 0.01 0.01 135 0.010965598075903058
0.011046824728317155 0.01 0.01 136 0.011046824728317155
0.01112805138073125 0.01 0.01 137 0.01112805138073125
0.011209278033145347 0.01 0.01 138 0.011209278033145347
0.011290504685559444 0.01 0.01 139 0.011290504685559444
0.011371731337973541 0.01 0.01 140 0.011371731337973541
0.011452957990387638 0.01 0.01 141 0.011452957990387638
```
Clearly showing, that it is a problem in your code and not the library: when the message text is "0.01", and you edit it to the same string, you don't actually modify the message, causing the error.

**Comment by gmunumel** [comment]
Thanks @sernot for your answer. 

The error was clueless about this. Would be nice to have it documented in so place or the library do nothing in this case.

**Comment by ghost** [comment]
"telethon.errors.rpcerrorlist.**MessageNotModifiedError**: **Content of the message was not modified** (caused by EditMessageRequest)" 
Seems descriptive enough.

**Comment by gmunumel** [comment]
Indeed, should I pay more attention to that.
