### ISSUE TITLE
The number of file parts is invalid (caused by SendMediaRequest)

### ISSUE THREAD

**Issue by alirezaimi** [LonamiWebs/Telethon#3863]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
from telethon import TelegramClient
import os
import sys
from natsort import natsorted

client = TelegramClient("XXX", "XX", "XX")
path = sys.argv[1]
try:
    ext = sys.argv[2]
except IndexError:
    ext = ""

def progress(i, j):
    pr = int((i/j)*100)
    file_size = round((j/1024)/1024, 2)
    remain_size = int((i/1024)/1024)
    print(f"Size {file_size} MB, remain {remain_size} MB, Remain : {pr}%", end="\r")


async def main():
    roots = []

    for root, _, fnames in os.walk(path):
        roots.append([root, fnames])

    roots = natsorted(roots)
    for root, fnames in roots:
        print(root, fnames)
        fnames = natsorted(fnames)
        for fname in fnames:
            files = os.path.join(root, fname)
            print(files)
            #print(ext in files)
            if ext in files:
                print(">> uploading : ", files)
                await client.send_file(XX, files, caption=files, progress_callback=progress)

with client:
    client.loop.run_until_complete(main())

...

```

**Traceback**
```
>> uploading :  Modern rrrr with uuuu/M/21 - Handling Authentication with 582411/5 - Rendering Authentication Status_en.srt
Traceback (most recent call last):
  File "aa.py", line 39, in <module>
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "aa.py", line 36, in main
    await client.send_file(XX, files, caption=files, progress_callback=progress)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/uploads.py", line 394, in send_file
    return self._get_response_message(request, await self(request), entity)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.FilePartsInvalidError: The number of file parts is invalid (caused by SendMediaRequest)

```

I can't understand why this error happened to me !

**Comment by Lonami** [comment]
Make sure you're not sending an empty file.

**Comment by alirezaimi** [comment]
In my case this error happened when file size is 0 .
Thanks .
