### ISSUE TITLE
I received a channel message, and when I tried to edit the message and send it again, I got an error:Failed to parse message

### ISSUE THREAD

**Issue by jianwei923** [LonamiWebs/Telethon#3872]
2022-07-14 17:42:12.578 | ERROR    | UI.MainPanel:async_task_send:356 - Traceback (most recent call last):
  File "D:\TG_PigTest\TestSpider\UI\MainPanel.py", line 336, in async_task_send
    msgs = await self.client.send_message(r_chat_id, caption +'\n'+ chat_label, file=media_s[0:5], parse_mode='html')
  File "D:\Python\Python39\lib\site-packages\telethon\client\messages.py", line 800, in send_message
    return await self.send_file(
  File "D:\Python\Python39\lib\site-packages\telethon\client\uploads.py", line 362, in send_file
    result += await self._send_album(
  File "D:\Python\Python39\lib\site-packages\telethon\client\uploads.py", line 435, in _send_album
    captions.append(await self._parse_message_text(c or '', parse_mode))
  File "D:\Python\Python39\lib\site-packages\telethon\client\messageparse.py", line 89, in _parse_message_text
    raise ValueError("Failed to parse message")
ValueError: Failed to parse message

**Comment by Lonami** [comment]
You need to include the failing message text used.

**Comment by Lonami** [comment]
Closing due to inactivity. Make sure the message is not whitespace-only or otherwise empty.
