### ISSUE TITLE
Bug. client.get_dialogs. Cannot cast User to any kind of int.

### ISSUE THREAD

**Issue by zedzhen** [LonamiWebs/Telethon#3879]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import telethon
import asyncio

loop = asyncio.new_event_loop()

client = telethon.TelegramClient('',  [api_id], [api_hash])

async def main():
    await client.connect()
    await client.send_code_request('+799*********')
    await client.sign_in(code=input('Code: '), password='[my password]')
    ds = await client.get_dialogs()

loop.run_until_complete(main())
```

**Traceback**
```
Traceback (most recent call last):
  File "D:/.../telethon_test.py", line 14, in <module>
    loop.run_until_complete(main())
  File "D:\Programs\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:/.../telethon_test.py", line 12, in main
    ds = await client.get_dialogs()
  File "D:\Programs\Python310\lib\site-packages\telethon\_misc\requestiter.py", line 100, in collect
    async for message in self:
  File "D:\Programs\Python310\lib\site-packages\telethon\_misc\requestiter.py", line 72, in __anext__
    if await self._load_next_chunk():
  File "D:\Programs\Python310\lib\site-packages\telethon\_client\dialogs.py", line 58, in _load_next_chunk
    entities = {utils.get_peer_id(x): x
  File "D:\Programs\Python310\lib\site-packages\telethon\_client\dialogs.py", line 58, in <dictcomp>
    entities = {utils.get_peer_id(x): x
  File "D:\Programs\Python310\lib\site-packages\telethon\_misc\utils.py", line 970, in get_peer_id
    _raise_cast_fail(peer, 'int')
  File "D:\Programs\Python310\lib\site-packages\telethon\_misc\utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast User to any kind of int.
```

**Comment by zedzhen** [comment]
Unable to reproduce.

**Comment by zedzhen** [comment]
Unable to reproduce.
