### ISSUE TITLE
UnboundLocalError: local variable 'peer' referenced before assignment

### ISSUE THREAD

**Issue by egormanga** [LonamiWebs/Telethon#3881]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.
	* with patches to some other bugs applied

**Code that causes the issue**
```python
from telethon import TelegramClient

client = TelegramClient(...)

async def main():
        global client

        client = await client.start()

        async with client:
                client.me = await client.get_me()
                await client.run_until_disconnected()
```

**Traceback**
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/telethon/_client/updates.py", line 176, in _update_loop
    await _dispatch(self, *updates_to_dispatch.popleft())
  File "/usr/lib/python3.10/site-packages/telethon/_client/updates.py", line 255, in _dispatch
    event_cache[handler._event] = event = handler._event._build(self, update, entities)
  File "/usr/lib/python3.10/site-packages/telethon/_events/messageread.py", line 79, in _build
    self._chat = entities.get(peer)
UnboundLocalError: local variable 'peer' referenced before assignment
```

**Comment by egormanga** [comment]
Adding

```patch
+else:
+    raise ValueError(update)
```

at `_events/messageread.py:76` results in:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/telethon/_client/updates.py", line 176, in _update_loop
    await _dispatch(self, *updates_to_dispatch.popleft())
  File "/usr/lib/python3.10/site-packages/telethon/_client/updates.py", line 255, in _dispatch
    event_cache[handler._event] = event = handler._event._build(self, update, entities)
  File "/usr/lib/python3.10/site-packages/telethon/_events/messageread.py", line 77, in _build
    raise ValueError(update)
ValueError: UpdateShort(update=UpdateUserStatus(user_id=..., status=...), date=datetime.datetime(2022, 7, 20, 17, 34, 9, tzinfo=datetime.timezone.utc))
```

**Comment by Lonami** [comment]
`https://github.com/LonamiWebs/Telethon/archive/master.zip` is currently broken. However the v1.25 version available in PyPi should work. Let me know if that's not the case.
