### ISSUE TITLE
Trying to get what has been edited on message

### ISSUE THREAD

**Issue by BlackRove** [LonamiWebs/Telethon#3883]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

Hey, so im trying to get the message by ID to see what has been edited on it. I think this is the function i should use since GetMessageRequest not giving back what i need.The ID and the username is 100% right. If there is an easier way to get that what has been edited on a message by messageID i would be pleased to know.

Thank you for ur time 

**Code that causes the issue**
```python
from telethon import TelegramClient
...
@client.on(events.NewMessage())
async def handler(event):
    
    sda = await client(functions.messages.GetMessagesRequest(id=[theid]))
    asdg = await client(functions.messages.GetMessageEditDataRequest(peer="username",id=theid))

```

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\telethon\client\updates.py", line 456, in _dispatch_update
    await callback(event)
  File "c:\Users\DEV\Documents\GitHub\autobet\main.py", line 292, in handler
    asdg = await client(functions.messages.GetMessageEditDataRequest(peer="r3f4ct0r",id=11348))
  File "C:\Users\DEV\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\DEV\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\telethon\client\users.py", line 88, in _call
    result = await future
telethon.errors.rpcerrorlist.MessageIdInvalidError: The specified message ID is invalid or you can't do that operation on such message (caused by GetMessageEditDataRequest)
```

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
