### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_premium'

### ISSUE THREAD

**Issue by cc00010** [LonamiWebs/Telethon#3890]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from pyrogram import Client
from flask import Flask, Response

api_id = XXXX
api_hash = XXXX
app = Flask(__name__)
client = Client('self', api_id, api_hash)

@app.before_request
def bef():
  if client.is_connected is None:
    client.connect()

@app.get('/')
def index():
    message = client.send_photo('me', './test.png') # <- here fails
    return Response()
...

```

**Traceback**
```
Traceback (most recent call last):
  File "/Users/xxx/hh/mtproto-py/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xxx/hh/mtproto-py/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xxx/hh/mtproto-py/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xxx/hh/mtproto-py/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/xxx/hh/mtproto-py/test.py", line 21, in index
    message = client.send_photo('me', './test.png')
  File "/Users/xxx/hh/mtproto-py/venv/lib/python3.9/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/xxx/hh/mtproto-py/venv/lib/python3.9/site-packages/pyrogram/methods/messages/send_photo.py", line 147, in send_photo
    file = await self.save_file(photo, progress=progress, progress_args=progress_args)
  File "/Users/xxx/hh/mtproto-py/venv/lib/python3.9/site-packages/pyrogram/methods/advanced/save_file.py", line 128, in save_file
    file_size_limit_mib = 4000 if self.me.is_premium else 2000
AttributeError: 'NoneType' object has no attribute 'is_premium'

```

**Additional**
I tried to remove the if check from here `file_size_limit_mib = 4000 if self.me.is_premium else 2000` and everything worked. It seems like it just doesn't know about `self.me`.

Am I missing something?

**Comment by cc00010** [comment]
closing it, wrong repository.
