### ISSUE TITLE
Fatal error handling updates

### ISSUE THREAD

**Issue by GitHubAtomicMan** [LonamiWebs/Telethon#3896]
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "C:\Users\Samm\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\updates.py", line 359, in _update_loop
    deadline - asyncio.get_running_loop().time()
  File "C:\Users\Samm\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "C:\Users\Samm\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\updates.py", line 359, in _update_loop
    deadline - asyncio.get_running_loop().time()
  File "C:\Users\Samm\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

**Comment by GirlBoomer** [comment]
Yeah, people busy and updates.py is not working as supposed to.

**Comment by Lonami** [comment]
See https://github.com/LonamiWebs/Telethon/issues/3921#issuecomment-1246923527. It should work fine still. It's just incorrectly logged. Is that the case?

**Comment by Lonami** [comment]
I'm going to close this assuming it has been fixed in the v1.24 branch.
