### ISSUE TITLE
Invalid object ID for a user. Make sure to pass the right types, for instance making sure that the request is designed for users or otherwise look for a different one more suited

### ISSUE THREAD

**Issue by senatroxx** [LonamiWebs/Telethon#3898]
Hi, i want to add members to a group but it gives me error:
```
Traceback (most recent call last):
        File "C:\Programming\Python\Scraper\modules\invite.py", line 111, in inviteUsers
          await client(InviteToChannelRequest(group_entity, [user_to_add]))
        File "C:\Users\athha\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
          return await self._call(self._sender, request, ordered=ordered)
        File "C:\Users\athha\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 84, in _call
          result = await future
      telethon.errors.rpcerrorlist.UserIdInvalidError: Invalid object ID for a user. Make sure to pass the right types, for instance making sure that the request is designed for users or otherwise look for a different one more suited (caused by InviteToChannelRequest)
```

This is the code
```
async def inviteUsers():
  n = 0
  group_entity = InputPeerChannel(targetGroup.id, targetGroup.access_hash)

  with alive_bar(len(participants)) as bar:
    for participant in participants:
      n += 1

      try:
        print(f'{Fore.GREEN}Inviting {Fore.YELLOW}{participant["name"]} ({participant["id"]})')
        user_to_add = InputUser(int(participant['id']), int(participant['access_hash']))
        await client(InviteToChannelRequest(group_entity, [user_to_add]))
        time.sleep(3)
      except FloodWaitError as e:
        print(f'{Fore.RED}FloodWaitError: Have to sleep {e} seconds.')
        time.sleep(e.seconds)
      except PeerFloodError:
        print(f"{Fore.RED}Getting Flood Error from telegram. Script is stopping now. Please try again after some time.")
        print(f'{Fore.YELLOW}Changing Session..')
        break
      except UserPrivacyRestrictedError:
        print(f"{Fore.YELLOW}The user's privacy settings do not allow you to do this. {Fore.RED}Skipping.")
      except UserNotMutualContactError:
        print(f"{Fore.YELLOW}The user's is not your mutual contact or the user's has block the group. {Fore.RED}Skipping.")
      except Exception as e:
        print(traceback.format_exc())
        print(f"{Fore.RED}Unexpected Error")
        print(e)
        continue

      bar()
```

It only work when using certain telegram account, but when using another telegram account it will show error like the one described above

**Comment by Lonami** [comment]
This is working as intended. Please search for previous issues for why.
