### ISSUE TITLE
MtProxy 

### ISSUE THREAD

**Issue by n3w-w3rld** [LonamiWebs/Telethon#3906]
**Checklist**
* [+] The error is in the library's code, and not in my own.
* [+] I have searched for this issue before posting it and there isn't a duplicate.
* [+] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

__Im try to Connect with MtProxy but i can't.__

**Code that causes the issue**
```    
Proxy = {'server': 'mci.irancell.arvancloud.com.example.com.manoto.beauty.', 'port': 443, 'secret': '7vQ1mpsyX_HR5QhN8OD3U3tzbGFjay5jb20=', 'Count': 0}
Proxy: tuple = (Proxy['server'], Proxy['port'], Proxy['secret'])

NewAccounts = TelegramClient(phone,
                                 api_id=rand[0][0],
                                 api_hash=rand[0][1],
                                 proxy=Proxy)

```

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\moham\PycharmProjects\pythonProject\bot.py", line 180, in <module>
    asyncio.run(Send_Code('+**********'))
  File "C:\Users\moham\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\moham\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\moham\PycharmProjects\pythonProject\bot.py", line 108, in Send_Code
    await NewAccounts.connect()
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\telegram_client.py", line 146, in connect
    return super().connect()
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\telegram_bare_client.py", line 115, in connect
    authenticator.do_authentication(transport)
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\network\authenticator.py", line 17, in do_authentication
    sender.connect()
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\network\mtproto_plain_sender.py", line 16, in connect
    self._transport.connect()
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\network\tcp_transport.py", line 21, in connect
<class 'socks.socksocket'>
    self.tcp_client.connect(self.ip, self.port,
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\extensions\tcp_client.py", line 40, in connect
    self._socket.connect((ip, port))
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\socks.py", line 788, in connect
    super(socksocket, self).connect(proxy_addr)
TypeError: str, bytes or bytearray expected, not int

```

**Comment by n3w-w3rld** [comment]
> **Checklist**
> 
> * [+] The error is in the library's code, and not in my own.
> * [+] I have searched for this issue before posting it and there isn't a duplicate.
> * [+] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.
> 
> **Im try to Connect with MtProxy but i can't.**
> 
> **Code that causes the issue**
> 
> ```
> Proxy = {'server': 'mci.irancell.arvancloud.com.example.com.manoto.beauty.', 'port': 443, 'secret': '7vQ1mpsyX_HR5QhN8OD3U3tzbGFjay5jb20=', 'Count': 0}
> Proxy: tuple = (Proxy['server'], Proxy['port'], Proxy['secret'])
> 
> NewAccounts = TelegramClient(phone,
>                                  api_id=rand[0][0],
>                                  api_hash=rand[0][1],
>                                  proxy=Proxy)
> ```
> 
> **Traceback**
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\moham\PycharmProjects\pythonProject\bot.py", line 180, in <module>
>     asyncio.run(Send_Code('+**********'))
>   File "C:\Users\moham\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\moham\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "C:\Users\moham\PycharmProjects\pythonProject\bot.py", line 108, in Send_Code
>     await NewAccounts.connect()
>   File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\telegram_client.py", line 146, in connect
>     return super().connect()
>   File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\telegram_bare_client.py", line 115, in connect
>     authenticator.do_authentication(transport)
>   File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\network\authenticator.py", line 17, in do_authentication
>     sender.connect()
>   File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\network\mtproto_plain_sender.py", line 16, in connect
>     self._transport.connect()
>   File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\network\tcp_transport.py", line 21, in connect
> <class 'socks.socksocket'>
>     self.tcp_client.connect(self.ip, self.port,
>   File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\extensions\tcp_client.py", line 40, in connect
>     self._socket.connect((ip, port))
>   File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\socks.py", line 47, in wrapper
>     return function(*args, **kwargs)
>   File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\socks.py", line 788, in connect
>     super(socksocket, self).connect(proxy_addr)
> TypeError: str, bytes or bytearray expected, not int
> ```
