### ISSUE TITLE
New MtProto

### ISSUE THREAD

**Issue by n3w-w3rld** [LonamiWebs/Telethon#3907]
**Checklist**
* [+] The error is in the library's code, and not in my own.
* [+] I have searched for this issue before posting it and there isn't a duplicate.
* [+] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.
 
This is my proxy :
    ```{'server': 'mci.irancell.arvancloud.com.example.com.manoto.beauty.', 'port': 443, 'secret': '7vQ1mpsyX_HR5QhN8OD3U3tzbGFjay5jb20=', 'Count': 0}```

**This is a new MtProxy in this proxy secret it's Base64**

**Code that causes the issue**
```    
NewAccounts = TelegramClient(phone,
                                 api_id=rand[0][0],
                                 api_hash=rand[0][1],
                                 proxy=Proxy,
                                 device_model=rand[2],
                                 system_version=str(rand[3]),
                                 app_version=str(rand[4]),
                                 lang_code=rand[5],
                                 system_lang_code=rand[6],
                                 connection=ConnectionTcpMTProxyRandomizedIntermediate)

```

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\moham\PycharmProjects\pythonProject\bot.py", line 195, in <module>
    asyncio.run(Send_Code('+***********'))
  File "C:\Users\moham\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\moham\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\moham\PycharmProjects\pythonProject\bot.py", line 110, in Send_Code
    await NewAccounts.connect()
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\client\telegrambaseclient.py", line 525, in connect
    if not await self._sender.connect(self._connection(
  File "C:\Users\moham\PycharmProjects\pythonProject\venv\lib\site-packages\telethon\network\connection\tcpmtproxy.py", line 101, in __init__
    self._secret = bytes.fromhex(proxy[2])
ValueError: non-hexadecimal number found in fromhex() arg at position 1
```

**Comment by Lonami** [comment]
Newer MTProxies are not supported. I have no interest to maintain them either. These were added by other people and have not been updated, possibly due to the lack of interest.

**Comment by Lonami** [comment]
I'm going to close this issue because I am unlikely to implement it myself.
