### ISSUE TITLE
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by json1c** [LonamiWebs/Telethon#3912]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```
with TelegramClient(
    StringSession(),
    api_id,
    api_hash,
    device_model="Redmi Note 10",
    lang_code="en",
    system_lang_code="en"
) as client:
    with open(f"{name}.session", "w") as file:
        file.write(client.session.save())

...

```
**Traceback**
```
Request caused struct.error: 'i' format requires -2147483648 <= number <= 2147483647: InvokeWithLayerRequest(layer=133, query=InitConnectionRequest(api_id=5782194302353, device_model='Redmi Note 10', system_version='5.15.0', app_version='1.24.0', system_lang_code='en', lang_pack='', lang_code='en', query=GetConfigRequest(), proxy=None, params=None))
Traceback (most recent call last):
  File "/root/telegram-raid-botnet/sessions/add_session.py", line 15, in <module>
    with TelegramClient(
  File "/usr/local/lib/python3.10/dist-packages/telethon/helpers.py", line 184, in _sync_enter
    return loop.run_until_complete(self.__aenter__())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 713, in __aenter__
    return await self.start()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/telegrambaseclient.py", line 541, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(
  File "/usr/local/lib/python3.10/dist-packages/telethon/network/mtprotosender.py", line 176, in send
    state = RequestState(request)
  File "/usr/local/lib/python3.10/dist-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/usr/local/lib/python3.10/dist-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "/usr/local/lib/python3.10/dist-packages/telethon/tl/functions/__init__.py", line 253, in _bytes
    self.query._bytes(),
  File "/usr/local/lib/python3.10/dist-packages/telethon/tl/functions/__init__.py", line 127, in _bytes
    struct.pack('<i', self.api_id),
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by Lonami** [comment]
Your API ID must come from my.telegram.org, where it won't exceed 32 bits.
