### ISSUE TITLE
CancelledError while downloading media.

### ISSUE THREAD

**Issue by LonelyJupiter** [LonamiWebs/Telethon#3921]
Encountered "concurrent.futures._base.CancelledError" while downloading media.
Is there anything wrong with the usage of async and await in my code? I'm a newbie to the async usages..
Appreciate it if you would point out my mistakes! kudos!

**Code that causes the issue**
```

from telethon import TelegramClient, sync
from conf import config

async def get_media(channel_username,client):
    msgs = await client.get_messages(channel_username, limit=1)
    if msgs[0].media is not None:
        print(msgs[0].media)
        salt = 'latest.csv'
        cfg = config()
        filename = cfg.get_pic_path() + '/' + str(salt)
        await client.download_media(msgs[0].media, filename)

async def main():
        channel_username = await client.get_input_entity('CHANNEL_NAME')
        await get_media(channel_username,client)

if __name__ == '__main__':

    cfg = config()
    data_storage_path = cfg.getpath()
    api_id = cfg.get_API_ID()
    api_hash = cfg.get_API_HASH()
    with TelegramClient(cfg.get_TG_AUTH_FILE_NAME(), api_id, api_hash) as client:
        client.loop.run_until_complete(main())

```

**Traceback**
```


Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 339, in _update_loop
    updates = await asyncio.wait_for(self._updates_queue.get(), deadline_delay)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError


```

**Comment by Lonami** [comment]
This should only be an incorrect log message. The code should still work. Is that the case?

**Comment by LonelyJupiter** [comment]
Thx for the reply. Yeah exactly, the code still works as intended.

Lonami ***@***.***> 于 2022年9月14日周三 23:16写道：
