### ISSUE TITLE
pip error when installing last Telethon version

### ISSUE THREAD

**Issue by f1refa11** [LonamiWebs/Telethon#3923]
**Checklist**
* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip
```

**Traceback**
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-k9tr4qmo-build/setup.py", line 244, in <module>
        main(sys.argv)
      File "/tmp/pip-k9tr4qmo-build/setup.py", line 185, in main
        generate(['tl', 'errors'])
      File "/tmp/pip-k9tr4qmo-build/setup.py", line 69, in generate
        from telethon_generator.generators import\
      File "/tmp/pip-k9tr4qmo-build/telethon_generator/generators/__init__.py", line 1, in <module>
        from .errors import generate_errors
      File "/tmp/pip-k9tr4qmo-build/telethon_generator/generators/errors.py", line 5
        f.write(f"    {error.canonical_name!r}: {error.capture_name!r},\n")
                                                                         ^
    SyntaxError: invalid syntax
```

**Comment by Lonami** [comment]
Sorry but Python 3.5 is no longer supported. Please update the Python installation.

**Comment by f1refa11** [comment]
Ok, what is the latest version of telethon that supports python 3.5?

**Comment by Lonami** [comment]
v1.24.

**Comment by f1refa11** [comment]
Thanks.
