### ISSUE TITLE
No need to check if the target is a user in permission related functions anymore

### ISSUE THREAD

**Issue by fossifer** [LonamiWebs/Telethon#3931]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Description**
Users are now able to send messages as a channel to remain anonymous, while group admins can also impose a restriction/ban directly on such channels, which forces participants to use their personal account. So there is no need to check `ty != helpers._EntityType.USER` and raise ValueError anymore if target is a channel since it is legitimate now. This applies to `edit_permissions` and `kick_participant`. Not sure for `edit_admin` (can channels become group admin now?).

**Code that causes the issue**
```python
from telethon import TelegramClient, functions, types
from telethon.tl.types import Channel

client = TelegramClient(...)

@client.on(events.NewMessage)
async def message_handler(event):
    chat_id = event.chat_id
    sender = await event.get_sender()
    if type(sender) is Channel:
        # Ban the user from sending messages as a channel
        # This causes the error
        await client.edit_permissions(entity=chat_id, user=sender, view_messages=False)
        # ... but this works!
        await client(functions.channels.EditBannedRequest(
            channel=chat_id,
            participant=sender,
            banned_rights=types.ChatBannedRights(until_date=None, view_messages=True)
        ))

client.start()
client.run_until_disconnected()
```

**Traceback**
```
Traceback (most recent call last):
  File "<venv path>/telethon/lib/python3.9/site-packages/telethon/client/updates.py", line 451, in _dispatch_update
    await callback(event)
  File "code.py", line 30, in message_handler
    await client.edit_permissions(entity=chat_id, user=sender, view_messages=False)
  File "<venv path>/telethon/lib/python3.9/site-packages/telethon/client/chats.py", line 1141, in edit_permissions
    raise ValueError('You must pass a user entity')

```

**Comment by fossifer** [comment]
My bad, in the latest version it works fine.
