### ISSUE TITLE
sendReactionRequest new reactions (non-premium)

### ISSUE THREAD

**Issue by nkhono** [LonamiWebs/Telethon#3932]
When using new reactions such as 🏆 to react, it gives out an error.

Used: sendReactionRequest

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\daman\Desktop\m.py", line 13, in <module>
    result = client(functions.messages.SendReactionRequest(
  File "C:\Users\daman\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\daman\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\daman\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\daman\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.ReactionInvalidError: Invalid reaction provided (only emoji are allowed) (caused by SendReactionRequest)

```

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
