### ISSUE TITLE
AuthKeyUnregisteredError

### ISSUE THREAD

**Issue by Ykyki4** [LonamiWebs/Telethon#3960]
I try to use telthon to send a message after a form in django, and i get this error. I tried to put my number, but it gives me the same error. Also some times I get the database is locked error. I tried to put the function send_message to another py file. and i get error with loops and Threads.

**Code that causes the issue**
```python
def get_message():
    request = Request.objects.all().last()
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    client = TelegramClient('anon', 'id', 'hash', loop=loop)
    client.loop.run_until_complete(send_message(client, request))
    
async def send_message(client, request):
    await client.connect()
    phone = request.phone
    await client.send_message(f'{phone}', 'Hello')

def index(request):
    course_left_top = Course.objects.all().first()
    course_left_bottom = Course.objects.all().last()
    course_right_top = Course.objects.all().last()
    course_right_bottom = Course.objects.all().first()
    form = RequestForm()
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            form.save()
            get_message()  
```
**Traceback**
```
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ogure\Documents\GitHub\SoftLine\main\views.py", line 31, in index
    get_message()
  File "C:\Users\ogure\Documents\GitHub\SoftLine\main\views.py", line 14, in get_message
    client.loop.run_until_complete(send_message(client, request))
  File "C:\Users\ogure\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\ogure\Documents\GitHub\SoftLine\main\views.py", line 19, in send_message
    await client.send_message(f'{phone}', 'Hello')
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\messages.py", line 823, in send_message
    entity = await self.get_input_entity(entity)
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\users.py", line 437, in get_input_entity
    await self._get_entity_from_string(peer))
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\users.py", line 529, in _get_entity_from_string
    for user in (await self(
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.AuthKeyUnregisteredError: The key is not registered in the system (caused by GetContactsRequest)
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ogure\Documents\GitHub\SoftLine\main\views.py", line 31, in index
    get_message()
  File "C:\Users\ogure\Documents\GitHub\SoftLine\main\views.py", line 14, in get_message
    client.loop.run_until_complete(send_message(client, request))
  File "C:\Users\ogure\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\ogure\Documents\GitHub\SoftLine\main\views.py", line 19, in send_message
    await client.send_message(f'{phone}', 'Hello')
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\messages.py", line 823, in send_message
    entity = await self.get_input_entity(entity)
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\users.py", line 437, in get_input_entity
    await self._get_entity_from_string(peer))
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\users.py", line 529, in _get_entity_from_string
    for user in (await self(
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\ogure\.virtualenvs\SoftLine-4m0tH3vg\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.AuthKeyUnregisteredError: The key is not registered in the system (caused by GetContactsRequest)
```

**Comment by Lonami** [comment]
Telethon uses `asyncio` which means using it with `threading` (and by extension `django`) is not trivial. Unfortunately this is not an issue in the library, and since there's nothing for me to fix here, I will be closing this issue.

The general recommendation is to use an `asyncio` alternative to `django`, or be very careful with `threading`. The documentation has a note on this.
