### ISSUE TITLE
Getting user limited by Telegram for DM sends - guidelines? [Telegram issue]

### ISSUE THREAD

**Issue by dsldsl** [LonamiWebs/Telethon#397]
I'm having a different-but-similar issue as [issue 297](https://github.com/LonamiWebs/Telethon/issues/297) -- it's more of a Telegram API / spam block issue. I'm unsure how to get support from them, so wanted to ask this community.

(Is there a good place to get Telegram support for questions around how to stay within guidelines and not get user limited for sending DMs?)

I am an admin in a large superchat room.  We’re working to help protect our users from fraud by having our team members reach out 1:1 to make sure they know to watch out for scammers.  We’re using the Telethon to help id and DM message users we think may be at risk.  I've followed different patterns with a few different admins and all get limited after around 50 DMs.  I think that we’re just hitting some automated spam filter or rate limit (vs user reporting) because the users we message all seem very engaged and appreciative.  

Thank you for any tips or directional guidance!

**Comment by Lonami** [comment]
> Is there a good place to get Telegram support for questions around how to stay within guidelines and not get user limited for sending DMs

The rules are mostly simple: don't talk to strangers as they can report you, and don't add strangers to groups or channels as they can report you too.

> We’re using the Telethon to help id and DM message users we think may be at risk.

That itself may be risky. Perhaps the best option would just be to mention them in the group to warn them, after all, they should have the mention button to jump to the mention and see your warning, without risking them to block whatever account you're using.

> I think that we’re just hitting some automated spam filter or rate limit (vs user reporting)

Hm, I have no idea about that so perhaps it could be that way. But if it exists, I'm unaware of it.

> `telethon.errors.rpc_errors.RPCError: PEER_FLOOD (code 400)`

Consider upgrading, the error should now be `PeerFloodError`.

**Comment by spam1712** [comment]
please suggest, how to except the error and go on with the program?

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 67, in monitorandsend
    result = client.send_message(adtarget,tgmessage)
  File "/home/kali/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 369, in send_message
    result = self(request)
  File "/home/kali/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 461, in __call__
    sender, call_receive, update_state, *requests
  File "/home/kali/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 518, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PeerFloodError`

**Comment by Lonami** [comment]
Well currently there's no way to globally capture the errors unless you define your custom function and use that instead. You see, the library can't know your control flow or what you would want to do in certain cases so I can't just "go on with the program". I'm open for suggestions though.

**Comment by spam1712** [comment]
kk thx figured it

`

from telethon.errors.rpc_error_list import PeerFloodError


			except PeerFloodError:
				print('')
				print('EXCEPTION')
				print('')	`

**Comment by Lonami** [comment]
More on this as the wiki link on #297 is now broken: http://telethon.readthedocs.io/en/latest/extra/troubleshooting/deleted-limited-or-deactivated-accounts.html.

**Comment by ogcrypto** [comment]
Sorry, you can only send messages to mutual contacts at the moment. More info »
Click for technical details

please help me i keep on getting this issue even when the time i was promise my account will be release

**Comment by jjhesk** [comment]
how to avoid this error?

**Comment by jjhesk** [comment]
how to avoid this error?

**Comment by Lonami** [comment]
The link from https://github.com/LonamiWebs/Telethon/issues/397#issuecomment-357892498 is (again) broken, the new one is https://docs.telethon.dev/en/latest/quick-references/faq.html#my-account-was-deleted-limited-when-using-the-library.
