### ISSUE TITLE
FloodWaitError again

### ISSUE THREAD

**Issue by vovabush** [LonamiWebs/Telethon#3987]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events
import json


chats = None
aggregatorChannel = None
api_id = None
api_hash = None

try:
  with open('config.json') as json_file:
    config = json.load(json_file)
    chats = tuple((config["channels"]))
    aggregatorChannel = config["aggregator"]
    api_id = config["api_id"]
    api_hash = config["api_hash"]
except Exception as e:
  print(str(e))

client = TelegramClient("session_name", api_id, api_hash)
client.start()

@client.on(events.NewMessage(chats=chats))
async def my_event_handler(event):
  if (event.poll is None):
    await client.forward_messages(aggregatorChannel, event.message)

with client:
    client.run_until_disconnected()

```

**Traceback**
```
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/opt/lib/python3.10/site-packages/telethon/client/updates.py", line 268, in _update_loop
    await self._dispatch_update(updates_to_dispatch.popleft())
  File "/opt/lib/python3.10/site-packages/telethon/client/updates.py", line 488, in _dispatch_update
    await builder.resolve(self)
  File "/opt/lib/python3.10/site-packages/telethon/events/common.py", line 99, in resolve
    await self._resolve(client)
  File "/opt/lib/python3.10/site-packages/telethon/events/newmessage.py", line 93, in _resolve
    await super()._resolve(client)
  File "/opt/lib/python3.10/site-packages/telethon/events/common.py", line 103, in _resolve
    self.chats = await _into_id_set(client, self.chats)
  File "/opt/lib/python3.10/site-packages/telethon/events/common.py", line 33, in _into_id_set
    chat = await client.get_input_entity(chat)
  File "/opt/lib/python3.10/site-packages/telethon/client/users.py", line 437, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/opt/lib/python3.10/site-packages/telethon/client/users.py", line 553, in _get_entity_from_string
    result = await self(
  File "/opt/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/opt/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 40155 seconds is required (caused by ResolveUsernameRequest)
Traceback (most recent call last):
  File "/opt/root/aggregator.py", line 55, in <module>
    client.run_until_disconnected()
  File "/opt/lib/python3.10/site-packages/telethon/client/updates.py", line 93, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "/opt/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
  File "/opt/lib/python3.10/site-packages/telethon/client/updates.py", line 35, in _run_until_disconnected
    raise self._updates_error
  File "/opt/lib/python3.10/site-packages/telethon/client/updates.py", line 268, in _update_loop
    await self._dispatch_update(updates_to_dispatch.popleft())
  File "/opt/lib/python3.10/site-packages/telethon/client/updates.py", line 488, in _dispatch_update
    await builder.resolve(self)
  File "/opt/lib/python3.10/site-packages/telethon/events/common.py", line 99, in resolve
    await self._resolve(client)
  File "/opt/lib/python3.10/site-packages/telethon/events/newmessage.py", line 93, in _resolve
    await super()._resolve(client)
  File "/opt/lib/python3.10/site-packages/telethon/events/common.py", line 103, in _resolve
    self.chats = await _into_id_set(client, self.chats)
  File "/opt/lib/python3.10/site-packages/telethon/events/common.py", line 33, in _into_id_set
    chat = await client.get_input_entity(chat)
  File "/opt/lib/python3.10/site-packages/telethon/client/users.py", line 437, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/opt/lib/python3.10/site-packages/telethon/client/users.py", line 553, in _get_entity_from_string
    result = await self(
  File "/opt/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/opt/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 40155 seconds is required (caused by ResolveUsernameRequest)

```

**Description**
My code worked successfully for half a year. All of a sudden this error started happening. I reinstalled the system, re-authorized, telegram works on other devices. What could be the problem and how fix it?

**Comment by Lonami** [comment]
This is working as intended. Telegram applies flood limits to some requests and Telethon is raising them as an error. It's not something Telethon can fix.

Use IDs as the filter for events if you wouldn't like to use usernames, which must be resolved when not in cache.

**Comment by vovabush** [comment]
Thanks for the quick response. Can you share an example how to use ids as filters please?
Isn't 
```Python
@client.on(events.NewMessage(chats=chats))
``` 
line what I need?

**Comment by Lonami** [comment]
If chats contains usernames and those usernames are not in cache Telethon will need to make a request, which is expensive, to convert them to their integer IDs. You can bypass this round-trip by passing the integer IDs yourself directly.

**Comment by vovabush** [comment]
I changed the username of the channel to their identifier and everything began to work. Thanks for the help.
