### ISSUE TITLE
`send_message` sometimes raises `struct.error: required argument is not an integer`

### ISSUE THREAD

**Issue by MaskRay** [LonamiWebs/Telethon#402]
`send_message(to.peer, text, reply_to=reply_to)` sometimes raises `struct.error: required argument is not an integer`

```
Traceback (most recent call last):
  File "/usr/bin/telegramircd", line 440, in wait
    send()
  File "/usr/bin/telegramircd", line 432, in send
    web.msg(client, to, to.privmsg_text, to.privmsg_reply)
  File "/usr/bin/telegramircd", line 324, in msg
    msg = self.proc.send_message(to.peer, text, reply_to=reply_to)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/telegram_client.py", line 369, in send_message
    result = self(request)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 461, in __call__
    sender, call_receive, update_state, *requests
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 481, in _invoke
    sender.send(*requests)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 91, in send
    self._send_message(message)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 133, in _send_message
    + bytes(message)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/tl/tl_message.py", line 17, in __bytes__
    body = GzipPacked.gzip_if_smaller(self.request)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/tl/gzip_packed.py", line 22, in gzip_if_smaller
    data = bytes(request)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/tl/message_container.py", line 17, in __bytes__
    ) + b''.join(bytes(m) for m in self.messages)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/tl/message_container.py", line 17, in <genexpr>
    ) + b''.join(bytes(m) for m in self.messages)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/tl/tl_message.py", line 17, in __bytes__
    body = GzipPacked.gzip_if_smaller(self.request)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/tl/gzip_packed.py", line 22, in gzip_if_smaller
    data = bytes(request)
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/tl/functions/messages.py", line 3936, in __bytes__
    bytes(self.peer),
  File "/home/ray/.local/lib/python3.6/site-packages/telethon/tl/types/__init__.py", line 9056, in __bytes__
    struct.pack('<q', self.access_hash),
struct.error: required argument is not an integer
```

Really awesome project. I have made my IRC <-> Telegram gateway (https://github.com/MaskRay/telegramircd) to use Telethon rather than telegram-cli (which leaks memory and often get stuck so I have to restart it every one day or two).

**Comment by Lonami** [comment]
Thanks for the kind words. This issue should have been fixed on #354 already (relevant commit https://github.com/LonamiWebs/Telethon/commit/05f7f076d53ac93e929f4b47429770b1884216f9) although I can't recall having pushed to PyPi yet since I always like to push several features together. Please confirm that your session file has `null`'s in it, this is what triggers the bug.
