### ISSUE TITLE
Fatal error handling updates (this is a bug in Telethon, please report it)

### ISSUE THREAD

**Issue by s84662355** [LonamiWebs/Telethon#4022]
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/utils.py", line 1024, in get_peer_id
    peer = get_peer(peer)
           ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast dict to any kind of Peer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/client/updates.py", line 394, in _update_loop
    updates_to_dispatch.extend(self._preprocess_updates(processed, users, chats))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/client/updates.py", line 404, in _preprocess_updates
    entities = {utils.get_peer_id(x): x
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/client/updates.py", line 404, in <dictcomp>
    entities = {utils.get_peer_id(x): x
                ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/utils.py", line 1026, in get_peer_id
    _raise_cast_fail(peer, 'int')
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast dict to any kind of int.

**Comment by s84662355** [comment]
def get_peer(peer):
    try:
        if isinstance(peer, int):
            pid, cls = resolve_id(peer)
            return cls(pid)
        if isinstance(peer,dict) and 'id' in peer and peer['id'] != 0:
            return types.PeerUser(peer['id'])
        elif peer.SUBCLASS_OF_ID == 0x2d45687:
            return peer
        elif isinstance(peer, (
                types.contacts.ResolvedPeer, types.InputNotifyPeer,
                types.TopPeer, types.Dialog, types.DialogPeer)):
            return peer.peer
        elif isinstance(peer, types.ChannelFull):
            return types.PeerChannel(peer.id)

**Comment by s84662355** [comment]
if isinstance(peer,dict) and 'id' in peer and peer['id'] != 0:
            return types.PeerUser(peer['id'])

**Comment by Lonami** [comment]
Please follow the issue template. What was the code used to trigger this error?

**Comment by Heryanto77** [comment]
Unknown error: A wait of 3541 seconds is required (caused by InviteToChannelRequest)

**Comment by Lonami** [comment]
Closing due to the lack of response and details.
