### ISSUE TITLE
Using pathlib.Path to download contact media leads to exception

### ISSUE THREAD

**Issue by d-Rickyy-b** [LonamiWebs/Telethon#4027]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.
---

To begin with: I only reproduced this issue myself on v1.24.0, because there have been issues with my project (I couldn't figure out how to use StateCache in order to download all available messages, starting from pts=0) on consecutive versions of telethon. But I linked the lines of code which cause the issue below. I don't see any fix for more recent versions.

### Description
When using an instance of `pathlib.Path` in `download_media()`, telethon will fail to download contact files.
This happens because there is no check if the file attribute is an instance of type `pathlib.Path`, as it is done in the other `_download_xyz` functions.

**For example `_download_file()`**:
https://github.com/LonamiWebs/Telethon/blob/1f8b59043b033476b2d5bf1a0e9b2bc8440511ca/telethon/client/downloads.py#L526-L537

**Compared to `_download_contact()`**:
https://github.com/LonamiWebs/Telethon/blob/1f8b59043b033476b2d5bf1a0e9b2bc8440511ca/telethon/client/downloads.py#L921-L930

The issue probably also persists for `_download_web_document()`:
https://github.com/LonamiWebs/Telethon/blob/1f8b59043b033476b2d5bf1a0e9b2bc8440511ca/telethon/client/downloads.py#L954-L964

### Solution (?)
Other functions used the staticmethod `_get_proper_filename()`. I was not sure when to use this. Otherwise I would have created a PR for this myself.

I assume that adding a simple type check for `pathlib.Path` should fix the issue.

```python
elif isinstance(file, pathlib.Path):
    file = str(file.absolute())
```

---
**Code that causes the issue**
```python
import asyncio
import logging
from pathlib import Path
from telethon import TelegramClient, events

async def new_message_handler(event):
    m = event.message
    media_path = (Path.cwd() / "media").absolute()

    try:
        await m.download_media(file=media_path)
    except Exception as e:
        logging.error(f"Couldn't download media for message id {m.id}: {e}")

async def wait_catch_up(bot: TelegramClient):
    # Wait until we have caught up with all updates.
    # Prevents the script from exiting before all downloads are finished.
    await bot.catch_up()
    while bot._updates_queue:
        await asyncio.wait(bot._updates_queue, return_when=asyncio.ALL_COMPLETED)

async def main(bot: TelegramClient, bot_token):
    await bot.start(bot_token=bot_token)

    bot.add_event_handler(new_message_handler, events.NewMessage)

    try:
        await wait_catch_up(bot)
    except Exception as e:
        logging.error("Exception while running bot:", e)
        return

    await bot.disconnect()
```

**Traceback**
```
Traceback (most recent call last):

File "/home/rico/projects/test/test.py", line 33, in new message_handler
	await m.download_media(file=media_path)
File "/home/rico/.local/lib/python3.10/site-packages/telethon/tl/custom/message.py", line 837, in download_media
	return await self._client.download_media(self, *args, **kwargs)
File "/home/rico/.local/lib/python3.10/site-packages/telethon/client/downloads.py", line 419, in download_media
	return self._download_contact(
File "/home/rico/.local/lib/python3.10/site-packages/telethon/client/downloads.py", line 931, in _download_contact
	f.write(result)
AttributeError: 'PosixPath' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
	File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
		msg = self.format(record)
	File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
		return fmt.format(record)
	File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
		record.message = record.getmessage()
	File "/usr/lib/python3.10/logging/__init__.py", line 368, in getmessage
		msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
	File "/home/rico/projects/test/test.py", line 140, in <module>
		asyncio.run(main(client, args.token))
	File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
		return loop.run_until_complete(main)
	File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
		self._run_forever()
	File " /usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
		self._run_once()
	File "/usr/iib/python3.10/asyncio/base_events.py", line 1896, in _run_once
		handle._run()
	File " /usr/lib/python3.10/asyncio/events.py", line 80, in _run
		self._context.run(self._callback, *self._args)
	File "/home/rico/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
		await callback(event)
	File "/home/rico/projects/test/test.py", line 35, in new message_handler
		logging.error("Couldn't download media: ", e)
Message: "Couldn't download media:"
Arguments: (AttributeError("'PosixPath' object has no attribute 'write'"),)
```

**Comment by Lonami** [comment]
Thanks for the very detailed report. It should be fixed now.
