### ISSUE TITLE
TimeoutError: Fatal error handling updates (this is a bug in Telethon, please report it)

### ISSUE THREAD

**Issue by igorivaniuk** [LonamiWebs/Telethon#4043]
v1.27.0 version

**Traceback**
```
client.updates:Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telethon/client/updates.py", line 320, in _update_loop
    diff = await self(get_diff)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.TimeoutError: Timeout while fetching data (caused by GetChannelDifferenceRequest)
```

**Comment by Lonami** [comment]
Thanks, this will be fixed in the next version.
