### ISSUE TITLE
RuntimeError: <MTProtoSender._send_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py:462> got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by arynyklas** [LonamiWebs/Telethon#4048]
**Checklist**

* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
from asyncio import run as run_asyncio

async def main():
    client = TelegramClient(...)
    await client.connect()

run_asyncio(main())
```

Runs on Ubuntu Ubuntu 20.04.4 LTS (focal)
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0] on linux

**Traceback**
```
^CTraceback (most recent call last):
  File "main.py", line 261, in <module>
    run_asyncio(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<MTProtoSender._send_loop() done, defined at /usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py:444> exception=RuntimeError("Task <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py:462>> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 462, in _send_loop
    batch, data = await self._send_queue.get()
  File "/usr/local/lib/python3.8/dist-packages/telethon/extensions/messagepacker.py", line 48, in get
    await self._ready.wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py:462>> got Future <Future pending> attached to a different loop
```

**Comment by Lonami** [comment]
The code you posted does not match the exception traceback. Make sure you are not reusing the client across `asyncio` loops. Remember, `asyncio.run` creates a new `asyncio` event loop every time. If you had connected the client in a different loop, and then try using it from a different one, it will fail.

Closing as the issue seems to be in your code and not the library.

**Comment by arynyklas** [comment]
It was my network's problem
Solved
