### ISSUE TITLE
Session files cannot be used

### ISSUE THREAD

**Issue by Kali1nee** [LonamiWebs/Telethon#4053]
I use the usual code to authorize and send a message in telegram
```
from telethon.sync import TelegramClient, events

api_id = '...'
api_hash = '...'

with TelegramClient('sessions/Fetish', api_id, api_hash) as client:
   await client.send_message('me', 'mmm')
```
Then comes the endless waiting

```
Server sent a very new message with ID 7206282712111363077, ignoring
Server sent a very new message with ID 7206282712140118017, ignoring
```

And when I stop the script, the following error is returned
```
Traceback (most recent call last):
  File "C:\Users\x\PycharmProjects\pythonProject\fl_projects\first order\Multi_tools.py", line 20, in <module>
    main()
  File "C:\Users\x\PycharmProjects\pythonProject\fl_projects\first order\Multi_tools.py", line 16, in main
    run(start())
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027FBFCB1480>
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by Lonami** [comment]
Make sure the session was created by Telethon as is not being used by anyone else. Make sure your system time is correct. If it still occurs, make sure there's no MITM.

The traceback you posted looks normal (except for the runtime error, but that seems to be a problem in the Python implementation of `asyncio` under Windows).
