### ISSUE TITLE
Large Files Download: ConnectionResetError: The server has closed the connection.

### ISSUE THREAD

**Issue by naeloob** [LonamiWebs/Telethon#406]
I'm using Telethon v0.15.4 with Telebackup, and when i try to download a big file (1Gb), it fails with this message : 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\wip\TeleBackup\backuper.py", line 419, in backup_media_thread
    msg.media, file=output)
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\telegram_client.py", line 821, in download_media
    media, file, date, progress_callback
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\telegram_client.py", line 880, in _download_document
    progress_callback=progress_callback
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\telegram_bare_client.py", line 716, in download_file
    input_location, offset, part_size
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\telegram_bare_client.py", line 429, in __call__
    sender, call_receive, update_state, *requests
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\telegram_bare_client.py", line 484, in _invoke
    sender.receive(update_state=update_state)
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\network\mtproto_sender.py", line 108, in receive
    body = self.connection.recv()
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\network\connection.py", line 147, in _recv_tcp_full
    body = self.read(packet_len - 12)
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\network\connection.py", line 204, in _read_plain
    return self.conn.read(length)
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\extensions\tcp_client.py", line 128, in read
    self._raise_connection_reset()
  File "D:\Soft\WinPython-32bit-3.5.2.3Zero\python-3.5.2\lib\site-packages\telethon\extensions\tcp_client.py", line 139, in _raise_connection_reset
    raise ConnectionResetError('The server has closed the connection.')
ConnectionResetError: The server has closed the connection.
```
It happens at diferent downloaded sizes 1XMb, 2XMb, 4XMb...
Any clue where to look?

PD : Now you can see why the resume "hack" :)

**Comment by Lonami** [comment]
1GB is a kinda big file (and Telebackup a kinda old project). If I remember correctly it uses a background thread to download files so it may be needing to create a temporary connection for every chunk (I need to change that, I just haven't though how or of a better alternative yet). There are two other issues open regarding both downloading files fails, and connection reset, so I think I'm going to close this one.
