### ISSUE TITLE
EditInlineBotMessageRequest fails if the dc id in InputBotInlineMessageID is other than the dc id in the user account

### ISSUE THREAD

**Issue by nitanmarcel** [LonamiWebs/Telethon#4064]
If you're trying to edit an message sent via inline query using `EditInlineBotMessageRequest` the message gets edited unless if the group it's on a different dc. If the dc id is different, in my case I'm on dc `4` but the message has been sent in a group in the dc `2` the request will fail.

**Checklist**

* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python

# Needs Inline mode and feedback set from BotFather

from telethon.sync import TelegramClient, events
from telethon.tl.functions.messages import EditInlineBotMessageRequest
from telethon.tl.types import UpdateBotInlineSend
client = TelegramClient('bot', api_id,
                        api_hash)

client.start(bot_token=bot_token)

@client.on(events.InlineQuery())
async def inline_uery(event):
    await event.answer([builder.article('Click me', text='Click me', buttons=[Button.inline('Please click me')])])

@client.on(events.Raw(UpdateBotInlineSend))
async def inline_send(event):
    await client(EditInlineBotMessageRequest(
        id=event.msg_id,
        message='text',
        no_webpage=True,
        media=None,
        reply_markup=None,
        entities=None
    ))

```

**Traceback**
```
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7212648782228001596 to SetInlineBotResultsRequest (7faef57b35b0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 252 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7212648782229561808 to MsgsAck (7faef57b3a60)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 44 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 7212648782228001596
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Handling update Updates
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7212648837106924208 to EditInlineBotMessageRequest (7faef5744a00)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 96 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7212648837108136328 to MsgsAck (7faef57b3580)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 44 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 7212648837106924208
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7212648837323389204 to MsgsAck (7faef57b3490)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7212648837324319036 to MsgsAck (7faef55f46a0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
ERROR:telethon.client.updates:Unhandled exception on test
Traceback (most recent call last):
  File "/home/nitamarcel/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "/home/nitamarcel/pcap/tggpt4/bot.py", line 211, in test
    await client(EditInlineBotMessageRequest(
  File "/home/nitamarcel/.local/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/nitamarcel/.local/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.MessageIdInvalidError: The specified message ID is invalid or you can't do that operation on such message (caused by EditInlineBotMessageRequest)

```

**Comment by nitanmarcel** [comment]
As Lonami mentioned in telegram, __telethon doesn't analyze outgoing requests to reconnect to dcs__. So I had to manually change the dc myself then come back to it once the request was sent.

Fixed code:


```
# Needs Inline mode and feedback set from BotFather

from telethon.sync import TelegramClient, events
from telethon.tl.functions.messages import EditInlineBotMessageRequest
from telethon.tl.types import UpdateBotInlineSend
client = TelegramClient('bot', api_id,
                        api_hash)

client.start(bot_token=bot_token)

@client.on(events.InlineQuery())
async def inline_uery(event):
    await event.answer([builder.article('Click me', text='Click me', buttons=[Button.inline('Please click me')])])

@client.on(events.Raw(UpdateBotInlineSend))
async def inline_send(event):
    request = EditInlineBotMessageRequest(
        id=event.msg_id,
        message='text',
        no_webpage=True,
        media=None,
        reply_markup=None,
        entities=None
    )
    exported = client.session.dc_id != event.msg_id.dc_id
    if exported:
        try:
            sender = await client._borrow_exported_sender(event.msg_id.dc_id)
            await client._call(sender, request)
        finally:
            await client._return_exported_sender(sender)
    else:
        await client(request)
```

**Comment by nitanmarcel** [comment]
Fixed, can't remember what I did wrong but `event.edit` works

**Comment by CatchingStars** [comment]
Sorry for bothering, but when is @client.on(events.Raw(UpdateBotInlineSend)) supposed to trigger? 
For me the following function never runs.

I am trying to catch the message the user generates via inline and edit it, but I can't find any way neither to access that message, nor to understand when it's sent.
