### ISSUE TITLE
Telethon Bug reporting 

### ISSUE THREAD

**Issue by 31onMusk** [LonamiWebs/Telethon#4097]
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "C:\Users\Elon Musk\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\updates.py", line 320, in _update_loop
    diff = await self(get_diff)
  File "C:\Users\Elon Musk\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Elon Musk\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
  File "C:\Users\Elon Musk\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\network\mtprotosender.py", line 625, in _handle_rpc_result
    result = state.request.read_result(reader)
  File "C:\Users\Elon Musk\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\tl\tlobject.py", line 219, in read_result
    return reader.tgread_object()
  File "C:\Users\Elon Musk\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\extensions\binaryreader.py", line 142, in tgread_object
    return clazz.from_reader(self)
  File "C:\Users\Elon Musk\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\tl\types\updates.py", line 78, in from_reader
    _x = reader.tgread_object()
  File "C:\Users\Elon Musk\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\extensions\binaryreader.py", line 140, in tgread_object
    raise error
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 8261ac61. Most likely, a TLObject was trying to be read when it should not be read. Remaining bytes: b"a\xaca\x82@!\x04\x00\x8a7\x99k\x00\x00\x00\x00\x8b\xfa0\xca\x06\xact\xe3Q\xd0\x92\xd0\xb7\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xbf\xd0\xbe\xd0\xb4\xd0\xbf\xd0\xb8\xd1\x81\xd0\xba\xd0\xb8 \xf0\x9f\x8d\x80 \xd1\x80\xd0\xb5\xd0\xb0\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8 \xf0\x9f\x91\x8d \xd0\xbf\xd1\x80\xd0\xbe\xd1\x81\xd0\xbc\xd0\xbe\xd1\x82\xd1\x80\xd1\x8b\xf0\x9f\x91\x80\x00\x00\nvzaimnostb\x00\x11\x1cn\x1c\x02\x00\x00\x00\xfe\xce1\x1bR\x91`I\x0c\x01\x08\x08\xb1\xdf\xa7\xe1E\x14U\x1dG\x00\x00\x00\x02\x00\x00\x00\xabeEd\x18\x04\x12\x9f\xfc\x05\x02\x00\xff\xff\xff\x7f\x15\xc4\xb5\x1c\x02\x00\x00\x00\xb0\xec\xf6?K\x00\x00\x02\x92$fO\x00\x00\x00\x00\xeaP\xc4elcv\x12\x08\xd0\x9c\xd0\xb0\xd0\xba\xd1\x81\x00\x00\x00\rusername02813\x00\x00I9\xb9\xed\x03tEd\xb0\xec\xf6?k\x00\x00\x02\xf9\x96Xn\x00\x00\x00\x00\x95\xe8?\xd0\xb5\x01\xca\xe4\x01G\x00\x00\x06Ilytaf\x00\x06\xf7\xd1\x82\x02\x00\x00\x00\xa3\xc51\x1b\xd9F\x88I\x14\x01\x08\x08\xcf\xfd\xc8;I'\x8cn\x1e\xbe\xbfJ(\xa2\xae\xc1s\x00\x00\x00\x02\x00\x00\x00\xf1Bo\xe2"

**Comment by Lonami** [comment]
Please follow the issue template. You seem to be out of date.
