### ISSUE TITLE
Error when using SetChatAvailableReactionsRequest

### ISSUE THREAD

**Issue by DanielWorker** [LonamiWebs/Telethon#4099]
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

```python
reactions = ChatReactionsSome(['🤩', '🤷‍♂', '⚡', '🦄', '👌', '🙏', '🤔', '🤮', '🎉', '💩', '🙈', '💊', '✍', '🤯', '😂', '❤'])
        return await self.tg_client(functions.messages.SetChatAvailableReactionsRequest(
            peer=self.chat.id,
            available_reactions=reactions
        ))
```

**Traceback**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "/usr/local/lib/python3.9/dist-packages/telethon/tl/functions/messages.py", line 6718, in _bytes
    self.available_reactions._bytes(),
  File "/usr/local/lib/python3.9/dist-packages/telethon/tl/types/__init__.py", line 5582, in _bytes
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.reactions)),b''.join(x._bytes() for x in self.reactions),
  File "/usr/local/lib/python3.9/dist-packages/telethon/tl/types/__init__.py", line 5582, in <genexpr>
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.reactions)),b''.join(x._bytes() for x in self.reactions),
AttributeError: 'str' object has no attribute '_bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bot/src/main.py", line 96, in runner
    await getattr(self.manage, func)()
  File "/home/bot/src/manage.py", line 479, in message
    await self.chat_message()
  File "/home/bot/src/manage.py", line 2323, in chat_message
    return await self.enable_reactions()
  File "/home/bot/src/manage.py", line 2095, in enable_reactions
    return await self.tg_client(functions.messages.SetChatAvailableReactionsRequest(
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 63, in _call
    future = sender.send(request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/network/mtprotosender.py", line 181, in send
    state = RequestState(request)
  File "/usr/local/lib/python3.9/dist-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/usr/local/lib/python3.9/dist-packages/telethon/tl/tlobject.py", line 200, in __bytes__
    raise TypeError('a TLObject was expected but found something else')
TypeError: a TLObject was expected but found something else
```

**Comment by Lonami** [comment]
The error is correct. `ChatReactionsSome` expects a list of [`Reaction`](https://tl.telethon.dev/types/reaction.html), as of the current version.

Raw API is not guaranteed to be stable across minor versions of the library.
