### ISSUE TITLE
Weird behavior on event.delete()

### ISSUE THREAD

**Issue by dglubokov** [LonamiWebs/Telethon#4129]
### Code that causes the issue

```python
API_ID = int(os.environ["TELEGRAM_API_ID"])
API_HASH = os.environ["TELEGRAM_API_HASH"]
client = TelegramClient("mimic", API_ID, API_HASH).start(bot_token=os.environ["TELEGRAM_BOT_TOKEN"])

@client.on(events.CallbackQuery(data=b"select"))
@client.on(events.NewMessage(pattern="/select"))
async def select_command(event: Union[Message, events.NewMessage]):
    sender = await event.get_sender()

    # TODO: Weird bug.
    await event.delete()
```

### Expected behavior

Successfully deleted message

### Actual behavior

Crashes with an error. It's strange that for the other button everything works fine. It is also strange that this happens only for one user. It seems that Telegram began to support large numbers and the telethon cannot successfully parse the number above.

### Traceback

```
	
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
2023-06-09 03:06:57	
                                                                 ^^^^^^^^^^^^^^^^^^^^
2023-06-09 03:06:57	
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(struct.pack('<i', x) for x in self.id),
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/tl/functions/messages.py", line 546, in <genexpr>
2023-06-09 03:06:57	
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-09 03:06:57	
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(struct.pack('<i', x) for x in self.id),
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/tl/functions/messages.py", line 546, in _bytes
2023-06-09 03:06:57	
           ^^^^^^^^^^^^^
2023-06-09 03:06:57	
    return self._bytes()
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/tl/tlobject.py", line 194, in __bytes__
2023-06-09 03:06:57	
                ^^^^^^^^^^^^^^
2023-06-09 03:06:57	
    self.data = bytes(request)
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/network/requeststate.py", line 17, in __init__
2023-06-09 03:06:57	
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-09 03:06:57	
    state = RequestState(req, after=ordered and state)
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 196, in send
2023-06-09 03:06:57	
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-09 03:06:57	
    future = sender.send(request, ordered=ordered)
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/client/users.py", line 63, in _call
2023-06-09 03:06:57	
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-09 03:06:57	
    return await self._call(self._sender, request, ordered=ordered)
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
2023-06-09 03:06:57	
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-09 03:06:57	
    return await self([functions.messages.DeleteMessagesRequest(
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/client/messages.py", line 1297, in delete_messages
2023-06-09 03:06:57	
    await client.delete_messages(event.chat_id, [event.id])
2023-06-09 03:06:57	
  File "/app/src/selection.py", line 29, in select
2023-06-09 03:06:57	
    await select(client=client, async_session=async_session, event=event)
2023-06-09 03:06:57	
  File "/app/./main.py", line 87, in select_command
2023-06-09 03:06:57	
    await callback(event)
2023-06-09 03:06:57	
  File "/usr/local/lib/python3.11/site-packages/telethon/client/updates.py", line 543, in _dispatch_update
2023-06-09 03:06:57	
Traceback (most recent call last):
2023-06-09 03:06:57	
Unhandled exception on select_command
2023-06-09 03:06:57	
Request caused struct.error: 'i' format requires -2147483648 <= number <= 2147483647: [<telethon.tl.functions.messages.DeleteMessagesRequest object at 0x7f238ba824d0>]
```

### Telethon version

1.28.5

### Python version

3.11

### Operating system (including distribution name and version)

Linux (Kubernetes Pod)

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by dglubokov** [comment]
ChatGPT-4 Hypothesis

> The error message 'i' format requires -2147483648 <= number <= 2147483647 is an indication that the function struct.pack('<i', x) is being called with a value x that is outside the valid range for an 'int' type in C, which is from -2147483648 to 2147483647.
> 
> In this specific case, the error occurs in the line b''.join(struct.pack('<i', x) for x in self.id),. This code is attempting to pack the elements of self.id as 'int' and join them together. However, it seems that one or more elements in self.id are outside the valid range for 'int'.
> 
> This might be due to incorrect data being passed to the DeleteMessagesRequest in your delete_messages function. Check the values of event.chat_id and event.id you are passing to delete_messages, especially event.id, which seems to be used as self.id later. The invalid value might be present there.
> 
> You should debug and validate your input data before passing them into the function to prevent such errors.

**Comment by Lonami** [comment]
These are the types or requests that take in a `InputBotInlineMessageID` as input:

```tl
updateBotInlineSend#12f12a07 flags:# user_id:long query:string geo:flags.0?GeoPoint id:string msg_id:flags.1?InputBotInlineMessageID = Update;
updateInlineBotCallbackQuery#691e9052 flags:# query_id:long user_id:long msg_id:InputBotInlineMessageID chat_instance:long data:flags.0?bytes game_short_name:flags.1?string = Update;
inputBotInlineMessageID#890c3d89 dc_id:int id:long access_hash:long = InputBotInlineMessageID;
inputBotInlineMessageID64#b6d915d7 dc_id:int owner_id:long id:int access_hash:long = InputBotInlineMessageID;
webViewMessageSent#c94511c flags:# msg_id:flags.0?InputBotInlineMessageID = WebViewMessageSent;
messages.editInlineBotMessage#83557dba flags:# no_webpage:flags.1?true id:InputBotInlineMessageID message:flags.11?string media:flags.14?InputMedia reply_markup:flags.2?ReplyMarkup entities:flags.3?Vector<MessageEntity> = Bool;
messages.setInlineGameScore#15ad9f64 flags:# edit_message:flags.0?true force:flags.1?true id:InputBotInlineMessageID user_id:InputUser score:int = Bool;
messages.getInlineGameHighScores#f635e1b id:InputBotInlineMessageID user_id:InputUser = messages.HighScores;
// LAYER 158
```

As you can see, there is none to delete messages.
