### ISSUE TITLE
UnicodeDecodeError for many different chats

### ISSUE THREAD

**Issue by ehtec** [LonamiWebs/Telethon#4133]
### Code that causes the issue

```python
from telethon.sync import TelegramClient
from telethon.tl.types import InputPeerChannel
import logging


api_id = 00000
api_hash = ''
phone_number = ''
group_username = 'thecyberworldproject'
output_file = 'test_output.txt'
password = ""

# Create a new instance of the Telegram client
client = TelegramClient('session_name', api_id, api_hash)

# Connect to the Telegram server
client.connect()

# If not authorized, send an authentication code to your phone
if not client.is_user_authorized():
    client.send_code_request(phone_number)
    try:
        client.sign_in(phone_number, input('Enter the code: '))
    except Exception as e:
        client.sign_in(password=password)


client.parse_mode = "html"
# Get the input peer of the group
entity = client.get_entity(group_username)
input_peer = InputPeerChannel(entity.id, entity.access_hash)

# Get all the text messages in the group
messages = []
messages_count = 0

# Save the messages to a file
with open(output_file, 'w', encoding='utf-8') as file:

    for message in client.iter_messages(entity=input_peer):
        # if hasattr(message, 'message'):
        try:
            print(f'{message.date}: {message.text}')
            file.write(f'{message.date}: {message.text}\n')
        except UnicodeDecodeError as e:
            logging.exception(e)
            print(message)
            print(message.message)
            print(message.raw_text)
            print("Trying to unparse...")
            msg = message.message
            print(msg.encode('utf-16', 'surrogatepass').decode('utf-16'))
            break

# Disconnect the client
client.disconnect()

print(f'Successfully downloaded and saved {messages_count} messages to {output_file}.')

```

### Expected behavior

The code above should download all text messages of the given chat (it is an example, the exact same error occured for many different chats though) in HTML parse mode.

### Actual behavior

The traceback shown below appears. It seems to come from https://github.com/LonamiWebs/Telethon/blob/9267917031e60367928da982bb49e4ee5c25ec52/telethon/extensions/html.py#L29 triggered at https://github.com/LonamiWebs/Telethon/blob/9267917031e60367928da982bb49e4ee5c25ec52/telethon/extensions/html.py#L229. If the `_del_surrogate` function was applied to the `text` parameter of the `unparse` function instead, no error is triggered. The value of `''.join(html)` cannot be printed for debugging, it makes another decoding error appear. However, I can print `(''.join(html)).encode('utf-16', 'surrogatepass')` which yields `b'\xff\xfe\n\x00=\xd8'`. Calling `b'\xff\xfe\n\x00=\xd8'.decode('utf-16')` yields the `UnicodeDecodeError` again. I do not know what exactly the `unparse` function is trying to do in this case that corrupts the encoding. If there is no better fix, I would suggest to replace the `_del_surrogate` function with
```python
return text.encode('utf-16', 'surrogatepass').decode('utf-16', errors='ignore')
```

### Traceback

```
ERROR:root:'utf-16-le' codec can't decode bytes in position 4-5: unexpected end of data
Traceback (most recent call last):
  File "/home/elias/git/cst-core/test_simple_tgscraper.py", line 45, in <module>
    print(f'{message.date}: {message.text}')
  File "/home/elias/.local/lib/python3.9/site-packages/telethon/tl/custom/message.py", line 353, in text
    self._text = self._client.parse_mode.unparse(
  File "/home/elias/.local/lib/python3.9/site-packages/telethon/extensions/html.py", line 185, in unparse
    entity_text = unparse(text=text[relative_offset:relative_offset + length],
  File "/home/elias/.local/lib/python3.9/site-packages/telethon/extensions/html.py", line 236, in unparse
    return _del_surrogate(''.join(html))
  File "/home/elias/.local/lib/python3.9/site-packages/telethon/extensions/html.py", line 29, in _del_surrogate
    return text.encode('utf-16', 'surrogatepass').decode('utf-16')
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 4-5: unexpected end of data
```

### Telethon version

1.28.5

### Python version

Python 3.9.2

### Operating system (including distribution name and version)

Debian 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
<details><summary>Misremembered, <code>.text</code> caches on first use</summary>

Strangely enough, this works:
```python
m = await client.get_messages('thecyberworldproject', ids=69512)
print(m.raw_text)
print(*m.entities)
print(m.text)
client.parse_mode = 'html'
print(m.text)
```

but this fails
```python
m = await client.get_messages('thecyberworldproject', ids=69512)
print(m.raw_text)
print(*m.entities)
# print(m.text)
client.parse_mode = 'html'
print(m.text)
```

</details>

In any case, the faulty message has these bytes from Telegram:

```python
message = bytes.fromhex('f09f93a3f09f93a3f09f93a3f09f93a3f09f93a30af09f988fd09fd0a0d098d093d09bd090d0a8d090d0ae20d0a2d095d091d0aff09fabb50af09f98aed09220d09dd09ed092d0abd09920d0a7d090d0a220f09f98ae0af09f9880f09f9880f09f9880f09f9880f09f9880f09f9fa30af09f94a5d0a320d09dd090d0a120d096d090d0a0d09ad09ef09f949e0ae2ac85efb88fd181d181d18bd0bbd0bad0b020d0b220d0bfd180d0bed184d0b8d0bbd0b5')
entities = (
    MessageEntityCustomEmoji(offset=0, length=2, document_id=5956145717062929500),
    MessageEntityCustomEmoji(offset=2, length=2, document_id=5953784150770060253),
    MessageEntityCustomEmoji(offset=4, length=2, document_id=5956183723228531712),
    MessageEntityCustomEmoji(offset=6, length=2, document_id=5956162926996884740),
    MessageEntityCustomEmoji(offset=8, length=2, document_id=5954210997504839406),
    MessageEntityCustomEmoji(offset=11, length=2, document_id=5379619324774326601),
    MessageEntityCustomEmoji(offset=30, length=2, document_id=5413825479406789631),
    MessageEntityCustomEmoji(offset=44, length=2, document_id=5413825479406789631),
    MessageEntityCustomEmoji(offset=47, length=2, document_id=5472183721203343695),
    MessageEntityCustomEmoji(offset=49, length=2, document_id=5472025271269858801),
    MessageEntityCustomEmoji(offset=51, length=2, document_id=5472098384498139185),
    MessageEntityCustomEmoji(offset=53, length=2, document_id=5472102086759949157),
    MessageEntityCustomEmoji(offset=55, length=2, document_id=5471900133102722439),
    MessageEntityCustomEmoji(offset=57, length=2, document_id=5472166240686447816),
    MessageEntityCustomEmoji(offset=60, length=2, document_id=5402406965252989103),
    MessageEntityCustomEmoji(offset=73, length=2, document_id=5456556671675410203),
    MessageEntityCustomEmoji(offset=76, length=2, document_id=5248948801674159296),
)
```

So this makes it easier to test offline.
