### ISSUE TITLE
  File "telethon\network\connection\connection.py" raise GeneratorExit  in _recv_loop(335)

### ISSUE THREAD

**Issue by hhxdestiny** [LonamiWebs/Telethon#4135]
### Code that causes the issue

```python
async for it_msg in self.client.iter_messages(id, offset_date=datetime.fromtimestamp(req['start_date']) - timedelta(hours=self._timezone), reverse=True, wait_time=1):
    ...
```

### Expected behavior

"get history message"

### Actual behavior

raise GeneratorExit

### Traceback

Traceback (most recent call last):
  File "telegram_test.py", line 70, in <module>
  File "service\telegram_bot.py", line 189, in consumer
  File "asyncio\base_events.py", line 574, in run_until_complete
  File "asyncio\base_events.py", line 541, in run_forever
  File "asyncio\base_events.py", line 1786, in _run_once
  File "asyncio\events.py", line 88, in _run
  File "telethon\network\connection\connection.py", line 335, in _recv_loop
GeneratorExit

### Telethon version

1.28.5

### Python version

3.7

### Operating system (including distribution name and version)

Windows11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Try upgrading your Python version. I'm fairly sure this is something Telethon can't "fix".
