### ISSUE TITLE
Bug while running bot

### ISSUE THREAD

**Issue by k3l3vr444** [LonamiWebs/Telethon#4142]
### Code that causes the issue

diff = await self(get_diff)

### Expected behavior

I was doing nothing but running bot. No any messages or callbacks

### Actual behavior

Bot did nothing for ~2 hours, and then i've got this erorrs

### Traceback

2023-06-24 20:44:09 | WARNING  | telethon.client.users          | #92   | Telegram is having internal issues ServerError: RPCError -500: No workers running (caused by GetChannelDifferenceRequest) 

2023-06-24 20:44:16 | ERROR    | telethon.client.updates        | #354  | Fatal error handling updates (this is a bug in Telethon, please report it) 
Traceback (most recent call last):
  File "/home/sammy/tgcleaning/virtualenv/lib/python3.9/site-packages/telethon/client/updates.py", line 281, in _update_loop
    diff = await self(get_diff)
  File "/home/sammy/tgcleaning/virtualenv/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/sammy/tgcleaning/virtualenv/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 547 seconds is required (caused by GetChannelDifferenceRequest)

### Telethon version

1.25

### Python version

3.9.14

### Operating system (including distribution name and version)

Ubuntu 20.04.3

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Telegram was having issues and the version of the library is out of date.
