### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by mrafieefard** [LonamiWebs/Telethon#4154]
### Code that causes the issue

```
from telethon import TelegramClient, events, sync

import socks
api_id = -
api_hash = -

client = TelegramClient('Crawl', api_id, api_hash)

client.set_proxy((socks.HTTP,"127.0.0.1","10809"))
```

### Expected behavior

" I trying to run a telethon session but this happened to me "

### Actual behavior

" Nothing just start a regular source also its runnable on my linux server "

### Traceback

```Server closed the connection: [WinError 64] The specified network name is no longer available
Server closed the connection: [WinError 64] The specified network name is no longer available
Connection error 1 during auth_key gen: ConnectionResetError: [WinError 64] The specified network name is no longer available
Connection error 2 during auth_key gen: ConnectionResetError: [WinError 64] The specified network name is no longer available
Server closed the connection: [WinError 64] The specified network name is no longer available
Server closed the connection: [WinError 64] The specified network name is no longer available
Connection error 3 during auth_key gen: ConnectionResetError: [WinError 64] The specified network name is no longer available
Connection error 4 during auth_key gen: ConnectionResetError: [WinError 64] The specified network name is no longer available
Server closed the connection: [WinError 64] The specified network name is no longer available
Server closed the connection: [WinError 64] The specified network name is no longer available
Connection error 5 during auth_key gen: ConnectionResetError: [WinError 64] The specified network name is no longer available
Connection error 6 during auth_key gen: ConnectionResetError: [WinError 64] The specified network name is no longer available
Traceback (most recent call last):
  File "h:\Python\TelegramCrawl\main.py", line 26, in <module>
    client.start()
  File "C:\Users\mrafi\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\mrafi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\mrafi\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\auth.py", line 135, in _start
    await self.connect()
  File "C:\Users\mrafi\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\telegrambaseclient.py", line 538, in connect
    if not await self._sender.connect(self._connection(
  File "C:\Users\mrafi\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\network\mtprotosender.py", line 132, in connect
    await self._connect()
  File "C:\Users\mrafi\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\network\mtprotosender.py", line 258, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)```

### Telethon version

1.28.5

### Python version

3.10.9

### Operating system (including distribution name and version)

Windows 11

### Other details

_No response_

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by ShayneBermejo** [comment]
In the [documentation](https://docs.telethon.dev/en/stable/basic/signing-in.html), 
For Python >= 3.6 : [install python-socks[asyncio]](https://github.com/romis2012/python-socks#installation) instead of Pysocks

**Comment by Lonami** [comment]
This is likely a problem with the proxy and not the library.

**Comment by mrafieefard** [comment]
I live in country that block telegram and I should use proxy also the proxy is working because I work my proxy at same time I start the source code

**Comment by mrafieefard** [comment]
> In the [documentation](https://docs.telethon.dev/en/stable/basic/signing-in.html), For Python >= 3.6 : [install python-socks[asyncio]](https://github.com/romis2012/python-socks#installation) instead of Pysocks

Can you please tell me how to use it in telethon library?

**Comment by mrafieefard** [comment]
> In the [documentation](https://docs.telethon.dev/en/stable/basic/signing-in.html), For Python >= 3.6 : [install python-socks[asyncio]](https://github.com/romis2012/python-socks#installation) instead of Pysocks

Omg thanks bro you're so helpful <3
