### ISSUE TITLE
telethon.client.updates - ERROR - Fatal error handling updates (this is a bug in Telethon v1.28.5, please report it)

### ISSUE THREAD

**Issue by JoGreen** [LonamiWebs/Telethon#4190]
### Code that causes the issue

it doesn't seem to be related to my code, so I don't fill this field

### Expected behavior

the client should be up and running 

### Actual behavior

The client suddenly shutted down

### Traceback

```
2023-08-28 14:38:19,288 - telethon.client.updates - ERROR - Fatal error handling updates (this is a bug in Telethon v1.28.5, please report it)
Traceback (most recent call last):
File "/home/ec2-user/copy-telegram-channels/my_telegram_account_bot/venv/lib/python3.9/site-packages/telethon/client/[updates.py](http://updates.py/)", line 340, in _update_loop
diff = await self(get_diff)
File "/home/ec2-user/copy-telegram-channels/my_telegram_account_bot/venv/lib/python3.9/site-packages/telethon/client/[users.py](http://users.py/)", line 30, in call
return await self._call(self._sender, request, ordered=ordered)
File "/home/ec2-user/copy-telegram-channels/my_telegram_account_bot/venv/lib/python3.9/site-packages/telethon/client/[users.py](http://users.py/)", line 83, in _call
result = await future
telethon.errors.rpcbaseerrors.RPCError: RPCError -505: Nothing stored (caused by GetChannelDifferenceRequest)
2023-08-28 14:38:19,294 - telethon.network.mtprotosender - INFO - Disconnecting from XXX.XXX.XXX.XXX:443/TcpFull...
2023-08-28 14:38:19,295 - telethon.network.mtprotosender - INFO - Disconnection from  XXX.XXX.XXX.XXX:443/TcpFull complete!
2023-08-28 14:38:19,295 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2023-08-28 14:38:19,321 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2023-08-28 14:38:19,335 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
```

### Telethon version

1.28.5

### Python version

3.9

### Operating system (including distribution name and version)

NAME="Amazon Linux" VERSION="2" ID="amzn" ID_LIKE="centos rhel fedora" VERSION_ID="2" PRETTY_NAME="Amazon Linux 2"

### Other details

I can't reproduce the issue, because it just happens ONCE on my production server after weeks it was working fine. no clues about a specific message triggering the issue

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
> it just happens ONCE on my production server

It's a temporary server issue that has made a comeback after some years.

**Comment by omkarsing6458** [comment]
telethon.client.updates: Fatal error handling updates (this is a bug in Telethon v1.28.5, please report it)

Traceback (most recent call last):

Same error coming in my code

Any solution for this

**Comment by Lonami** [comment]
You're using an outdated version.
