### ISSUE TITLE
Fatal error handling updates (this is a bug in Telethon v1.30.2, please report it)

### ISSUE THREAD

**Issue by Juranik** [LonamiWebs/Telethon#4199]
### Code that causes the issue

Fatal error handling updates (this is a bug in Telethon v1.30.2, please report it)
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 308, in _update_loop
    diff = await self(get_diff)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.DateEmptyError: Date empty (caused by GetDifferenceRequest)
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\main.py", line 224, in <module>
    bot.run_until_disconnected()
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 96, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 38, in _run_until_disconnected
    raise self._updates_error
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 308, in _update_loop
    diff = await self(get_diff)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.DateEmptyError: Date empty (caused by GetDifferenceRequest)

Process finished with exit code 1

### Expected behavior

I had talking with chatGPT in my telegrambot

### Actual behavior

When I was talking with chatgpt appear this error

### Traceback

Fatal error handling updates (this is a bug in Telethon v1.30.2, please report it)
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 308, in _update_loop
    diff = await self(get_diff)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.DateEmptyError: Date empty (caused by GetDifferenceRequest)
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\main.py", line 224, in <module>
    bot.run_until_disconnected()
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 96, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 38, in _run_until_disconnected
    raise self._updates_error
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 308, in _update_loop
    diff = await self(get_diff)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.DateEmptyError: Date empty (caused by GetDifferenceRequest)

Process finished with exit code 1

### Telethon version

1.30.2

### Python version

3.10.11

### Operating system (including distribution name and version)

windows 10 21H2

### Other details

Fatal error handling updates (this is a bug in Telethon v1.30.2, please report it)
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 308, in _update_loop
    diff = await self(get_diff)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.DateEmptyError: Date empty (caused by GetDifferenceRequest)
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\main.py", line 224, in <module>
    bot.run_until_disconnected()
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 96, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 38, in _run_until_disconnected
    raise self._updates_error
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\updates.py", line 308, in _update_loop
    diff = await self(get_diff)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\PycharmProjects\MyChatGPT\venv\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.DateEmptyError: Date empty (caused by GetDifferenceRequest)

Process finished with exit code 1

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Should've been fixed by https://github.com/LonamiWebs/Telethon/commit/7325718f0ee3d62893b50dd1d6f915e69363c4e7.
