### ISSUE TITLE
Strange behaviour with AuthKeyDuplicatedError 

### ISSUE THREAD

**Issue by yoursteacup** [LonamiWebs/Telethon#4214]
### Code that causes the issue

```import asyncio
import datetime

from api_client.client import APIClient

from telethon.sessions import StringSession
from telethon import TelegramClient


async def some_test():
    bot = APIClient.get_bot()

    session = StringSession(bot.session_file)
    client = TelegramClient(
        session=session,
        api_id=bot.api_id,
        api_hash=bot.api_hash,
    )
    print(bot.phone_number, datetime.datetime.now().strftime("%H:%m:%S"))

    await client.start(phone=bot.phone_number)
    dialogs = await client.get_dialogs()
    print(dialogs[0].entity.username, datetime.datetime.now().strftime("%H:%m:%S"))


if __name__ == "__main__":
    asyncio.run(some_test())
```

### Expected behavior

I use bots for subscribing to channels and monitoring updates constantly. Application is actually working fine but only with several accounts. 
Noticed that some of accounts actually CAN be used simultaneously by different applications without any troubles and some of them can not.

### Actual behavior

Was running this test I attached. API client retrieved bot with ID 4 and I got the AuthKeyDuplicatedError. It was strange because there were no other applications that used same session file. 
Did run test on bot with ID 8 and noticed that everything was fine with getting a proper result. And even more so, this bot was used on remote virtual machine that has different IP address and was used on my computer with no problem. 
```
+lookatmeimanumber 13:09:44
markettwits 13:09:48
```
```
+lookatmeimanumber 13:09:44
markettwits 13:09:49
```
My question is why this error occurs where there is no seemed reasons for that and does not occur where there is an obvious one session usage from multiple places?

### Traceback

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ivsed/services/core/telegram/telegram-executor/tests/capabilities.py", line 27, in <module>
    asyncio.run(some_test())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ivsed/services/core/telegram/telegram-executor/tests/capabilities.py", line 21, in some_test
    await client.start(phone=bot.phone_number)
  File "/home/ivsed/services/core/telegram/telegram-executor/.venv/lib/python3.11/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/home/ivsed/services/core/telegram/telegram-executor/.venv/lib/python3.11/site-packages/telethon/client/telegrambaseclient.py", line 593, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(LAYER, req))
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))
```

### Telethon version

1.30.3

### Python version

3.11

### Operating system (including distribution name and version)

Ubuntu 20.04.5 LTS

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Extremely unlikely that this is a bug in the library that can be fixed. I am pretty certain this is just the way Telegram works, and I don't think there's any point in me spending any time trying to bypass that, if at all possible.

> My question is why this error occurs where there is no seemed reasons for that and does not occur where there is an obvious one session usage from multiple places?

I cannot answer that. This is Telegram's own doing and only Telegram really knows.
