### ISSUE TITLE
getting floodwaiterror when calling get_input_entity

### ISSUE THREAD

**Issue by smart-developerr** [LonamiWebs/Telethon#422]
Hi! , I'm trying to send a simple message to my chat by using [this link](https://github.com/LonamiWebs/Telethon/wiki/Sending-Requests) and my code is:

```
from telethon import TelegramClient
from telethon.tl.functions.messages import SendMessageRequest

api_id = some-int
api_hash = 'some-hash'
phone_number = 'some-number'

client = TelegramClient('mySession5', api_id, api_hash, update_workers=3)
print(client.connect())
print(client.is_user_authorized())

peer = client.get_input_entity('computer_ebooks1')
result = client(SendMessageRequest(peer, 'Hello there!'))
print(result)
```

 but it does not work properly and i get this error:

```
True
True
Traceback (most recent call last):
  File "tclient.py", line 12, in <module>
    peer = client.get_input_entity('computer_ebooks1')
  File "C:\Users\Ali\projects\telegram bot dev branch\myenv\Lib\site-packages\telethon\telegram_client.py", line 1092, in get_input_entity
    return utils.get_input_peer(self._get_entity_from_string(peer))
  File "C:\Users\Ali\projects\telegram bot dev branch\myenv\Lib\site-packages\telethon\telegram_client.py", line 1057, in _get_entity_from_string
    self(ResolveUsernameRequest(entity))
  File "C:\Users\Ali\projects\telegram bot dev branch\myenv\Lib\site-packages\telethon\telegram_bare_client.py", line 429, in __call__
    sender, call_receive, update_state, *requests
  File "C:\Users\Ali\projects\telegram bot dev branch\myenv\Lib\site-packages\telethon\telegram_bare_client.py", line 517, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.FloodWaitError: (FloodWaitError(...), 'A wait of 52733 seconds is required')
```

**Comment by Lonami** [comment]
Calling `ResolveUsernameRequest` which is what the request does too often results in a flood wait. Print the user and hardcode it if possible. I may also save the username to the session file so it doesn't have to be queried, but I still need to debate that.
