### ISSUE TITLE
GetChatInviteImportersRequest (messages.getChatInviteImporters) doesn't work properly

### ISSUE THREAD

**Issue by marperia** [LonamiWebs/Telethon#4222]
### Code that causes the issue

I was trying to get all users who came through invite link, but when I tried to call
```python
chan = client.get_entity(int(chat_id))
result = client(functions.messages.GetChatInviteImportersRequest(
    peer=chan,
    link='https://t.me/...',
    limit=100,
))
```

### Actual behavior

It threw me an exception
```python
GetChatInviteImportersRequest.__init__() missing 2 required positional arguments: 'offset_date' and 'offset_user'
```
It's even unlogical: we are trying to set offset before we get first results. We don't know user and date before we first get it.

### Expected behavior

As written in here https://core.telegram.org/method/messages.getChatInviteImporters, you should make these two params unnecessary
### Traceback

```
python /home/user/project/file.py 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/user/project/file.py", line 92, in <module>
    main(params)
  File "/home/user/project/file.py", line 29, in main
    result = client(functions.messages.GetChatInviteImportersRequest(
TypeError: GetChatInviteImportersRequest.__init__() missing 2 required positional arguments: 'offset_date' and 'offset_user'
```

### Telethon version

1.27.0 from pipy and 1.31.0

### Python version

3.10.12

### Operating system (including distribution name and version)

Ubuntu 22.04

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
The error tells you that you're missing parameters:

> ```
> TypeError: GetChatInviteImportersRequest.__init__() missing 2 required positional arguments: 'offset_date' and 'offset_user'
> ```

This is not something that needs fixing in Telethon.
