### ISSUE TITLE
Can bot actively join designated channels？？

### ISSUE THREAD

**Issue by GodFatherClover** [LonamiWebs/Telethon#4230]
### Describe your suggested feature

```
async def cuihua():
    proxy_address = '127.0.0.1'
    proxy_port = 52551
    bot_token = 'xxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    async with TelegramClient('cuihua_bot', api_id, api_hash, proxy=("socks5", proxy_address, proxy_port)) as bot:
        await bot.start(bot_token=bot_token)
        print(await bot.get_me())
        await bot(JoinChannelRequest(channel='https://t.me/xxxxxxxxxxxx'))
        
```

```

Traceback (most recent call last):
  File "D:\Github\TelethonDemo\main.py", line 41, in <module>
    asyncio.run(cuihua())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Github\TelethonDemo\main.py", line 25, in cuihua
    await bot(JoinChannelRequest(channel='https://t.me/cuihuaceshi'))
  File "D:\Github\TelethonDemo\venv\Lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\TelethonDemo\venv\Lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by JoinChannelRequest)

Process finished with exit code 1

```

Can this library solve this problem？？？

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Sorry I didn't reply earlier, but the answer to:
> Can bot actively join designated channels

is no.
