### ISSUE TITLE
app ids above a limit breaks the authentication.

### ISSUE THREAD

**Issue by blairn** [LonamiWebs/Telethon#4256]
### Code that causes the issue

the xxxx are replaced with the hash... the problem is the account id part of it.

```python
client.start(bot_token="6985016276:xxxxxxxxxxxxxxxxxx")
```

### Expected behavior

have it successfully connect.

### Actual behavior

Request caused struct.error: 'i' format requires -2147483648 <= number <= 2147483647: InvokeWithLayerRequest(layer=166, query=InitConnectionRequest(api_id=6985016276, device_model='PC 64bit', system_version='5.19.0', app_version='1.32.1', system_lang_code='en', lang_pack='', lang_code='en', query=GetConfigRequest(), proxy=None, params=None))

Note the account id, is about the limit for integers. 

### Traceback

_I've also replace the hash in this as well, for obvious reasons...._ 

This is using the https://github.com/LonamiWebs/Telethon/archive/v1.zip verson...

Traceback (most recent call last):
  File "/home/ubuntu/heia_collectors/telegram/./telegram_mongo.py", line 59, in <module>
    client.start(bot_token="6985016276:xxx...")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/telethon/client/auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 593, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(LAYER, req))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/telethon/network/mtprotosender.py", line 183, in send
    state = RequestState(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/telethon/tl/functions/__init__.py", line 253, in _bytes
    self.query._bytes(),
  File "/home/ubuntu/.local/lib/python3.10/site-packages/telethon/tl/functions/__init__.py", line 127, in _bytes
    struct.pack('<i', self.api_id),
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### Telethon version

1.32.1

### Python version

3.10.7

### Operating system (including distribution name and version)

ubuntu

### Other details

Looks like it is just the type being wrong in the auth module, I'll go in have a look, see if I can fix it myself.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
What BotFather gives you is not the API_ID/API_hash. It's the bot token.

The API_ID/API_HASH comes from https://my.telegram.org.

In Telethon, you need all three values to use bot accounts.

**Comment by blairn** [comment]
Thank you so very much!! (Seriously your comment has made me able to get this sorted)

Sorry for bugging you on this.
