### ISSUE TITLE
TypeNotFoundError: Could not find a matching Constructor ID eb602f25

### ISSUE THREAD

**Issue by khoben** [LonamiWebs/Telethon#4273]
### Code that causes the issue

```python
from telethon import TelegramClient, events

client = TelegramClient('phone', api_id, api_hash)

@client.on(events.NewMessage(chats = [123123]))
async def handler(event):
    print(event.raw_text)
    await client.send_message(entity=321321, message=entity.message)

client.start()
client.run_until_disconnected()
```

### Expected behavior

I expect to receive a new message and send it to another channel

### Actual behavior

An `telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID eb602f25` error occurs

### Traceback

```bash
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 556, in _recv_loop
    await self._process_message(message)
  File "/app/.heroku/python/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 571, in _process_message
    await handler(message)
  File "/app/.heroku/python/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 669, in _handle_gzip_packed
    message.obj = reader.tgread_object()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/telethon/extensions/binaryreader.py", line 142, in tgread_object
    return clazz.from_reader(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/telethon/tl/types/__init__.py", line 35391, in from_reader
    _x = reader.tgread_object()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/telethon/extensions/binaryreader.py", line 140, in tgread_object
    raise error
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID eb602f25. See the FAQ for more details. Remaining bytes: b"%/`\xeb+@\x10\x02\x10\x00\x00\x00\x18\xac'\x08\x00\x00\x00\x00\xb2\xce\x9c!q\x93\x1c\x1b\x07Channel\x0bChannel_Bot\x06\xf7\xd1\x82\x02\x00\x00\x00\xa9\xa71\x1b\x18\xac'\x08\x10\x01\x08\x08\xb1\xf2\xf9_\xedg4QEp3\xad\x1f\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x15\xc4\xb5\x1c\x01\x00\x00\x00~\xea\x81\x19`0\x10\x00\x0c\x00\x00\x00'w\xb5J\x00\x00\x00\x00\xd1\x88\x81v\xa2\x851+/\xd0\x9c\xd0\xbe\xd0\xb9 \xd0\xbf\xd1\x83\xd1\x82\xd1\x8c \xd0\xb8\xd0\xb7 \xd0\xb1\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xbd\xd1\x8b \xd0\xba \xd1\x81\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xb5\x0brealbestov1\x11\x1cn\x1c\x02\x00\x00\x00\xaf\xa71\x1bC4\xd0\x13\x12\x01\x08\x08\xae\x915\xba\x86@\xac\x08\xc1\xfa\xd1E\x15\x0c\xb3\x00\x02\x00\x00\x00\xa4\xdb\xd2\\\xb3\xa6ze\x00\x00\x00\x00"
Unhandled error while processing msgs
```

### Telethon version

1.33.1

### Python version

3.11

### Operating system (including distribution name and version)

Ubuntu 22.04

### Other details

It works with `1.32.0` version

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by khoben** [comment]
It looks like the problem is in the [old session](https://docs.telethon.dev/en/stable/quick-references/faq.html#what-does-could-not-find-a-matching-constructor-id-for-the-tlobject-mean). Invalid objects (from layer 166) are being received for layer 167.
