### ISSUE TITLE
Quart login example is not working for me

### ISSUE THREAD

**Issue by rjnrohit** [LonamiWebs/Telethon#4278]
### Code that causes the issue

https://github.com/LonamiWebs/Telethon/blob/v1/telethon_examples/quart_login.py

### Expected behavior

It should return a login form when I hit the url `localhost:5000`

### Actual behavior

When I try the command
`python3 quart_login.py`, it just crashes

### Traceback

```
 * Serving Quart app 'example'
 * Debug mode: False
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Running on http://127.0.0.1:5000 (CTRL + C to quit)
Traceback (most recent call last):
  File "/Users/rohit/tg/lib/python3.8/site-packages/hypercorn/asyncio/lifespan.py", line 76, in wait_for_startup
    await asyncio.wait_for(self.startup.wait(), timeout=self.config.startup_timeout)
  File "/opt/homebrew/Cellar/python@3.8/3.8.18_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 143, in <module>
    app.run()
  File "/Users/rohit/tg/lib/python3.8/site-packages/quart/app.py", line 850, in run
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/opt/homebrew/Cellar/python@3.8/3.8.18_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/rohit/tg/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 44, in serve
    await worker_serve(
  File "/Users/rohit/tg/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 73, in worker_serve
    await lifespan.wait_for_startup()
  File "/Users/rohit/tg/lib/python3.8/site-packages/hypercorn/asyncio/lifespan.py", line 78, in wait_for_startup
    raise LifespanTimeoutError("startup") from error
hypercorn.utils.LifespanTimeoutError: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<MTProtoSender._send_loop() done, defined at /Users/rohit/tg/lib/python3.8/site-packages/telethon/network/mtprotosender.py:446> exception=RuntimeError("Task <Task pending name='Task-8' coro=<MTProtoSender._send_loop() running at /Users/rohit/tg/lib/python3.8/site-packages/telethon/network/mtprotosender.py:464>> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/Users/rohit/tg/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 464, in _send_loop
    batch, data = await self._send_queue.get()
  File "/Users/rohit/tg/lib/python3.8/site-packages/telethon/extensions/messagepacker.py", line 48, in get
    await self._ready.wait()
  File "/opt/homebrew/Cellar/python@3.8/3.8.18_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-8' coro=<MTProtoSender._send_loop() running at /Users/rohit/tg/lib/python3.8/site-packages/telethon/network/mtprotosender.py:464>> got Future <Future pending> attached to a different loop
```

### Telethon version

1.33.1

### Python version

3.8

### Operating system (including distribution name and version)

macOS14.2

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
> hypercorn.utils.LifespanTimeoutError: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.

I have no idea what this is, but it doesn't sound like a problem with Telethon. It is unlikely I'll look into this any time soon.

**Comment by rjnrohit** [comment]
> > hypercorn.utils.LifespanTimeoutError: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.
> 
> I have no idea what this is, but it doesn't sound like a problem with Telethon. It is unlikely I'll look into this any time soon.

I have checked the sample `quart_app.py` it is working in my system 
```python3
from quart import Quart
from quart_cors import cors

app = Quart(__name__)
app = cors(app, allow_origin="*")


@app.route('/')
async def hello():
    return 'hello'


# Connect the client before serving with Quart
@app.before_serving
async def startup():
    print('startup')


# After we're done serving (near shutdown), clean up the client
@app.after_serving
async def cleanup():
    print('cleanup')

app.run()
```

but when I run 
```python3
# Connect the client before serving with Quart
@app.before_serving
async def startup():
    print(api_hash, api_id)
    try: 
        await client.connect()
    except OSError as e:
        print("Failed to connect. OSError: ", e)
    print("startup123")
```

It fails, I think `client.connect()` is not working properly for me. Based on above changes It does print `api_hash` & `api_id` but it doesn't print `startup1223`
