### ISSUE TITLE
Internal ValueError in package reader

### ISSUE THREAD

**Issue by i-s-m-mipt** [LonamiWebs/Telethon#4295]
### Code that causes the issue

```
def update_database(self, channel_id: str, channel_hash: str, message_id_1: str, message_id_n: str, file: str):
        entity = types.InputPeerChannel(int(channel_id), int(channel_hash))
        separator = ','; n_messages = 0; n_comments = 0
        with open(file, 'a', encoding = "utf-8") as fout:
            for message in self.client.iter_messages(entity, ids = list(range(int(message_id_1), int(message_id_n) + 1))):
                if (message                 != None  and 
                    message.message         != ""    and 
                    message.replies         != None  and 
                    message.replies.replies != 0     and 
                    message.replies.replies <= 30000):
                    fout.write("M" + separator + str(int(message.date.timestamp())) + separator + 
                               str(message.id) + separator + repr(message.message) + '\n'); n_messages += 1
                    for comment in self.client.iter_messages(entity, reply_to = message.id):
                        if (isinstance(comment.sender, types.User) and not comment.sender.bot):
                            fout.write("C" + separator + str(int(comment.date.timestamp())) + separator + 
                                       str(comment.sender.id) + separator + repr(comment.message) + '\n'); n_comments += 1
            self.client._entity_cache.clear()
        return (str(n_messages) + " " + str(n_comments))
```

### Expected behavior

I expected only "Request was unsuccessful 6 time(s)" here.

### Actual behavior

Non-regular exception appeared in console, it is the first time after many successful calls.

### Traceback

```
Traceback (most recent call last):
  File "C:\Libraries\python\lib\site-packages\telethon\network\connection\connection.py", line 329, in _recv_loop
    data = await self._recv()
  File "C:\Libraries\python\lib\site-packages\telethon\network\connection\connection.py", line 372, in _recv
    return await self._codec.read_packet(self._reader)
  File "C:\Libraries\python\lib\site-packages\telethon\network\connection\tcpfull.py", line 27, in read_packet
    body = await reader.readexactly(packet_len - 8)
  File "C:\Libraries\python\lib\asyncio\streams.py", line 694, in readexactly
    raise ValueError('readexactly size can not be less than zero')
ValueError: readexactly size can not be less than zero
```

### Telethon version

1.25.2

### Python version

3.10.0

### Operating system (including distribution name and version)

Windows 10

### Other details

Server-grabber, intensive network loads, parallel sessions for loading. Exception probably due to bad network connection.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Only the latest version is supported. You're using an old version.
