### ISSUE TITLE
Why telethon import sqlite even if using string session? Problem when developing on Vercel

### ISSUE THREAD

**Issue by thePromger** [LonamiWebs/Telethon#4319]
### Code that causes the issue

from telethon import TelethonClient

### Expected behavior

I am running it on vercel, and i got to know that vercel doesn't have sqlite support then i tried using string session instead of sqlite for telethon session then it should not raise sqlite module import error

### Actual behavior

I am running it on vercel, and i got to know that vercel doesn't have sqlite support then i tried using string session instead of sqlite for telethon session but i am still getting sqlite module not found error, then how to solve this issue, how to use telethon without sqlite, how to avoid sqlite import but can import telethon

### Telethon version

1.34

### Python version

3.9

### Operating system (including distribution name and version)

Debian/Ubuntu

### Other details

It's been running on vercel

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
The error is only thrown if you create a SQLiteSession:
https://github.com/LonamiWebs/Telethon/blob/d90d0dc00fbb1a5c071254ecbac483bf5601e0a4/telethon/sessions/sqlite.py#L35
Don't do that and it shouldn't raise.

**Comment by thePromger** [comment]
i won't create sqlite session, i am using string session then it also raises _sqlite3 module not found error
syntax : 
client = TelegramClient(StringSession(string), data)
but i am still getting this error when program starts and telethon gets imported if i use it in exception block then it issues telethon not found error

**Comment by thePromger** [comment]
I have one more question
how to solve these issue, i am using tg user to read new messages using new message event from channel but sometimes either few messages gets dropped/not received to client or sometimes i get old days messages like today i got 16 feb message from tg client as a new message
and one message is gets dropped in between messages from a channel
and how to optimize the timings for receiving new messages to client, mostly i am getting delay of around 30 - 1 min, this delay mostly happens when i am reading message in a client as a user.

**Comment by thePromger** [comment]
> The error is only thrown if you create a SQLiteSession:
> 
> https://github.com/LonamiWebs/Telethon/blob/d90d0dc00fbb1a5c071254ecbac483bf5601e0a4/telethon/sessions/sqlite.py#L35
> 
> 
> Don't do that and it shouldn't raise.



Here's the logs while deploying to vercel : 

[10:51:23.268] Running build in Washington, D.C., USA (East) – iad1
[10:51:23.874] Previous build cache not available
[10:51:24.344] Cloning completed: 930.392ms
[10:51:24.616] Running "vercel build"
[10:51:25.082] Vercel CLI 33.5.2
[10:51:25.702] Running "install" command: `python3 --version && pip install -r requirements.txt && python3 -m albot`...
[10:51:25.718] Python 3.9.8
[10:51:26.385] Collecting telethon (from -r requirements.txt (line 1))
[10:51:26.404]   Downloading Telethon-1.34.0.tar.gz (576 kB)
[10:51:26.418]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 576.9/576.9 kB 52.7 MB/s eta 0:00:00
[10:51:26.486]   Installing build dependencies: started
[10:51:28.065]   Installing build dependencies: finished with status 'done'
[10:51:28.066]   Getting requirements to build wheel: started
[10:51:28.234]   Getting requirements to build wheel: finished with status 'done'
[10:51:28.236]   Preparing metadata (pyproject.toml): started
[10:51:28.422]   Preparing metadata (pyproject.toml): finished with status 'done'
[10:51:28.530] Collecting psutil (from -r requirements.txt (line 2))
[10:51:28.535]   Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
[10:51:28.552] Collecting asyncio (from -r requirements.txt (line 3))
[10:51:28.557]   Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)
[10:51:28.564]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 34.2 MB/s eta 0:00:00
[10:51:28.581] Collecting pyaes (from telethon->-r requirements.txt (line 1))
[10:51:28.585]   Downloading pyaes-1.6.1.tar.gz (28 kB)
[10:51:28.595]   Installing build dependencies: started
[10:51:29.846]   Installing build dependencies: finished with status 'done'
[10:51:29.848]   Getting requirements to build wheel: started
[10:51:29.979]   Getting requirements to build wheel: finished with status 'done'
[10:51:29.982]   Preparing metadata (pyproject.toml): started
[10:51:30.136]   Preparing metadata (pyproject.toml): finished with status 'done'
[10:51:30.161] Collecting rsa (from telethon->-r requirements.txt (line 1))
[10:51:30.166]   Downloading rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
[10:51:30.221] Collecting pyasn1>=0.1.3 (from rsa->telethon->-r requirements.txt (line 1))
[10:51:30.224]   Downloading pyasn1-0.5.1-py2.py3-none-any.whl.metadata (8.6 kB)
[10:51:30.243] Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
[10:51:30.251]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 kB 65.9 MB/s eta 0:00:00
[10:51:30.256] Downloading rsa-4.9-py3-none-any.whl (34 kB)
[10:51:30.263] Downloading pyasn1-0.5.1-py2.py3-none-any.whl (84 kB)
[10:51:30.268]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.9/84.9 kB 29.3 MB/s eta 0:00:00
[10:51:30.272] Building wheels for collected packages: telethon, pyaes
[10:51:30.273]   Building wheel for telethon (pyproject.toml): started
[10:51:30.653]   Building wheel for telethon (pyproject.toml): finished with status 'done'
[10:51:30.654]   Created wheel for telethon: filename=Telethon-1.34.0-py3-none-any.whl size=649201 sha256=5d2b13f61afef83a45543dc5177057df00fe8ae7cfbf8ff5a242391223d633ab
[10:51:30.655]   Stored in directory: /vercel/.cache/pip/wheels/18/15/9d/52e1e9bec313dab543a961e52426ce52621d5f3bd7f3901340
[10:51:30.659]   Building wheel for pyaes (pyproject.toml): started
[10:51:30.839]   Building wheel for pyaes (pyproject.toml): finished with status 'done'
[10:51:30.840]   Created wheel for pyaes: filename=pyaes-1.6.1-py3-none-any.whl size=26346 sha256=f5203741d107e939eaf12c4c096cac57751c8090509e362ed6c02f1ce81dda47
[10:51:30.840]   Stored in directory: /vercel/.cache/pip/wheels/33/13/e9/ef9894385084d8e4fab38f5f83afda49a3d593d8afc907c8fd
[10:51:30.843] Successfully built telethon pyaes
[10:51:30.882] Installing collected packages: pyaes, asyncio, pyasn1, psutil, rsa, telethon
[10:51:31.935] Successfully installed asyncio-3.4.3 psutil-5.9.8 pyaes-1.6.1 pyasn1-0.5.1 rsa-4.9 telethon-1.34.0
[10:51:31.936] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[10:51:31.937] 
[10:51:31.937] [notice] A new release of pip is available: 23.3.2 -> 24.0
[10:51:31.938] [notice] To update, run: pip install --upgrade pip
[10:51:32.210] Traceback (most recent call last):
[10:51:32.210]   File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
[10:51:32.211]     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
[10:51:32.211]   File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
[10:51:32.212]     return _get_module_details(pkg_main_name, error)
[10:51:32.212]   File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
[10:51:32.212]     __import__(pkg_name)
[10:51:32.212]   File "/vercel/path0/albot/__init__.py", line 1, in <module>
[10:51:32.212]     from telethon import TelegramClient
[10:51:32.213]   File "/usr/local/lib/python3.9/site-packages/telethon/__init__.py", line 1, in <module>
[10:51:32.213]     from .client.telegramclient import TelegramClient
[10:51:32.213]   File "/usr/local/lib/python3.9/site-packages/telethon/client/__init__.py", line 16, in <module>
[10:51:32.213]     from .updates import UpdateMethods  # Required for buttons (register callbacks)
[10:51:32.214]   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 12, in <module>
[10:51:32.214]     import sqlite3
[10:51:32.214]   File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
[10:51:32.214]     from sqlite3.dbapi2 import *
[10:51:32.215]   File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
[10:51:32.215]     from _sqlite3 import *
[10:51:32.215] ModuleNotFoundError: No module named '_sqlite3'
[10:51:32.254] Error: Command "python3 --version && pip install -r requirements.txt && python3 -m albot" exited with 1
