### ISSUE TITLE
1.37.0 breaks handling of messageReactions#4f2b9479

### ISSUE THREAD

**Issue by toriningen** [LonamiWebs/Telethon#4480]
### Code that causes the issue

```
import base64
from telethon.extensions import BinaryReader

data = base64.b64decode('''eZQrTwYAAAAVxLUcAQAAAIDL0aMAAAAAuIYiGwPinaQEAAAAFcS1
HAMAAAA8tnmMAAAAACIXUVkqIJ8eAAAAADvFzWa4hiIbA+KdpDy2eYwAAAAAIhdRWbaefRAAAAAAacT
NZriGIhsD4p2kPLZ5jAAAAAAiF1FZwbDtLAAAAADjms1muIYiGwPinaQ=''')

with BinaryReader(data) as reader:
    reactions = reader.tgread_object()

print(reactions.stringify())
```

### Expected behavior

It should have printed this (and in telethon==1.36.0 it does):

```
MessageReactions(
	results=[
		ReactionCount(
			reaction=ReactionEmoji(
				emoticon='❤'
			),
			count=4,
			chosen_order=None
		),
	],
	min=False,
	can_see_list=True,
	reactions_as_tags=False,
	recent_reactions=[
		MessagePeerReaction(
			peer_id=PeerUser(
				user_id=513744938
			),
			date=datetime.datetime(2024, 8, 27, 12, 23, 23, tzinfo=datetime.timezone.utc),
			reaction=ReactionEmoji(
				emoticon='❤'
			),
			big=False,
			unread=False,
			my=False
		),
		MessagePeerReaction(
			peer_id=PeerUser(
				user_id=276668086
			),
			date=datetime.datetime(2024, 8, 27, 12, 19, 53, tzinfo=datetime.timezone.utc),
			reaction=ReactionEmoji(
				emoticon='❤'
			),
			big=False,
			unread=False,
			my=False
		),
		MessagePeerReaction(
			peer_id=PeerUser(
				user_id=753774785
			),
			date=datetime.datetime(2024, 8, 27, 9, 22, 43, tzinfo=datetime.timezone.utc),
			reaction=ReactionEmoji(
				emoticon='❤'
			),
			big=False,
			unread=False,
			my=False
		),
	]
)
```

### Actual behavior

In telethon==1.37.0 it shows an error, not being able to find a matching constructor for [4f2b9479](https://corefork.telegram.org/type/MessageReactions)

### Traceback

```
Traceback (most recent call last):
  File "C:\Work\telethon-bug\load.py", line 9, in <module>
    reactions = reader.tgread_object()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toriningen\AppData\Local\pypoetry\Cache\virtualenvs\export-telegram-HE-BkgHm-py3.12\Lib\site-packages\telethon\extensions\binaryreader.py", line 140, in tgread_object
    raise error
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 4f2b9479. See the FAQ for more details. Remaining bytes: b'y\x94+O\x06\x00\x00\x00\x15\xc4\xb5\x1c\x01\x00\x00\x00\x80\xcb\xd1\xa3\x00\x00\x00\x00\xb8\x86"\x1b\x03\xe2\x9d\xa4\x04\x00\x00\x00\x15\xc4\xb5\x1c\x03\x00\x00\x00<\xb6y\x8c\x00\x00\x00\x00"\x17QY* \x9f\x1e\x00\x00\x00\x00;\xc5\xcdf\xb8\x86"\x1b\x03\xe2\x9d\xa4<\xb6y\x8c\x00\x00\x00\x00"\x17QY\xb6\x9e}\x10\x00\x00\x00\x00i\xc4\xcdf\xb8\x86"\x1b\x03\xe2\x9d\xa4<\xb6y\x8c\x00\x00\x00\x00"\x17QY\xc1\xb0\xed,\x00\x00\x00\x00\xe3\x9a\xcdf\xb8\x86"\x1b\x03\xe2\x9d\xa4'
```

### Telethon version

1.37.0

### Python version

3.12

### Operating system (including distribution name and version)

Windows 11 (23H2 22631.4249)

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by toriningen** [comment]
Some other constructors are broken as well (1.36.0 -> 1.37.0):
```
telethon.tl.functions.channels.ClickSponsoredMessageRequest: 18afbc93 -> 01445d75
telethon.tl.functions.channels.ToggleSignaturesRequest: 1f69b606 -> 418d549c
telethon.tl.functions.messages.ExportChatInviteRequest: a02ce5d5 -> a455de90
telethon.tl.functions.messages.RequestAppWebViewRequest: 8c5a3b3c -> 53618bce
telethon.tl.functions.messages.RequestSimpleWebViewRequest: 1a46500a -> 413a3e73
telethon.tl.functions.messages.SaveDraftRequest: 7ff3b806 -> d372c5ce
telethon.tl.functions.messages.SetChatAvailableReactionsRequest: 5a150bd4 -> 864b2581
telethon.tl.functions.payments.GetStarsTransactionsRequest: 673ac2f9 -> 69da4557
telethon.tl.types.AppWebViewResultUrl: 3c1b4f0d -> None
telethon.tl.types.Boost: 2a1c8c71 -> 4b3e14d6
telethon.tl.types.BotInfo: 8f300b57 -> 82437e74
telethon.tl.types.BroadcastRevenueBalances: 8438f1c6 -> c3ff71e7
telethon.tl.types.Channel: 0aadfc8f -> fe4478bd
telethon.tl.types.ChannelParticipant: c00c07c0 -> cb397619
telethon.tl.types.ChannelParticipantSelf: 35a8bfa7 -> 4f607bef
telethon.tl.types.ChatInvite: cde0ec40 -> fe65389d
telethon.tl.types.ChatInviteExported: 0ab4a819 -> a22cbd96
telethon.tl.types.DocumentAttributeVideo: d38ff1c2 -> 43c57c48
telethon.tl.types.DraftMessage: 3fccf7ef -> 2d65321f
telethon.tl.types.InputInvoiceStars: 1da33ad8 -> 65f00ce3
telethon.tl.types.InputStorePaymentStars: 4f0ee8df -> None
telethon.tl.types.MediaAreaCoordinates: 03d1ea4e -> cfc9e002
telethon.tl.types.MediaAreaGeoPoint: df8b3b22 -> cad5452d
telethon.tl.types.MessageActionGiveawayLaunch: 332ba9ed -> a80f51e4
telethon.tl.types.MessageActionGiveawayResults: 2a9fadc5 -> 87e2f155
telethon.tl.types.MessageMediaDocument: 4cf4d72d -> dd570bd5
telethon.tl.types.MessageMediaGiveaway: daad85b0 -> aa073beb
telethon.tl.types.MessageMediaGiveawayResults: c6991068 -> ceaa3ea1
telethon.tl.types.MessageReactions: 4f2b9479 -> 0a339f0b
telethon.tl.types.SimpleWebViewResultUrl: 882f76bb -> None
telethon.tl.types.SponsoredMessage: bdedf566 -> 4d93a990
telethon.tl.types.StarsTransaction: cc7079b2 -> ee7522d5
telethon.tl.types.UpdateMessageExtendedMedia: 5a73a98c -> d5a41724
telethon.tl.types.User: 215c4438 -> 83314fca
telethon.tl.types.WebViewResultUrl: 0c14557c -> 4d22ff98
telethon.tl.types.auth.SentCodeTypeFirebaseSms: 13c90f17 -> 009fd736
telethon.tl.types.payments.GiveawayInfoResults: 00cd5570 -> e175e66f
telethon.tl.types.payments.StarsStatus: 8cf4ee60 -> bbfa316c
```

I dug a bit into the previous versions, and it seems that backward compatibility within minor versions is not maintained.

For example, `telethon.tl.patched.Message` in 1.35.0 was `2357bf25`, became `94345242` in 1.36.0.

This is consistent with layer changes in schema.

So it's perhaps not a bug per se, just an (unfounded) expectation that Telethon would support previous schema layers - and if someone wants to persist TL objects, then pinning Telethon version is necessary.

**Comment by Lonami** [comment]
> backward compatibility within minor versions is not maintained

Indeed, not when it comes to raw API changes, and v1's hacky Message inherits the raw type pretty blatantly. So any changes in it also affect it.
