### ISSUE TITLE
Argument out of Range using GetParticipantsRequest()

### ISSUE THREAD

**Issue by mrUlrik** [LonamiWebs/Telethon#459]
I am using the example provided at
https://github.com/LonamiWebs/Telethon/wiki/Retrieving-all-chat-members

At application start up I fetch a list of PeerChannel using get_dialog. I am looping through the list with the hopes of using GetParticipantsRequest().

I'm populating an InputChannel with PeerChannel.id and PeerChannel.access_hash. The example does not show that hash is a required field, though when using the method it states it requires it, so I provide it PeerChannel.access_hash there too.

**Line 92 is: input_channel, search, offset, limit, sub.access_hash**
````
offset = 0
limit = 10
search = ChannelParticipantsSearch('')
input_channel = InputChannel(
    sub.id, sub.access_hash
)

participants = self.invoke(GetParticipantsRequest(
    input_channel, search, offset, limit, sub.access_hash
))
````

**Traceback**
````
Traceback (most recent call last):
  File "\myproject\myproject.py", line 92, in __init__
    sub, search, offset, limit, sub.access_hash
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 439, in __call__
    sender, call_receive, update_state, *requests
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 493, in _invoke
    sender.send(*requests)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\network\mtproto_sender.py", line 91, in send
    self._send_message(message)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\network\mtproto_sender.py", line 133, in _send_message
    + bytes(message)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\tl\tl_message.py", line 25, in __bytes__
    body = GzipPacked.gzip_if_smaller(self.request)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\tl\gzip_packed.py", line 22, in gzip_if_smaller
    data = bytes(request)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\tl\message_container.py", line 26, in __bytes__
    ) + b''.join(bytes(m) for m in self.messages)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\tl\message_container.py", line 26, in <genexpr>
    ) + b''.join(bytes(m) for m in self.messages)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\tl\tl_message.py", line 25, in __bytes__
    body = GzipPacked.gzip_if_smaller(self.request)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\tl\gzip_packed.py", line 22, in gzip_if_smaller
    data = bytes(request)
  File "\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\tl\functions\channels.py", line 980, in __bytes__
    struct.pack('<i', self.hash),
struct.error: argument out of range
````

**Comment by Lonami** [comment]
[Quote](https://github.com/LonamiWebs/Telethon/wiki/Accessing-the-Full-API#notes):
> Note that some requests have a "hash" parameter. This is **not** your `api_hash`! It likely isn't your self-user `.access_hash` either. It's a special hash used by Telegram to only send a difference of new data that you don't already have with that request, so you can leave it to 0, and it should work (which means no hash is known yet).

So use 0.
