### ISSUE TITLE
Need help to UploadProfilePhotoRequest

### ISSUE THREAD

**Issue by plexab** [LonamiWebs/Telethon#468]
I use the code:

**from telethon.tl.functions.photos import UploadProfilePhotoRequest
...
client.invoke(UploadProfilePhotoRequest(file='C:/Users/DDD/Pictures/pic/image52.jpg')**

does not work for me, and an error is issued:

`Traceback (most recent call last):
UploadProfilePhotoRequest(file='C:/Users/DDD/Pictures/pic/image52.jpg')
  File "C:/Users/DDD/PycharmProjects/tel_tst/tele.py", line 65, in <module>
    resu = client.invoke(UploadProfilePhotoRequest(file='C:/Users/DDD/Pictures/pic/image52.jpg'))
  File "C:\Program Files\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 439, in __call__
    sender, call_receive, update_state, *requests
  File "C:\Program Files\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 493, in _invoke
    sender.send(*requests)
  File "C:\Program Files\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 91, in send
    self._send_message(message)
  File "C:\Program Files\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 133, in _send_message
    + bytes(message)
  File "C:\Program Files\Python36\lib\site-packages\telethon\tl\tl_message.py", line 25, in __bytes__
    body = GzipPacked.gzip_if_smaller(self.request)
  File "C:\Program Files\Python36\lib\site-packages\telethon\tl\gzip_packed.py", line 22, in gzip_if_smaller
    data = bytes(request)
  File "C:\Program Files\Python36\lib\site-packages\telethon\tl\message_container.py", line 26, in __bytes__
    ) + b''.join(bytes(m) for m in self.messages)
  File "C:\Program Files\Python36\lib\site-packages\telethon\tl\message_container.py", line 26, in <genexpr>
    ) + b''.join(bytes(m) for m in self.messages)
  File "C:\Program Files\Python36\lib\site-packages\telethon\tl\tl_message.py", line 25, in __bytes__
    body = GzipPacked.gzip_if_smaller(self.request)
  File "C:\Program Files\Python36\lib\site-packages\telethon\tl\gzip_packed.py", line 22, in gzip_if_smaller
    data = bytes(request)
  File "C:\Program Files\Python36\lib\site-packages\telethon\tl\functions\photos.py", line 180, in __bytes__
    bytes(self.file),
TypeError: string argument without an encoding

Process finished with exit code 1
`

Thanks

**Comment by plexab** [comment]
Solved

**Comment by Lonami** [comment]
Say how. That'll help other people.

**Comment by plexab** [comment]
before need call **client.upload_file**

**input_file = client.upload_file('photo.jpg')
result = client.invoke(UploadProfilePhotoRequest(input_file))**

**Comment by Lonami** [comment]
Okay but why did you reopen this.
