### ISSUE TITLE
ValueError: The result of the invoked request is always None

### ISSUE THREAD

**Issue by chabanovsky** [LonamiWebs/Telethon#48]
After I switched to the upstream version I got the following error a few times

> ValueError: The result of the invoked request is always None

Here is my traceback.

```
Traceback (most recent call last):
  File "site/rudevs.py", line 29, in <module>
    client.start()
  File "/development/rudevs/chats/telegram/telegram.py", line 105, in start
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 100, in sync_telegram
    self.get_content(channels, self.telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 62, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 363, in get_message_history
    add_offset=add_offset))
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 179, in invoke
    raise ValueError('The result of the invoked request is always None')
ValueError: The result of the invoked request is always None
```

I do not know how exactly to reproduce the error. As I understand it happens if I join new a channel then try to `get_history` with 30 messages.

**Comment by Lonami** [comment]
Did you try commenting out the line I told you?

**Comment by chabanovsky** [comment]
@Lonami Could you please point me to the line that I should change? Sorry, I could forget to change it.

**Comment by Lonami** [comment]
Heh this is the third time 😄

The line is the 235 on `mtproto_sender.py`, under `telethon/network`, that is, [this one](https://github.com/LonamiWebs/Telethon/blob/f24d4f4a0e629d65d19b9e37d03efdfa6cd07b57/telethon/network/mtproto_sender.py#L235) :)

**Comment by chabanovsky** [comment]
Oops. I rewrote it during the last pull. Now I commented it out. Testing...

**Comment by chabanovsky** [comment]
Got the following error

```

WARNING:root:Message ack confirmed a request
WARNING:root:Read RPC error: (RPCError(...), 'A wait of 16 seconds is required.')
Should wait 16s. Sleeping until then.
Exception in thread Updates thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 408, in updates_thread_method
    self.send_ping()
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 84, in send_ping
    self.receive(request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 138, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 221, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 281, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 243, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 256, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 100, in sync_telegram
    self.get_content(channels, self.telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 62, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 363, in get_message_history
    add_offset=add_offset))
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 179, in invoke
    raise ValueError('The result of the invoked request is always None')
ValueError: The result of the invoked request is always None
```

**Comment by Lonami** [comment]
This time the error is clear, the main thread did go to sleep after "A wait of 16 seconds is required." was received, but the updates thread did not, I assume the server refused to reply to the ping request or replying a message update? I will add the sleep on the updates thread, revert the last change of retries and ignore the acks…

**Comment by chabanovsky** [comment]
After the last update `--telethon-log=DEBUG` works for my app too. In the app I do not send anything the server. The app just listens a few channels (I'm going perform some ML/NLP tasks).

**Comment by Lonami** [comment]
Did this solve after fixing #47?

**Comment by chabanovsky** [comment]
@Lonami I have not seen this error anymore after I updated to upstream and changed code according your recommendations. It seems it was fixed.

**Comment by Lonami** [comment]
> It seems it was fixed.

Alright then, if you don't mind I will close this issue. Feel free to open it again if the bug reappears, or open a new issue if I introduced new bugs :P thanks for the help!

**Comment by chabanovsky** [comment]
Thank you for the library and the help!
