### ISSUE TITLE
Can not sign in: 'Two-steps verification is enabled and a password is required'

### ISSUE THREAD

**Issue by orkenstein** [LonamiWebs/Telethon#495]
Hi! 
Running `telethon 0.15.5.7`
Trying to login to account like this:
```
from telethon import TelegramClient

# These example values won't work. You must get your own api_id and
# api_hash from https://my.telegram.org, under API Development.
api_id = <id>
api_hash = <hash>
phone_number = <phone>

client = TelegramClient('session_name', api_id, api_hash)
client.connect()

if not client.is_user_authorized():
    client.send_code_request(phone_number)
    code = input('Enter code: ')
    print(code)
    myself = client.sign_in(phone=phone_number, code=code)
    print(myself.stringify())
```

The code is successfully delivered to my existing Telegram account (like 82489) and then I get the error on `sign_in` attempt:
```
Traceback (most recent call last):
  File "My_Script.py", line 16, in <module>
    myself = client.sign_in(phone_number, code)
  File "/Users/orkenstein/.local/share/virtualenvs/TelegramFun-Pi5t42Y5/lib/python3.6/site-packages/telethon/telegram_client.py", line 201, in sign_in
    result = self(SignInRequest(phone, phone_code_hash, code))
  File "/Users/orkenstein/.local/share/virtualenvs/TelegramFun-Pi5t42Y5/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 439, in __call__
    sender, call_receive, update_state, *requests
  File "/Users/orkenstein/.local/share/virtualenvs/TelegramFun-Pi5t42Y5/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 530, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.SessionPasswordNeededError: (SessionPasswordNeededError(...), 'Two-steps verification is enabled and a password is required')
```

What am I doing wrong?

**Comment by Lonami** [comment]
> What am I doing wrong?

Not reading the wiki/examples.

**Comment by orkenstein** [comment]
@Lonami that was fast :D

**Comment by SyrianProgrammer** [comment]
Hi @orkenstein please see this page:
https://github.com/LonamiWebs/Telethon/wiki/Two-Factor-Authorization
