### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by amirmohamad** [LonamiWebs/Telethon#510]
I got this error when run try_telethon.py 

```
Unexpected error (<class 'ValueError'>): too many values to unpack (expected 2) at
Traceback (most recent call last):
  File "try_telethon.py", line 43, in <module>
    client.run()
  File "/var/www/html/newtelethon/telethon_examples/interactive_telegram_client.py", line 141, in run
    dialogs, entities = self.get_dialogs(limit=dialog_count)
ValueError: too many values to unpack (expected 2)

Thanks for trying the interactive example! Exiting...
```

can you tell me why?

**Comment by Lonami** [comment]
@amirmohamad read the changelog.

**Comment by Lonami** [comment]
My bad though, forgot to update README and such.

**Comment by amirmohamad** [comment]
I'm waiting for update. thanks for instant answer

**Comment by Lonami** [comment]
Nothing to update, it simply doesn't return a `tuple` anymore.
