### ISSUE TITLE
.session file is not in json form

### ISSUE THREAD

**Issue by amirmohamad** [LonamiWebs/Telethon#511]
After sign in by `try_telethon.py` the `amir.session` is like this:
```
5351 4c69 7465 2066 6f72 6d61 7420 3300
0400 0101 0040 2020 0000 0008 0000 0007
0000 0000 0000 0000 0000 0003 0000 0004
0000 0000 0000 0000 0000 0001 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0008
002d e602 0d00 0000 0301 b900 03be 02cb
01b9 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0082 0f03 0717 1d1d
0183 7174 6162 6c65 656e 7469 7469 6573
```
and its contents is not in json form. for this reason I get this error:

```
==================
= Initialization =
==================
Initializing interactive example...
Traceback (most recent call last):
  File "/var/www/html/newtelethon/telethon/tl/session.py", line 141, in _check_migrate_json
    data = json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 98: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./try_telethon.py", line 38, in <module>
    **kwargs)
  File "/var/www/html/newtelethon/telethon_examples/interactive_telegram_client.py", line 84, in __init__
    update_workers=1
  File "/var/www/html/newtelethon/telethon/telegram_client.py", line 123, in __init__
    **kwargs
  File "/var/www/html/newtelethon/telethon/telegram_bare_client.py", line 96, in __init__
    session = Session(session)
  File "/var/www/html/newtelethon/telethon/tl/session.py", line 84, in __init__
    entities = self._check_migrate_json()
  File "/var/www/html/newtelethon/telethon/tl/session.py", line 157, in _check_migrate_json
    except (UnicodeDecodeError, json.decoder.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```
what is the problem?
I did not even add a line of code!

**Comment by Lonami** [comment]
It's `sqlite` now but I'll look into the second error.

**Comment by amirmohamad** [comment]
What should I do to solve the problem?

**Comment by Lonami** [comment]
Wait. It's strange because Python 3.6 does have `JSONDecodeError` inside `.decoder`:
```python
>>> import json
>>> json.loads('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'll just `except` the `UnicodeDecodeError`.
