### ISSUE TITLE
RPC_CALL_FAIL

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#512]
A few moments ago. About 30 of our accounts were faced with this error.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 505, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_errors.ServerError: (ServerError(...), 'RPC_CALL_FAIL')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "schedules.py", line 244, in <module>
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/home/hamoon/telegram_python_v2/schedules/safe_schedule.py", line 31, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "schedules.py", line 229, in create_process
    scheduler = SafeScheduler()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "schedules.py", line 142, in worker
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 447, in __call__
    result = self._invoke(sender, call_receive, *requests)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 534, in _invoke
    '[ERROR] Telegram is having some internal issues', e
Message: '[ERROR] Telegram is having some internal issues'
Arguments: (ServerError(ServerError(...), 'RPC_CALL_FAIL'),)
```
What does this message mean?

**Comment by Lonami** [comment]
https://outage.report/telegram. Telegram itself had issues and internal errors. Nothing I can do.
