### ISSUE TITLE
Unable to Auth Due to PhoneMigrateError

### ISSUE THREAD

**Issue by skeledrew** [LonamiWebs/Telethon#517]
I am following the tutorial in the wiki to use Telethon but I am unable to auth my phone number as I get a PhoneMigrateError when doing clt.send_code_request().
``` bash
>>> from telethon import TelegramClient as TGC
>>> api_id = 00000
>>> api_hash = '???????'
>>> phone = '+1##########'
>>> clt = TGC('gvoice', api_id, api_hash)
>>> clt.connect()
True
>>> clt.is_user_authorized()
False
>>> clt.send_code_request()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: send_code_request() missing 1 required positional argument: 'phone'
>>> clt.send_code_request(phone)
Traceback (most recent call last):
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 560, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/telegram_client.py", line 149, in send_code_request
    result = self(SendCodeRequest(phone, self.api_id, self.api_hash))
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 474, in __call__
    sender, call_receive, update_state, *requests
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 579, in _invoke
    self._reconnect(new_dc=e.new_dc)
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 297, in _reconnect
    dc = self._get_dc(new_dc)
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 326, in _get_dc
    TelegramBareClient._config = self(GetConfigRequest())
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 474, in __call__
    sender, call_receive, update_state, *requests
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 538, in _invoke
    sender.receive(update_state=update_state)
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 147, in receive
    self._process_msg(remote_msg_id, remote_seq, reader, update_state)
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 226, in _process_msg
    return self._handle_rpc_result(msg_id, sequence, reader)
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 523, in _handle_rpc_result
    request.on_response(reader)
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/tl/functions/help.py", line 134, in on_response
    self.result = reader.tgread_object()
  File "/home/skeledrew/.pyenv/versions/general/lib/python3.6/site-packages/telethon/extensions/binary_reader.py", line 136, in tgread_object
    raise TypeNotFoundError(constructor_id)
telethon.errors.common.TypeNotFoundError: (TypeNotFoundError(...), 'Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 0x232d5905. Most likely, a TLObject was trying to be read when it should not be read.')
>>> TGC.__version__
'0.16.0.4'
```
None of the other related issues here (or anywhere else on the web I found) have been helpful, however doing a little searching got me to [this resource](https://core.telegram.org/api/datacenter). So if the issue is that the datacenter is incorrect, how can I find the current DC and change it? If not, what else may be the issue? What other steps can I take to troubleshoot?

Thanks.

**Comment by LeeHJones** [comment]
I just got this same error when I ported a piece of code to a new Mac laptop. It's running OS Sierra 10.12.6. The code works just fine on El Capitan 10.11. I had DEBUG turned on for other reasons, and got this:

```
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 560, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 1')

```

Again, the program works fine on my old Mac running El Capitan 10.11, but breaks on Sierra 10.12.6.

**Comment by brhenrique** [comment]
Same here, using Ubuntu 16.10 and Python 3.6

```
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 560, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 1')
```

**Comment by Lonami** [comment]
Ohh it might be https://github.com/LonamiWebs/Telethon/commit/2a10f315119283b2976261f2585551610b680320.

**Comment by Lonami** [comment]
Anyone can test this? I pushed `v0.16.0.5` to PyPi.

**Comment by skeledrew** [comment]
@Lonami just updated and it's working great. Thanks!

**Comment by Lonami** [comment]
Alrighty. Still not sure why it wasn't working though.
