### ISSUE TITLE
Issue with Heroku

### ISSUE THREAD

**Issue by vitalibr** [LonamiWebs/Telethon#523]
I'm trying to run my script on heroku, but it's crashing. On my computer, it works perfectly, I do not know what that mistake might be.
I'm using file session.
it creates the .session file but fails shortly after.
error:
```Traceback (most recent call last):
  File "app.py", line 71, in <module>
    init_client()
  File "app.py", line 36, in init_client
    spawn_read_thread=False)
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/telegram_client.py", line 123, in __init__
    **kwargs
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 96, in __init__
    session = Session(session)
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/tl/session.py", line 117, in __init__
    ) without rowid"""
sqlite3.OperationalError: near "without": syntax error
INFO:telethon.telegram_bare_client:Disconnecting...
DEBUG:telethon.telegram_bare_client:Stopping all workers...
```

Heroku env:
python3 --version
Python 3.6.3

My local machine:
python3 --version                   
Python 3.6.2

----------

Running this code:
```python
import sqlite3
print(sqlite3.version)
print(sqlite3.sqlite_version)
```
version - pysqlite version
sqlite_version - sqlite version

on my local machine:
2.6.0
3.19.3

on heroku:
2.6.0
3.7.9

**Comment by Lonami** [comment]
Yes, looks like the lower `sqlite` version of Heroku is causing this issue. Can they upgrade?

**Comment by Lonami** [comment]
I guess this also works.
