### ISSUE TITLE
ImportError: cannot import name 'helpers'

### ISSUE THREAD

**Issue by amirRamirfatahi** [LonamiWebs/Telethon#524]
hi, I have python 3.4 and telethon 0.16.0.9
```python
from telegramCrawler import telethon
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/amir/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/amir/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/amir/Pegah/khabargardi-django-hermes/Hermes/telegramCrawler/telethon.py", line 1, in <module>
    from telethon import TelegramClient
  File "/home/amir/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/amir/.virtualenvs/test/lib/python3.4/site-packages/telethon/__init__.py", line 2, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/home/amir/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/amir/.virtualenvs/test/lib/python3.4/site-packages/telethon/telegram_bare_client.py", line 12, in <module>
    from . import helpers as utils, version
  File "/home/amir/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/amir/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/amir/.virtualenvs/test/lib/python3.4/site-packages/telethon/helpers.py", line 6, in <module>
    from telethon.crypto import AES
  File "/home/amir/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/amir/.virtualenvs/test/lib/python3.4/site-packages/telethon/crypto/__init__.py", line 8, in <module>
    from .auth_key import AuthKey
  File "/home/amir/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/amir/.virtualenvs/test/lib/python3.4/site-packages/telethon/crypto/auth_key.py", line 7, in <module>
    from .. import helpers as utils
ImportError: cannot import name 'helpers'

**Comment by Lonami** [comment]
Patched on https://github.com/LonamiWebs/Telethon/commit/f4182376f13f9f801cd5b26517ba54dd6daa3777 and https://github.com/LonamiWebs/Telethon/commit/3c686fecdfc22a2ed7eb3c97f7bd1c156eff94d7. Not on PyPi. Will push now.

**Comment by Lonami** [comment]
Upgrade to v0.16.0.10.

**Comment by amirRamirfatahi** [comment]
thanks a lot!
didn't expect that speed!

**Comment by amirRamirfatahi** [comment]
hi can I get technical advice and help from you?
it would be a great help to me
