### ISSUE TITLE
Connection Reset on Heroku

### ISSUE THREAD

**Issue by GiovanniCardamone** [LonamiWebs/Telethon#532]
I'm trying to deploy an app to Herkou, but the tcp client got Connection Reset, so i'm unable to connect to telegram,

i'm using the version `telethon = "==0.15.5.7"`,

here the log
```
Traceback (most recent call last):
  File "app_main.py", line 15, in main
    kernel = Kernel(config, users)
  File "/app/utils/Singleton.py", line 7, in get_instance
    instances[cls] = cls(*args, **kwargs)
  File "/app/app/Kernel.py", line 71, in __init__
    self.clients.append(self.create_client(user))
  File "/app/app/Kernel.py", line 127, in create_client
    client.inject(i)
  File "/app/app/clients/ChatClient.py", line 27, in inject
    if issubclass(data,ChatModule) : self.load_module(data)
  File "/app/app/clients/ChatClient.py", line 50, in load_module
    module.load(self)
  File "/app/app/contracts/ChatModule.py", line 94, in load
    self.id = self.client.client.get_entity(self.recipient).id
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/telegram_client.py", line 1052, in get_entity
    return self._get_entity_from_string(entity)
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/telegram_client.py", line 1078, in _get_entity_from_string
    self(ResolveUsernameRequest(entity))
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 439, in __call__
    sender, call_receive, update_state, *requests
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 479, in _invoke
    authenticator.do_authentication(self._sender.connection)
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/network/authenticator.py", line 27, in do_authentication
    return _do_authentication(connection)
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/network/authenticator.py", line 45, in _do_authentication
    sender.send(bytes(req_pq_request))
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/network/mtproto_plain_sender.py", line 30, in send
    struct.pack('<QQi', 0, self._get_new_msg_id(), len(data)) + data
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/network/connection.py", line 182, in _send_tcp_full
    self.write(data + crc)
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/network/connection.py", line 219, in _write_plain
    self.conn.write(data)
  File "/app/.heroku/python/lib/python3.6/site-packages/telethon/extensions/tcp_client.py", line 108, in write
    raise ConnectionResetError()
ConnectionResetError
```

as you can see the error is on  `client.get_entity` method, but i cannot understand why.

-Thanks

**Comment by Lonami** [comment]
First time ever I see a `ConnectionResetError` while authenticating…:
https://github.com/LonamiWebs/Telethon/blob/4f441219b164e6f5dee5e12f356869c40c8ba7ef/telethon/network/authenticator.py#L59

**Comment by Lonami** [comment]
So first of all you should upgrade the library to `v0.16`. Second you should make sure that you've signed in and authorized successfully before running `.get_entity()`.

**Comment by Lonami** [comment]
Also make sure you've called `.connect()`:
https://github.com/LonamiWebs/Telethon/blob/4f441219b164e6f5dee5e12f356869c40c8ba7ef/telethon/telegram_bare_client.py#L511-L518

**Comment by GiovanniCardamone** [comment]
ok, i got why this happned, i stored the session in a folder missing in git because was in .gitignore,
adding that folder to project solved the issue.

Sorry, but i didn't noticed because the client apparently was connected. thanks for help.
