### ISSUE TITLE
Could not find user with username XXXXXXXX

### ISSUE THREAD

**Issue by rezakeramati** [LonamiWebs/Telethon#553]
I'm trying to send a user (which I know he has Telegram account) a message, having his phone number.
I face the following stacktrace (where XXXXXXXXXXXX is the phone number):
But if I add him to my contacts, I don't give this error
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\tl\entity_database.py", line 159, in _parse_key
    return self._phone_id[phone]
KeyError: 'XXXXXXXXXXXX'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\tl\entity_database.py", line 182, in __getitem__
    return self._entities[self._parse_key(key)]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\tl\entity_database.py", line 164, in _parse_key
    raise ValueError() from e
ValueError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\telegram_client.py", line 1081, in _get_entity_from_string
    return self.session.entities[entity]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\tl\entity_database.py", line 184, in __getitem__
    raise KeyError(key) from e
KeyError: 'XXXXXXXXXXXX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 51, in <module>
    client.send_message(mobile,message)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\telegram_client.py", line 390, in send_message
    entity = self.get_input_entity(entity)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\telegram_client.py", line 1113, in get_input_entity
    return utils.get_input_peer(self._get_entity_from_string(peer))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\telegram_client.py", line 1084, in _get_entity_from_string
    'Could not find user with username {}'.format(entity)
ValueError: Could not find user with username XXXXXXXXXXXX
```

**Comment by Lonami** [comment]
Upgrade.

**Comment by rezakeramati** [comment]
@Lonami 
Getting this error on the latest version
```
C:\Users\Administrator\Desktop\scripts\Telegram>C:\Users\Administrator\AppData\L
ocal\Programs\Python\Python36\python.exe client.py 164398 9cc25592973cd875af43dc
1fb82c1e75 MRB
Traceback (most recent call last):
  File "client.py", line 51, in <module>
    client.send_message(mobile,message)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\telegram_client.py", line 578, in send_message
    entity = self.get_input_entity(entity)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\telegram_client.py", line 1713, in get_input_entity
    return utils.get_input_peer(self._get_entity_from_string(peer))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\telethon\telegram_client.py", line 1680, in _get_entity_from_string
    'Cannot turn "{}" into any entity (user or chat)'.format(string)
TypeError: Cannot turn "+98XXXXXXXXXX" into any entity (user or chat)
```

**Comment by Lonami** [comment]
You need to "see" that user first so call `GetContactsRequest` until you find him, then it should work.

**Comment by rezakeramati** [comment]
@Lonami 
I have his number but he is not in my contacts. Does that still work?

**Comment by Lonami** [comment]
@rezakeramati no.
