### ISSUE TITLE
How to disable database storage for sessions?

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#560]
I'm getting this error while trying to use TelegramClient.
I don't want to use any DBs, just ".session" files and memory, so how do I disable it?
```
  File "C:\Users\Администратор\Desktop\Controller_bot\classes\Client.py", line 89, in reconnect
    spawn_read_thread=False)
  File "C:\Python\lib\site-packages\telethon\telegram_client.py", line 160, in __init__
    **kwargs
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 101, in __init__
    DEFAULT_PORT
  File "C:\Python\lib\site-packages\telethon\session.py", line 223, in set_dc
    self._update_session_table()
  File "C:\Python\lib\site-packages\telethon\session.py", line 260, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
```

**Comment by Lonami** [comment]
You can't disable it, but I'll look into fixing it. Could you describe what were you doing exactly to trigger this issue, and the SQLite version you're using?

**Comment by vegeta1k95** [comment]
I'm using a lot (>20) of TelegramClients with different session files in parallel processes (multiprocessing module), it seems they concurently trying to write into DB. SQLite 2.6.0

**Comment by Lonami** [comment]
Are you using a different session name for each client? Otherwise you shouldn't be doing that.

**Comment by vegeta1k95** [comment]
Yes, different session name for each client.

**Comment by Lonami** [comment]
It's quite strange several clients are trying to access the same session file then…

**Comment by vegeta1k95** [comment]
Is it crucial if I just comment line 

> self._update_session_table()

in set_dc in session.py?

I don't care about DBs really if info is taken from .session files otherwise.

**Comment by Lonami** [comment]
Those lines are needed to persist the updated information in the database, and yes, the right IP address and authorization key must match if you want it to work (or you'll be "signed out"). There must be a reason why this is occuring which I can't think of and a better fix. Using sqlite is in my opinion a big improvement and I don't have plans to revert to JSON, so I would really appreciate if you collaborated to helo me out fix this as I haven't been able to reproduce the issue.

**Comment by vegeta1k95** [comment]
The only information I can provide is that this error happened after reconnection attempt after connection got dropped due to proxy timeout. Maybe previous DB connection didn't close properly before reconnection.
Here's my code:

> for _ in range(self.retries):
>             try:
>                 proxy = self.get_new_proxy(timeout=timeout)
>                 self.logger.info('Trying to connect to proxy', proxy[1] + ':' + str(proxy[2]))
>                 self.client = TelegramClient(self.session,
>                          cfg.api_id, cfg.api_hash,
>                          proxy = proxy,
>                          spawn_read_thread=False)
>                 self.logger.info('Connecting...')   
>                 self.client.connect()
>                 self.logger.info('Connected.')
>                 self.update_status(online=True) 
>             except Exception as err:
>                 self.logger.error('ERROR while trying to reconnect', err)
>                 try:
>                     self.client.disconnect()
>                 except: pass

Here's my log:

[26-01-2018 01:20:57]: ================================================
[26-01-2018 01:20:57]:               Initialization... 
[26-01-2018 01:20:57]:               Trying to connect to proxy 123.201.139.190:14605 
[26-01-2018 01:20:57]:               Connecting... 
[26-01-2018 01:21:02]:               #[ERROR]# ERROR while trying to reconnect Error connecting to SOCKS5 proxy 123.201.139.190:14605: timed out 
[26-01-2018 01:21:02]:               #[Traceback]# Traceback (most recent call last):
  File "C:\Python\lib\site-packages\socks.py", line 794, in connect
    super(socksocket, self).connect(proxy_addr)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\Controller_bot\classes\Client.py", line 91, in reconnect
    self.client.connect()
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 193, in connect
    self._sender.connect()
  File "C:\Python\lib\site-packages\telethon\network\mtproto_sender.py", line 62, in connect
    self.connection.connect(self.session.server_address, self.session.port)
  File "C:\Python\lib\site-packages\telethon\network\connection.py", line 100, in connect
    self.conn.connect(ip, port)
  File "C:\Python\lib\site-packages\telethon\extensions\tcp_client.py", line 75, in connect
    self._socket.connect(address)
  File "C:\Python\lib\site-packages\socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "C:\Python\lib\site-packages\socks.py", line 806, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 123.201.139.190:14605: timed out

[26-01-2018 01:21:02]:               #[ERROR]# Trying to handle error: Error connecting to SOCKS5 proxy 123.201.139.190:14605: timed out 
[26-01-2018 01:21:02]:               #[Traceback]# Traceback (most recent call last):
  File "C:\Python\lib\site-packages\socks.py", line 794, in connect
    super(socksocket, self).connect(proxy_addr)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\Controller_bot\classes\Client.py", line 91, in reconnect
    self.client.connect()
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 193, in connect
    self._sender.connect()
  File "C:\Python\lib\site-packages\telethon\network\mtproto_sender.py", line 62, in connect
    self.connection.connect(self.session.server_address, self.session.port)
  File "C:\Python\lib\site-packages\telethon\network\connection.py", line 100, in connect
    self.conn.connect(ip, port)
  File "C:\Python\lib\site-packages\telethon\extensions\tcp_client.py", line 75, in connect
    self._socket.connect(address)
  File "C:\Python\lib\site-packages\socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "C:\Python\lib\site-packages\socks.py", line 806, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 123.201.139.190:14605: timed out

[26-01-2018 01:21:02]:               #[ERROR]# Error value None 
[26-01-2018 01:21:02]:               #[Traceback]# Traceback (most recent call last):
  File "C:\Python\lib\site-packages\socks.py", line 794, in connect
    super(socksocket, self).connect(proxy_addr)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\Controller_bot\classes\Client.py", line 91, in reconnect
    self.client.connect()
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 193, in connect
    self._sender.connect()
  File "C:\Python\lib\site-packages\telethon\network\mtproto_sender.py", line 62, in connect
    self.connection.connect(self.session.server_address, self.session.port)
  File "C:\Python\lib\site-packages\telethon\network\connection.py", line 100, in connect
    self.conn.connect(ip, port)
  File "C:\Python\lib\site-packages\telethon\extensions\tcp_client.py", line 75, in connect
    self._socket.connect(address)
  File "C:\Python\lib\site-packages\socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "C:\Python\lib\site-packages\socks.py", line 806, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 123.201.139.190:14605: timed out

[26-01-2018 01:21:02]:               Waiting for new proxy... 
[26-01-2018 01:21:02]:               Proxy has been obtained. 
[26-01-2018 01:21:02]:               Trying to connect to proxy 187.64.245.121:15786 
[26-01-2018 01:21:08]:               #[ERROR]# ERROR while trying to reconnect database is locked 
[26-01-2018 01:21:08]:               #[Traceback]# Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\Controller_bot\classes\Client.py", line 89, in reconnect
    spawn_read_thread=False)
  File "C:\Python\lib\site-packages\telethon\telegram_client.py", line 160, in __init__
    **kwargs
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 101, in __init__
    DEFAULT_PORT
  File "C:\Python\lib\site-packages\telethon\session.py", line 223, in set_dc
    self._update_session_table()
  File "C:\Python\lib\site-packages\telethon\session.py", line 260, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked

**Comment by Lonami** [comment]
Okay. So I never close the database and that might be the issue? I'm not sure when it should be closed. On `disconnect()`? But it might be needed also while disconnecting (e.g., to perform the initial connection). I'm not sure how to get around this in a clean way.

**Comment by Lonami** [comment]
Okay I've pushed `v0.16.2.3` to PyPi could you please try? Yeah I see you're using the same filename but the other connection is never explicitly closed so I guess calling its `__del__` takes a while.

**Comment by ingria** [comment]
+1 for supporting JSON storage. Sqlite is overkill and pain in the ass, especially when using Telethon in something more serious than pet project.

**Comment by Lonami** [comment]
Excuse me? What's a pain in the ass is reinventing the wheel to map usernames and such to ID and hash, which sqlite does well. Storing IDs and hashes in JSON is a bad idea.

**Comment by ingria** [comment]
We've already discussed this problem in #484. Not planning to argue, just providing feedback from (rather) big project.

Anyway, thank God you didn't choose MongoDB. 🤷‍♂️

**Comment by Lonami** [comment]
Yeah, I wouldn't add a rather big dependency like that, but really, sqlite totally makes sense here. I don't have many devices to test this on so user feedback like this is the only way to get this right. If only I could reproduce every bug around here…

**Comment by vegeta1k95** [comment]
Ok, fix #560 seems to work fine. No more DB locked errors.

**Comment by Lonami** [comment]
Neat.

**Comment by excelenz** [comment]
the same. I have telegram client open in the same machine, so when i close it the error dissapear.
