### ISSUE TITLE
Inline Answer Timeout Error

### ISSUE THREAD

**Issue by 12102man** [LonamiWebs/Telethon#563]
Hello everyone,

I was trying to make a test for my bot, and this is what I got:
`Traceback (most recent call last):
  File "/Users/mikhailtkachenko/PycharmProjects/InnoLib/testbot.py", line 77, in <module>
    testEnrollProcess()
  File "/Users/mikhailtkachenko/PycharmProjects/InnoLib/testbot.py", line 58, in testEnrollProcess
    data='Faculty'
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 440, in __call__
    result = self._invoke(call_receive, *requests)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 529, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_base_errors.RPCError: Timeout (code -503)
`

Also it looks like everything works properly, because my bot reacts properly on button pressing. The problem is that telethon presses this button for 4 times and then raises an exception. I saw issue #326 with the same problem, but there's no solution. Waiting for your reply, thanks!

**Comment by Lonami** [comment]
I'm closing this since you said you worked around it [here](https://github.com/LonamiWebs/Telethon/issues/326#issuecomment-360975459). Further discussion should happen there. Still not sure what should the library do…
