### ISSUE TITLE
telethon  does not work under proxy

### ISSUE THREAD

**Issue by JohnsonElizee** [LonamiWebs/Telethon#574]
1. my mac is using proxy, it's failed to run telethon, blocked on .start() or .connect()
2. I set proxy info for telethon, it does not work too.
code:-----------------------------------------------------

import logging
import socks
logging.basicConfig(level=logging.DEBUG)
from telethon import TelegramClient

api_id = xxxxx
api_hash = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

host = '127.0.0.1'
host = 'localhost'
port = 49330
proxy = (socks.SOCKS5, host, port)

#client = TelegramClient('session_1', api_id, api_hash, proxy)
client = TelegramClient('session_1', api_id, api_hash)
client.start()

erro:----------------------------------------------------------
INFO:telethon.telegram_bare_client:Connecting to 149.154.167.51:443...
INFO:telethon.telegram_bare_client:Connection success!
DEBUG:telethon.telegram_bare_client:Invoking GetStateRequest
INFO:telethon.telegram_bare_client:Initializing a new connection while invoking
Traceback (most recent call last):
  File "newclient.py", line 17, in <module>
    client.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_client.py", line 261, in start
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 202, in connect
    self.sync_updates()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 586, in sync_updates
    self.updates.process(self(GetStateRequest()))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 441, in __call__
    result = self._invoke(call_receive, *requests)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 486, in _invoke
    self._sender.send(*requests)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 108, in send
    self._send_message(message)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 160, in _send_message
    self.connection.send(utils.pack_message(self.session, message))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/network/connection.py", line 240, in send
    raise ValueError('Invalid connection mode specified: ' + str(self._mode))
# ValueError: Invalid connection mode specified: (2, 'localhost', 49330)
INFO:telethon.telegram_bare_client:Disconnecting...
DEBUG:telethon.telegram_bare_client:Stopping all workers...
DEBUG:telethon.telegram_bare_client:Disconnecting the socket...

-------------------------------------------------------------------------
thank u for any info to help me fix this issue

**Comment by Lonami** [comment]
> ValueError: Invalid connection mode specified: (2, 'localhost', 49330)

Well, there you have it. The parameter on which you passed the proxy is actually for the **connection mode and NOT the proxy**. So you can try [RTFM](http://telethon.readthedocs.io/en/latest/extra/basic/creating-a-client.html?highlight=proxy#creating-a-client) which is actually described in [several places](http://telethon.readthedocs.io/en/latest/extra/basic/telegram-client.html#telethon.telegram_client.TelegramClient).
