### ISSUE TITLE
ERROR: test_authenticator (telethon_tests.network_test.NetworkTests)

### ISSUE THREAD

**Issue by kissste** [LonamiWebs/Telethon#592]
Hi,
I'm trying to run "python3 run_tests.py"
and getting the following error(s):

Run network tests (y/n)?: y
..F.F....E.
======================================================================
ERROR: test_authenticator (telethon_tests.network_test.NetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/steve/Telethon/telethon_tests/network_test.py", line 42, in test_authenticator
    authenticator.do_authentication(transport)
  File "/home/steve/Telethon/telethon/network/authenticator.py", line 39, in do_authentication
    return _do_authentication(connection)
  File "/home/steve/Telethon/telethon/network/authenticator.py", line 59, in _do_authentication
    sender.send(bytes(req_pq_request))
  File "/home/steve/Telethon/telethon/network/mtproto_plain_sender.py", line 45, in send
    struct.pack('<QQi', 0, self._get_new_msg_id(), len(data)) + data
  File "/home/steve/Telethon/telethon/network/connection.py", line 240, in send
    raise ValueError('Invalid connection mode specified: ' + str(self._mode))
ValueError: Invalid connection mode specified: 149.154.167.40

======================================================================
FAIL: test_calc_key (telethon_tests.crypto_test.CryptoTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/steve/Telethon/telethon_tests/crypto_test.py", line 82, in test_calc_key
    expected_key, key)
AssertionError: Invalid key (expected ("b"\xaf\.....""), got ("b"\xdc.....""))

======================================================================
FAIL: test_fingerprint_from_key (telethon_tests.crypto_test.CryptoTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/steve/Telethon/telethon_tests/crypto_test.py", line 127, in test_fingerprint_from_key
    )) == b'!k\xe8l\x02+\xb4\xc3', 'Wrong fingerprint calculated'
AssertionError: Wrong fingerprint calculated

----------------------------------------------------------------------
Ran 11 tests in 0.055s

FAILED (failures=2, errors=1)

Any ideas?

Thank you

**Comment by kissste** [comment]
Never mind, found it:
https://github.com/LonamiWebs/Telethon/pull/385/commits/84f8f6e013b6b687bfa07fb3afca766eb526d6ff
