### ISSUE TITLE
Some DB error

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#593]
Some sessions have this error when creating new clients:
```
 Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\Controller_bot\classes\Client.py", line 89, in reconnect
    spawn_read_thread=False)
  File "C:\Python\lib\site-packages\telethon\telegram_client.py", line 159, in __init__
    **kwargs
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 88, in __init__
    session = Session(session)
  File "C:\Python\lib\site-packages\telethon\session.py", line 110, in __init__
    version = c.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Lonami** [comment]
Right, easy fix.

**Comment by Lonami** [comment]
I'm actually not sure how you managed to get the database in such situation… there should always be a value in there.

**Comment by Lonami** [comment]
I'm going to close this, the database is in a weird state. If you find a way on how to reproduce consistently let me know.
