### ISSUE TITLE
Error: The phone number a user is trying to use for authorization is associated with DC 4

### ISSUE THREAD

**Issue by chri1389** [LonamiWebs/Telethon#606]
Hello,

I have implemented a client telegram (telethon API).
If I use a specific user number, it run very well.
If I use an other user number, there is a problem:
Traceback (most recent call last):
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 527, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 4')

N.B. this last user number, until yesterday worked very well.

Why??

Thank you very much!

**Comment by Lonami** [comment]
@chri1389 what's your Python code and library version?

**Comment by chri1389** [comment]
my python code version is 3 (I run the script with "python3 scriptName.py")..

**Comment by Lonami** [comment]
@chri1389 not what I asked. I want the Python source code you programmed and the version of the Telethon library you have installed.

**Comment by chri1389** [comment]
Code:
`from telethon import TelegramClient
api_id = 
api_hash = ''

client = TelegramClient(input("Insert name sessione:"), api_id, api_hash)
client.start()`


THIS IS THE OUTPUT:
Insert name sessione:chri
Please enter your phone: *****
Traceback (most recent call last):
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 527, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 4')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "telegram_gate.py", line 11, in <module>
    client.start()
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 292, in start
    sent_code = self.send_code_request(phone, force_sms=force_sms)
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 196, in send_code_request
    result = self(SendCodeRequest(phone, self.api_id, self.api_hash))
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 438, in __call__
    result = self._invoke(call_receive, *requests)
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 547, in _invoke
    return self._invoke(call_receive, *requests)
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 527, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.FloodWaitError: (FloodWaitError(...), 'A wait of 74263 seconds is required')




**********

If I use an other telephone number, it runs well (it asks the code etc.)...

I am sorry, How can see the telethon version installed?

**Comment by chri1389** [comment]
THIS IS THE OUTPUT:

Insert name session:chri
Please enter your phone: *****
Traceback (most recent call last):
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 527, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 4')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "telegram_gate.py", line 11, in <module>
    client.start()
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 292, in start
    sent_code = self.send_code_request(phone, force_sms=force_sms)
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 196, in send_code_request
    result = self(SendCodeRequest(phone, self.api_id, self.api_hash))
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 438, in __call__
    result = self._invoke(call_receive, *requests)
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 547, in _invoke
    return self._invoke(call_receive, *requests)
  File "/home/christian/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 527, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.FloodWaitError: (FloodWaitError(...), 'A wait of 74263 seconds is required')




**********

If I use an other telephone number, it runs well (it asks the code etc.)...
Why?

**Comment by Lonami** [comment]
`PhoneMigrateError` is handled fine. The problem is you need to `FloodWaitError` for `A wait of 74263 seconds`.
