### ISSUE TITLE
BlockingIOError: [Errno 35] Resource temporarily unavailable

### ISSUE THREAD

**Issue by chabanovsky** [LonamiWebs/Telethon#61]
After the last update from the upstream I get the following error each time (as I understand) when I lose an internet connection (for example, a pc goes to hibernate mode and back or a router reassigns an IP–address). After the exception the app stop receiving updates. 

```
Exception in thread UpdatesThread:
Traceback (most recent call last):
  File "/development/Telethon/telethon/network/tcp_client.py", line 80, in read
    partial = self.socket.recv(left_count)
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 429, in updates_thread_method
    seq, body = self.transport.receive(timeout)
  File "/development/Telethon/telethon/network/tcp_transport.py", line 40, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/development/Telethon/telethon/network/tcp_client.py", line 92, in read
    'The read operation exceeded the timeout.')
TimeoutError: The read operation exceeded the timeout.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/development/Telethon/telethon/network/tcp_client.py", line 80, in read
    partial = self.socket.recv(left_count)
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 444, in updates_thread_method
    self.receive(r)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 135, in receive
    seq, body = self.transport.receive(timeout)
  File "/development/Telethon/telethon/network/tcp_transport.py", line 40, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/development/Telethon/telethon/network/tcp_client.py", line 92, in read
    'The read operation exceeded the timeout.')
TimeoutError: The read operation exceeded the timeout
```

**Comment by Lonami** [comment]
Well this also happened on [#47](https://github.com/LonamiWebs/Telethon/issues/47#issuecomment-292781727) so maybe if this happens I should try disconnect and then reconnecting?

**Comment by Lonami** [comment]
I'm not sure if this will work, but at least it's worth a try.

**Comment by Lonami** [comment]
Those timeouts are probably related to #94 @chabanovsky. Can you please test the upstream version too?

**Comment by Lonami** [comment]
There are a few newer issues also mentioning both Errno 35 and Errno11 (causing TimeoutError). Discussion has been moved there. Also, [check your system time](https://time.is/) and the [wiki front page](https://github.com/LonamiWebs/Telethon/wiki).
