### ISSUE TITLE
Cannot turn "{}" into any entity (user or chat)'.format(string)

### ISSUE THREAD

**Issue by onezens** [LonamiWebs/Telethon#647]
Traceback (most recent call last):
  File "client.py", line 29, in <module>
    print(client.get_entity('+86185xxxxxxxx'))
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 2006, in get_entity
    for x in inputs
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 2006, in <listcomp>
    for x in inputs
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 2052, in _get_entity_from_string
    'Cannot turn "{}" into any entity (user or chat)'.format(string)
TypeError: Cannot turn "+86185xxxxxxxx" into any entity (user or chat)

**Comment by Lonami** [comment]
Well, there you have it. The library can't find that phone in your contact list and so it fails.
