### ISSUE TITLE
channels.DeleteHistoryRequest not recognizes the InputChannel object

### ISSUE THREAD

**Issue by owneroxxor** [LonamiWebs/Telethon#667]
I'am struggling to delete messages from my private channel:

```
def deleteChannelMessages ():
	a = InputChannel(1164591773,-598320989858967052)
	output = client(DeleteHistoryRequest(a, 100))
```

I get the following error:

```
Traceback (most recent call last):
  File "bot_telegram.py", line 1249, in <module>
    main()
  File "bot_telegram.py", line 1204, in main
    deleteChannelMessages()
  File "bot_telegram.py", line 1170, in deleteChannelMessages
    output = client(DeleteHistoryRequest(a,100))
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 443, in __call__
    result = self._invoke(call_receive, *requests)
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 532, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited
```

Spent all my bullets trying other messages.delete* methods, no success. What could be wrong?

**ps: this InputChannel object is working for other methods I use.**

**Comment by Lonami** [comment]
Strangely enough, I can reproduce. Yes, the library is correctly using the `InputChannel` type (and not `InputPeerChannel`). Weird.

**Comment by owneroxxor** [comment]
Any other way to do that, maybe? The channels are almost a cellphone-freeze trap. So many messages, need an automated way to delete those.

**Comment by Lonami** [comment]
If you want to delete it you probably want to *leave* the channel. Still wonder why it's failing though.

**Comment by owneroxxor** [comment]
Ohh, I can't just do that, a lot of people in it. I want delete to all of them.

**Comment by Lonami** [comment]
Leaving a channel shouldn't destroy it. Not even if you own it, but do some tests first.

**Comment by owneroxxor** [comment]
Also tryied directly using TelegramClient.delete_messages(chanEntity,<msgIdList>):
The call gets processed and returns a AffectedMessages object with 'pts' and 'pts_count' which I don't know what they mean. Anyway. Not working either.

```

2018-03-08 14:39:32,156 - telethon.network.mtproto_sender - DEBUG - Sending requests with IDs: DeleteMessagesRequest: 6530583553278841028
2018-03-08 14:39:32,226 - telethon.network.mtproto_sender - DEBUG - Processing Remote Procedure Call result
2018-03-08 14:39:32,226 - telethon.network.mtproto_sender - DEBUG - Received response for request with ID 6530583553278841028
{'_': 'AffectedMessages', 'pts': 12094, 'pts_count': 0}
```

**Comment by blockinfo** [comment]
Also met problems when using client(DeleteMessagesRequest(inputchannel, msg)). Get TypeError: object of type 'InputChannel' has no len()

**Comment by Lonami** [comment]
You should re-read the parameter list for that request.

**Comment by therapy** [comment]
@Lonami, i am still experiencing this
