### ISSUE TITLE
Exception in getting specific post from a channel

### ISSUE THREAD

**Issue by gtavasoli** [LonamiWebs/Telethon#67]
Hi, this error is not general and happened for me in a specific post. When I get a post with `post_id = 64` from channel `@yaminpour` this exception occurred. There is no error in getting other posts from the channel. (link to post: `https://t.me/yaminpour/64`) I guess there is a bug in the telethon.

It's my code:

```
from telethon import TelegramClient
from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.functions.messages import GetHistoryRequest
from telethon.utils import InputPeerChannel

client = TelegramClient('@SessID', api_id, api_hash)
client.connect()

username = 'yaminpour'

channel_info = client_1.invoke(ResolveUsernameRequest(username))
cid = channel_info.peer.channel_id
ah = channel_info.chats[0].access_hash

result = client.invoke(
    # It get only post with post_id = 64
    GetHistoryRequest(
        InputPeerChannel(cid, ah),
        limit=1,
        offset_date=None,
        offset_id=65,
        max_id=0,
        min_id=63,
        add_offset=0))     #the exception happened in this line
```

and this is exception:

```
Traceback (most recent call last):
  File "sample.py", line 17, in <module>
    client_1.connect()
  File "Python_Path\Python\Python35\site-packages\telethon\telegram_client.py", line 118, in connect
    layer=layer, query=query))
  File "Python_Path\Python\Python35\site-packages\telethon\telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "Python_Path\Python\Python35\site-packages\telethon\network\mtproto_sender.py", line 139, in receive
    request)
  File "Python_Path\Python\Python35\site-packages\telethon\network\mtproto_sender.py", line 222, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "Python_Path\Python\Python35\site-packages\telethon\network\mtproto_sender.py", line 285, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "Python_Path\Python\Python35\site-packages\telethon\network\mtproto_sender.py", line 217, in process_msg
    return self.handle_rpc_result(msg_id, sequence, reader, request)
  File "Python_Path\Python\Python35\site-packages\telethon\network\mtproto_sender.py", line 360, in handle_rpc_result
    request.on_response(compressed_reader)
  File "Python_Path\Python\Python35\site-packages\telethon\tl\functions\invoke_with_layer.py", line 34, in on_response
    self.result = reader.tgread_object()
  File "Python_Path\Python\Python35\site-packages\telethon\utils\binary_reader.py", line 128, in tgread_object
    result.on_response(self)
  File "Python_Path\Python\Python35\site-packages\telethon\tl\types\messages\channel_messages.py", line 64, in on_response
    messages_item = reader.tgread_object()
  File "Python_Path\Python\Python35\site-packages\telethon\utils\binary_reader.py", line 128, in tgread_object
    result.on_response(self)
  File "Python_Path\Python\Python35\site-packages\telethon\tl\types\message.py", line 148, in on_response
    self.media = reader.tgread_object()
  File "Python_Path\Python\Python35\site-packages\telethon\utils\binary_reader.py", line 128, in tgread_object
    result.on_response(self)
  File "Python_Path\Python\Python35\site-packages\telethon\tl\types\message_media_document.py", line 32, in on_response
    self.document = reader.tgread_object()
  File "Python_Path\Python\Python35\site-packages\telethon\utils\binary_reader.py", line 128, in tgread_object
    result.on_response(self)
  File "Python_Path\Python\Python35\site-packages\telethon\tl\types\document.py", line 68, in on_response
    attributes_item = reader.tgread_object()
  File "Python_Path\Python\Python35\site-packages\telethon\utils\binary_reader.py", line 128, in tgread_object
    result.on_response(self)
  File "Python_Path\Python\Python35\site-packages\telethon\tl\types\document_attribute_audio.py", line 63, in on_response
    self.performer = reader.tgread_string()
  File "Python_Path\Python\Python35\site-packages\telethon\utils\binary_reader.py", line 92, in tgread_string
    return str(self.tgread_bytes(), encoding='utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 72: unexpected end of data
```

**Comment by Lonami** [comment]
Closing since this is the same as #49. Trying your code, though. It's an useful example to test with.
