### ISSUE TITLE
AuthBytesInvalidError - The provided authorization is invalid

### ISSUE THREAD

**Issue by skripka696** [LonamiWebs/Telethon#671]
Hello! I am using your Telegram client and at the last time I have some errors
```telethon.errors.rpc_error_list.AuthBytesInvalidError: (AuthBytesInvalidError(...), 'The provided authorization is invalid')
Traceback (most recent call last):
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 1549, in download_file
    input_location, offset, part_size
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 441, in __call__
    result = self._invoke(call_receive, *requests)
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 530, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.FileMigrateError: (FileMigrateError(...), 'The file to be accessed is currently stored in DC 5')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/rq/worker.py", line 789, in perform_job
    rv = job.perform()
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/rq/job.py", line 573, in perform
    self._result = self._execute()
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/rq/job.py", line 579, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./tasks/download_media.py", line 37, in download_media
    action[msg_data.get('media').get('_')](data)
  File "./tasks/download_media.py", line 56, in parse_document
    file = get_file(msg, media_path)
  File "./tasks/download_media.py", line 43, in get_file
    return client.download_media(msg, file=media_path)
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 1313, in download_media
    media, file, date, progress_callback
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 1347, in _download_photo
    progress_callback=progress_callback
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 1562, in download_file
    client = self._get_exported_client(e.new_dc)
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 375, in _get_exported_client
    id=export_auth.id, bytes=export_auth.bytes
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 441, in __call__
    result = self._invoke(call_receive, *requests)
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 530, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.AuthBytesInvalidError: (AuthBytesInvalidError(...), 'The provided authorization is invalid')
Traceback (most recent call last):
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 1549, in download_file
    input_location, offset, part_size
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 441, in __call__
    result = self._invoke(call_receive, *requests)
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 530, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.FileMigrateError: (FileMigrateError(...), 'The file to be accessed is currently stored in DC 5')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/rq/worker.py", line 789, in perform_job
    rv = job.perform()
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/rq/job.py", line 573, in perform
    self._result = self._execute()
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/rq/job.py", line 579, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./tasks/download_media.py", line 37, in download_media
    action[msg_data.get('media').get('_')](data)
  File "./tasks/download_media.py", line 56, in parse_document
    file = get_file(msg, media_path)
  File "./tasks/download_media.py", line 43, in get_file
    return client.download_media(msg, file=media_path)
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 1313, in download_media
    media, file, date, progress_callback
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 1347, in _download_photo
    progress_callback=progress_callback
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 1562, in download_file
    client = self._get_exported_client(e.new_dc)
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 375, in _get_exported_client
    id=export_auth.id, bytes=export_auth.bytes
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 441, in __call__
    result = self._invoke(call_receive, *requests)
  File "/home/lightit/telegram_api_data/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 530, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.AuthBytesInvalidError: (AuthBytesInvalidError(...), 'The provided authorization is invalid')
```
If I will replace SQLiteSession with AlchemySession, will it help me resolve this issue?

**Comment by skripka696** [comment]
And one more. How can I fill out entitiy table when i use AlchemySession? When I log in, it is empty, and when I try join  to channel, I have got error:
`>>>self.client(JoinChannelRequest(channel))
Traceback (most recent call last):
  File "/opt/pycharm/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/user/projects/teleton_telegram/venv/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 434, in __call__
    request.resolve(self, utils)
  File "/home/user/projects/teleton_telegram/venv/lib/python3.5/site-packages/telethon/tl/functions/channels.py", line 971, in resolve
    self.channel = utils.get_input_channel(client.get_input_entity(self.channel))
  File "/home/user/projects/teleton_telegram/venv/lib/python3.5/site-packages/telethon/telegram_client.py", line 2250, in get_input_entity
    return self.session.get_input_entity(peer)
  File "/home/user/projects/teleton_telegram/venv/lib/python3.5/site-packages/telethon/sessions/memory.py", line 179, in get_input_entity
    result = self.get_entity_rows_by_username(username)
  File "/home/user/projects/teleton_telegram/venv/lib/python3.5/site-packages/telethon/sessions/sqlalchemy.py", line 197, in get_entity_rows_by_username
    return row.id, row.hash if row else None
AttributeError: 'NoneType' object has no attribute 'id'`

**Comment by Lonami** [comment]
Regarding the first error could you please surround your comment with triple backticks (<code>```</code>)? I don't feel like reading that as it is now.

**Comment by skripka696** [comment]
@Lonami I've updated format of my comment, please check

**Comment by Lonami** [comment]
I have a feeling https://github.com/LonamiWebs/Telethon/commit/491302bb32734e642fa704dada887b6d97fe0d34fixed this.
