### ISSUE TITLE
AttributeError: 'Event' object has no attribute 'deleted_ids'

### ISSUE THREAD

**Issue by dales** [LonamiWebs/Telethon#674]
Using the latest version (0.18.0.1) on Python 3.6.3

I deleted a message from a group I am part of (via the desktop client) and in my code I have

```python
@client.on(events.MessageDeleted)
def message_deleted(event):
    print("Deleted")
```
2018-03-08 16:54:04,883 - telethon.update_state - ERROR - Unhandled exception on worker 1
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.6/site-packages/telethon/update_state.py", line 104, in _worker_loop
    self.handler(update)
  File "/home/.../venv/lib/python3.6/site-packages/telethon/telegram_client.py", line 2039, in _on_handler
    event = builder.build(update)
  File "/home/.../venv/lib/python3.6/site-packages/telethon/events/__init__.py", line 898, in build
    peer=types.PeerChannel(update.channel_id)
  File "/home/.../venv/lib/python3.6/site-packages/telethon/events/__init__.py", line 911, in __init__
    self.deleted_ids = self.deleted_ids
AttributeError: 'Event' object has no attribute 'deleted_ids'

**Comment by Lonami** [comment]
This silly bug was fixed on https://github.com/LonamiWebs/Telethon/commit/dc99d119c321613a4c0b226dfe23175f84e86deb, but isn't yet on PyPi.

**Comment by dales** [comment]
Thanks. Fixed it local repo. Will wait for next pypi version
