### ISSUE TITLE
RuntimeError: Number of retries reached 0 for ['GetStateRequest'].

### ISSUE THREAD

**Issue by onezens** [LonamiWebs/Telethon#697]
my test code :
```
from telethon import TelegramClient
import socks

# These example values won't work. You must get your own api_id and
# api_hash from https://my.telegram.org, under API Development.
api_id = 12345
api_hash = '0123456789abcdef0123456789abcdef'

client = TelegramClient('session_name', api_id, api_hash, proxy=(socks.SOCKS5, '127.0.0.1', 1080))
client.start()
```

error Info:
how to resolve it ?
```
➜  test git:(master) ✗ python3 test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    client.start()
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 297, in start
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 213, in connect
    self.sync_updates()
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 597, in sync_updates
    self.updates.process(self(GetStateRequest()))
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 463, in __call__
    self._reconnect()
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 285, in _reconnect
    return self.connect()
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 213, in connect
    self.sync_updates()
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 597, in sync_updates
    self.updates.process(self(GetStateRequest()))
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 466, in __call__
    [type(x).__name__ for x in requests]
RuntimeError: Number of retries reached 0 for ['GetStateRequest'].
```

**Comment by onezens** [comment]
sorry , I had fix this because my socks proxy is timeout.
