### ISSUE TITLE
Some errors on work script

### ISSUE THREAD

**Issue by c4uran** [LonamiWebs/Telethon#701]
i followed that instruction:

Goto https://my.telegram.org and generate api id and api hash
Install Telethon library with pip3 install telethon
Run following code (replace api_id, api_hash and username with your values):

got that:
```
$ python3 telegram-media-dowload.py 
Please enter your phone: +**********
Please enter the code you received: *****
Signed in successfully as *****
/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py:1084: UserWarning: get_message_history is deprecated, use get_messages instead
  'get_message_history is deprecated, use get_messages instead'
Traceback (most recent call last):
  File "telegram-media-dowload.py", line 10, in <module>
    for message in client.get_message_history('************', limit=100):
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 1086, in get_message_history
    return self.get_messages(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 1078, in get_messages
    msgs = UserList(self.iter_messages(*args, **kwargs))
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/collections/__init__.py", line 1039, in __init__
    self.data = list(initlist)
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 998, in iter_messages
    entity = self.get_input_entity(entity)
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 2347, in get_input_entity
    return utils.get_input_peer(self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 2314, in _get_entity_from_string
    'Cannot turn "{}" into any entity (user or chat)'.format(string)
TypeError: Cannot turn "************" into any entity (user or chat)
```
am i doing something wrong?
in my script i have russian username looks like Иван Иванович

**Comment by Lonami** [comment]
Make sure `Иван Иванович` (exactly that) is in your dialogs. You can also use their `'@username'` or `'+123456'` phone iff they're in your contacts.

**Comment by Lonami** [comment]
Could you show your entire code? I'm actually not sure what has gone wrong.

**Comment by c4uran** [comment]
i used telephone number and its worked well, thank you
