### ISSUE TITLE
Cannot cast ReceivedNotifyMessage to any kind of InputPeer.

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#722]
Error occurs when trying to call ReceivedMessagesRequest request.
```
Traceback (most recent call last):
  File "D:\telegram\test_3\1.py", line 51, in <module>
    print(client(ReceivedMessagesRequest(99999)))
  File "D:\Program Files\Python363\lib\site-packages\telethon\telegram_bare_client.py", line 443, in __call__
    result = self._invoke(call_receive, *requests)
  File "D:\Program Files\Python363\lib\site-packages\telethon\telegram_bare_client.py", line 501, in _invoke
    self._sender.receive(update_state=self.updates)
  File "D:\Program Files\Python363\lib\site-packages\telethon\network\mtproto_sender.py", line 150, in receive
    self._process_msg(remote_msg_id, remote_seq, reader, update_state)
  File "D:\Program Files\Python363\lib\site-packages\telethon\network\mtproto_sender.py", line 200, in _process_msg
    return self._handle_rpc_result(msg_id, sequence, reader)
  File "D:\Program Files\Python363\lib\site-packages\telethon\network\mtproto_sender.py", line 506, in _handle_rpc_result
    self.session.process_entities(request.result)
  File "D:\Program Files\Python363\lib\site-packages\telethon\session.py", line 375, in process_entities
    p = utils.get_input_peer(e, allow_self=False)
  File "D:\Program Files\Python363\lib\site-packages\telethon\utils.py", line 126, in get_input_peer
    _raise_cast_fail(entity, 'InputPeer')
  File "D:\Program Files\Python363\lib\site-packages\telethon\utils.py", line 80, in _raise_cast_fail
    type(entity).__name__, target))
TypeError: Cannot cast ReceivedNotifyMessage to any kind of InputPeer.
```

**Comment by Lonami** [comment]
Works for me. Guess it has something to do with the messages you have received.

**Comment by Lonami** [comment]
Alright, I can reproduce if I set a message ID high enough to pick up a new message.
