### ISSUE TITLE
ValueError on importing Telethon

### ISSUE THREAD

**Issue by Kyngo** [LonamiWebs/Telethon#768]
Whenever I try to import Telethon (like in the README.md or in any other way), I get an RSA error, and it looks like this:

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/telethon/__init__.py", line 2, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 10, in <module>
    from .crypto import rsa
  File "/usr/local/lib/python3.5/dist-packages/telethon/crypto/rsa.py", line 122, in <module>
    add_key(pub)
  File "/usr/local/lib/python3.5/dist-packages/telethon/crypto/rsa.py", line 53, in add_key
    key = rsa.PublicKey.load_pkcs1(pub)
  File "/usr/lib/python3/dist-packages/rsa/key.py", line 65, in load_pkcs1
    return method(keyfile)
  File "/usr/lib/python3/dist-packages/rsa/key.py", line 191, in _load_pkcs1_pem
    der = rsa.pem.load_pem(keyfile, 'RSA PUBLIC KEY')
  File "/usr/lib/python3/dist-packages/rsa/pem.py", line 85, in load_pem
    raise ValueError('No PEM start marker "%s" found' % pem_start)
ValueError: No PEM start marker "b'-----BEGIN RSA PUBLIC KEY-----'" found
</pre>

Does anyone know why is this happening and how can I fix it?

**Comment by Lonami** [comment]
Perhaps you have an old version of the `rsa` package installed?

**Comment by Kyngo** [comment]
That did the thing. Thanks for your help!
