### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by mamdosein97** [LonamiWebs/Telethon#775]
Hi. what does this error mean and why is occured?
This happens after about 100's message that i get and download it:

Traceback (most recent call last):
   downloaded = download_media_of_message(video, file_path, video_size)
  File "/root/bot_enteghal/telegram_downloader.py", line 42, in download_media_of_message
    download_result = client.download_media(media, downloading_path)
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py", line 1920, in download_media
    media, file, date, progress_callback
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py", line 2010, in _download_document
    progress_callback=progress_callback
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py", line 2176, in download_file
    input_location, offset, part_size
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_bare_client.py", line 459, in call
    result = self._invoke(call_receive, *requests)
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_bare_client.py", line 520, in _invoke
    self._sender.receive(update_state=self.updates)
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/mtproto_sender.py", line 136, in receive
    body = self.connection.recv()
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/connection.py", line 205, in _recv_tcp_full
    body = self.read(packet_len - 12)
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/connection.py", line 298, in _read_plain
    return self.conn.read(length)
  File "/usr/local/lib/python3.6/dist-packages/telethon/extensions/tcp_client.py", line 156, in read
    with BufferedWriter(BytesIO(), buffer_size=size) as buffer:
MemoryError

Would you please help?

**Comment by Lonami** [comment]
Can you enable logging?

**Comment by mamdosein97** [comment]
I extended my server RAM and it hasn't happened yet again. As soon as it happens again i will share its logging here.

**Comment by Lonami** [comment]
Reopen if it happens and/or you have logs.
