### ISSUE TITLE
TelegramClient doesn't actually support temporary sessions

### ISSUE THREAD

**Issue by cher-nov** [LonamiWebs/Telethon#78]
There's a comment in the `TelegramClient`:
```python
def __init__(self, session, api_id, api_hash, proxy=None):
        """Initializes the Telegram client with the specified API ID and Hash.

           Session can either be a `str` object (the filename for the loaded/saved .session)
           or it can be a `Session` instance (in which case list_sessions() would probably not work).
           If you don't want any file to be saved, pass `None`
           ...
```

But actually passing of `None` causes next exception:
```
Traceback (most recent call last):
  File "./tglogin.py", line 13, in <module>
    cli = telethon.TelegramClient(None, TGAPP_API_ID, TGAPP_API_HASH)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 72, in __init__
    'The given session must either be a string or a Session instance.')
ValueError: The given session must either be a string or a Session instance.
```

**Comment by Lonami** [comment]
Yay easy bugs!
