### ISSUE TITLE
Cannot find any entity corresponding to 

### ISSUE THREAD

**Issue by karopass** [LonamiWebs/Telethon#810]
Hi!
Thanks for nice work! I have recently used this module for track presence of number using below codes.
https://github.com/gentoo-root/telegram-tracker/blob/master/track/__main__.py
Its giving me error called 
`'Cannot find any entity corresponding to "{}"'.format(string)`

Full error is like below
```
[
C:\Users\Administrator\Downloads\telegram-tracker-master\telegram-tracker-master>python -m track '+91XXXXXXXXXX'
Traceback (most recent call last):
File "C:\ProgramData\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "C:\ProgramData\Miniconda3\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\Administrator\Downloads\telegram-tracker-master\telegram-tracker-master\track_main.py", line 50, in
contact = client.get_entity(contact_id)
File "C:\ProgramData\Miniconda3\lib\site-packages\telethon\telegram_client.py", line 2553, in get_entity
for x in inputs
File "C:\ProgramData\Miniconda3\lib\site-packages\telethon\telegram_client.py", line 2553, in
for x in inputs
File "C:\ProgramData\Miniconda3\lib\site-packages\telethon\telegram_client.py", line 2606, in _get_entity_from_string
'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "'+91XXXXXXXXXX'"](url)
```
How can I solve it?
Thanks

**Comment by Lonami** [comment]
If that +91 is supposed to be a phone number make sure it's 1. in your contacts and 2. that you're not casting it to an `int`. Format your issue better next time.

**Comment by karopass** [comment]
@Lonami 
Thanks a lot for quick response!
It have solved my issue.
Thank You somuch!

**Comment by Afonichev** [comment]
@Lonami  If the file with the names of the groups in the ASCII encoding, **get_entity** works fine, if in UTF-8, then '_Cannot find any entity corresponding to "channel_name"_', how to fix it? Perhaps I incorrectly read from the file?

```python
with open('filename', 'r+') as file:
    buffer = mmap.mmap(file.fileno(), 0, access=mmap.ACCESS_READ)
    while True:
        group = buffer.readline()
        if group == b'':
            break
        group = group.strip().decode()
        ...
        channel = client.get_entity(group)
        ...
    buffer.close()
```
