### ISSUE TITLE
BlockingIOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by chiva** [LonamiWebs/Telethon#83]
I'm receiving the following error, it occurs randomly, it can be after a few minutes or after a few hours.

I'm using master as of today (930dc99f311c7999c8592457c09399030d23e733)

Code is running in a VPS, so the internet connection is pretty good, and the server itself is not heavily loaded with other tasks.

```
Exception in thread UpdatesThread:                                                                                                          [21/1816]
Traceback (most recent call last):
  File "/home/joshua/python/Telethon/telethon/network/tcp_client.py", line 84, in read
    partial = self.socket.recv(left_count)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joshua/python/Telethon/telethon/network/mtproto_sender.py", line 440, in updates_thread_method
    seq, body = self.transport.receive(timeout)
  File "/home/joshua/python/Telethon/telethon/network/tcp_transport.py", line 45, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/home/joshua/python/Telethon/telethon/network/tcp_client.py", line 96, in read
    'The read operation exceeded the timeout.')
TimeoutError: The read operation exceeded the timeout.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joshua/python/Telethon/telethon/network/tcp_client.py", line 84, in read
    partial = self.socket.recv(left_count)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joshua/python/Telethon/telethon/network/mtproto_sender.py", line 456, in updates_thread_method
    self.receive(r)
  File "/home/joshua/python/Telethon/telethon/network/mtproto_sender.py", line 146, in receive
    seq, body = self.transport.receive(timeout)
  File "/home/joshua/python/Telethon/telethon/network/tcp_transport.py", line 45, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/home/joshua/python/Telethon/telethon/network/tcp_client.py", line 96, in read
    'The read operation exceeded the timeout.')
TimeoutError: The read operation exceeded the timeout.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joshua/python/Telethon/telethon/network/mtproto_sender.py", line 459, in updates_thread_method
    self.reconnect()
  File "/home/joshua/python/Telethon/telethon/network/mtproto_sender.py", line 68, in reconnect
    self.connect()
  File "/home/joshua/python/Telethon/telethon/network/mtproto_sender.py", line 56, in connect
    self.transport.connect()
  File "/home/joshua/python/Telethon/telethon/network/tcp_transport.py", line 19, in connect
    self.tcp_client.connect(self.ip, self.port)
  File "/home/joshua/python/Telethon/telethon/network/tcp_client.py", line 37, in connect
    self.socket.connect((ip, port))
OSError: [Errno 9] Bad file descriptor
```

Other times it stops receiving updates, similar to issue #50

**Comment by Lonami** [comment]
> ```
> OSError: [Errno 9] Bad file descriptor
> ```

I knew there was a issue mentioning this somewhere, I would swear it's been fixed on [`bbd3eb7`](https://github.com/LonamiWebs/Telethon/commit/bbd3eb7c28d9c21e0d486ab9983335cb72d44124) and [`6550d83`](https://github.com/LonamiWebs/Telethon/commit/6550d83d429487ec8f2899659eb1a76a5121ef03). I will close this for now. If you could please test the upstream version and see if you manage to reproduce this, then please reopen the issue.
