### ISSUE TITLE
AttributeError: 'DraftMessageEmpty' object has no attribute 'message'

### ISSUE THREAD

**Issue by ReS4** [LonamiWebs/Telethon#844]
today i had an unexpected error for fetching my dialogs.

```
Traceback (most recent call last):
  File "F:\App\core\main.py", line 233, in get_dialogs
    ls = self.client.get_dialogs(limit=limit)
  File "F:\v_env\lib\site-packages\telethon\telegram_client.py", line 664, in get_dialogs
    dialogs = UserList(self.iter_dialogs(*args, **kwargs))
  File "C:\Python34\lib\collections\__init__.py", line 932, in __init__
    self.data = list(initlist)
  File "F:\v_env\lib\site-packages\telethon\telegram_client.py", line 645, in iter_dialogs
    yield Dialog(self, d, entities, messages)
  File "F:\v_env\lib\site-packages\telethon\tl\custom\dialog.py", line 82, in __init__
    self.draft = Draft(client, dialog.peer, dialog.draft)
  File "F:\v_env\lib\site-packages\telethon\tl\custom\draft.py", line 33, in __init__
    self._text = markdown.unparse(draft.message, draft.entities)
AttributeError: 'DraftMessageEmpty' object has no attribute 'message' 
```

any idea how to fix it? my codes were OK and run perfectly. :(

**Comment by ReS4** [comment]
I tested :
telethon==0.17.0
telethon==0.18.0
telethon==0.19.0
and still the same error occur.

**Comment by Lonami** [comment]
0.17 really has that error? Huh. What version were you using before?

**Comment by ReS4** [comment]
telethon==0.18.3 was my last version that i built my application with it and it work until 5 hours ago !!!

**Comment by Lonami** [comment]
Uninstall the current version and install 0.18.3 then?

**Comment by ReS4** [comment]
downgrading to 0.18.3 and nothing changed. still the same error.

**Comment by Lonami** [comment]
It's very very weird it worked before and nog now. Make 100% sure you're using 0.18.3. `print(telethon.__version__)`.

**Comment by ReS4** [comment]
Yes current version is 0.18.3.
Since i have no DraftMessage in my dialogs, it's very wiered !

![capture2](https://user-images.githubusercontent.com/6023799/41298145-f97480b6-6e75-11e8-8d71-7e68d9a12040.PNG)

**Comment by acassio22** [comment]
Same error here

**Comment by Lonami** [comment]
@acassio22 even installing an older version? That's kind of impossible.

**Comment by ReS4** [comment]
i changed telethon/tl/custom/draft.py from:

```
    ..
    ..
    def __init__(self, client, peer, draft):
        self._client = client
        self._peer = peer
        if not draft:
            draft = DraftMessage('', None, None, None, None)

        self._text = markdown.unparse(draft.message, draft.entities)
        self._raw_text = draft.message
        self.date = draft.date
        self.link_preview = not draft.no_webpage
        self.reply_to_msg_id = draft.reply_to_msg_id
```

to
```
    ..
    ..
    def __init__(self, client, peer, draft):
        self._client = client
        self._peer = peer
        if not draft:
            draft = DraftMessage('', None, None, None, None)

        if not isinstance(draft, DraftMessageEmpty):
            self._text = markdown.unparse(draft.message, draft.entities)
            self._raw_text = draft.message
            self.date = draft.date
            self.link_preview = not draft.no_webpage
            self.reply_to_msg_id = draft.reply_to_msg_id
```

and the error disappeared.

**Comment by Lonami** [comment]
@ReS4 yeah that should definitely fix it but like I said I can't apply it now :)

**Comment by ReS4** [comment]
@Lonami I think something changed in telegram api and it's a critical error ! because i have no problem untile some hours ago..

**Comment by Lonami** [comment]
@ReS4 if it's a "critical error", it's fine to use your patched version until I can fix it.

**Comment by ReS4** [comment]
:'(

**Comment by ReS4** [comment]
@Lonami Now my patch works. Could this change have side effects on other codes? i don't have dominate on whole telethon APIs.

**Comment by intsol** [comment]
What's the status of this patch? Is the patch considered production code for the moment?

**Comment by Lonami** [comment]
Yes.

**Comment by intsol** [comment]
Thankyou.....It's a surprise when you restart a bot which has been running for 2 months without issue and it crashes :)

**Comment by intsol** [comment]
Understood. Thanks again.  Awesome library and documentation 🙏

**Comment by Faith001** [comment]
Also, if you don't mind losing functionality or don't work with drafts in the first place and the above fix doesn't work for you, go ahead and just comment out this entire section: 

```       self._text = markdown.unparse(draft.message, draft.entities)
        self._raw_text = draft.message
        self.date = draft.date
        self.link_preview = not draft.no_webpage
        self.reply_to_msg_id = draft.reply_to_msg_id
```
Just remember to account for this in your own code.

**Comment by Lonami** [comment]
…the fix above works though. You can `pip install -U telethon` to get the fix. **Don't run `pip install --no-cache --upgrade git+https://github.com/LonamiWebs/Telethon@master`** since `master` is now `async`!

**Comment by wowkin2** [comment]
Is this bug fixed only for async version?

**Comment by Lonami** [comment]
No.

**Comment by wowkin2** [comment]
Found that it is fixed starting from `0.19.1.6`, which works in sync mode with few changes.

**Comment by Lonami** [comment]
@wowkin2 the `telethon-sync` package also works in "sync mode" with a few changes, and (most importantly) will be maintained.

**Comment by wowkin2** [comment]
Is that just a branch or module or separate repo?

**Comment by Lonami** [comment]
Separate branch published as a package in PyPi.
