### ISSUE TITLE
Error when downloading media

### ISSUE THREAD

**Issue by jreinert** [LonamiWebs/Telethon#855]
I ran into this issue using telegramircd which uses telethon. I get the following trace for all requests to download media:

```
Unhandled exception
                                         Traceback (most recent call last):
                                           File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 405, in start
                                             await resp.prepare(request)
                                           File "/usr/lib/python3.6/site-packages/aiohttp/web_response.py", line 300, in prepare
                                             return await self._start(request)
                                           File "/usr/lib/python3.6/site-packages/aiohttp/web_response.py", line 605, in _start
                                             return await super()._start(request)
                                           File "/usr/lib/python3.6/site-packages/aiohttp/web_response.py", line 367, in _start
                                             await writer.write_headers(status_line, headers)
                                           File "/usr/lib/python3.6/site-packages/aiohttp/http_writer.py", line 100, in write_headers
                                             buf = _serialize_headers(status_line, headers)
                                           File "aiohttp/_http_writer.pyx", line 138, in aiohttp._http_writer._serialize_headers
                                           File "aiohttp/_http_writer.pyx", line 110, in aiohttp._http_writer.to_str
                                         TypeError: Cannot serialize non-str key None
```

I'm using telethon version 0.18.3

**Comment by Lonami** [comment]
> I'm using telethon version 0.18.3

I'm not going to support old versions. Furthermore that error is completely outside of the `telethon` package, so maybe you did something wrong when using `aiohttp`?

**Comment by jreinert** [comment]
heh that was quick. alright. i'll look into it

**Comment by Lonami** [comment]
[@GitHubBot](https://t.me/GitHubBot) helps.
