### ISSUE TITLE
Missing files in the source distribution

### ISSUE THREAD

**Issue by lilydjwg** [LonamiWebs/Telethon#859]
* get the source tarball from PyPI and extract
* run `python setup.py build`
* get the following error:

```pybt
Traceback (most recent call last):
  File "setup.py", line 240, in <module>
    main()
  File "setup.py", line 176, in main
    generate(['tl', 'errors'])
  File "setup.py", line 59, in generate
    from telethon_generator.parsers import parse_errors, parse_tl, find_layer
  File ".../Telethon-0.19.1.6/telethon_generator/parsers/__init__.py", line 1, in <module>
    from .errors import Error, parse_errors
  File ".../Telethon-0.19.1.6/telethon_generator/parsers/errors.py", line 5, in <module>
    from ..utils import snake_to_camel_case
ModuleNotFoundError: No module named 'telethon_generator.utils'
```

**Comment by Lonami** [comment]
@lilydjwg I get this too, it's really weird and I'm not sure why it happens.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/777c91ee1458723d4cc9a7be717523addacb61e3

**Comment by Lonami** [comment]
For now you can install Telethon from the repository directly:
```sh
# `telethon` package
pip install --no-cache --upgrade git+https://github.com/LonamiWebs/Telethon@sync

# `telethon-aio` package
pip install --no-cache --upgrade git+https://github.com/LonamiWebs/Telethon@master
```
