### ISSUE TITLE
TypeError: The given session must be a Session instance.

### ISSUE THREAD

**Issue by Humphry150** [LonamiWebs/Telethon#860]
`client = TelegramClient("test", settings.api_id, settings.api_hash, proxy=(socks.SOCKS5, settings.host, settings.port))`

Traceback (most recent call last):
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/python/tgrobot2.0/telethonaio_bot/src/client.py", line 27, in <module>
    client = TelegramClient("test", settings.api_id, settings.api_hash, proxy=(socks.SOCKS5, settings.host, settings.port))
  File "/home/hanfei/.local/lib/python3.5/site-packages/telethon/telegram_client.py", line 197, in __init__
    **kwargs
  File "/home/hanfei/.local/lib/python3.5/site-packages/telethon/telegram_bare_client.py", line 101, in __init__
    raise TypeError('The given session must be a Session instance.')
TypeError: The given session must be a Session instance.

**Comment by Lonami** [comment]
What version did you install?

**Comment by botzill** [comment]
Having the same issues while installing: `Telethon-aio-0.19.0.7`. Installed version `Telethon-aio-0.19.0.1` and seems to not have that anymore, any ideas?

**Comment by Lonami** [comment]
You want `pip install -U Telethon==1.0rc1`.
