### ISSUE TITLE
sqlite3

### ISSUE THREAD

**Issue by proroot** [LonamiWebs/Telethon#861]
I work in multithreading

```
2018-06-24 16:03:02    ERROR: Unknown exception in the read thread! Disconnecting and leaving it to main thread
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 735, in _recv_thread_impl
    self.idle(stop_signals=tuple())
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 696, in idle
    self._sender.receive(update_state=self.updates)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 180, in receive
    self._process_msg(remote_msg_id, remote_seq, reader, update_state)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 230, in _process_msg
    return self._handle_rpc_result(msg_id, sequence, reader)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 543, in _handle_rpc_result
    self.session.process_entities(request.result)
  File "/usr/lib64/python3.4/site-packages/telethon/sessions/sqlite.py", line 299, in process_entities
    'insert or replace into entities values (?,?,?,?,?)', rows
sqlite3.OperationalError: database is locked
```

**Comment by Lonami** [comment]
You need to make sure you `disconnect()` properly.

**Comment by proroot** [comment]
How to do it?

**Comment by Lonami** [comment]
You call `disconnect()`.

**Comment by proroot** [comment]
ConnectionResetError: The server has closed the connection.

**Comment by Lonami** [comment]
Then connect again. If you're disconnected you need to disconnect, and that's no longer related with the original issue.
