### ISSUE TITLE
sqlite3

### ISSUE THREAD

**Issue by proroot** [LonamiWebs/Telethon#862]
The work is in multithreading, I do disconnect, and the other clients have not done the work yet, and they immediately fall off

Sorry to have created another topic, but you're making a decision too fast

**Comment by Lonami** [comment]
No. The database will be locked if you don't close it properly and that's not a concern of the library. The library will correctly close the database if you call `disconnect()` when you're not using the client. **You can't use the same session with several clients at once**. Unless you give me a minimal code example that can reproduce the issue, I'm not willing to fix it.

**Comment by proroot** [comment]
```
class MyThread(Thread):
    def __init__(self, name):
        Thread.__init__(self)
        self.name = name

    def run(self):
        for i in range(10):
            #.......

            for account in accounts:
                try:
                    proxy = (
                        socks.SOCKS5,
                        account['proxy']['server'],
                        int(account['proxy']['port']),
                        1,
                        account['proxy']['user'],
                        account['proxy']['password']
                    )

                    client = TelegramClient(
                        'sessions/1',
                        api_id,
                        api_hash,
                        proxy=proxy,
                        timeout=timedelta(seconds=10)
                    )

                    client.connect()

                    # ........
                except Exception as e:
                    print(traceback.format_exc())


def create_threads():
    for i in range(100):
        name = "Thread #%s" % (i + 1)
        my_thread = MyThread(name)
        my_thread.start()


if __name__ == "__main__":
    create_threads()
```

**Comment by Lonami** [comment]
> `'sessions/1'`

You're reusing the same session. This is wrong and should not be done.

**Comment by proroot** [comment]
I made a mistake, I updated the code)

**Comment by Lonami** [comment]
You don't call `disconnect()` on `except` so it's also wrong. I have already said this several times.

**Comment by proroot** [comment]
```
                except Exception as e:
                    print(traceback.format_exc())

                client.disconnect()
```

If, I do this, I see such an error

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 735, in _recv_thread_impl
    self.idle(stop_signals=tuple())
  File "/usr/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 714, in idle
    self._sender.send(GetStateRequest())
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 132, in send
    self._send_message(message)
  File "/usr/lib64/python3.4/site-packages/telethon/network/mtproto_sender.py", line 193, in _send_message
    self.connection.send(helpers.pack_message(self.session, message))
  File "/usr/lib64/python3.4/site-packages/telethon/network/connection/tcpfull.py", line 65, in send
    self.write(data + crc)
  File "/usr/lib64/python3.4/site-packages/telethon/extensions/tcp_client.py", line 140, in write
    self._raise_connection_reset(e)
  File "/usr/lib64/python3.4/site-packages/telethon/extensions/tcp_client.py", line 204, in _raise_connection_reset
    from original
ConnectionResetError: The server has closed the connection.
```

**Comment by proroot** [comment]
Apparently, when there is disconnect, then all clients are reset

**Comment by proroot** [comment]
https://stackoverflow.com/a/26864360
