### ISSUE TITLE
TypeError: object TelegramClient can't be used in 'await' expression

### ISSUE THREAD

**Issue by akeinhell** [LonamiWebs/Telethon#864]
im started new project from example: https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/print_updates.py

and catch exception
```
Traceback (most recent call last):
  File "new.py", line 34, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "new.py", line 21, in main
    await client.start(phone='+7xxxxxxxxxxx')
TypeError: object TelegramClient can't be used in 'await' expression
```

python version: `Python 3.6.5`

DockerFile
```
FROM python:latest

RUN mkdir /app

WORKDIR /app

ADD ./ /app
RUN pip install -U Telethon
CMD python new.py
```

**Comment by Lonami** [comment]
That example is for the async version of the library, select the sync branch.

**Comment by akeinhell** [comment]
@Lonami in async version

```
Traceback (most recent call last):
  File "new.py", line 34, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "new.py", line 19, in main
    client = TelegramClient('session_name', 'xxxx',  'xxx')
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 197, in __init__
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 101, in __init__
    raise TypeError('The given session must be a Session instance.')
TypeError: The given session must be a Session instance.
Exception ignored in: <bound method TelegramBareClient.__del__ of <telethon.telegram_client.TelegramClient object at 0x7ff5df39a470>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 174, in __del__
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 246, in disconnect
AttributeError: 'TelegramClient' object has no attribute '_user_connected'
```

**Comment by Lonami** [comment]
@akeinhell `telethon-aio` from PyPi is broken and I'm aware. Install `pip install -U Telethon-aio==1.0rc1`

**Comment by akeinhell** [comment]
@Lonami thx, its working!
