### ISSUE TITLE
Error in start()

### ISSUE THREAD

**Issue by Inokenty90** [LonamiWebs/Telethon#868]
Version: Telethon-1.0.post1

```from telethon import TelegramClient

api_id = 000000
api_hash = '0000000000000000000000000000000'

client = TelegramClient('test', api_id, api_hash)

client.start()
```
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
   client.start()
  File "telethon\client\auth.py", line 109, in start
    else self.loop.run_until_complete(coro)
  File "Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "telethon\client\auth.py", line 143, in _start
    me = await self.sign_in(phone, code_callback())
TypeError: sign_in() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by Tolsi** [comment]
+1

**Comment by Lonami** [comment]
Thanks.
