### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'key'

### ISSUE THREAD

**Issue by proroot** [LonamiWebs/Telethon#882]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "telethon_2/network/mtprotosender.py", line 385, in _send_loop
    body = self.state.pack_message(message)
  File "telethon_2/network/mtprotostate.py", line 88, in pack_message
    self.auth_key.key[88:88 + 32] + data + padding).digest()
AttributeError: 'NoneType' object has no attribute 'key'
```

Telethon sync 1.0.3

During registration

**Comment by proroot** [comment]
```
Traceback (most recent call last):
  File "telethon_2/network/mtprotosender.py", line 481, in _recv_loop
    self._process_message(message)
  File "telethon_2/network/mtprotosender.py", line 500, in _process_message
    handler(message)
  File "/var/www/proroot/data/www/tmsmm.ru/app/Console/Commands/Python/app/modules/telethon_2/network/mtprotosender.py", line 527, in _handle_rpc_result
    result = message.obj.read_result(reader)
  File "telethon_2/tl/tlobject.py", line 163, in read_result
    return reader.tgread_object()
  File "telethon_2/extensions/binaryreader.py", line 147, in tgread_object
    raise error
telethon_2.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 2215bcbd. Most likely, a TLObject was trying to be read when it should not be read. Remaining bytes: b'\xbd\xbc\x15"7\x97y\xbc\x122fa4a924a5bc2d2b90\x00\x90\x11\xd3:\xf6\xf8\xd4\x9d\xd0t\x06\'\x89\xf2\xef\x0c\x8a\xc5`\x98=\xa0\x1c\x82'

```

Still there is such
