### ISSUE TITLE
TypeNotFoundError

### ISSUE THREAD

**Issue by proroot** [LonamiWebs/Telethon#888]
Often gives an error, and the script hangs when registering an account

```
2018-07-10 16:30:14    ERROR: Unhandled exception while processing TLMessage(msg_id=6576580259652098049, seq_no=5, obj=RpcResult(req_msg_id=6576580258873057316, body=b'\xbd\xbc\x15"7\x97y\xbc\x129122021881ef0ac2dd\x00Y\x1aBq\xe7\xa6\xa8\x96&*\xa8p\x04\'\x06\x0c\xa1\x1b\xa8\xbdsNY&', error=None), container_msg_id=None, after_id=0)
Traceback (most recent call last):
  File "telethon_2/network/mtprotosender.py", line 481, in _recv_loop
    self._process_message(message)
  File "telethon_2/network/mtprotosender.py", line 500, in _process_message
    handler(message)
  File "telethon_2/network/mtprotosender.py", line 527, in _handle_rpc_result
    result = message.obj.read_result(reader)
  File "telethon_2/tl/tlobject.py", line 163, in read_result
    return reader.tgread_object()
  File "telethon_2/extensions/binaryreader.py", line 147, in tgread_object
    raise error
telethon_2.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 2215bcbd. Most likely, a TLObject was trying to be read when it should not be read. Remaining bytes: b'\xbd\xbc\x15"7\x97y\xbc\x129122021881ef0ac2dd\x00Y\x1aBq\xe7\xa6\xa8\x96&*\xa8p\x04\'\x06\x0c\xa1\x1b\xa8\xbdsNY&'
```

**Comment by proroot** [comment]
sync version 1.0.3

**Comment by Lonami** [comment]
You should first upgrade to 1.0.4.

**Comment by proroot** [comment]
Updated, I'm testing

**Comment by proroot** [comment]
The bug is present in the new version too

**Comment by proroot** [comment]
If he would simply throw an exception, then ok, but the script starts to hang

**Comment by proroot** [comment]
I'm already testing

**Comment by proroot** [comment]
Tomorrow, unsubscribe, after the tests

**Comment by proroot** [comment]
well thank you)
