### ISSUE TITLE
Unhandled exception after connection reset, AttributeError: 'NoneType' object has no attribute 'msg_id'

### ISSUE THREAD

**Issue by arrix** [LonamiWebs/Telethon#908]
The following error log was seen after an account got deactivated by telegram.

`AttributeError: 'NoneType' object has no attribute 'msg_id'` and `Received response without parent request` look like protocol errors.

It would nice if the library handles such errors gracefully.

Question: Is there any way for user code to catch or get notified of UserDeactivatedError?

```
2018-07-19 17:46:30,384 INFO mtprotosender.py#431 Connection reset while receiving
2018-07-19 17:46:30,386 INFO mtprotosender.py#239 Connecting to 91.108.56.130:443...
2018-07-19 17:46:30,854 INFO mtprotosender.py#284 Connection to 91.108.56.130 complete!
2018-07-19 17:46:30,859 INFO updates.py#284 Asking for the current state after reconnect...
2018-07-19 17:46:31,263 ERROR mtprotosender.py#480 Unhandled exception while processing TLMessage(msg_id=6579862371338787841, seq_no=4, obj=MessageContainer(messages=[TLMessage(msg_id=6579862371338768385, seq_no=3, obj=RpcResult(req_msg_id=6579862185019319008, body=None, error=RpcError(error_code=401, error_message='USER_DEACTIVATED')), container_msg_id=None), TLMessage(msg_id=6579862371338782721, seq_no=4, obj=MsgsAck(msg_ids=[6579862186969030452]), container_msg_id=None)]), container_msg_id=None)
Traceback (most recent call last):
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 475, in _recv_loop
    await self._process_message(message)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 494, in _process_message
    await handler(message)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 542, in _handle_container
    await self._process_message(inner_message)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 494, in _process_message
    await handler(message)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 512, in _handle_rpc_result
    MsgsAck([message.msg_id])
AttributeError: 'NoneType' object has no attribute 'msg_id'
2018-07-19 17:46:32,274 ERROR mtprotosender.py#480 Unhandled exception while processing TLMessage(msg_id=6579862371361891329, seq_no=5, obj=RpcResult(req_msg_id=6579862183236670920, body=None, error=RpcError(error_code=400, error_message='PHONE_NUMBER_UNOCCUPIED')), container_msg_id=None)
Traceback (most recent call last):
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 475, in _recv_loop
    await self._process_message(message)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 494, in _process_message
    await handler(message)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 512, in _handle_rpc_result
    MsgsAck([message.msg_id])
AttributeError: 'NoneType' object has no attribute 'msg_id'
2018-07-19 17:46:33,280 INFO updates.py#288 Failed to get current state: UserDeactivatedError('The user has been deleted/deactivated')
2018-07-19 17:46:33,287 INFO mtprotosender.py#532 Received response without parent request: b"\x16\t\x05\xcd\x00\x00\x00\x00\xc3\xf4\x13.\x17\x04\x00\x00\x8bpi'r\x97-\x03>\xe2%\xea\x05Bryan\x00\x00\x07Stinson\r8617024474483\x00\x00(\xa2@A\xdf\xa0\xa3\xe6{\x0e7\x93-F\x85\x87\xcb\xfa\x95;\x1eb\x81T"
2018-07-19 17:46:49,694 INFO mtprotosender.py#431 Connection reset while receiving
```

**Comment by Lonami** [comment]
> It would nice if the library handles such errors gracefully.

It would be nice if bugs didn't exist. However, they do. And by the way, it *was* handled gracefully. The error got logged properly and the library didn't crash.

**Comment by arrix** [comment]
Thanks for making it even more graceful! It is good to know that the unhandled exception can be safely ignored.

I'll test with the new code.

**Comment by Lonami** [comment]
`pip install --upgrade git+https://github.com/LonamiWebs/Telethon@master` may be of help.
