### ISSUE TITLE
Reconnection keeps retrying but program eventually exits with ConnectionError

### ISSUE THREAD

**Issue by arrix** [LonamiWebs/Telethon#910]
Version 1.1.1 master 26f121060d114add6083e48d0ba0b90e293d6d0a
There are pages of logs though it all happened in the same second.

Observations
1. Reconnection retry starts over after 5/5 fails
1. Attempt 1 at connecting failed seen after Attempt 4 at connecting failed
1. It seems some logs are duplicated e.g. Failed reconnection retry 1/5
1. Connection to 91.108.56.140 complete! but it still kept retrying
1. The program eventually exists with ConnectionError

It appears that some of the retry attempts are out of order.
Maybe retry attempts triggered by multiple requests are running at the same time?

I guess the by design behavior is

1. only one reconnection retry attempt at a time
1. give up after 5/5 failures and raise ConnectionError
1. user code is supposed to handle ConnectionError after auto reconnect failure and decide what to do

```
2018-07-25 19:55:11,534 INFO mtprotosender.py#316 Failed reconnection retry 2/5
2018-07-25 19:55:11,534 INFO mtprotosender.py#239 Connecting to 91.108.56.140:443...
2018-07-25 19:55:11,534 WARNING mtprotosender.py#246 Attempt 2 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,534 WARNING mtprotosender.py#246 Attempt 2 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,535 WARNING mtprotosender.py#246 Attempt 4 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,535 WARNING mtprotosender.py#246 Attempt 4 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,535 WARNING mtprotosender.py#246 Attempt 1 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,535 WARNING mtprotosender.py#246 Attempt 1 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,535 INFO mtprotosender.py#284 Connection to 91.108.56.140 complete!
2018-07-25 19:55:11,536 INFO updates.py#300 Asking for the current state after reconnect...
2018-07-25 19:55:11,537 WARNING mtprotosender.py#246 Attempt 1 at connecting failed: ProxyConnectionError: Error connecting to SOCKS5 proxy localhost:1086: [Errno 106] Transport endpoint is already connected
2018-07-25 19:55:11,537 WARNING mtprotosender.py#246 Attempt 3 at connecting failed: ConnectionResetError:
```

.....

```
2018-07-25 19:55:11,627 WARNING mtprotosender.py#246 Attempt 5 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,628 INFO mtprotosender.py#316 Failed reconnection retry 1/5
2018-07-25 19:55:11,628 INFO mtprotosender.py#239 Connecting to 91.108.56.140:443...
2018-07-25 19:55:11,628 WARNING mtprotosender.py#246 Attempt 5 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,628 INFO mtprotosender.py#316 Failed reconnection retry 1/5
2018-07-25 19:55:11,628 INFO mtprotosender.py#239 Connecting to 91.108.56.140:443...
2018-07-25 19:55:11,628 WARNING mtprotosender.py#246 Attempt 2 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,628 WARNING mtprotosender.py#246 Attempt 2 at connecting failed: ConnectionResetError:
2018-07-25 19:55:11,629 INFO updates.py#300 Asking for the current state after reconnect...
2018-07-25 19:55:11,629 ERROR base_events.py#1268 Task exception was never retrieved
future: <Task finished coro=<UpdateMethods._handle_auto_reconnect() done, defined at /home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py:296> exception=ConnectionError('Cannot send requests while disconnected',)>
Traceback (most recent call last):
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 38, in __call__
    future = self._sender.send(request, ordered=ordered)
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 202, in send
    raise ConnectionError('Cannot send requests while disconnected')
ConnectionError: Cannot send requests while disconnected
Traceback (most recent call last):
  File "crawler.py", line 535, in <module>
    loop.run_until_complete(func())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "crawler.py", line 477, in main_listen2
    await user_listen_messages(user_id)
  File "crawler.py", line 461, in user_listen_messages
    await receive_messages2(account_client.client)
  File "crawler.py", line 443, in receive_messages2
    await client.disconnected
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/updates.py", line 301, in _handle_auto_reconnect
    state = await self(functions.updates.GetStateRequest())
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
ConnectionError
```

**Comment by arrix** [comment]
Saw this error again. Full log at http://ix.io/1ioz

**Comment by Lonami** [comment]
A lot of changes after https://github.com/LonamiWebs/Telethon/compare/096424ea7809e5512a932c79eff6676695c1d27e...dc7713645329c26b83c38fa0350a69031d81c638, so this may be fixed.
