### ISSUE TITLE
KeyError 

### ISSUE THREAD

**Issue by mdenushev** [LonamiWebs/Telethon#915]
```python
ERROR:telethon.network.mtprotosender:Unhandled exception while processing TLMessage(msg_id=6582517886488681473, seq_no=71954, obj=MessageContainer(messages=[TLMessage(msg_id=6582517886488668161, seq_no=71954, obj=BadMsgNotification(bad_msg_id=6582517684495826084, bad_msg_seqno=68249, error_code=20), container_msg_id=None), TLMessage(msg_id=6582517886488670209, seq_no=71954, obj=BadMsgNotification(bad_msg_id=6582517684495826096, bad_msg_seqno=68252, error_code=20), container_msg_id=None), TLMessage(msg_id=6582517886488676353, seq_no=71954, obj=MsgsAck(msg_ids=[6582517871680707272, 6582517871680707276, 6582517871680707280, 6582517871680707284, 6582517871680707288, 6582517871680707292, 6582517872038154564, 6582517872100669800, 6582517872663157404, 6582517872663157408, 6582517872663157412, 6582517872663157416]), container_msg_id=None)]), container_msg_id=None)
Traceback (most recent call last):
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 481, in _recv_loop
    self._process_message(message)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 500, in _process_message
    handler(message)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 548, in _handle_container
    self._process_message(inner_message)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 500, in _process_message
    handler(message)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 704, in _handle_ack
    self._clean_containers(ack.msg_ids)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 342, in _clean_containers
    del self._pending_messages[message.msg_id]
KeyError: 6582517881065611076
```
telethon-sync(1.0.4)

**Comment by Lonami** [comment]
This sometimes happens, however I don't know why or when. Can you reproduce this issue consistently, and if so, what should I do to make this bug occur?

**Comment by Lonami** [comment]
Please reopen the issue once you provide the information I asked you for.
