### ISSUE TITLE
aggressive iter_participants TypeError: 'ChannelParticipants' object does not support indexing

### ISSUE THREAD

**Issue by arrix** [LonamiWebs/Telethon#918]
iter_participants sometimes raises `TypeError: 'ChannelParticipants' object does not support indexing`

When it happens, I run the script again and it usually works without error.
 1.1.1 master 26f121060d114add6083e48d0ba0b90e293d6d0a with the #904 fix
```
Traceback (most recent call last):
  ...
    async for member in client.iter_participants(group, aggressive=True):
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/async_generator/_impl.py", line 271, in __anext__
    return await self._do_it(self._it.__next__)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/async_generator/_impl.py", line 199, in __next__
    return self._invoke(self._it.__next__)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/Users/aaa/venvs/myenv/lib/python3.7/site-packages/telethon/client/chats.py", line 118, in iter_participants
    participants = results[i]
TypeError: 'ChannelParticipants' object does not support indexing
```

**Comment by Lonami** [comment]
Can't reproduce. Please post instructions on how to trigger this issue and if possible the public megagroup where this is happening. Once that's done and you have made sure it doesn't work under `pip install --upgrade git+https://github.com/LonamiWebs/Telethon@master` you can reopen.
