### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by bybaga** [LonamiWebs/Telethon#924]
```python
Exception in thread Thread-1982:
Traceback (most recent call last):
  File "C:\Program Files\python3.6.5\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\python3.6.5\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 363, in _send_loop
    messages = self._send_queue.get(timeout=1)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 775, in get
    items = self.get_nowait()
  File "C:\Program Files\python3.6.5\lib\queue.py", line 192, in get_nowait
    return self.get(block=False)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 775, in get
    items = self.get_nowait()
  File "C:\Program Files\python3.6.5\lib\queue.py", line 192, in get_nowait
    return self.get(block=False)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 775, in get
    items = self.get_nowait()
  File "C:\Program Files\python3.6.5\lib\queue.py", line 192, in get_nowait
    return self.get(block=False)
```

i got this for 50k times and then

```python 
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\network\mtprotosender.py", line 753, in get
    result = super().get(block=block, timeout=timeout)
  File "C:\Program Files\python3.6.5\lib\queue.py", line 158, in get
    with self.not_empty:
RecursionError: maximum recursion depth exceeded
```

**Comment by Lonami** [comment]
What version of `telethon-sync` are you using?

**Comment by bybaga** [comment]
now i got this 

```python

Traceback (most recent call last):
  File "C:\Users\Администратор.WIN-H2O5EF29JET\Desktop\11\main.py", line 333, in <module>
    gcp(link, lock_gcp)
  File "C:\Users\Администратор.WIN-H2O5EF29JET\Desktop\11\main.py", line 214, in gcp
    participants = client.get_participants(info, aggressive=True)
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\client\chats.py", line 175, in get_participants
    for x in self.iter_participants(*args, **kwargs):
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\client\chats.py", line 115, in iter_participants
    participants = results[i]
TypeError: 'ChannelParticipants' object does not support indexing
