### ISSUE TITLE
Problem in DC changing

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#935]
See this:

```
2018-08-04 08:50:36_telethon.client.downloads_INFO: Downloading file in chunks of 131072 bytes
2018-08-04 08:50:36_telethon.client.downloads_INFO: File lives in another DC
2018-08-04 08:50:36_telethon.network.mtprotosender_INFO: Connecting to 149.154.167.50:443...
2018-08-04 08:50:37_telethon.network.mtprotosender_INFO: Connection to 149.154.167.50 complete!
2018-08-04 08:50:37_telethon.client.telegrambaseclient_INFO: Exporting authorization for data center DcOption(media_only=False, port=443, static=False, cdn=False, id=2, ipv6=False, tcpo_only=False, secret=None, ip_address='149.154.167.50')
2018-08-04 08:50:37_telethon.client.telegrambaseclient_INFO: Disconnecting borrowed sender for DC 2
2018-08-04 08:50:37_telethon.network.mtprotosender_INFO: Disconnecting from 149.154.167.50...
2018-08-04 08:50:37_telethon.network.mtprotosender_INFO: Disconnection from 149.154.167.50 complete!
2018-08-04 08:50:37_telethon.network.mtprotosender_INFO: Connecting to 149.154.167.50:443...
2018-08-04 08:50:37_telethon.network.mtprotosender_INFO: Disconnecting from 149.154.167.50...
2018-08-04 08:50:37_telethon.network.mtprotosender_INFO: Disconnection from 149.154.167.50 complete!
2018-08-04 08:50:37_telethon.network.mtprotosender_WARNING: Attempt 1 at connecting failed: ConnectionResetError:
2018-08-04 08:50:37_asyncio_ERROR: Task exception was never retrieved
future: <Task cancelling coro=<MTProtoSender._recv_loop() done, defined at /usr/local/lib/python3.5/dist-packages/telethon/network/mtprotosender.py:415> exception=InvalidStateError('FINISHED: <Future finished result=None>',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtprotosender.py", line 425, in _recv_loop
    body = await self._connection.recv()
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/connection/tcpabridged.py", line 18, in recv
    length = struct.unpack('<B', await self.read(1))[0]
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcpclient.py", line 191, in read
    self.sock_recv(bytes_left)
  File "/usr/local/lib/python3.5/dist-packages/telethon/extensions/tcpclient.py", line 150, in _wait_timeout_or_close
    loop=self._loop
  File "/usr/lib/python3.5/asyncio/tasks.py", line 347, in wait
    return (yield from _wait(fs, timeout, return_when, loop))
  File "/usr/lib/python3.5/asyncio/tasks.py", line 430, in _wait
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtprotosender.py", line 429, in _recv_loop
    await self.disconnect()
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtprotosender.py", line 140, in disconnect
    await self._disconnect()
  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtprotosender.py", line 174, in _disconnect
    self._disconnected.set_result(None)
  File "/usr/lib/python3.5/asyncio/futures.py", line 329, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <Future finished result=None>
2018-08-04 08:50:37_telethon.network.mtprotosender_INFO: Connection to 149.154.167.50 complete!
2018-08-04 08:50:37_telethon.client.downloads_INFO: Downloading file in chunks of 131072 bytes
2018-08-04 08:50:37_telethon.client.telegrambaseclient_INFO: Disconnecting borrowed sender for DC 2
2018-08-04 08:50:37_telethon.network.mtprotosender_INFO: User is already disconnected!
```

**Comment by Lonami** [comment]
<details><summary>Can't reproduce</summary>
```
INFO:telethon.crypto.aes:libssl detected, it will be used for encryption
DEBUG:asyncio:Using selector: EpollSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91 complete!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) InvokeWithLayerRequest...
DEBUG:telethon.network.mtprotosender:Sending 136 bytes...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848335365543100 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 104 bytes...
DEBUG:telethon.network.mtprotosender:Handling bad salt for message 6585848335365543100
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) InvokeWithLayerRequest...
DEBUG:telethon.network.mtprotosender:Sending 136 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848335365543100 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848336002230024 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 168 bytes...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling new session created
DEBUG:telethon.network.mtprotosender:Handling acknowledge for [6585848335365543100]
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 472 bytes...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6585848335365543100
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) GetStateRequest...
DEBUG:telethon.network.mtprotosender:Sending 72 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848336362696028 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 120 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848336364463188 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 104 bytes...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6585848336362696028
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) GetHistoryRequest...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848337185623504 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848337187780716 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 1592 bytes...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6585848337185623504
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) GetConfigRequest...
DEBUG:telethon.network.mtprotosender:Sending 72 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848337590942716 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848337594388344 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 472 bytes...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6585848337590942716
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 1...
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51 complete!
INFO:telethon.client.telegrambaseclient:Exporting authorization for data center DcOption(id=2, ip_address='149.154.167.51', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, secret=None)
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) ExportAuthorizationRequest...
DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848341760474184 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848341765762308 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 232 bytes...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6585848341760474184
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) InvokeWithLayerRequest...
DEBUG:telethon.network.mtprotosender:Sending 280 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848337838103628 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 104 bytes...
DEBUG:telethon.network.mtprotosender:Handling bad salt for message 6585848337838103628
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) InvokeWithLayerRequest...
DEBUG:telethon.network.mtprotosender:Sending 280 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848337838103628 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848338217720368 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 168 bytes...
DEBUG:telethon.network.mtprotosender:Handling container
DEBUG:telethon.network.mtprotosender:Handling new session created
DEBUG:telethon.network.mtprotosender:Handling acknowledge for [6585848337838103628]
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 216 bytes...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6585848337838103628
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.client.downloads:Downloading file in chunks of 131072 bytes
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) GetFileRequest...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848338646208144 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 120 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848338649443960 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 47016 bytes...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6585848338646208144
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.client.downloads:Saving 46906 more bytes
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) GetFileRequest...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848340941851596 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MsgsAck...
DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6585848340943516712 sent!
DEBUG:telethon.network.mtprotosender:Decoding packet of 104 bytes...
DEBUG:telethon.network.mtprotosender:Handling update UpdateShort
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Decoding packet of 104 bytes...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 6585848340941851596
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.client.telegrambaseclient:Disconnecting borrowed sender for DC 2
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.51...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
DEBUG:telethon.network.mtprotosender:Cancelling the send loop...
DEBUG:telethon.network.mtprotosender:Cancelling the receive loop...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.51 complete!
INFO:telethon.network.mtprotosender:User is already disconnected!
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.91...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
DEBUG:telethon.network.mtprotosender:Cancelling the send loop...
DEBUG:telethon.network.mtprotosender:Cancelling the receive loop...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.91 complete!
INFO:telethon.network.mtprotosender:User is already disconnected!
```
</details>

Unless you tell me which version you are using I can't help.

**Comment by Lonami** [comment]
While I can't reproduce the issue this should probably fix what you're seeing.

**Comment by hnikaein** [comment]
v1.1.1

**Comment by hnikaein** [comment]
When I change from 1.0.4 to 1.1.1 I got this exception for all dc change messages.

**Comment by Lonami** [comment]
`pip install --upgrade git+https://github.com/LonamiWebs/Telethon@master`

**Comment by hnikaein** [comment]
Can you please list commits that I should use?

**Comment by Lonami** [comment]
They're literally shown in this issue since they reference it.

**Comment by hnikaein** [comment]
This is a small program that have problem:
```
async def main():
    client = TelegramClient(PHONE_NUMBER, API_ID, API_HASH)

    await client.start()
    media = (await client.get_messages(limit=1, entity=ENT_ID)).data[0].media
    await client.download_file(media.document.thumb.location, "1.jpg", file_size=media.document.thumb.size)
    await client.download_media(media, "1.webp")


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by hnikaein** [comment]
@Lonami
This is a small program that have problem:
```
async def main():
    client = TelegramClient(PHONE_NUMBER, API_ID, API_HASH)

    await client.start()
    media = (await client.get_messages(limit=1, entity=ENT_ID)).data[0].media
    await client.download_file(media.document.thumb.location, "1.jpg", file_size=media.document.thumb.size)
    await client.download_media(media, "1.webp")


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
This is output:
```
2018-08-09 18:32:13_asyncio_DEBUG: Using selector: SelectSelector
2018-08-09 18:32:13_telethon.network.mtprotosender_INFO: Connecting to 149.154.167.92:443...
2018-08-09 18:32:13_telethon.network.mtprotosender_DEBUG: Connection attempt 1...
2018-08-09 18:32:13_telethon.network.mtprotosender_DEBUG: Connection success!
2018-08-09 18:32:13_telethon.network.mtprotosender_DEBUG: Starting send loop
2018-08-09 18:32:13_telethon.network.mtprotosender_DEBUG: Starting receive loop
2018-08-09 18:32:13_telethon.network.mtprotosender_INFO: Connection to 149.154.167.92 complete!
2018-08-09 18:32:13_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) InvokeWithLayerRequest...
2018-08-09 18:32:13_telethon.network.mtprotosender_DEBUG: Sending 136 bytes...
2018-08-09 18:32:13_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:13_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721056504334640 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Decoding packet of 104 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Handling bad salt for message 6587721056504334640
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) InvokeWithLayerRequest...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Sending 136 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721056504334640 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) MsgsAck...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Sending 88 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721057778722596 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Decoding packet of 168 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Handling container
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Handling new session created
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Handling acknowledge for [6587721056504334640]
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Decoding packet of 456 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Handling RPC result for message 6587721056504334640
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) GetStateRequest...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Sending 72 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721058350224328 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) MsgsAck...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Sending 120 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721058354055240 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Decoding packet of 104 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Handling RPC result for message 6587721058350224328
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) GetHistoryRequest...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Sending 120 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721058940184428 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) MsgsAck...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Sending 88 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721058944153620 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Decoding packet of 488 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Handling RPC result for message 6587721058940184428
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) GetConfigRequest...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Sending 72 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721059574523760 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) MsgsAck...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Sending 88 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721059578492952 sent!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Decoding packet of 456 bytes...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Handling RPC result for message 6587721059574523760
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:14_telethon.network.mtprotosender_INFO: Connecting to 149.154.167.50:443...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Connection attempt 1...
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: Connection success!
2018-08-09 18:32:14_telethon.network.mtprotosender_DEBUG: New auth_key attempt 1...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Starting send loop
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Starting receive loop
2018-08-09 18:32:15_telethon.network.mtprotosender_INFO: Connection to 149.154.167.50 complete!
2018-08-09 18:32:15_telethon.client.telegrambaseclient_INFO: Exporting authorization for data center DcOption(id=2, ip_address='149.154.167.50', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, secret=None)
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) ExportAuthorizationRequest...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Sending 88 bytes...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721063999459700 sent!
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) MsgsAck...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Sending 88 bytes...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721064003418400 sent!
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Decoding packet of 232 bytes...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Handling RPC result for message 6587721063999459700
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) InvokeWithLayerRequest...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Sending 264 bytes...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721060256165340 sent!
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Decoding packet of 104 bytes...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Handling bad salt for message 6587721060256165340
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) InvokeWithLayerRequest...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Sending 264 bytes...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721060256165340 sent!
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) MsgsAck...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Sending 88 bytes...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721060816987824 sent!
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Decoding packet of 168 bytes...
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Handling container
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Handling new session created
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Handling acknowledge for [6587721060256165340]
2018-08-09 18:32:15_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Decoding packet of 152 bytes...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Handling RPC result for message 6587721060256165340
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:16_telethon.client.downloads_INFO: Downloading file in chunks of 131072 bytes
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) GetFileRequest...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Sending 104 bytes...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721061693343596 sent!
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) MsgsAck...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Sending 120 bytes...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721061697311832 sent!
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Decoding packet of 5816 bytes...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Handling RPC result for message 6587721061693343596
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:16_telethon.client.downloads_DEBUG: Saving 5708 more bytes
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) GetFileRequest...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Sending 104 bytes...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721062351232008 sent!
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Packing 1 outgoing message(s) MsgsAck...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Sending 88 bytes...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Outgoing messages 6587721062355200248 sent!
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Decoding packet of 104 bytes...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Handling RPC result for message 6587721062351232008
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Receiving items from the network...
2018-08-09 18:32:16_telethon.client.telegrambaseclient_INFO: Disconnecting borrowed sender for DC 2
2018-08-09 18:32:16_telethon.network.mtprotosender_INFO: Disconnecting from 149.154.167.50...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Closing current connection...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Cancelling 0 pending message(s)...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Cancelling the send loop...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Cancelling the receive loop...
2018-08-09 18:32:16_telethon.network.mtprotosender_INFO: Disconnection from 149.154.167.50 complete!
2018-08-09 18:32:16_telethon.network.mtprotosender_INFO: Connecting to 149.154.167.50:443...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Connection attempt 1...
2018-08-09 18:32:16_telethon.network.mtprotosender_INFO: Disconnecting from 149.154.167.50...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Closing current connection...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Cancelling 0 pending message(s)...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Cancelling the send loop...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Cancelling the receive loop...
2018-08-09 18:32:16_telethon.network.mtprotosender_INFO: Disconnection from 149.154.167.50 complete!
2018-08-09 18:32:16_telethon.network.mtprotosender_WARNING: Attempt 1 at connecting failed: ConnectionResetError: 
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Connection attempt 2...
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Connection success!
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Starting send loop
2018-08-09 18:32:16_telethon.network.mtprotosender_DEBUG: Starting receive loop
2018-08-09 18:32:16_telethon.network.mtprotosender_INFO: Connection to 149.154.167.50 complete!
2018-08-09 18:32:16_telethon.client.downloads_INFO: Downloading file in chunks of 131072 bytes
2018-08-09 18:32:16_telethon.client.telegrambaseclient_INFO: Disconnecting borrowed sender for DC 2
2018-08-09 18:32:16_telethon.network.mtprotosender_INFO: User is already disconnected!
Traceback (most recent call last):
  File "main_temp.py", line 32, in <module>
    loop.run_until_complete(main())
  File "C:\Python36\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "main_temp.py", line 27, in main
    await client.download_media(media, "1.webp")
  File "C:\Python36\lib\site-packages\telethon\client\downloads.py", line 137, in download_media
    media, file, date, progress_callback
  File "C:\Python36\lib\site-packages\telethon\client\downloads.py", line 337, in _download_document
    progress_callback=progress_callback)
  File "C:\Python36\lib\site-packages\telethon\client\downloads.py", line 231, in download_file
    input_location, offset, part_size
  File "C:\Python36\lib\site-packages\telethon\network\mtprotosender.py", line 202, in send
    raise ConnectionError('Cannot send requests while disconnected')
ConnectionError: Cannot send requests while disconnected
```

**Comment by hnikaein** [comment]
@Lonami 
both of examples, downloaded thumbnail before downloading the main file. Did you test this situation?

**Comment by poustchi** [comment]
Yes. I can download thumbnail without any issue. The interesting thing is when I run the same code on windows 10 (python 3.6) everything is fine and I can download video without error!!!

**Comment by hnikaein** [comment]
I got error with win10+python3.7 and ubuntu16.04+python3.5.2
But I don't think that is a matter of versions.

**Comment by AlexanderSov** [comment]
I have the same problem, Telethon==1.1.1

**Comment by zircher90** [comment]
The error only happens when you sign up with it and if that number is in another region in other words voip numbers. You could get some and try them for yourself if you wish.

**Comment by Lonami** [comment]
Can anyone try the `master` branch?

**Comment by hnikaein** [comment]
It seems master have error:
```
Traceback (most recent call last):
  File "main_temp.py", line 7, in <module>
    from telethon import TelegramClient
  File "C:\Python36\lib\site-packages\telethon\__init__.py", line 2, in <module>
    from .client.telegramclient import TelegramClient
  File "C:\Python36\lib\site-packages\telethon\client\__init__.py", line 12, in <module>
    from .telegrambaseclient import TelegramBaseClient
  File "C:\Python36\lib\site-packages\telethon\client\telegrambaseclient.py", line 12, in <module>
    from ..crypto import rsa
  File "C:\Python36\lib\site-packages\telethon\crypto\__init__.py", line 8, in <module>
    from .authkey import AuthKey
  File "C:\Python36\lib\site-packages\telethon\crypto\authkey.py", line 7, in <module>
    from ..extensions import BinaryReader
  File "C:\Python36\lib\site-packages\telethon\extensions\__init__.py", line 6, in <module>
    from .binaryreader import BinaryReader
  File "C:\Python36\lib\site-packages\telethon\extensions\binaryreader.py", line 9, in <module>
    from ..errors import TypeNotFoundError
  File "C:\Python36\lib\site-packages\telethon\errors\__init__.py", line 16, in <module>
    from .rpcerrorlist import *
ModuleNotFoundError: No module named 'telethon.errors.rpcerrorlist'
```

**Comment by Lonami** [comment]
Not sure how you installed  but you need to `python3 setup.py gen`.

**Comment by hnikaein** [comment]
Excuse me I didn't do that.
With version 1.2 the problem exists. But with master, there is no problem.
