### ISSUE TITLE
The server has closed the connection 

### ISSUE THREAD

**Issue by seby2000** [LonamiWebs/Telethon#94]
After about three hours I find this error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/namoso/Telethon/telethon/network/mtproto_sender.py", line 444, in updates_thread_method
    self.send_ping()
  File "/home/namoso/Telethon/telethon/network/mtproto_sender.py", line 103, in send_ping
    self.receive(request)
  File "/home/namoso/Telethon/telethon/network/mtproto_sender.py", line 152, in receive
    seq, body = self.transport.receive(timeout)
  File "/home/namoso/Telethon/telethon/network/tcp_transport.py", line 45, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/home/namoso/Telethon/telethon/network/tcp_client.py", line 91, in read
    'The server has closed the connection (recv() returned 0 bytes).')
ConnectionResetError: The server has closed the connection (recv() returned 0 bytes).

Traceback (most recent call last):
  File "namoso.py", line 32, in <module>
    tg.invoke(SendMessageRequest(InputPeer, "/start", rnd))
  File "/home/namoso/Telethon/telethon/telegram_client.py", line 172, in invoke
    self.sender.send(request)
  File "/home/namoso/Telethon/telethon/network/mtproto_sender.py", line 134, in send
    self.send_packet(writer.get_bytes(), request)
  File "/home/namoso/Telethon/telethon/network/mtproto_sender.py", line 194, in send_packet
    self.transport.send(cipher_writer.get_bytes())
  File "/home/namoso/Telethon/telethon/network/tcp_transport.py", line 37, in send
    self.tcp_client.write(writer.get_bytes())
  File "/home/namoso/Telethon/telethon/network/tcp_client.py", line 57, in write
    self.socket.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Lonami** [comment]
Can you please test @seby2000? Remember to add these lines somewhere in your file:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

So that I can see if we get a "Server disconnected us. Reconnecting..." message (hence, it should work if it doesn't crash afterwards).
