### ISSUE TITLE
Sending image file fails

### ISSUE THREAD

**Issue by arrix** [LonamiWebs/Telethon#943]
Telethon 1.1.1 master
```
Traceback (most recent call last):
  ...
    update = await client.send_file(link, image_file)
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/uploads.py", line 176, in send_file
    msg = self._get_response_message(request, await self(request), entity)
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 38, in __call__
    future = self._sender.send(request, ordered=ordered)
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 215, in send
    message = self.state.create_message(request)
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/network/mtprotostate.py", line 50, in create_message
    out=True  # Pre-convert the request into bytes
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/tl/core/tlmessage.py", line 52, in __init__
    body = GzipPacked.gzip_if_smaller(self.obj)
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/tl/core/gzippacked.py", line 21, in gzip_if_smaller
    data = bytes(request)
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/tl/functions/messages.py", line 3426, in __bytes__
    bytes(self.media),
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/tl/types/__init__.py", line 7391, in __bytes__
    bytes(self.file),
TypeError: cannot convert 'NoneType' object to bytes
```

It worked after I reverted to 26f121060d114add6083e48d0ba0b90e293d6d0a

**Comment by Lonami** [comment]
I assume such commit is not the oldest to still work, and it's just an old working one since participants have nothing to do with photos.

**Comment by pgirikishore** [comment]
Can you share the code to send a file?
Thanks in adance
