### ISSUE TITLE
telethon with flask 

### ISSUE THREAD

**Issue by azarezade** [LonamiWebs/Telethon#949]
I trying to run a flask api service which run a function that talks to bot to get a url using telethon.
when I run that function using `python3 get_url.py` it works ok, but when I set it up using flaks it return the following strange error!
```
bato@srv43899:~/bato-services$ python3.6 api.py                                                                                                                                      
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2018-08-07 16:07:30,469] ERROR in app: Exception on /music [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 10, in music
    print(get_music_url(q))
  File "/home/bato/bato-services/services/music.py", line 30, in get_music_url
    client = authorize_telegram_client()
  File "/home/bato/bato-services/services/__init__.py", line 105, in authorize_telegram_client
    client = TelegramClient(TELEGRAM_CLIENT, api_id, api_hash)  # spawn_read_thread=False # update_workers=4
  File "/usr/local/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 170, in __init__
    self._loop = loop or asyncio.get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 676, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 584, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
127.0.0.1 - - [07/Aug/2018 16:07:30] "GET /music?q=adel HTTP/1.1" 500 -
```

**Comment by Lonami** [comment]
#946, #912, #884, #872.

**Comment by azarezade** [comment]
but my case is more strange than them!
the same flask app runs without any error in my laptop but it return the above error when I run it in a remote server!

**Comment by Lonami** [comment]
Different versions.

**Comment by azarezade** [comment]
No all things are the same!
