### ISSUE TITLE
client.get_dialogs() limit

### ISSUE THREAD

**Issue by bybaga** [LonamiWebs/Telethon#950]
```python
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    limit=1)
  File "D:\code\TelegramSessionRegister\lib\site-packages\telethon\client\dialogs.py", line 126, in get_dialogs
    for x in self.iter_dialogs(*args, **kwargs):
TypeError: iter_dialogs() got multiple values for argument 'limit'
```
while doing this:

```python
dialog = client.get_dialogs(InputPeerUser(user_id='xxxxxx',
                                          access_hash='xxxxxx'
                                          ),
                            limit=1)
```

also, if i do `client.get_dialogs()` w/o limit:

```python
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    access_hash='xxxxxx'))
  File "D:\code\TelegramSessionRegister\lib\site-packages\telethon\client\dialogs.py", line 126, in get_dialogs
    for x in self.iter_dialogs(*args, **kwargs):
  File "D:\code\TelegramSessionRegister\lib\site-packages\telethon\client\dialogs.py", line 51, in iter_dialogs
    limit = float('inf') if limit is None else int(limit)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'InputPeerUser'
```

`telethon-sync == 1.0.4` (from pip)

**Comment by Lonami** [comment]
"Getting dialogs from an user" has never been a thing, and you're using an old version.

**Comment by bybaga** [comment]
`telethon == 1.1.1`

```python
dialog = client.get_dialogs(InputPeerUser(user_id='xxxxxx',
                                                                   access_hash='xxxxxx'
                                                                   )
                                           )
```

```python
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    access_hash='xxxxxx'
  File "D:\code\TelegramSessionRegister\lib\site-packages\telethon\client\dialogs.py", line 130, in get_dialogs
    for x in self.iter_dialogs(*args, **kwargs):
  File "D:\code\TelegramSessionRegister\lib\site-packages\telethon\client\dialogs.py", line 51, in iter_dialogs
    limit = float('inf') if limit is None else int(limit)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'InputPeerUser'
```

**Comment by Lonami** [comment]
What should getting dialogs from an specific user do? I already told you that has never existed.
