### ISSUE TITLE
Telethon connection with Telegram and sending message

### ISSUE THREAD

**Issue by adeelnoor** [LonamiWebs/Telethon#976]
I am following 

https://telethon.readthedocs.io/en/stable/extra/basic/creating-a-client.html

HERE is my code, 

import logging
import asyncio
import getpass, time
import telethon.sync
logging.basicConfig(level=logging.WARNING)
from telethon.tl.functions.messages import GetHistoryRequest
from telethon.utils import get_input_peer
from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.types import InputChannelEmpty
from telethon.tl.types.messages import Messages
from telethon.tl.types.contacts import Contacts
from telethon import TelegramClient, sync
from telethon.errors import SessionPasswordNeededError
api_id = *****
api_hash = ********
loop = asyncio.get_event_loop()
async def main():
	client = await TelegramClient('test', api_id, api_hash).start()
	await client.connect()
	await client.send_message('forexentrepreneur', 'Hello! Talking to you from Telethon')
loop.run_until_complete(main())

# I got an error below

WARNING:telethon.network.mtprotosender:Attempt 5 at connecting failed: TimeoutError: 
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "test.py", line 20, in main
    client = await TelegramClient('test', api_id, api_hash).start()
  File "/usr/local/lib/python3.7/site-packages/telethon/client/auth.py", line 95, in start
    await self.connect()
  File "/usr/local/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 273, in connect
    self.session.server_address, self.session.port)
  File "/usr/local/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 123, in connect
    await self._connect()
  File "/usr/local/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 248, in _connect
    .format(self._retries))
ConnectionError: Connection to Telegram failed 5 times

What I am doing wrong?

**Comment by m3r3lin** [comment]
I think you should use vpn or peoxy for some countries for example Iran

**Comment by adeelnoor** [comment]
I am using VPN for US, will it work?

**Comment by m3r3lin** [comment]
some Proxifire block your request 
Use vpn connection for example Kaspersky Vpn (daily 200MB free)

**Comment by m3r3lin** [comment]
Telegram filtered or blocked in your country?

**Comment by adeelnoor** [comment]
yes

**Comment by m3r3lin** [comment]
Use vpn and proxy for os, not for your browser

**Comment by adeelnoor** [comment]
ok thanks, do you suggest any vpn for mac?

**Comment by m3r3lin** [comment]
Sorry i do not know, search in google or use
Mtproto telethon #877 issue

**Comment by Fisab** [comment]
I used USA proxy, but it output this:
`>>> from telethon import TelegramClient
>>> api_hash = 'xxxxxxxxxxxxxxxxxxxxxxxx'
>>> api_id = xxxxxx
>>> client = TelegramClient('session_name', api_id, api_hash)
>>> client.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vladsudakov/anaconda3/lib/python3.7/site-packages/telethon/client/auth.py", line 114, in start
    else self.loop.run_until_complete(coro)
  File "/Users/vladsudakov/anaconda3/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/vladsudakov/anaconda3/lib/python3.7/site-packages/telethon/client/auth.py", line 121, in _start
    await self.connect()
  File "/Users/vladsudakov/anaconda3/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 319, in connect
    loop=self._loop, proxy=self._proxy
  File "/Users/vladsudakov/anaconda3/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 140, in connect
    await self._connect()
  File "/Users/vladsudakov/anaconda3/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 226, in _connect
    .format(self._retries))
ConnectionError: Connection to Telegram failed 5 times`

**Comment by cadet354** [comment]
You must set proxy to TelegramClient, for example:
client = TelegramClient('session_name5', api_id, api_hash, proxy=(socks.SOCKS5, "195.201.xxx.xxx", 1080, True, "proxy_user", "proxy_password"))
sign_client = await client.start()

**Comment by Fisab** [comment]
> You must set proxy to TelegramClient, for example:
> client = TelegramClient('session_name5', api_id, api_hash, proxy=(socks.SOCKS5, "195.201.xxx.xxx", 1080, True, "proxy_user", "proxy_password"))
> sign_client = await client.start()

For run this i use server at USA

**Comment by jjhesk** [comment]
cool

**Comment by reedniv** [comment]
> You must set proxy to TelegramClient, for example:
> client = TelegramClient('session_name5', api_id, api_hash, proxy=(socks.SOCKS5, "195.201.xxx.xxx", 1080, True, "proxy_user", "proxy_password"))
> sign_client = await client.start()

How if use **mtproxy** not **SOCKS5**?
How to applying?

Socks.mtproxy right? Or why?

**Comment by cadet354** [comment]
> > You must set proxy to TelegramClient, for example:
> > client = TelegramClient('session_name5', api_id, api_hash, proxy=(socks.SOCKS5, "195.201.xxx.xxx", 1080, True, "proxy_user", "proxy_password"))
> > sign_client = await client.start()
> 
> How if use **mtproxy** not **SOCKS5**?
> How to applying?
> 
> Socks.mtproxy right? Or why?

may be that (https://github.com/pyrogram/pyrogram/issues/90) is good place for this question
