### ISSUE TITLE
Cannot get_entity by number

### ISSUE THREAD

**Issue by mdenushev** [LonamiWebs/Telethon#983]
I'm trying to get entity by number like you described [here](https://telethon.readthedocs.io/en/latest/extra/examples/telegram-client.html#getting-entities)
```python
Traceback (most recent call last):
  File "D:/github/wa-tg-numbers/main.py", line 23, in <module>
    client.get_peer_id('+xxxxx')
  File "D:\github\wa-tg-numbers\venv\lib\site-packages\telethon\client\users.py", line 296, in get_peer_id
    peer = self.get_input_entity(peer)
  File "D:\github\wa-tg-numbers\venv\lib\site-packages\telethon\client\users.py", line 260, in get_input_entity
    self._get_entity_from_string(peer))
  File "D:\github\wa-tg-numbers\venv\lib\site-packages\telethon\client\users.py", line 360, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "+xxxxx"
```
This number registered in Telegram

`telethon-sync == 1.0.4`

**Comment by Lonami** [comment]
Registered *and* in your contacts?

**Comment by mdenushev** [comment]
It's me.

**Comment by Lonami** [comment]
It still may be possible that the library has not saved your self user before. You can (and should) use `'me'` for that.

**Comment by mdenushev** [comment]
So another question

**Comment by Lonami** [comment]
Questions do not belong in the issues sections. Read the docs (accessing full API).
