### ISSUE TITLE
Can't connect to Telegram

### ISSUE THREAD

**Issue by lgg** [LonamiWebs/Telethon#996]
Can't connect to Telegram servers from computer. Telegram Desktop works fine with Outline VPN and Proxy.
Platfrom: Win7 x64
Python and pip:
```
$ py -V
Python 3.6.6
$ pip3 -V
pip 18.0
```

File:
```
import socks
import logging
from telethon import TelegramClient, sync
api_id=APPID
api_hash='APIAPPHASHHERE'

logging.basicConfig(level=logging.DEBUG)
client = TelegramClient('test_session1290192012',
    api_id, api_hash,
    #proxy=(socks.SOCKS5, 'PROXYHOST', PROXYPORT, 'PROXYUSERNAME', 'PROXYUSERNAMEPASS')
)
client.start()
for message in client.iter_messages('chatname'):
    client.download_media(message)
```

File with Proxy:
```
import socks
import logging
from telethon import TelegramClient, sync
api_id=APPID
api_hash='APIAPPHASHHERE'

logging.basicConfig(level=logging.DEBUG)
client = TelegramClient('test_session1290192012',
    api_id, api_hash,
    proxy=(socks.SOCKS5, 'PROXYHOST', PROXYPORT, 'PROXYUSERNAME', 'PROXYUSERNAMEPASS')
)
client.start()
for message in client.iter_messages('chatname'):
    client.download_media(message)

```

Debug: With Outline VPN on
```
DEBUG:asyncio:Using selector: SelectSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError:
DEBUG:telethon.network.mtprotosender:Connection attempt 2...
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: OSError: [WinError 10022] Получен недопустимый аргумент
DEBUG:telethon.network.mtprotosender:Connection attempt 3...
WARNING:telethon.network.mtprotosender:Attempt 3 at connecting failed: OSError: [WinError 10022] Получен недопустимый аргумент
DEBUG:telethon.network.mtprotosender:Connection attempt 4...
WARNING:telethon.network.mtprotosender:Attempt 4 at connecting failed: OSError: [WinError 10022] Получен недопустимый аргумент
DEBUG:telethon.network.mtprotosender:Connection attempt 5...
WARNING:telethon.network.mtprotosender:Attempt 5 at connecting failed: OSError: [WinError 10022] Получен недопустимый аргумент
Traceback (most recent call last):
  File "load.py", line 12, in <module>
    client.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\auth.py", line 111, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\auth.py", line 118, in _start
    await self.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\telegrambaseclient.py", line 319, in connect
    self.session.server_address, self.session.port)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtprotosender.py", line 126, in connect
    await self._connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtprotosender.py", line 251, in _connect
    .format(self._retries))
ConnectionError: Connection to Telegram failed 5 times
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.51...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.51 complete!
```

With Outline VPN off:
```
DEBUG:asyncio:Using selector: SelectSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError:
DEBUG:telethon.network.mtprotosender:Connection attempt 2...
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: OSError: [WinError 10022] Получен недопустимый аргумент
DEBUG:telethon.network.mtprotosender:Connection attempt 3...
WARNING:telethon.network.mtprotosender:Attempt 3 at connecting failed: OSError: [WinError 10022] Получен недопустимый аргумент
DEBUG:telethon.network.mtprotosender:Connection attempt 4...
WARNING:telethon.network.mtprotosender:Attempt 4 at connecting failed: OSError: [WinError 10022] Получен недопустимый аргумент
DEBUG:telethon.network.mtprotosender:Connection attempt 5...
WARNING:telethon.network.mtprotosender:Attempt 5 at connecting failed: OSError: [WinError 10022] Получен недопустимый аргумент
Traceback (most recent call last):
  File "load.py", line 12, in <module>
    client.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\auth.py", line 111, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\auth.py", line 118, in _start
    await self.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\telegrambaseclient.py", line 319, in connect
    self.session.server_address, self.session.port)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtprotosender.py", line 126, in connect
    await self._connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtprotosender.py", line 251, in _connect
    .format(self._retries))
ConnectionError: Connection to Telegram failed 5 times
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.51...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.51 complete!
```

With Proxy ON and without Outline VPN:
```
DEBUG:asyncio:Using selector: SelectSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
INFO:telethon.extensions.tcpclient:Connection will be made through proxy (2, 'PROXYHOST', PROXYPORT, 'USERNAME', 'PASSHERE')
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: GeneralProxyError: Socket error: 0x02: Connection not allowed by ruleset
DEBUG:telethon.network.mtprotosender:Connection attempt 2...
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: ConnectionResetError:
DEBUG:telethon.network.mtprotosender:Connection attempt 3...
WARNING:telethon.network.mtprotosender:Attempt 3 at connecting failed: ConnectionResetError:
DEBUG:telethon.network.mtprotosender:Connection attempt 4...
WARNING:telethon.network.mtprotosender:Attempt 4 at connecting failed: ConnectionResetError:
DEBUG:telethon.network.mtprotosender:Connection attempt 5...
WARNING:telethon.network.mtprotosender:Attempt 5 at connecting failed: ConnectionResetError:
Traceback (most recent call last):
  File "load.py", line 12, in <module>
    client.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\auth.py", line 111, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\auth.py", line 118, in _start
    await self.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\client\telegrambaseclient.py", line 319, in connect
    self.session.server_address, self.session.port)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtprotosender.py", line 126, in connect
    await self._connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtprotosender.py", line 251, in _connect
    .format(self._retries))
ConnectionError: Connection to Telegram failed 5 times
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.51...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Cancelling 0 pending message(s)...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.51 complete!

```

By the way, when connecting from server which is located in Amsterdam everything works fine.

**Comment by Lonami** [comment]
The `WinError 10022` you show seems related to https://github.com/dabeaz/curio/issues/75. Maybe you could try Python 3.7? Not sure if it got fixed. I can also find this same issue in https://github.com/Nullspeaker/ch.py/issues/54. However your logs don't mention `select`, but perhaps because the traceback was lost. Depending on your experience and how much you're willing to help, you could try adapting https://github.com/LonamiWebs/Telethon/blob/master/telethon/extensions/tcpclient.py to work around it… Somehow.

**Comment by lgg** [comment]
@Lonami thanks for response. As i can understand this bug is caused by:
https://bugs.python.org/issue29256

Python 3.7 - still not fixed.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/compare/096424ea7809e5512a932c79eff6676695c1d27e...dc7713645329c26b83c38fa0350a69031d81c638 (`asyncio.open_connection`) may help this issue, so try the master branch.
